### ISSUE TITLE
Cannot use @aws-amplify/ui-react with StackBlitz

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#1003]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### Please describe your bug.

When trying to create a demo app on [Stackblitz](https://stackblitz.com) using `@aws-amplify/ui-react` package, I get the following error:

![Unable to find package @aws-amplify/ui-react-v1](https://user-images.githubusercontent.com/6165315/146277699-852f469c-d653-4c1b-a37a-d5fc4147a61e.png)

It appears that StackBlitz doesn't support installing packages under aliases (like `@aws-amplify/ui-react-v1`). See https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/package.json#L53

### What's the expected behaviour?

A customer can build a demo app on [Stackblitz](https://stackblitz.com) using our `@aws-amplify/ui-react` package. 

### Help us reproduce the bug!

1. Go to StackBlitz https://stackblitz.com/edit/react-wl6mzt
2. Attempt to add `@aws-amplify/ui-react` as a dependency. 
3. Observe error message preventing dependency from being added
![Unable to find package @aws-amplify/ui-react-v1](https://user-images.githubusercontent.com/6165315/146277699-852f469c-d653-4c1b-a37a-d5fc4147a61e.png)

**Comment by 0618** [comment]
I was able to install `@aws-amplify/ui-react@1.2.9`, but can't get rid off the error message

https://stackblitz.com/edit/react-j5fgfx?file=package.json

**Comment by dbanksdesign** [comment]
This is fixed now thanks to the WONDERFUL people at StackBlitz!
