### ISSUE TITLE
readme  click `getting-started` url error

### ISSUE THREAD

**Issue by Liberxue** [aws-amplify/amplify-ui#1016]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### Please describe your bug.

readme  click `getting-started` url error

### What's the expected behaviour?

readme  click `getting-started` url error

### Help us reproduce the bug!

readme  click `getting-started` url error

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/5831248/146629627-8370de0b-6b94-4aff-9fef-ccf486caff40.png)

**Comment by dbanksdesign** [comment]
Thank you for filing this issue! I have created #1021 to fix the issue. For anyone looking, the correct URL is https://ui.docs.amplify.aws/getting-started/installation

**Comment by dbanksdesign** [comment]
The fix is live! Closing this issue.

**Comment by Liberxue** [comment]
> Thank you for filing this issue! I have created #1021 to fix the issue. For anyone looking, the correct URL is https://ui.docs.amplify.aws/getting-started/installation

`aws-amplify` Repository do not need external [PR](https://github.com/aws-amplify/amplify-ui/pull/1017)?
