### ISSUE TITLE
Failed to resolve '@aws-amplify/ui/styles.css' when using Parcel or Vite

### ISSUE THREAD

**Issue by julienben** [aws-amplify/amplify-ui#1020]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### Please describe your bug.

Hello! I'm trying to switch from Webpack to Vite or Parcel and having an issue in both when trying to `import '@aws-amplify/ui-react/styles.css'`.

I get the following error (in Parcel):

```
🚨 @parcel/core: Failed to resolve '@aws-amplify/ui/styles.css' from './node_modules/@aws-amplify/ui-react/dist/index.css'

/Users/myname/code/reponame/node_modules/@aws-amplify/ui-react/dist/index.css:1:9
> 1 | @import"@aws-amplify/ui/styles.css";
>   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | 

🚨 @parcel/resolver-default: Cannot load file './@aws-amplify/ui/styles.css' in './node_modules/@aws-amplify/ui-react/dist'.
```

This line works (only in Parcel): `import '@aws-amplify/ui-react/node_modules/@aws-amplify/ui/dist/styles.css';`

Any idea why this might be happening? Thanks!!

### What's the expected behaviour?

The CSS should load with the snippet provided in the documentation.

### Help us reproduce the bug!

1. Create a React app with Vite or Parcel as the bundler
2. Try importing `@aws-amplify/ui-react/styles.css`
3. Get error message ;)

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hi @julienben, thank for reporting this issue. I was able to reproduce this error using parcel, and it's now fixed on the main branch. It will be generally available when the next release gose out. In the meantime you can test out the fix by installing the change with the following pre-release tag:

`npm i @aws-amplify/ui-react@0.0.0-next-59d8b8e-20211120234739`

You had also mentioned you were having trouble with `vitejs`, but I didn't see an error message for `vite` on the ticket. If you are still having issues, would you mind opening up a separate issue and the error message you're getting.

**Comment by julienben** [comment]
@reesscot Thanks for the super fast turnaround time!! 

BTW, the issue in Vite was exactly the same (failure to resolve the CSS). Will test with your new version and open a new issue if it was fixed for Parcel but not Vite.

Thanks again!
