### ISSUE TITLE
New Authenticator is not compatible with React Router V6

### ISSUE THREAD

**Issue by artidata** [aws-amplify/amplify-ui#1028]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### Please describe your bug.

When using the old authenticator, react-router v6 can run smoothly. This is not reproducible when using the new authenticator. 

### What's the expected behaviour?

React router v6 works with the new authenticator as well.

### Help us reproduce the bug!

1. Initialize a `create-react-app` project.
2. Initialize amplify project with cognito auth backend.
3. Install the latest react-router v6 and latest amplify ui.
4. Copy and paste `index.js` and `app.js` from the following repo: https://github.com/artidata/new-authenticator. For the old authenticator - or the working sample, the code is in [main](https://github.com/artidata/new-authenticator/tree/main) branch . Whereas, the new authenticator - or the non working sample the code is in the [new](https://github.com/artidata/new-authenticator/tree/new) branch.

### Code Snippet

The relevant code is mentioned in the reproducing steps section.

### Additional information and screenshots

`package.json` file
```{json}
{
  "name": "new-authenticator",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^2.1.5",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^4.3.11",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

**Comment by dbanksdesign** [comment]
I just forked your repo and created a PR on it with a fix to get the new Authenticator working with React Router v6. I got it working using the `withAuthenticator` higher-order component

https://github.com/artidata/new-authenticator/pull/1

**Comment by artidata** [comment]
Got it working locally too. However, you essentially wrapped the whole `<App/>` component within a new authenticator. The existing else clause is not reached and will never be reached. If I added other component within the else clause it will never be shown.  For example, the following 'pre login' text will never be seen.
```diff
} else {
    return (
+      <div>
+       <h1>Pre Login</h1>
        <Authenticator variation="modal" />
+     </div>
    );
  }
```
You can reproduce this with my latest commit on : https://github.com/artidata/new-authenticator/blob/new/src/App.js

My app looks more like this: https://github.com/artidata/new-authenticator/blob/main/src/App.js, where you also have routes before login. How do you refactor it with the new authenticator? 

The authenticator is also further deep down a popover component. Wrapping the whole `<App/>` with `withAuthenticator` will break non SignedIn state.

**Comment by dbanksdesign** [comment]
Ah ok thanks for the clarification! We are investigating right now. To summarize: you have both un-authenticated and authenticated routes in your router and using `withRouter` at the App layer doesn't allow that (plus you want to use the modal version of the authenticator so it appears in a popover).

**Comment by artidata** [comment]
Yes, and If you mean  

> using ~~withRouter~~ `withAuthenticator` at the App layer doesn't allow that

then we are on the same page.

**Comment by artidata** [comment]
Recent updates in the docs and package has solved the issue. The fix is in the same repo: https://github.com/artidata/new-authenticator. I'm closing this for now. Thanks.
