### ISSUE TITLE
Documentation: Table of Contents showing 'select your cookie preferences'

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-ui#1044]
<img width="1440" alt="CleanShot 2021-12-23 at 14 04 35@2x" src="https://user-images.githubusercontent.com/321279/147295001-5514bd69-821c-4858-b4ac-eee6f9e1867d.png">

**Comment by wlee221** [comment]
Closing as per #1045. Thanks @dbanksdesign!
