### ISSUE TITLE
withAuthenticator does not work when deploy in Amplify hosting 

### ISSUE THREAD

**Issue by entest-hai** [aws-amplify/amplify-ui#1047]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

I use withAuthenticator(HomePage) for authentication, it work well locally, can authenticate with via cognito without any issues. However, when I deploy  it does work, and type username and password then nothing change. Noted that I have configured ssr: true 
```
Amplify.configure(
  {
    ...amplifyConfig, ssr: true
  }
)

```

### What's the expected behaviour?

Expected to login without any issue

### Help us reproduce the bug!

I run the deployed web, open inspector but not error or warning pop up. Enter correct username and password, but nothing change, I expect should be login well as running next js locally.  

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ErikCH** [comment]
Hi @entest-hai !

We've made many improvements and updates to our application since this bug was opened. Is this still an issue? Can you retry today? Also make sure you install our latest version here https://ui.docs.amplify.aws/

**Comment by entest-hai** [comment]
@ErikCH thank you
