### ISSUE TITLE
Support for unprotected routes

### ISSUE THREAD

**Issue by Shomari** [aws-amplify/amplify-ui#1058]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

It would be nice to be able to simply pass in a list of routes that should be unprotected.  These routes would not be redirected to the login flow and could proceed as normal.  Currently, you have to come up with work around for routing if you want a home page to be unprotected but all other to be protected.  

This is harder with the new version of the UI as you don't have the same access to authState as you did in the previous version where you could follow the docs https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#basic-usage to get the result you were looking for. 

### Please describe a solution you'd like.

Pass in a list of routes to Authenticator that would not be redirected

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by Milan-Shah** [comment]
@Shomari Thank you for creating a feature-request. We are currently working on our useAuthenticatorHook Milestone which includes passing in a list of routes to Authenticator that would not be redirected. We recently merged a PR to enable useAuthenticator usage outside of <Authenticator /> component. Please see here[https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react%402.2.0]. Let us know if you have any questions or feedback :)
