### ISSUE TITLE
Possible wrong TS type for CognitoUser used by withAuthenticator

### ISSUE THREAD

**Issue by lacion** [aws-amplify/amplify-ui#1064]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

When using `import { CognitoUserAmplify } from '@aws-amplify/ui';` as a type for the user prop pass by `withAuthenticator` to the component type, script complains that user does not have an attributes property

`Property 'attributes' does not exist on type 'CognitoUserAmplify'`

When it clearly does, as at the point the component have that prop, the user is already authenticated.

- [ ] 

### What's the expected behaviour?

one should be able to access `user.attributes.email` from the user prop pass by `withAuthenticator`  when the user prop is of type `CognitoUserAmplify`

### Help us reproduce the bug!

Using as a prop type

```typescript
interface IAppProps {
  user: CognitoUserAmplify
  signOut: ReturnType<typeof useAuthenticator>['signOut']
}
```

calling 

```typescript
user.attributes.email
```

will result in

`Property 'attributes' does not exist on type 'CognitoUserAmplify'.`

### Code Snippet

```typescript
import React, { useEffect } from 'react'
import './App.css'

import { Amplify } from 'aws-amplify'
import { withAuthenticator, useAuthenticator } from '@aws-amplify/ui-react'
import { CognitoUserAmplify } from '@aws-amplify/ui'

import { awsConfig } from './aws-exports'
Amplify.configure(awsConfig)

interface IAppProps {
  user: CognitoUserAmplify
  signOut: ReturnType<typeof useAuthenticator>['signOut']
}

function App({ signOut, user }: IAppProps): JSX.Element {

  useEffect(() => {
      if (user) {
        console.log(user.attributes.email)
    }
  }, [user])

  return (
    <div>well hello there!</div>
  )
}

export default withAuthenticator(App, {
  variation: 'default',
  loginMechanisms: ['email'],
})


```

**Comment by reesscot** [comment]
Just wanted to add an additional note that @lacion did a `console.log` of the `user` object and it had the attributes object. We seem to be missing a lot of the properties in our `CognitoUserAmplify` TS type.

![image](https://user-images.githubusercontent.com/6165315/147712224-6fb3f004-26d3-4d62-bc78-ff37e3886e94.png)

**Comment by ericclemmons** [comment]
Yes, I believe this needs to be corrected within the Amplify JS library. When a `user` is returned, `attributes` are set on that object (as seen above), but aren't part of the interface:

https://github.com/aws-amplify/amplify-js/blob/6c4d4b5fc737652f88dcdfa26bdb02a1defdfa2e/packages/auth/src/Auth.ts#L1335-L1337

**Comment by wlee221** [comment]
@ErikCH has added in TS types for attributes in #1296, closing.
