### ISSUE TITLE
Cannot change brand theme variables

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-ui#1068]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

CRA

### Please describe your bug.

I am trying to overwrite the primary brand colors using a theme to to theme all Amplify components.
But the values for brand theming stay on the default values.

### What's the expected behaviour?

I want to be able update the primary brand colors to red. 
Am I doing something wrong when configuring my theme? 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/36597466/147853108-5f58bd78-4afd-4473-8f96-b62c5aab2ea4.png">

### Help us reproduce the bug!

`index.js`
```
export const myTheme = {
  name: 'my-theme',
  tokens: {
    colors: {
      brand: {
        primary: { value: 'black' },
      },
    },
  },
  overrides: [
    {
      // colorMode: 'dark',
      tokens: {
        colors: {
          brand: {
            primary: { 
              10: { value: 'red'},  
              20: { value: 'red'},  
              30: { value: 'red'},  
              40: { value: 'red'},  
              50: { value: 'red'},  
              60: { value: 'red'},  
              70: { value: 'red'},  
              80: { value: 'red'},  
              90: { value: 'red'},  
              100: { value: 'red'},  
            }
          },
          black: { value: '#fff' },
          white: { value: '#000' },
        },
      },
    }]
};

ReactDOM.render(
  <React.StrictMode>
    <AmplifyProvider theme={myTheme}>
      <Authenticator.Provider>
        <App />
      </Authenticator.Provider>
    </AmplifyProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
```

`Login.js`
```
...
        <Authenticator signUpAttributes={["email", "phone_number"]} components={components}>
        </Authenticator>
...
```

In  the example above I expect all components that use the brand color to be red.
However the `Authenticator` component in my app still shows the `Teal` color (default primary brand color) .

**Comment by hvergara** [comment]
Hey @Nxtra! Thanks for reaching out.

Our theming system expect a whole set of intermediate values for color tokens (e.g 10, 20, 30, ...., 100), not just a single value.

The following example displays an Authenticator component with a `red` brand color:
```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import '@aws-amplify/ui-react/styles.css';

import { AmplifyProvider, Authenticator } from '@aws-amplify/ui-react';

const myTheme = {
  name: 'my-theme',
  tokens: {
    colors: {
      brand: {
        primary: {
          10: { value: 'red' },
          20: { value: 'red' },
          30: { value: 'red' },
          40: { value: 'red' },
          50: { value: 'red' },
          60: { value: 'red' },
          70: { value: 'red' },
          80: { value: 'red' },
          90: { value: 'red' },
          100: { value: 'red' },
        }
      },
    },
  }
};

ReactDOM.render(
  <React.StrictMode>
    <AmplifyProvider theme={myTheme}>
      <Authenticator.Provider>
        <App />
      </Authenticator.Provider>
    </AmplifyProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
```
<img width="609" alt="Screen Shot 2022-01-06 at 1 21 37 AM" src="https://user-images.githubusercontent.com/181777/148327682-ded8d8bf-b109-4c30-85da-111843e54a08.png">

We're considering to include some utility functions to generate a palette based on a single value, like the one used on some of our example apps: https://github.com/aws-amplify/amplify-ui/blob/main/examples/next/utils.ts (see `usePalette`)

Please let us know if this approach works for you 😀

**Comment by Nxtra** [comment]
That works! Great, thanks.
