### ISSUE TITLE
authenticator: match form disable UX across frameworks

### ISSUE THREAD

**Issue by wlee221** [aws-amplify/amplify-ui#1070]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React, Angular, Vue

### Which UI component?

Authenticator

### How is your app built?

N/A, this is present in all implementations

### Please describe your bug.

Currently `@aws-amplify/react` disables only the submit button whenever authenticator is pending, whereas React/Vue disable the whole form. I believe the latter behavior is desirable to prevent unexpected form mutation between states.

### What's the expected behaviour?

Match framework implementations to have the same disabling UX.

### Help us reproduce the bug!

*React*

1. `yarn && yarn build && yarn next-example dev`
2. http://localhost:3000/ui/components/authenticator/sign-in-with-email
3. Submit sign in or sign up request
4. Only the button is disabled and form is still mutable.

*Vue*
1. `yarn && yarn build && yarn vue-example dev`
2. http://localhost:3000/ui/components/authenticator/sign-in-with-email
3. Submit sign in or sign up request
4. Entire form is disabled.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ErikCH** [comment]
Merged
