### ISSUE TITLE
Add option for showing hidden field labels

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#1074]
### On which framework/platform would you like to see this feature implemented?

React, Angular, Vue

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

There should be a method changing the `labelHidden` property in the Authenticator SignIn, SignUp, etc form fields. Some customers have expressed the desire to show a label above the form fields. This label is already there, but it's hidden using the `sr-only` class because the `hideLabel` prop is hardcoded to false.

Benefits:
* Users can Authenticator forms more accessible, especially for longer forms
* Easier for users to make the form match their Brand identity

### Please describe a solution you'd like.

Perhaps we could expose a config to allow overriding specific props like  the`labelHidden` prop.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by wlee221** [comment]
Agreed, and it's also inconsistent. `signUp` screen shows usernameAlias, password, and confirm-password without labels but other attributes with labels. See https://ui.docs.amplify.aws/components/authenticator#signupattributes for example.

**Comment by pauchena** [comment]
I agree. In my company we need custom the authenticator 
according to customer design. And it would be very nice for us to be able to add labels to the inputs. Thanks!

**Comment by Milan-Shah** [comment]
Good call. Adding it to our upcoming sprint planning discussions.

**Comment by ErikCH** [comment]
This has been merged. Please reopen if the problem occurs again. https://ui.docs.amplify.aws/components/authenticator#form-field-customization
