### ISSUE TITLE
How to disable SignUp?

### ISSUE THREAD

**Issue by ngervasi** [aws-amplify/amplify-ui#1078]
### On which framework/platform would you like to see this feature implemented?

Angular

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Is it possible to disable or hide the SignUp tab?
I need to only allow login, not signup.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by saivarunk** [comment]
Apparently, the docs suggest using CSS to hide the Signup form and tabs. This is not a good suggestion, probably needs a different approach.
https://ui.docs.amplify.aws/components/authenticator#additional-css-styling

**Comment by Milan-Shah** [comment]
@ngervasi As @saivarunk suggested, we are working on introducing a better solution for hiding a sign up tab. For now, please consider using CSS and let us know if you have any issues!

**Comment by Milan-Shah** [comment]
We have started the implemented and adding a reference of this ticket with another one which is in our current sprint.

**Comment by ErikCH** [comment]
I just merged this in! It should be available in our next release. There will be a new `hideSignUp` prop you can pass in, to hide the sign up page. Closing this for now.

**Comment by ngervasi** [comment]
Thanks! Works perfectly.

**Comment by AlexThomas90210** [comment]
Does not seem to work for react native?
