### ISSUE TITLE
bug: menu primitive missing dark mode styling

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#1096]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

All

### Please describe your bug.

Menu dropdown doesn't have dark mode styling.
![Screen Shot 2022-01-05 at 3 00 52 PM](https://user-images.githubusercontent.com/6165315/148302189-a3c58ddd-d8fe-4f0f-9d3f-5857c90e91be.png)

### What's the expected behaviour?

Menu dropdown should have dark mode styling.

### Help us reproduce the bug!

1. Visit: https://ui.docs.amplify.aws/components/menu
2. Change mode to Dark Mode by clicking the moon

**Comment by dbanksdesign** [comment]
Looks fixed to me:

![CleanShot 2022-02-18 at 10 11 45](https://user-images.githubusercontent.com/321279/154738943-83254622-c078-4187-800a-0e0a231b8dc9.png)

@jacoblogan do you want to do the honors of closing?

**Comment by reesscot** [comment]
Let's make some more updates so the dropdown doesn't disappear against the dark background.
