### ISSUE TITLE
Update blog post to use ui-react v2

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#1106]
Currently this [Blog post](https://aws.amazon.com/blogs/mobile/run-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/) uses and old version of the ui-react components. We should update it to use v2.

**Comment by joebuono** [comment]
https://aws-blogs-prod.amazon.com/mobile/running-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/
