### ISSUE TITLE
Change order of Authenticator fields

### ISSUE THREAD

**Issue by Jesmaster** [aws-amplify/amplify-ui#1120]
We've set up Cognito to capture the email, password, given name and family name for a user.

When I use the Authenticator component they are in the order email, password, family name, given name. I want to change the order to given name, family name, email, password.

I tried setting the signUpAttributes array to put the fields in the order I want them but it seems the order they are in the array has no effect on how it displays on the component.
`signUpAttributes={['given_name', 'family_name', 'email', 'password']}`

I didn't see anything in the documentaton about this but I found if I directly edit the aws_cognito_signup_attributes array in aws-exports.js and change the order there it DOES change the order on the Authenticator component but this doesn't seem like a great workaround.

Is there a way to do this or do I need to completely override the component SignUp form fields similar to adding custom attribute form fields?

**Comment by Jesmaster** [comment]
I just realized that signUpAttributes is changing the order for everything except email and password. If I don't pass it then family name shows before given name but setting it to my example above switches those two but still put email and password first.

**Comment by ErikCH** [comment]
Hi @Jesmaster ! This feature has been added. You can now change the order of the `signUp` fields. Please see the instructions here https://ui.docs.amplify.aws/components/authenticator#sign-up-field-order
It will be released in the latest version of the authenticator later today
