### ISSUE TITLE
Documentation: SelectField missing name

### ISSUE THREAD

**Issue by Jesmaster** [aws-amplify/amplify-ui#1131]
The documentation for the SelectField is missing the "name" prop. I tried it out in code and it works fine.

https://ui.docs.amplify.aws/components/selectfield

**Comment by Jesmaster** [comment]
Also "name" and "value" are missing from the props list on the CheckboxField docs.

**Comment by zchenwei** [comment]
> Also "name" and "value" are missing from the props list on the CheckboxField docs.

I think the main reason we didn't put these props are because they are not visible from page, which might cause confusion for some customers

**Comment by Jesmaster** [comment]
Yeah that makes sense, maybe a note somewhere that all of the normal html properties are available would be good, need to assume it right now.

**Comment by jacoblogan** [comment]
A section has been added to the docs component pages describing this behavior
