### ISSUE TITLE
Support documentation for theming with vue

### ISSUE THREAD

**Issue by hessel-bb** [aws-amplify/amplify-ui#1143]
### On which framework/platform would you like to see this feature implemented?

Vue

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I was browsing the Amplify UI docs ( https://ui.docs.amplify.aws/theming?platform=vue ) and switched to vue but apparently there is a lack of documentation for vue. I am having a hard time figuring out how to style the Authenticator component.

I tried things like

```
//app.vue
<style>
[data-amplify-authenticator] {
  --amplify-colors-background-secondary: var(--amplify-colors-neutral-100);
  --amplify-colors-background-tertiary: var(--amplify-colors-black);
  
  --amplify-components-text-color: var(--amplify-colors-font-interactive);
}

.amplify-button {
  background-color:  linear-gradient(45deg,#41e2c5,#98f579) !important;
}}
</style>
```

### Please describe a solution you'd like.

I would like to see how to style your login forms with vue 3. I think many others would want this too.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
Hi @hessel-bb !

The styling section on Vue is just a starting point for people looking to customize the Authenticators look and feel. With that said it should work.

For example, you can override any of the theming by overriding the `amplify-components` CSS variables. Here is an example of fully overriding the look and feel of the Authenticator.

```
<style>
[data-amplify-authenticator] {
  --amplify-colors-background-primary: var(--amplify-colors-neutral-90);
  --amplify-colors-background-secondary: var(--amplify-colors-neutral-100);
  --amplify-colors-background-tertiary: var(--amplify-colors-black);
  --amplify-colors-border-primary: var(--amplify-colors-neutral-20);
  --amplify-colors-border-secondary: var(--amplify-colors-neutral-40);
  --amplify-colors-border-tertiary: var(--amplify-colors-neutral-60);
  --amplify-colors-brand-primary-10: var(--amplify-colors-teal-100);
  --amplify-colors-brand-primary-20: var(--amplify-colors-teal-90);
  --amplify-colors-brand-primary-40: var(--amplify-colors-teal-80);
  --amplify-colors-brand-primary-60: var(--amplify-colors-teal-60);
  --amplify-colors-brand-primary-80: var(--amplify-colors-teal-40);
  --amplify-colors-brand-primary-90: var(--amplify-colors-teal-20);
  --amplify-colors-brand-primary-100: var(--amplify-colors-teal-10);
  --amplify-colors-font-interactive: var(--amplify-colors-white);
  --amplify-components-heading-color: var(--amplify-colors-neutral-20);
  --amplify-components-tabs-item-active-border-color: var(
    --amplify-colors-white
  );
  --amplify-components-tabs-item-active-color: var(--amplify-colors-white);
  --amplify-components-tabs-item-color: var(--amplify-colors-white);
  --amplify-components-tabs-item-focus-color: var(--amplify-colors-white);
  --amplify-components-text-color: var(--amplify-colors-font-interactive);
  --amplify-components-button-link-color: green;
}

.amplify-button {
  background: linear-gradient(
    217deg,
    rgba(255, 0, 0, 0.8),
    rgba(255, 0, 0, 0) 70.71%
  ) !important;
}

</style>
```

This would produce an authenticator looking like this.

![image](https://user-images.githubusercontent.com/65630/149371761-409cbdd4-250a-472e-b441-84a3f74f0a79.png)

You could also just target only buttons that are primary.

```
.amplify-button[data-variation="primary"] {
  background: linear-gradient(
    217deg,
    rgba(255, 0, 0, 0.8),
    rgba(255, 0, 0, 0) 70.71%
  );
}
```

I noticed there was a typo in your `linear-gradient` that was causing it not to work.

Let me know if that helps!

We are looking to adding more theming around Vue and other frameworks in the future, which which will expand the customization available.

**Comment by ErikCH** [comment]
I added more documentation for theming on this. Should be live shortly -> https://ui.docs.amplify.aws/components/authenticator
