### ISSUE TITLE
Error on build a Typescript React app

### ISSUE THREAD

**Issue by nicolasfara** [aws-amplify/amplify-ui#1154]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Webpack

### Please describe your bug.

Create a fresh new React application with the command: `yarn create react-app smart-shelf-frontend --template typescript`
Initialize Amplify with `amplify init` and all the other amplify commands.
Install the following library: `yarn install aws-amplify @aws-amplify/ui-react`. The versions are respectively `4.3.12` and `2.1.7`.  

Add `auth` component from Amplify and configure the `App.tsx` file as follow:
```typescript
import {Authenticator, Button} from '@aws-amplify/ui-react';
import "@aws-amplify/ui-react/styles.css"
import "./App.css"
import Amplify from "aws-amplify";
import awsExports from "./aws-exports";

Amplify.configure(awsExports);

export default function App() {
    return (
        <Authenticator>
            {
                ({signOut, user}) =>
                    <main>
                        <h1>Hello {user.username}</h1>
                        <Button onClick={signOut}>Sign out</Button>
                    </main>
            }
        </Authenticator>
    )
}
```

Run the application with `yarn start`.
The following error appear:
```
ERROR in ./node_modules/@aws-amplify/ui-react/dist/esm/index.js 34536:9-17
export 'useId' (imported as 'n9') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
 @ ./src/App.tsx 4:0-62 12:30-43 25:39-45
 @ ./src/index.tsx 7:0-24 11:33-36
```

### What's the expected behaviour?

No error should be thrown

### Help us reproduce the bug!

1. `yarn create react-app smart-shelf-frontend --template typescript`
2. Initialize new app in Amplify
3. yarn install aws-amplify @aws-amplify/ui-react
4. Add `auth` component in Amplify
5. Setup `App.tsx` with `Authentication` component
6. `yarn start`

The error should be appear.

### Code Snippet

```typescript
import {Authenticator, Button} from '@aws-amplify/ui-react';
import "@aws-amplify/ui-react/styles.css"
import "./App.css"
import Amplify from "aws-amplify";
import awsExports from "./aws-exports";

Amplify.configure(awsExports);

export default function App() {
    return (
        <Authenticator>
            {
                ({signOut, user}) =>
                    <main>
                        <h1>Hello {user.username}</h1>
                        <Button onClick={signOut}>Sign out</Button>
                    </main>
            }
        </Authenticator>
    )
}
```

### Additional information and screenshots

```
{
  "name": "amplify-demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "typescript": "^4.5.4"
  }
}
```

**Comment by ErikCH** [comment]
Hi @nicolasfara ! We have fixed this issue. Please install `@aws-amplify/ui-react` version `2.1.8`. That should resolve this issue! Let me know.
