### ISSUE TITLE
Users get stuck after AdminCreateUser API called with a missing required attribute

### ISSUE THREAD

**Issue by ThomasRooney** [aws-amplify/amplify-ui#1155]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

Given a cognito userpool that has a required attribute "preferred_username"
And a user is invited to that userpool via a `cognito.adminCreateUser` API call lacking this `preferred_username` required attribute (in this case, the API call is made in a lambda upon another user inviting them)
The user is created successfully, and the admin invitation message is sent (default: `Your username is {####} and temporary password is {####}`.

When the user attempts to login through the `Authenticator` component, after the user enters username/password, they enter a 
 screen for changing their password for login.
 
Upon attempting to login, the error message `Invalid attributes given, preferred_username is missing` is provided.

However, given the user has no place to enter the required attribute `preferred_username`, they are now stuck until manual resolution by an administrator.

### What's the expected behaviour?

In the Cognito Hosted UI, and the prior amplify authenticator UI, the user is prompted to enter their `preferred_username`, similar to the signup flow.
Upon entering this attribute and confirming the password change, the attribute is expected to make its way to Cognito.

### Help us reproduce the bug!

Version: "@aws-amplify/ui-react": "2.1.8",
Also in version: "2.0.0" (I upgraded to 2.1.8 to validate it wasn't already solved)

Available workaround: creating the user with the full set of attributes. However this isn't ideal in many scenarios.

Network Request:

POST https://cognito-idp.eu-west-2.amazonaws.com/

```
{
    "ChallengeName": "NEW_PASSWORD_REQUIRED",
    "ClientId": "<REDACTED>",
    "ChallengeResponses": {
        "NEW_PASSWORD": "<REDACTED>",
        "USERNAME": "<REDACTED>"
    },
    "Session": "<REDACTED>"
}
```

Network Response:

`{"__type":"InvalidParameterException","message":"Invalid attributes given, preferred_username is missing"}`

### Code Snippet

Authenticator is configured with explicit attributes for `signUpAttributes`

```tsx
                <Authenticator
                  loginMechanisms={['email']}
                  signUpAttributes={['email', 'preferred_username']}
                  socialProviders={['google', 'amazon']}
                >
                  {() => <LoadingScreen />}
                </Authenticator>
```
UserPool is configured like so (via CDK)

```ts
      userPool = new UserPool(this, `ReflowUserPool`, {
        userPoolName: `${props.workspace}.Reflow`,
        selfSignUpEnabled: true,
        passwordPolicy: {
          tempPasswordValidity: Duration.days(3),
          minLength: 8,
          requireLowercase: true,
          requireUppercase: true,
          requireDigits: true,
          requireSymbols: false,
        },
        signInAliases: { email: true },
        standardAttributes: {
          email: {
            required: true,
            mutable: true,
          },
          preferredUsername: {
            required: true,
            mutable: true,
          },
        },
        autoVerify: {
          email: true,
        },
        customAttributes: {
          teamId: new StringAttribute({ mutable: true }),
        },
      });
```

User is invited like so:

```ts
  const cognitoResp = await cognito
    .adminCreateUser({
      DesiredDeliveryMediums: ['EMAIL'],
      ForceAliasCreation: false,
      UserAttributes: [
        {
          Name: 'email',
          Value: newUser.email,
        },
        {
          Name: 'custom:teamId',
          Value: team.id,
        },
      ],
      UserPoolId: userPoolId,
      Username: newUser.email,
    })
    .promise();
```

### Additional information and screenshots

![dev reflow io_](https://user-images.githubusercontent.com/2904857/149679686-8fd5cdda-832c-49e9-a2e3-f6c025f11ce1.png)

![localhost_3100_ (1)](https://user-images.githubusercontent.com/2904857/149680285-3306d630-6caa-4f6a-b4f2-7d78f5bb526d.png)

**Comment by ErikCH** [comment]
Hi @ThomasRooney!

I was able to reproduce this. I'll add it to our bug list, and we'll see if we can get a fix out!
