### ISSUE TITLE
Missing translation in Authenticator

### ISSUE THREAD

**Issue by Ashafix** [aws-amplify/amplify-ui#1156]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

create react app

### Please describe your bug.

Some texts are not translated, e.g.

- "Reset your password" link
- "Send code" button

### What's the expected behaviour?

All texts should be translated if a translation is available.

### Help us reproduce the bug!

Self contained example based on the change-your-layout demo in the documentation.
https://codesandbox.io/s/change-your-layout-forked-yv7tf?file=/src/Login.js

It happens with other languages as well (tried de, es, it)

### Code Snippet

```javascript
// Put your code below this line.
import { Authenticator } from "@aws-amplify/ui-react";

import { Header } from "./Header";
import { Footer } from "./Footer";
import { SignInHeader } from "./SignInHeader";
import { SignInFooter } from "./SignInFooter";
import { translations } from '@aws-amplify/ui';
import { I18n } from 'aws-amplify';

const components = {
  Header,
  SignIn: {
    Header: SignInHeader,
    Footer: SignInFooter
  },
  Footer
};

I18n.putVocabularies(translations);
I18n.setLanguage('de');

export function Login() {
  return (
    <Authenticator components={components}>
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user.username}</h1>
          <button onClick={signOut}>Sign out</button>
        </main>
      )}
    </Authenticator>
  );
}
```

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/15069160/149778525-37e7eac7-5cb7-495a-9956-24a57ca57d3a.png)
![image](https://user-images.githubusercontent.com/15069160/149778532-2ad0608b-57be-40de-8f77-be579ec3adf5.png)

**Comment by eli6** [comment]
@Ashafix I realised this too after creating the Swedish translation now. It depends on different things for different translations, in the case of "Send code", the translation template for German only translates "Send Code" with an uppercase C. Translations are case-sensitive so that's why it doesn't work. It's very important that the left hand side of the translations are exact.

Other translations are simply missing from the template (for example "We Emailed You") and have to be added.

I'd be happy look into this a bit more if help is needed.

**Comment by Ashafix** [comment]
@eli6 : Thanks! That solved the problem for "Send Code". I've tried the same thing for "Reset your password", all variations of upper/lower case and trailing spaces I could think of, but not success.

**Comment by eli6** [comment]
@Ashafix The reason I can see why "Reset your password" and some other strings are not translated is that they are not passed to the "translate()" function in the change-your-layout demo. Try this in the file SignInFooter.js:

First import translate:
```
import { translate } from '@aws-amplify/ui';
```
Then you can write the footer function like this:

```
export function SignInFooter() {
  const { toResetPassword } = useAuthenticator();
  const { tokens } = useTheme();

  //perform translation here:
  const resetText = translate(`Reset your password`);

  return (
    <Flex justifyContent="center" padding={`0 0 ${tokens.space.medium}`}>
      //and here you use the translated variable: 
      <Link onClick={toResetPassword}>{resetText}</Link>
    </Flex>
  );
}
```

**Comment by Ashafix** [comment]
Ooof, that was kind of obvious in hindsight. 
Thanks!

I'll check the missing translations (capitalization) and make a PR.

**Comment by ErikCH** [comment]
@Ashafix Thanks for the translations! I'll look this over today!

**Comment by ErikCH** [comment]
This has been merged and released. Please let me know if this is still occuring!
