### ISSUE TITLE
QR Code is missing secret key on TOTP setup page

### ISSUE THREAD

**Issue by bwindsor** [aws-amplify/amplify-ui#1158]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create react app (react-scripts)

### Please describe your bug.

The the TOTP setup page, the QR code is invalid. The contents of the QR code are 
This bug was introduced in #1083 

Specifically, the reason for this bug is that `secretKey` is now being stored using `React.useState`, and so `secretKey` is referenced before the component has rerendered, and therefore `totpCode` still has its old value.

https://github.com/aws-amplify/amplify-ui/blob/f888639c7fe2464b689dc6c7663cbd9b2a5312ae/packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx#L32-L35

A solution would be to change these lines to
```typescript
      const newSecretKey = await Auth.setupTOTP(user);
      setSecretKey(newSecretKey);
      const issuer = 'AWSCognito';
      const totpCode = `otpauth://totp/${issuer}:${user.username}?secret=${newSecretKey}&issuer=${issuer}`;
      const qrCodeImageSource = await QRCode.toDataURL(totpCode);
```

### What's the expected behaviour?

The contents of the QR code should be `otpauth://totp/${issuer}:${user.username}?secret=${this.secretKey}&issuer=${issuer}`

In reality, `this.secretKey` is an empty string.

### Help us reproduce the bug!

Start any authentication flow with requires one time passwords. Try scanning the QR code with an Authenticator app. Your Authenticator app will say it is invalid. Try parsing the QR code with any generic QR code scanner (e.g. Google Lens). You'll see that the string is something like `otpauth://totp/AWSCognito:abcder?secret=&issuer=AWSCognito`

**Comment by ErikCH** [comment]
Hi @bwindsor !

You are right, it's not working correctly. I pushed up a fix, we'll get this in soon!

**Comment by ErikCH** [comment]
@bwindsor Oops didn't see your PR! I went ahead and merged mine, but thanks for the info! It should be in our next release!

**Comment by bwindsor** [comment]
@ErikCH No problem, I think the PRs we're pretty much identical anyway. Thanks for getting it sorted so quickly!
