### ISSUE TITLE
Can't use StepperField from Figma ui-component in Collection

### ISSUE THREAD

**Issue by lobbin** [aws-amplify/amplify-ui#1161]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### Please describe your bug.

If I create a component in Figma, containing a StepperField and then try to connect to the component with the StepperField in a Collection (via overrides), I'm not able to differentiate which of the items in the collection that's responsible for the step change as the onStepChange event only contains the step value and not the full event.

### What's the expected behaviour?

That the StepperField -/+ emits a full onChange event and that the current onChange event contains a currentTarget.

### Help us reproduce the bug!

.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hi @lobbin,
You can access the collection item or index by using the `item` or `index` parameters in your `onStepChange` handler. Here's an example:

```jsx
      <Collection
        type="list"
        items={["first", "second", "third", "fourth"]}
        gap="1.5rem"
      >
        {(item, index) => (
          <Card key={index} padding="1rem">
            <Text>{item}</Text>
            <StepperField
              label="Controlled stepper"
              min={0}
              max={10}
              step={1}
              onStepChange={(step) =>
                console.log(`index: ${index}, item: ${item}, step: ${step}`)
              }
              labelHidden
            />
          </Card>
        )}
      </Collection>
```

Please let us know if this solves your issue.

**Comment by lobbin** [comment]
Hi @reesscot,

Thanks, but in my case, the Collection contains "Item", where "Item" is generated via the Figma integration, so I don't think I can do it like your example? Main problem is that the StepperField isn't available directly from the Collection.

**Comment by reesscot** [comment]
@lobbin Maybe you could use the overrides prop to pass the `item` down to your custom component which wraps the StepperField? See:
https://docs.amplify.aws/console/uibuilder/override/#via-component-props

If you could please provide more code and more details of what you're trying to accomplish, that would help me debug further.

**Comment by dbanksdesign** [comment]
@lobbin we are working on a better overrides experience for Studio UI Builder especially as it relates to collections and items within a collection. Your use-case is exactly one we are looking to fix before Amplify Studio UI Builder goes to general availability.

**Comment by lobbin** [comment]
> 

It looks like this

```
ItemCollection
  Item (component via Figma integration)
    Flex
      StepperField
```

It's working fine with override props as I'm doing this on other components. However, those other components have event and event.currentTarget, which means I can find other props that way. OnStepChange doesn't do that, so I can't go down that path. If needed, I can provide actual code.

**Comment by lobbin** [comment]
> @lobbin we are working on a better overrides experience for Studio UI Builder especially as it relates to collections and items within a collection. Your use-case is exactly one we are looking to fix before Amplify Studio UI Builder goes to general availability.

Thanks, looking forward to it :)

**Comment by dbanksdesign** [comment]
@lobbin we recently released the updated overrides behavior that includes better collection item overrides (https://docs.amplify.aws/console/uibuilder/override/#extend-generated-collections-via-overrideitems-prop) as well as per component overrides (https://docs.amplify.aws/console/uibuilder/override/#extend-generated-components-via-overrides-prop). 

You mentioned your Collection is in your React code and the items in the Collection are a component generated from Figma correct? Your code could look like this with the new overrides code:

```jsx
<Collection
  type="list"
  items={["first", "second", "third", "fourth"]}
  gap="1.5rem"
>
  {(item, index) => (
    // Item is a generated component from Figma
    <Item overrides={{
      // 'StepperField' is the layer name in Figma
      'StepperField': {
        onStepChange(step) {
          console.log(`index: ${index}, item: ${item}, step: ${step}`)
        }
      }
    }} />
  )}
</Collection>
```

The reason `onStepChange` isn't a full HTML event is because it is not a real HTML event like `onChange` on an input. It is a event specific to this component. Let me know if the above code works for you or if you still have an issue. Thanks!

**Comment by lobbin** [comment]
@dbanksdesign Thanks, that's exactly the solution I'm after!
