### ISSUE TITLE
Configurable linear loader

### ISSUE THREAD

**Issue by lobbin** [aws-amplify/amplify-ui#1173]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I'd like a combination of the linear loader and slider. As in, a linear loader where I can configure the min, max and current step. This can for example be used in conjunction with a file upload.

### Please describe a solution you'd like.

At the moment I'm using the regular slider field, hiding the slider button.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @lobbin, thanks for your feature request. Do you have an example of what you think it would look like? Is there another library that offers this that would give us some inspiration?

**Comment by lobbin** [comment]
Hi @reesscot,

I'm thinking in line of a general Windows progress bar, for instance.

![progress-bars-image3](https://user-images.githubusercontent.com/409736/150575425-69448dfd-259b-4a5a-86dd-70acad831d5c.png)

**Comment by reesscot** [comment]
@lobbin This is now available in the latest version of our Loader component. See:
https://ui.docs.amplify.aws/components/loader#variation
