### ISSUE TITLE
ConfirmSignUp subtitleText is not translatable

### ISSUE THREAD

**Issue by evagm** [aws-amplify/amplify-ui#1182]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

The `subtitleText` cannot be transalted because it's not wrapped with `translate()` and includes a value within the string.  

 https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx#L53-L60

### What's the expected behaviour?

That `subtitleText` can be translated using `I18n` from `aws-amplify`.

### Help us reproduce the bug!

Set the language to something other than english in your app.
`I18n.setLanguage({ANOTHER_LANG CODE});`

View the Autenticator's ConfirmSignUp and see that the `subtitleText` is still in english.

**Comment by ErikCH** [comment]
This is a good one. We could add 2 strings, and wrap them both in translate. One before the dynamic text, and then after. It would be a little more tedious to update the translations, but it's possible. How does that sound @evagm ?

**Comment by evagm** [comment]
That sounds good @ErikCH!

**Comment by ErikCH** [comment]
Hi @evagm ! We added these new translations now. You should be able to completly translate the text. It will be in our next release. I'm closing this for now. Feel free to reopen if you still have problems after next weeks release.

Here are the new texts. They are also listed in the docs.
```

Your code is on the way. To log in, enter the code we emailed to
Your code is on the way. To log in, enter the code we texted to
Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.
It may take a minute to arrive.
```

**Comment by evagm** [comment]
Thanks so much @ErikCH!
