### ISSUE TITLE
Update references to phone number dial code

### ISSUE THREAD

**Issue by slaymance** [aws-amplify/amplify-ui#1185]
### On which framework/platform would you like to see this feature implemented?

React, Angular, Vue

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Similar to our [changes to documentation](https://github.com/aws-amplify/amplify-ui/pull/1132), we want to update our references to `country_code` in the Authenticator components and state machine to a different variable name.

### Please describe a solution you'd like.

The new variable name can be `regionCode` to match the update to our documentation.

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [X] ⚠️ This feature might incur a breaking change.

**Comment by Milan-Shah** [comment]
@slaymance When we start the implementation for this, lets keep the variable name as regionOrCountryCode. We are required to not only say region or country alone. CC: @zchenwei

**Comment by reesscot** [comment]
Moved to internal ticket queue, since this is not an customer facing issue
