### ISSUE TITLE
withAuthenticator is giving lots of errors

### ISSUE THREAD

**Issue by spharsh** [aws-amplify/amplify-ui#1194]
I have created a small app and linked it with dynamoDB. It is a simple blog app, and I can see and retrieve my posts. But the moment I add withAuthenticator after doing amplify add auth, my website is not working, and there are so many errors.

All these errors go away, moment I remove this withAuthenticator from App.js.

Can someone please help me with this? I need to add sign-in and sign-out and that's why I am using AWS cognito service.

below is the simple code
import React from 'react';
import './App.css';
import CreatePost from './components/CreatePost';
import DisplayPosts from './components/DisplayPosts';
**import { withAuthenticator } from 'aws-amplify-react'**

function App() {
  return (
    <div className="App">
      <CreatePost />
      <DisplayPosts />
    </div>
  );
}

**export default withAuthenticator(App);**

**Comment by ErikCH** [comment]
Hi @spharsh !

It looks like you are using our older `aws-amplify-react` library. Can you try using our new one? 

https://ui.docs.amplify.aws/getting-started/installation

Is there a reason why you are trying to use the older one?

**Comment by spharsh** [comment]
> Hi @spharsh !
> 
> It looks like you are using our older `aws-amplify-react` library. Can you try using our new one?
> 
> https://ui.docs.amplify.aws/getting-started/installation
> 
> Is there a reason why you are trying to use the older one?

Hi Eric,

Thanks for the reply and yes I figured it out yesterday. I guess I wasn't updated enough!

Harsh

**Comment by wlee221** [comment]
We'll go ahead and close this issue as per @ErikCH's suggestion, but please let us know if you come across any issues!
