### ISSUE TITLE
SMS MFA Wrong code entered string not translating

### ISSUE THREAD

**Issue by jerocosio** [aws-amplify/amplify-ui#1200]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

When a user inputs a wrong SMS MFA code after logging in, the string shown can't be translated using the regular translation file, I'm trying to achieve it through:

`
"Invalid code or auth state for the user.":
    "Código de verificación incorrecto, por favor vuelva a intentarlo.",
`

But it's not working. 

### What's the expected behaviour?

To be able to translate the 'Invalid code or auth state for the user.' text to any language whenever a user introduces the wrong code.

### Help us reproduce the bug!

Set up a translation language, add the string you want to translate 'Invalid code or auth state for the user.', enter a wrong SMS MFA Code on Authenticator, and the error string doesn't change.

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

<img width="529" alt="Screen Shot 2022-01-26 at 9 12 35 p m" src="https://user-images.githubusercontent.com/933413/151285471-42d510f0-0f9a-4a38-9160-82e18a44bfd0.png">

**Comment by jerocosio** [comment]
Same happens whenever the code has expired as this string can't be translated also: 'Invalid session for the user, session is expired.'

I tried to find both of this strings on the code base but I couldn't find them.

**Comment by ErikCH** [comment]
Hi @jerocosio !

I'll add those translations thanks!

**Comment by Milan-Shah** [comment]
Thanks @ErikCH for adding the fix. @jerocosio Please reopen the issue if it doesnt resolve your issue!
