### ISSUE TITLE
[missing-page] Broken link on installation page

### ISSUE THREAD

**Issue by Jezzabell91** [aws-amplify/amplify-ui#1211]
**Page**: [`https://ui.docs.amplify.aws/theme`](https://ui.docs.amplify.aws/theme)
**Feedback**:  In the [`styles`](https://ui.docs.amplify.aws/getting-started/installation#styles) section the theme link is broken.

**Comment by ErikCH** [comment]
Thanks @Jezzabell91 ! I do see a broken link in the styles getting started section! We'll get a fix up for that.

**Comment by ErikCH** [comment]
This fix has been merged. It will be available on the live site shortly. Please reopen if this occurs again.
