### ISSUE TITLE
Angular with amplify-authenticator + onAuthUIStateChange breaks angular refresh

### ISSUE THREAD

**Issue by reg19b** [aws-amplify/amplify-ui#1218]
**Describe the bug**
Folowwing the documentation to add an apmlify-authenticator that updates when userState changes lead to break angular mechanism 
([https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#manage-auth-state-and-conditional-app-rendering](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#manage-auth-state-and-conditional-app-rendering))

Then, the routing does not correctly work, as angular material Dialogs.
In fact, it seems that any DOM component that is added after does not correcly work.
Maybe it is due to the use of ` ChangeDetectorRef detectChanges()`. But if we don't use it, nothing is refresh.

**Comment by Rajan-Gupta1** [comment]
@wlee221 I have spent time looking at the documentation at the link provided above for angular but unable to determine how I can call use route as part of amplify-authenticator . 
What I am trying to do is to call a method after a successful login.
