### ISSUE TITLE
Keep Specificity of all selectors to 010 to allow CSS-in-JS overrides

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1236]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I'm using [Stitches](https://stitches.dev/) to style the Heading component but it's not working as expected. Example:
```ts
import { Heading } from "@aws-amplify/ui-react";
import { styled } from "src/utils/stitches.config.js";
const StyledHeading = styled(Heading); // or styled(Heading, { fontSize: "$xxl" }) doesn't work as well

function MyHeading() {
  return <StyledHeading css={{ fontSize: "$xxl" }} /> // xxl token defined in theme
}
```

### Please describe a solution you'd like.

Could the specificity of the styles applied to the Heading component be reduced?

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by dbanksdesign** [comment]
@jacoblogan did the work to make all selector specificity at 010. I tried it out with Emotion and it works like a charm. Haven't tried with Stitches, but I assume it will work there too.

**Comment by jacoblogan** [comment]
I just verified with Stitches you should be good to go @bestickley, please let me know if you are still seeing this issue.

**Comment by bestickley** [comment]
Will do, thank you @jacoblogan!
