### ISSUE TITLE
React : Outdated documentation in main docs for hiding Authenticator fields

### ISSUE THREAD

**Issue by ibussieres** [aws-amplify/amplify-ui#1237]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

Documentation in the [new doc portal](https://ui.docs.amplify.aws/components/authenticator#sign-up-fields) seems up to date but does not explain how to hide fields, specifically the username field which appears to be a common request when paired with the `usernameAlias={"email"}` prop and value.

However, this is explained in the [main docs](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#hiding-form-fields), but using `AmplifyAuthenticator`, `AmplifySignIn` and `AmplifySignOut` imports which are not supported in the most recent version.

The same applies to [this portion](https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js/) of the main docs.

### What's the expected behaviour?

Updated docs should reflect the most recent changes to Authenticator API and `ui-react`.

### Help us reproduce the bug!

This is a documentation issue.

**Comment by ErikCH** [comment]
Hi @ibussieres !

We have ways you can customize the sign up form, that you already linked. 
https://ui.docs.amplify.aws/components/authenticator#sign-up-fields

The example shows a way to add additional fields, which you can also do using the `[signUpAttribute](https://ui.docs.amplify.aws/components/authenticator#signupattributes)`

We don't really have a straight forward way of removing fields yet. We are looking into adding back in the `formFields` custom prop, which could be used to add some new features including removing, reordering, and adding placeholders. I'll update this issue as soon as we have this in place!

**Comment by ibussieres** [comment]
@ErikCH  Thanks !

I hadn't realized the `formFields` custom prop was explicitly removed. I just thought the docs were outdated.
However, maybe you can point me towards a quick way to achieve the same form fields as in those docs you sent me. That is precisely what I am trying to achieve, and when I use the snippet, it of course uses a username field instead of email.

Email (not username)
Password
Password Confirmation

**Comment by ErikCH** [comment]
Hi @ibussieres !

Sorry for the delay.

For what you are asking you should be able to use some of our configuration props.

Make sure you are using the latest version of the amplify [CLI](https://docs.amplify.aws/cli/). It should automatically detect that you setup your account using `email` and not `username`. The amplify UI will then show an `email` field instead of a `username` field.

If that's still not working add a `loginMechanisms` prop to your application. Make sure to only add in `['email']` as seen in this [documentation](https://ui.docs.amplify.aws/components/authenticator#login-mechanisms)

Let me know if that fixes your issues. Otherwise I'll close this.

**Comment by ErikCH** [comment]
Closing this for now! Please reopen if the issue still occurs.
