### ISSUE TITLE
Amplify Authenticator UI for Web

### ISSUE THREAD

**Issue by ReinaldoGonzaga** [aws-amplify/amplify-ui#1240]
### On which framework/platform would you like to see this feature implemented?

Flutter

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Amplify Authenticator UI for Web in the pub.dev (not only IOs and Android).
Tks

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@ReinaldoGonzaga Have you see the Flutter Authenticator released in Preview? https://docs.amplify.aws/ui/auth/authenticator/q/framework/flutter
does this address your need, or do you need something else?
