### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1245]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

N/A

### Please describe your bug.

Cannot import `IconLogout` even though Logout is an icon listed on MDI site: https://fonts.google.com/icons?icon.query=logout. See screenshot below.

### What's the expected behaviour?

Should be able to import `IconLogout`.

### Help us reproduce the bug!

N/A

### Code Snippet

N/A

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/35735118/152356338-72303104-dec1-44a5-9386-5e2faf430085.png)

**Comment by bestickley** [comment]
Noticed this is also true of `Manage Accounts` icon

**Comment by dbanksdesign** [comment]
We are actually considering removing all built-in icons because it is a pain for issues like this, and instead direct users to import whichever icon library they want (like react-icons for example). What are your thoughts on that?

**Comment by bestickley** [comment]
@dbanksdesign I agree with that consideration. `react-icons` is great and I'll use it in my projects as an alternative. Thank you for the insight!
