### ISSUE TITLE
Authenticator components customization not working for several steps

### ISSUE THREAD

**Issue by msolano00** [aws-amplify/amplify-ui#1256]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

Customization for several steps (ResetPassword, ForgotPassword, ConfirmSignIn) isn't being reflected. I am trying to add a custom `Header` and `Footer` to each one of these and it is still showing the same default behavior.

### What's the expected behaviour?

Custom components used in the Authenticator `components` object should update the different views in the router.

### Help us reproduce the bug!

Steps:

1. Please use the attached code snippet for the components property in the Authenticator
2. Start the app
3. Click on `Reset your password`

### Code Snippet

```javascript
import React from 'react';
import styled from '@emotion/styled';
import Amplify, { Auth } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/dist/styles.css';

Amplify.configure({
  Auth: {
    region: process.env.REACT_APP_COGNITO_CONFIG_REGION,
    userPoolId: process.env.REACT_APP_COGNITO_CONFIG_USERPOOL_ID,
    userPoolWebClientId: process.env.REACT_APP_COGNITO_CONFIG_USERPOOL_WEBCLIENT_ID,
    mandatorySignIn: process.env.REACT_APP_COGNITO_CONFIG_MANDATORY_SIGNIN,
    authenticationFlowType: process.env.REACT_APP_COGNITO_CONFIG_AUTHENTICATION_FLOW_TYPE,
  },
});

function LoginHeader() {
  return(
    <div>
      This is the header
    </div>
  );
};

export default function App() {
  const components = {
    Header() {
      return <div style={{ marginTop: '100px' }} />;
    },
    SignIn: {
      Header() {
        return <LoginHeader />;
      },
    },
    ResetPassword: {
      Header() {
        return <LoginHeader />;
      },
    },
  };

  return (
    <Authenticator components={components}>
      {({ signOut, user }) => (
        <ThemeProvider
          customTheme={{
            breakpoints: createBreakpoints({
              xxs: 1000,
              xs: 1100,
              anyOtherName: 1200,
            }),
          }}
        >
          <div>
            Just a test  
          </div>
        </ThemeProvider>
      )}
    </Authenticator>
  );
};

```

**Comment by msolano00** [comment]
Here is a sandbox example: https://codesandbox.io/s/amplify-customization-issue-0dd11

**Comment by ErikCH** [comment]
Hi @msolano00 !

Yes, we are missing those pages! We'll add this as a bug, since it seems like you can overwrite headers and footers in Vue and Angular for those pages, just not React.

**Comment by nk9** [comment]
I note that there is also an issue requesting a checkbox to let users remember the current device. Work for that may happen in [`ConfirmSignIn`](https://github.com/aws-amplify/amplify-ui/blob/f7f77237e69272f1d1d878620946e2914354b503/packages/react/src/components/Authenticator/ConfirmSignIn/ConfirmSignIn.tsx), so it would be good to get these taken care of at the same time if possible. See #1271

**Comment by ErikCH** [comment]
This has been added in! Should be in the next release. Please reopen if you have issues.

**Comment by msolano00** [comment]
Hi @ErikCH!

Reset password works well but confirmSignIn is still not working. Can you confirm this was added in the release?

@SWechterMcKinsey

**Comment by ErikCH** [comment]
Hi @msolano00 ! Is it the header and footer? I do see it's in the release, we added a test for it too. 

If you're still having issues, feel free to open a new issue, and we can try to reproduce it.
