### ISSUE TITLE
Export AuthenticatorProps

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1265]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Could the `AuthenticatorProps` be exported? I'm trying to create a wrapper `MyAuthenticator` component that accepts `AuthenticatorProps` plus some additional props

### Please describe a solution you'd like.

`import type { AuthenticatorProps } from "@aws-amplify/ui-react";`

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by bestickley** [comment]
It would also be great if more types could be exported like `SignUpAttributes` too.

**Comment by calebpollman** [comment]
@bestickley The `AuthenticatorProps` interface is available for import from `@aws-amplify/ui-react`. Please open an another issue if there are more types you would like to see exported!
