### ISSUE TITLE
Authenticator SignIn with TOTP - user attributes missing

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1270]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### Please describe your bug.

I've enabled MFA on my Cognito User Pool with TOTP. On login, the `user` param in the function which is a child to `Authenticator` component does not contain `user.attributes.email` or `user.attributes.given_name` or `user.attributes.family_name` which are required attributes in my user pool. However, when I refresh they are available. Is this intended behavior? Regardless, it would be nice if Authenticator component made sure these values were present.

I'm showing the user info in the account menu of the header and because of this it's currently blank (although I did find a workaround - see below).

### What's the expected behaviour?

`user` contains `attributes` with attributes that were filled out on sign up.

### Help us reproduce the bug!

I think this bug is simple enough to not need a reproduction environment but I can if needed.

### Code Snippet

Here is the workaround I have right now. I added this snippet into the child component of Authenticator.
```typescript
const {
    signOut,
    user: initUser,
  } = props;
const [user, setUser] = useState(initUser);
useEffect(() => {
    async function getUserAttributes() {
      const attributes = await new Promise<Record<string, string>>(
        (resolve, reject) =>
          user.getUserAttributes((err, result) => {
            if (err) reject(err);
            if (result) {
              resolve(
                result.reduce(
                  (prev, cur) => ({ ...prev, [cur.Name]: cur.Value }),
                  {} as Record<string, string>
                )
              );
            } else {
              throw new Error("getUserAttributes returned undefined");
            }
          })
      );
      setUser((u) => ({ ...u, attributes } as CognitoUser));
    }
    if (!user.attributes) getUserAttributes();
  }, [user]);

```
 `user` is passed to my `<Header />` which will re-render when it's updated showing the correct info.

**Comment by ErikCH** [comment]
Hi @bestickley !

I was looking at this, and you are right. When a user first logs in, we save the data from the `Auth.signIn` and push it into our store. That data does NOT have the `user.attributes` in it.

When you refresh the browser, we run a `Auth.currentAuthenticatedUser()` which adds in that `attribute` section. We'll need to look into a way that it behaves the same way.

As a workaround for now, you can grab the attributes in a different way. Instead of grabbing it from `user.attributes`, you can find all that data in the `idToken` at `user.signInUserSession.idToken.payload`. Could you try that and see if the data you are looking for is there?

**Comment by bestickley** [comment]
Hey @ErikCH, great tip! Thanks so much. Do you have any recommendations for typing the user when utilizing that payload? I came up with this but I guess it'll be different for each user pool:

```ts
export type CognitoUser = CognitoUserAmplify & {
  attributes?: Record<string, string>;
  signInUserSession: {
    idToken: {
      payload: {
        aut: string;
        auth_time: number;
        "cognito:groups": string[];
        "cognito:username": string;
        email: string;
        email_verified: string;
        event_id: string;
        exp: string;
        family_name: string;
        given_name: string;
        iat: string;
        iss: string;
        jti: string;
        origin_jti: string;
        sub: string;
      };
    };
  };
};
```

**Comment by ErikCH** [comment]
Hi @bestickley !

That is something we haven issue [on](https://github.com/aws-amplify/amplify-ui/issues/1064). The `CognitoUserAmplify` is missing some attributes.

For now, creating your own type would be your best bet.  That looks good.

**Comment by ErikCH** [comment]
This issue has been fixed, and has been released! Please try out the latest version of the authenticator, and reopen this issue if it occurs again

**Comment by jonathanlb** [comment]
I'm having a similar issue using @aws-amplify/ui-vue version 2.3.1 (released yesterday)?  Should I open another issue, or did the fix not get pushed out to npm, yet?

Here's a snippet demonstrating the missing attributes using the Vue.js Authenticator (authentication credentials are also unavailable):

```
<template>
  <authenticator :hide-sign-up="true">
    <template v-slot="{ user, signOut }">
      <!-- undef user fields 1st time only -->
      <p>Hello {{ user?.attributes?.name }}!</p>
      <!-- other AWS access, e.g. S3 reads, fail 1st time, too. -->
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

<script>
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import Amplify from 'aws-amplify';
import awsconfig from './aws-exports'; // amplify config

Amplify.configure(awsconfig);

export default {
  name: 'App',
  components: {
    Authenticator
  },
  data() {
    return {}
  }
}
</script>
```

**Comment by ErikCH** [comment]
Yes, please open a new issue and we can try to reproduce it.

**Comment by bestickley** [comment]
@ErikCH, I switched to the `useAuthenticator` hook instead of using a function as a child of `<Authenticator>` and now I'm getting the same issue. I've configured auth with TOTP so this is right after I use TOTP MFA. The issue only appears on the first login of the user. After refreshing it works correctly.

Relevant code:
```ts
function Header(props: HeaderProps): ReactElement {
  const { accountMenuBc, setOpen, open, title } = props;
  const { user, signOut } = useAuthenticator();
  const [leftOpen, setLeftOpen] = useState(false);
  const bps = useBps();
  const navigate = useNavigate();
  const username = user.username;
  let email = "",
    family_name = "",
    given_name = "";
  if (user.attributes) {
    email = user.attributes.email;
    family_name = user.attributes.family_name;
    given_name = user.attributes.given_name;
  }
  const fullName = `${given_name} ${family_name}`;
  ....
}
```
And here is the user object when I set a breakpoint right after the `userAuthenticator` hook:
![Screen Shot 2022-03-24 at 10 39 36 AM](https://user-images.githubusercontent.com/35735118/159943392-d5320f97-c772-4533-aaa7-097bcd65c79a.png)
