### ISSUE TITLE
Token Pagination - Handle undefined totalPages

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1287]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I'm building a table with pagination for a DynamoDB table where I don't know the total number of pages. Currently, with the `Pagination` component, it requires `totalPages`. Could the `Pagination` component handle the case where `totalPages` is given?

### Please describe a solution you'd like.

When no total pages is given, let the next page item be ellipses but show previous page numbers items as they can be jumped to as user can cache data client side.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Discussed offline with @bestickley that the core ask here is that Pagination can be used with an API where the total number of pages is unknown until you reach the last page of data. 

We are planning on solving this issue by adding an additional `hasMorePages` prop. Users will be able to combine this `hasMorePages` prop with `totalPages` (which will remain a required prop). In this use case `totalPages` will indicate the total pages of content loaded from the API _so far_ and `hasMorePages` will indicate when the end of the data has been reached (and thus the Pagination component's next button will be disabled).
