### ISSUE TITLE
The Image primitive cannot display local image files

### ISSUE THREAD

**Issue by matriedel** [aws-amplify/amplify-ui#1300]
Steps to reproduce the issue

Use App.js example from https://ui.docs.amplify.aws/

- Make an image file "LocalPicture.png" available in App.js folder 
- Replace Image src link to a local image file e.g. 
         "Image src="./LocalPicture.png"
- Run app and you see the broken image symbol

**Comment by reesscot** [comment]
Hi @matriedel, I think what you are seeing is that an image must be hosted to be loaded via HTTP. You can see that the Image component is able to render images which are hosted in this [example](https://ui.docs.amplify.aws/components/image).
