### ISSUE TITLE
"Back to sign in" button on password change screen does not work

### ISSUE THREAD

**Issue by mmarinova-mm** [aws-amplify/amplify-ui#1305]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Webpack 5

### Please describe your bug.

When logging in with a user for the first time, they are shown the screen to set their permanent password. If they click the "Back to Sign In" button, nothing happens.
![image](https://user-images.githubusercontent.com/13468194/153653343-973eb62e-11db-48e7-aa79-4f92c6b33e1e.png)

### What's the expected behaviour?

I expect the user to be taken back to the first screen and to be able to try logging in with different credentials.

### Help us reproduce the bug!

1. Have a user that is in the FORCE_CHANGE_PASSWORD state.
2. Use the Authenticator component, enter the users username and temporary password.
3. When on the Change Password screen, click on "Back to Sign In".
4. Nothing happens.

### Code Snippet

```typescript
// Irrelevant code ommitted with '...'
// Login.vue
<template>
  <div>
    ...
    <Authenticator>
      ...
      <template v-slot:force-new-password-header>
        <h3 class="heading">Change Password</h3>
        <p>...</p>
      </template>
    </Authenticator>
  </div>
</template>

<script>

import Amplify, { Auth, Hub } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-vue';

import '@aws-amplify/ui-vue/styles.css';

export default {
  components: {
    Authenticator,
  },
  setup() {
    Amplify.configure({
      Auth: {
        userPoolId: XXX,
        userPoolWebClientId: YYY,
        cookieStorage: {
          domain: window.location.hostname,
          expires: 1,
          sameSite: 'strict',
          secure: true,
        },
      },
    });

    Hub.listen('auth', (data) => {
      if (data.payload.event == 'signIn') {
        ...
      }
    });
  },
};
</script>

```

### Additional information and screenshots

Workaround is to refresh the page and start over.

Versions:
ui-vue: 2.0.10
aws-amplify: 4.3.13
vue: 3.2.29
webpack: 5.67.0

**Comment by ErikCH** [comment]
Hi @mmarinova-mm! I was able to reproduce this on Vue, React and Angular! We'll put it on the roadmap to get done soon!

**Comment by ErikCH** [comment]
This has been fixed, and will be in our next release soon!

**Comment by mmarinova-mm** [comment]
Thank you for the fast resolution!
