### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by ShawnCockburn** [aws-amplify/amplify-ui#1312]
[docs/src/pages/getting-started/installation/dependencies.react.mdx line 28](https://github.dev/aws-amplify/amplify-ui/blob/b4bc4d528ff061ea2d7750d335f3fa4913f90433/docs/src/pages/getting-started/installation/dependencies.react.mdx#L28) is:

```js
export default = () => (
```

**but it should be:**

```js
export default () => (
```

**Comment by wlee221** [comment]
Thanks, I have made the adjustment in #1316.
