### ISSUE TITLE
Link Component Theme: visited link color takes priority over focus and hover colors

### ISSUE THREAD

**Issue by Jesmaster** [aws-amplify/amplify-ui#1334]
For links generated with the Link component, when hovering over a visited link the color does not change to the hover color, same for focus.

Can easily replicate with the following theme override
```
components: {
            link: {
                hover: { color: { value: "green" } },
                visited: { color: { value: "hotpink" } },
            },
}
```

**Comment by reesscot** [comment]
It looks like this would be a matter of [moving](https://developer.mozilla.org/en-US/docs/Web/CSS/:visited) the :visited styles above :active. @Jesmaster are you interested in submitting a PR to fix this? 

Code is here:
https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/theme/css/component/link.scss#L19-L22
