### ISSUE TITLE
Authenticator.Provider gives undefined element type

### ISSUE THREAD

**Issue by Robert-Forrest** [aws-amplify/amplify-ui#1345]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

I want to use Authenticator.Provider to give access to authentication info elsewhere via useAuthenticator.

When I wrap my app in the Authenticator.Provider the following error is thrown before any rendering can occur:

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

I am however able to wrap the app in the withAuthenticator HOC with no errors, but this locks down the entire app to being behind authentication when I want to have some public pages. I also want to use a customised Authenticator component, and I am not sure how to do this with the HOC, while I can simply load my custom Authenticator component on the /login page otherwise. 

### What's the expected behaviour?

No error is thrown, useAuthenticator can be used throughout the app to access authentication information.

### Help us reproduce the bug!

react: ^17.0.2
aws-amplify/ui-react: ^2.3.0
next: ^12.0.10

### Code Snippet

```javascript
import Amplify from 'aws-amplify'
import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react'
Amplify.configure({ ... })

function App({ Component, pageProps }) {
  return <Component {...pageProps} />      
}
export default () => (
  <Authenticator.Provider>
    <App/>
  </Authenticator.Provider>
)
```

**Comment by wlee221** [comment]
This looks like a bug on studio, will transfer this to adminui repo 🙏

**Comment by wlee221** [comment]
> I am however able to wrap the app in the withAuthenticator HOC with no errors, but this locks down the entire app to being behind authentication when I want to have some public pages.

Right, `withAuthenticator` is more for SPA usage and is not suitable for routed Apps.

**Comment by wlee221** [comment]
The reason your code snippet doesn't work is because you're not passing `{ Component, pageProps }` to your default export. It should be:

```diff
- export default () => (
+ export default (props) => (
  <Authenticator.Provider>
-   <App/>
+   <App {...props} />
  </Authenticator.Provider>
)
```

I created a codesandbox similar to your case for your reference: https://codesandbox.io/s/nextjs12-authenticator-p39p18?file=/pages/_app.js 🙏

**Comment by wlee221** [comment]
I'm closing this issue as per proper syntax is suggested, but please let us know if the problem persists. 

I'll also a create a docs issue for https://ui.docs.amplify.aws/getting-started/installation#packages to include `next.js` snippets.
