### ISSUE TITLE
Authenticator Signin triggers .GetUser API twice

### ISSUE THREAD

**Issue by jamesaucode** [aws-amplify/amplify-ui#1385]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

The Amplify UI React Authenticator fetches data from the `.GetUser` api on Cognito twice instead of just once.

### What's the expected behaviour?

Should only fetch data from `.GetUser` once.

### Help us reproduce the bug!

1. Create a React app with Create React App.
2. Initialize an amplify project with the cli `amplify init`
3. Add `Auth` to the application
4. Install `aws-amplify` and `@aws-amplify/ui-react`
5. Add the Authenticator component to the application
6. Create a user
7. SignIn
8. Go to the network tab, you should see 2 API request to the `.GetUser` API on cognito

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

package.json
```json
{
  "name": "auth-test-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^2.4.0",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.0.3",
    "@types/node": "^16.11.14",
    "@types/react": "^17.0.37",
    "@types/react-dom": "^17.0.11",
    "aws-amplify": "^4.3.12",
    "qrcode.react": "^1.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "typescript": "^4.5.4",
    "web-vitals": "^2.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/qrcode.react": "^1.0.2"
  }
}
```

**Comment by ErikCH** [comment]
Thanks @jamesaucode ! I'll look at this.

**Comment by wlee221** [comment]
Hi @jamesaucode, sorry for leaving this open for so long. 

It is expected we call `Auth.getUser` more than once as per implementation detail. We don't have a guaranteed contract what that number should be, so I wouldn't rely on that behavior for your unit tests if applicable. Please let us know if you got questions or concerns!
