### ISSUE TITLE
Sidebar not scrolling for the Amplify UI website 

### ISSUE THREAD

**Issue by techandmedia** [aws-amplify/amplify-ui#1398]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Nextjs

### Please describe your bug.

Side bar for Amplify UI website is not able to scroll, must zoom in to 50% to see the side bar

### What's the expected behaviour?

Side bar able to scroll

### Help us reproduce the bug!

https://ui.docs.amplify.aws/component
![Capture](https://user-images.githubusercontent.com/15700861/155528213-cdfc7892-0420-4ded-80c5-8c79c160ca5c.JPG)

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ErikCH** [comment]
Hi @techandmedia !

I'm on a mac using chrome and I was able to scroll the side bar using my mouse. 

Are you a mac? Have you checked your mac scroll bar settings? 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/65630/156077099-0145623f-7b3e-444b-a650-808669a3b1c1.png">

What browser and OS are you using?

**Comment by ErikCH** [comment]
I'm going to close this issue @techandmedia . Please re-open it if it continues to occur.
