### ISSUE TITLE
FR (Primitives): Multi-Select Component

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1405]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Vite

### Please describe your bug.

When using the component `SelectField` with the `multiple` attribute, if I add more than 3 options it overflows below the select box.

### What's the expected behaviour?

Select box encapsulate all options when `multiple` is enabled.

### Help us reproduce the bug!

See below

### Code Snippet

```typescript
<SelectField
        label="Components:"
        multiple
        placeholder="Select Components"
      >
        <option value="component-1">Component 1</option>
        <option value="component-2">Component 2</option>
        <option value="component-3">Component 3</option>
        <option value="component-3">Component 4</option>
        <option value="component-3">Component 5</option>
      </SelectField>

```

### Additional information and screenshots

![image (4)](https://user-images.githubusercontent.com/35735118/155602384-f2ade458-5227-495f-9f17-578a5c8f2dbd.png)
![image (3)](https://user-images.githubusercontent.com/35735118/155602386-c355f7db-8ed5-4fc7-882b-266a47f79cc0.png)

**Comment by zchenwei** [comment]
Thanks for bring this up! I would think of it more like a feature request versus a bug. We didn't consider the `multiple` use case when design `SelectField`

**Comment by bestickley** [comment]
@zchenwei, ah I see. Do you mind removing the "bug" label and adding "feature-request"? Thank you!

**Comment by zchenwei** [comment]
> @zchenwei, ah I see. Do you mind removing the "bug" label and adding "feature-request"? Thank you! I don't seem to be able to.

Sure. There we go!

**Comment by rainbowfeathersfarm** [comment]
Hey All, in case anyone runs across this before it is implemented, I got help from someone on the Discord chat to add the following CSS to get it to work until then.

`.amplify-select[multiple] {
  overflow: auto;
}`

Seems obvious after seeing it, but for someone like me who works more on the backend API side than the front end UI, it was very helpful for me.

**Comment by hbuchel** [comment]
To add to this, we should probably:
- hide the dropdown arrow when `multiple` attribute is used.
- Allow for setting a size (though unfortunately this clashes with our 'size' variant prop) so we might have to re-name it (selectSize or something). This is default behavior in HTML select element https://codepen.io/hbuchel/pen/ExGYxdE

**Comment by hbuchel** [comment]
Marking as completed; support for the `multiple` and `size` attributes were added in [@aws-amplify/ui-react@5.3.1](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react%405.3.1) Please see [updated documentation ](https://ui.docs.amplify.aws/react/components/selectfield#multiple-selections)
