### ISSUE TITLE
TextAreaField is not exported from @aws-amplify/ui-react

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1413]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Vite

### Please describe your bug.

TextAreaField is not exported from `@aws-amplify/ui-react`. I checked the code and it looks like it's being exported but I'm not able to import.

### What's the expected behaviour?

TextAreaField is exported from `@aws-amplify/ui-react`

### Help us reproduce the bug!

N/A

### Code Snippet

N/A

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/35735118/155640100-f71d050a-063c-4457-9157-e8c1849052a4.png)

**Comment by zchenwei** [comment]
`TextAreaField` is available on version `2.6.1` and above. Did you upgrade your `@aws-amplify/ui-react`? Thanks!

**Comment by bestickley** [comment]
@zchenwei, yes, I'm on 2.6.2. As you can see in the screenshot, the props are being exported but not `TextAreaField`

**Comment by zchenwei** [comment]
<img width="644" alt="Screen Shot 2022-02-25 at 11 38 35 AM" src="https://user-images.githubusercontent.com/40295569/155784096-134f7503-da77-485b-a4f6-21995cd9c4e6.png">

I am on 2.6.2..But I can load the `TextAreaField`. Did you check your lock file to see if the version is correct?

**Comment by bestickley** [comment]
Reloading my VS Code window worked! Apologize for the false alarm. Thank you, @zchenwei !

**Comment by dbanksdesign** [comment]
@bestickley  one VSCode shortcut I use regularly is `Typescript: Restart TS server` from the command palette
