### ISSUE TITLE
[React] Authenticator forgot password uncaught exception in 2.6 release

### ISSUE THREAD

**Issue by yyao84** [aws-amplify/amplify-ui#1414]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

The Authenticator component produces an uncaught (in promise) exception in xstate after resetting password.  This issue is not apparent in @aws-amplify/ui-react@2.5.0.  The password is reset, but the dialog hangs due to the exception.

### What's the expected behaviour?

After inputting the reset code, new password and confirm password, then selecting "Submit," the dialog should take me back to the sign in prompt (or log me in, I don't recall how it was supposed to work). With 2.5.0 it takes me back to the sign in.

### Help us reproduce the bug!

Select "Forgot your password?"
> Input username, password, confirm password
> Submit
> Uncaught exception here

Cognito pool configuration: 
```
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "email",
      "email_verified"
    ],
```

### Code Snippet

```typescript
                    <Authenticator>
                        {({ signOut, user }) => (
                            <Box>
                                <Button onClick={signOut}>Log Out</Button>
                            </Box>
                        )}
                    </Authenticator>
```

### Additional information and screenshots

Full exception:
```
Uncaught (in promise) TypeError: e.data is undefined
    actorDoneData index.ts:182
    updatedContext utils.js:368
    updateContext utils.js:350
    resolveActions actions.js:415
    resolveTransition StateNode.js:890
    transition StateNode.js:826
    nextState interpreter.js:703
    provide serviceScope.js:8
    nextState interpreter.js:702
    send interpreter.js:105
    process scheduler.js:65
    schedule scheduler.js:44
    send interpreter.js:101
    spawnMachine interpreter.js:980
    update interpreter.js:305
    send interpreter.js:107
    process scheduler.js:65
    schedule scheduler.js:44
    send interpreter.js:101
    spawnPromise interpreter.js:1007
    promise callback*./node_modules/xstate/es/interpreter.js/Interpreter.prototype.spawnPromise interpreter.js:1001
    spawn interpreter.js:929
    exec interpreter.js:866
    execute interpreter.js:201
    update interpreter.js:227
    send interpreter.js:107
    process scheduler.js:65
    schedule scheduler.js:44
    send interpreter.js:101
    spawnPromise interpreter.js:1007
    promise callback*./node_modules/xstate/es/interpreter.js/Interpreter.prototype.spawnPromise interpreter.js:1001
    spawn interpreter.js:929
    exec interpreter.js:866
    execute interpreter.js:201
    update interpreter.js:227
    send interpreter.js:107
    process scheduler.js:65
    schedule scheduler.js:44
    send interpreter.js:101
    sendTo interpreter.js:133
    exec interpreter.js:790
    execute interpreter.js:201
    update interpreter.js:227
    send interpreter.js:107
    process scheduler.js:65
    schedule scheduler.js:44
    send interpreter.js:101
    node_modules bundle.js:51296
    node_modules bundle.js:48115
```

**Comment by wlee221** [comment]
Thanks @yyao84, I could repro this -- looking into it

**Comment by wlee221** [comment]
Fix has been merged and will be on our next release, planned tomorrow @4pm PST. You can track our release in #1420. 

Please let us know if problem persists after release 🙏
