### ISSUE TITLE
Changing initialState props don't reflect changes to the Authenticator. 

### ISSUE THREAD

**Issue by artidata** [aws-amplify/amplify-ui#1427]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I have 2 buttons, sign in and sign up button outside the authenticator component. I wish that when the user press sign in, the authenticator will be in the `signIn` route. Whereas, when the user press sign up, the authenticator will be  in the `signUp` route. I thought that changing the `initialState` props alllow that, apparenly No. Let me know if there is existing solution on this. Hope this [codesandbox](https://codesandbox.io/s/inspiring-cohen-0ygnm4?file=/src/App.js) help.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
Hi @artidata !

The initialState prop isn't reactive, the way you are expecting it to be.

The better way of doing this is to use the `useAuthenticator` hook and use the trigger transitions `toSignIn` and `toSignOut`. The only caveat is that you wrap your app in a `Authenticator.Provider` or use the `withAuthenticator` wrapper.

I made a code sandbox illustrating how this works here.
https://codesandbox.io/s/condescending-hellman-4v1lx2?file=/src/App.js

Here is the documentation on it. https://ui.docs.amplify.aws/components/authenticator#trigger-transitions

Let me know if this solves the problem, and I'll close this issue.

**Comment by artidata** [comment]
Thanks @ErikCH,  the docs doesn't mention exhaustively on what's retrieved when invoking the `useAuthenticator` hook. But yeah sandbox helps. You can close the issue.

**Comment by Milan-Shah** [comment]
Thanks @ErikCH . @artidata Let us know if you have any other issues :)
