### ISSUE TITLE
Authenticator handleConfirmSignUp not receiving password as indicated in documentation

### ISSUE THREAD

**Issue by stellarjaysoftware** [aws-amplify/amplify-ui#1448]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

The documentation says handleConfirmSignUp will be passed {username, code, password}:
https://ui.docs.amplify.aws/components/authenticator#override-function-calls

Using the override in my app and looking at the source code shows that it does not return password, only username and code:
https://github.com/aws-amplify/amplify-ui/blob/88b15eb9aa608b58ca84fbf60e1beba8090f32e2/packages/ui/src/machines/authenticator/defaultServices.ts#L37

### What's the expected behaviour?

Expected behavior is that handleConfirmSignUp would be passed the password as the documentation says it should.

### Help us reproduce the bug!

Create an app that uses the handleConfirmSignUp override and set a breakpoint inside the function.

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

This screenshot shows that username and code are sent to handleConfirmSignUp, but password is not:
![authenticator-handleConfirmSignUp](https://user-images.githubusercontent.com/64604698/156455434-9950cd1a-e3dd-46a6-ae42-f799b72fed9d.png)

**Comment by ErikCH** [comment]
Hi @stellarjaysoftware !

You are right, the documentation we have is wrong. You cannot pass a `password` to `confirmSignUp`! The Confirm sign up page only asks for a `username` and a `code`. So no need for a password.

I will push up a fix for that soon!

**Comment by ErikCH** [comment]
I have fixed the documentation issue. Closing this issue
