### ISSUE TITLE
"Messages" not reaching chatbot from s3 

### ISSUE THREAD

**Issue by nwokdean** [aws-amplify/amplify-ui#1465]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Chatbot

### How is your app built?

amplify, 

### Please describe your bug.

{ "status": "Error", "data": { "errors": [ { "errorType": "UnauthorizedException", "message": "Permission denied" } ] } } 

Issue we are getting for Amplify UI application. 

### What's the expected behaviour?

The automation should run end to end, and the message in s3 should be available in chatbot. 

### Help us reproduce the bug!

S3 to SQS by way of lambda..

### Code Snippet

const AWS = require('aws-sdk');
const { FormatAttributes, FormatResponse } = require('./utils.js');
const sqs = new AWS.SQS({ region: 'us-west-2' });
exports.handler = async function(event, context, callback) {
    if (event.path == '/queue' && event.httpMethod == "POST") {
        var params = FormatAttributes(event.body);
        var sts = sqs.sendMessage(params);
        var result = await sts.promise();
        console.log(result);
        return callback(null, FormatResponse(200, result));
    } else {
        return callback(null, FormatResponse(400, ""));
    }

};

**Comment by ErikCH** [comment]
Hi @nwokdean !

Can you describe what you are trying to accomplish?

So you're setting up a Lambda function that takes a messaging SQS queue then triggers a message to that queue?

**Comment by nwokdean** [comment]
Hi Erik,

Yes! And it uses appsync and grapgql, so not sure if that is relating to the issue as well. I can share a copy of the python code.. just filter to YOVAGETQUEUEITEM and you will see what needs to happen and the error we are getting.

Also, this is a very pressing issue that needs to be resolved today, so if we can set up time to meet, that will be great.

Thanks,
Dede

**Comment by wlee221** [comment]
Can you provide us more information on:
- Please provide your environment information: `npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages`
- Which version of `ChatBot` are you using? Any code snippet on your frontend code will be appreciated.

**Comment by reesscot** [comment]
@nwokdean Are you still having this issue? If so, can you provide the information that @wlee221 requested above?

**Comment by Milan-Shah** [comment]
@nwokdean Since we havent heard from you for a while now, we will close this issue. Please let us know if you are still having this issue and feel free to reopen this ticket or create a new one!
