### ISSUE TITLE
Authenticator - docs around sending custom field to cognito

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-ui#1478]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App / Webpack 5.x

### Please describe your bug.

The documentation, under [Authenticator Custom fields](https://ui.docs.amplify.aws/components/authenticator?platform=react#sign-up-fields) has an example that shows how to add a custom field & add validation to it.

```ts
<CheckboxField
  errorMessage={validationErrors.acknowledgement}
  hasError={!!validationErrors.acknowledgement}
  name="acknowledgement"
  value="yes"
  label="I agree with the Terms & Conditions"
/>
```

If the component above is used as it is, the validation works but it won't actually be sent to Cognito. Strictly speaking it might not be the purpose of this specific field (given it's a checkbox) but customers using the example as-is and as a reference for other custom attributes will stumble on this same issue.

The solution would be to change the `name` prop to use the proper prefix: `custom:acknowledgement` (this will require also to change the `validateCustomSignUp` example):
```ts
<CheckboxField
  errorMessage={validationErrors.acknowledgement}
  hasError={!!validationErrors.acknowledgement}
  name="custom:acknowledgement"
  value="yes"
  label="I agree with the Terms & Conditions"
/>
```

If specified as above Authenticator will actually send it to Cognito.

### What's the expected behaviour?

Documentation to include an example that I can copy/paste and "just works".

### Help us reproduce the bug!

Copy/paste the example & observe that the custom field "acknowledgement" from the example is not included sent 

### Code Snippet

See https://ui.docs.amplify.aws/components/authenticator?platform=react#sign-up-fields

**Comment by ErikCH** [comment]
Hi @dreamorosi 

The purpose of the example is to show how to add in custom validation logic into your sign up form. It's not there to show how to add a checkbox as a custom attribute to send to Cognito. 

A better way to do that is to add the `signUpAttributes` prop as seen here. https://ui.docs.amplify.aws/components/authenticator#sign-up-attributes

Does that make sense?

**Comment by dreamorosi** [comment]
Makes sense and I'm aware of how to send custom attributes. 

I just wanted to point out that as a customer approaching the documentation I was confused when I saw the field being included in the lifecycle of the form (validation, and it being in the `formData` object) but then not seeing it sent to Cognito.

I think a note or a reference that links to the section you mentioned would be nice, but if you think it's unnecessary feel free to close the issue!

**Comment by ErikCH** [comment]
OK! We'll go ahead and add that note @dreamorosi . That makes sense.

**Comment by ErikCH** [comment]
Hi @dreamorosi !

We updated our documentation on sign up form fields and attributes, to make it more clear! Thanks
