### ISSUE TITLE
Internationalization not working as expected

### ISSUE THREAD

**Issue by robert-brower-impaq** [aws-amplify/amplify-ui#1502]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Angular 12

### Please describe your bug.

The documentation found here https://docs.amplify.aws/lib/utilities/i18n/q/platform/js/#setlanguage states, "In the browser, Amplify detects browser language automatically."

This seems misleading because I could not get that to work without this code in my app:

I18n.putVocabularies(translations);

Please change the documentation to say: "In the browser, Amplify detects browser language automatically and will automatically display them if you include this line in your code: I18n.putVocabularies(translations);

...or something to that effect. Thanks.

### What's the expected behaviour?

The Authenticator component should automatically display the translations.

### Help us reproduce the bug!

It would be good if you could provide a link to a pregenerated stackblitz.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by artidata** [comment]
@robert-brower-impaq Here's my approach on using I18n shipped by the aws-amplify: https://codesandbox.io/s/github/artidata/amplify-i18n/tree/main/

**Comment by wlee221** [comment]
Looking at this now. 

```
I18n.putVocabularies(translations);
```

is something UI specific but the docs you linked to is general Amplify docs, so I'm not sure if we should add any Amplify UI specific description there. I'll close this for now, but we're still open to suggestions -- please let us know if you got ideas 🙏
