### ISSUE TITLE
loading prop on Input components shows Placeholder

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1503]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I'd like the option to provide a loading prop to any Input that if true, would cause the component to show the [Placeholder](https://ui.docs.amplify.aws/components/placeholder?platform=react) component instead. I'm thinking placeholder should display below label so label is visible while loading is true. This can be done easily now with a ternary operator but built-in support would be a nice touch.
```ts
     {loading ? (
        <Flex direction="column" gap=".5rem">
          <label className="amplify-label">Name:</label>
          <Placeholder height={42} />
        </Flex>
      ) : (
        <TextField
          errorMessage={formState.errors.friendlyName?.message}
          hasError={Boolean(formState.errors.friendlyName)}
          placeholder="My Use Case"
          label="Name:"
        />
      )}
```

### Please describe a solution you'd like.

See above.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@bestickley I think you can use the Placeholder children to accomplish this:
```
  <Placeholder isLoaded={isLoaded}>
    <TextField
          errorMessage={formState.errors.friendlyName?.message}
          hasError={Boolean(formState.errors.friendlyName)}
          placeholder="My Use Case"
          label="Name:"
        />
  </Placeholder>
```

**Comment by bestickley** [comment]
Hi @reesscot, yes that can be done, but I lose the label of the input during loading and it's a little more verbose. This is definitely a nice to have feature as your workaround is great for now.
