### ISSUE TITLE
It seems collection do not expose overrideItems

### ISSUE THREAD

**Issue by minganp** [aws-amplify/amplify-ui#1515]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

react app

### Please describe your bug.

With a component synchronized from Figma, I generate a collection in Amplify Studio UI.  After I pull into  App, I found that I can't use overrideItems as props for the collection, and I got 
   ```red
        react-dom.development.js:67 Warning: React does not recognize the `overrideItems` prop on a DOM element.  
```
My code:
```js
<div className="productsCollection">
   <ProductCardmiddleCollection 
      overrideItems={({ item, index }) => ({
           backgroundColor: 'white',
           onClick:()=>{alert(`hi ${item.id} ${index}`)}}             
    )}/>
</div>
```
when I check the ProductCardmiddleCollection.jsx, I also cannot find the expose of overrideItems.
```js
export default function ProductCardmiddleCollection(props) {
  const {
    products,
    items: itemsProp,
    overrides: overridesProp,
    ...rest
  } = props;
  const overrides = { ...overridesProp };
  const items =
    itemsProp !== undefined
      ? itemsProp
      : useDataStoreBinding({
          type: "collection",
          model: Products,
        }).items;
  return (
    <Collection
      type="list"
      direction="column"
      justifyContent="stretch"
      items={items || []}
      {...rest}
      {...getOverrideProps(overrides, "Collection")}
    >
      {(item, index) => (
        <ProductCardmiddle
          products={item}
          key={item.id}
          {...getOverrideProps(overrides, "Collection.ProductCardmiddle[0]")}
        ></ProductCardmiddle>
      )}
    </Collection>
  );
}
```
the version of amplify: 
 "@aws-amplify/ui-react": "^2.10.0",
  "aws-amplify": "^4.3.16",

from https://docs.amplify.aws/console/uibuilder/override/#extend-generated-collections-via-overrideitems-prop I can see that all generated Collection code exposes an overrideItems prop, 

### What's the expected behaviour?

but why I cannot find it? and if like this, how can I get each item? thanks a lot

### Help us reproduce the bug!

I just follow the instruction, I never find I can find the overrideItem

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hi @minganp,
It sounds like you need to upgrade your Figma file and update your Amplify CLI. Please do the following:

Upgrade Figma file: https://docs.amplify.aws/console/uibuilder/figmatocode/#upgrading-figma-files

Update Amplify CLI:
```
npm install -g @aws-amplify/cli@latest
```

Please let us know if that fixes your issue.

**Comment by minganp** [comment]
According to your instruction, I still cannot solve the problem. When I create another totally new project, it works. Thank you. Now I'm trying to migrate the project to the new one. It's also a challenge to immigrate the dynamo data and schema. I wonder if you can give me further information on how to solve the existing issue, maybe an explanation why I must update Figma components.

**Comment by reesscot** [comment]
Hi @minganp,
There was an update on March 2 as part of the 1.0.0 release that includes breaking changes to the Figma file. 


> [Figma file changelog](https://docs.amplify.aws/console/uibuilder/figmatocode/#figma-file-changelog)
1.0.0: March 2 2022
>
>    Fixing primitive component layer names to map properly to React props.
    **Removing the Icon primitive and adding a custom Icon component. This change allows for easier icon customization.**
    Fixing visual discrepancies between Figma file and React components.
    Re-organizing primitive component variants to make the default variant more expected. For example, default size and default variation of the button instead of the primary variation.
    Adding version number to the Figma file
    
Have you tried copying your components from your old Figma file to a new Figma file duplicated from the new community file as described in https://docs.amplify.aws/console/uibuilder/figmatocode/#upgrading-figma-files? After that you'll need to sync the Figma components in Studio and run `amplify pull` to download them to your React codebase.

**Comment by minganp** [comment]
Thank you very much.
