### ISSUE TITLE
Amplify Reset Password Hangs

### ISSUE THREAD

**Issue by rrhalim** [aws-amplify/amplify-ui#1567]
### Before creating a new issue, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

I used amplify's withAuthenticator as shown below for my /mainPage path. But when I tried to reset password, supply the confirmation code and submit it, the page hangs. It should refresh my /mainPage page.

    import { withAuthenticator } from "@aws-amplify/ui-react";
    import "@aws-amplify/ui-react/styles.css";
    function MainPage({ signOut, user }) {
      return (
        <>
          <h1>Hello {user.username}</h1>
          <button onClick={signOut}>Sign out</button>
        </>
     );
    }
    export default withAuthenticator(MainPage);

![Z9Gez](https://user-images.githubusercontent.com/100475670/159487879-f7957a62-787c-4aa3-8ba5-46ebd7a38739.png)

### What's the expected behaviour?

After clicking on submit, it should refresh my /mainPage.

### Help us reproduce the bug!

I just follow the instruction in the tutorial.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by wlee221** [comment]
Hi @rrhalim, thanks for opening this issue. I was not able to reproduce it however. Do you still experience this problem in latest `@aws-amplify/ui-react` (ie. ^2.15.0)?

Here's my codesandbox based on your repro steps. https://codesandbox.io/s/pm09hf?file=/src/routes/MainPage.js

**Comment by wlee221** [comment]
I would remove any lockfile and re-install latest. If the problem persists, please provide a repro repository (or fork that codesandbox!) 🙏

**Comment by rrhalim** [comment]
Hi @wlee221, after upgrading the version, the reset password no longer hangs.  Thank you.
