### ISSUE TITLE
Authenticator form field customization ignored for middle_name field

### ISSUE THREAD

**Issue by stellarjaysoftware** [aws-amplify/amplify-ui#1585]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

I'm applying form field customization described here: https://ui.docs.amplify.aws/components/authenticator#form-field-customization

I'm hiding field labels for inputs on the sign up tab.
![Screen Shot 2022-03-24 at 2 34 44 PM](https://user-images.githubusercontent.com/64604698/160014436-f1fb5ce2-3a34-45d9-9ad0-1130660264fb.png)

My customization code:
`const formFields = {
    signUp: {
      confirm_password: {
        labelHidden: false,
        label:
          "Password must include a number, an upper case, a lower case and a special character. Example: P4ssw*rd",
      },
      given_name: {
        labelHidden: true,
      },
      middle_name: {
        labelHidden: true,
        isRequired: false,
      },
      family_name: {
        labelHidden: true,
      },
      phone_number: {
        labelHidden: true,
      },
    },
  };`

This is passed into the Authenticator component as documented:
`<Authenticator
                signUpAttributes={[
                  "given_name",
                  "middle_name",
                  "family_name",
                  "phone_number",
                ]}
                formFields={formFields}
                components={authComponents}
              >...</Authenticator>
`

The customization I'm applying works for all fields except **middle_name**.  I can hide or show the labels and change isRequired for given_name, family_name, etc.  **Options set for middle_name are ignored.**

version: "@aws-amplify/ui-react": "^2.7.0"

Thanks for looking into it!

### What's the expected behaviour?

The input label should be hidden for the middle_name field as it is will the other fields, but it is not.

### Help us reproduce the bug!

- create-react-app, implement a simple Authenticator component.  
- pass signUpAttributes to the Authenticator component including middle_name
- pass formFields options including middle_name: { labelHidden: true, isRequired: false }
- confirm the label display and requirement for the middle_name field

### Code Snippet

see description above

**Comment by ErikCH** [comment]
Hi @stellarjaysoftware !

I'll see if we can reproduce this. Can you check the name attribute of the `middle_name` field?  Does it show `middle_name` as the name?

**Comment by stellarjaysoftware** [comment]
@ErikCH 
Yes, middle_name is the input name attribute.  
![Screen Shot 2022-03-24 at 4 43 42 PM](https://user-images.githubusercontent.com/64604698/160027691-b238430a-77eb-4111-bfd4-d7c01c25dfed.png)

**Comment by ErikCH** [comment]
Hi @stellarjaysoftware !

I just tried reproduce this and I'm having some problems. It seems to work correctly with my setup.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/65630/165804863-4de99129-b535-44d6-8402-de11f3b4ea18.png">

The label is not showing up, and it's not required.

I wonder if there is some sort of components passing in that's overriding the sign up middle name field? If you take out the `components` does it look ok?

Can you paste your `authComponents` for me to see as well

**Comment by stellarjaysoftware** [comment]
I just upgraded to the newest version of @aws-amplify/ui-react and the problem has gone away!  Thanks for looking into it anyways.
