### ISSUE TITLE
TypeError: t is not a function

### ISSUE THREAD

**Issue by OlehObodin** [aws-amplify/amplify-ui#1596]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

After auth I have error
TypeError: t is not a function

### What's the expected behaviour?

Should view content

### Help us reproduce the bug!

- Install Next.js, 
- add _app.js, 
- add Authenticator component to _app.js
- SignUp ok, then Login -> fail

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/100937342/160298428-03c20ab1-e425-4a16-974c-4e68dfb612e7.png)

**Comment by ErikCH** [comment]
Hi @OlehObodin !

I'm sorry you are having this issue. What versions of Amplify libraries are you using? And does this happen after you build as well?

**Comment by enes-sahin** [comment]
Hi @OlehObodin;

I also had the same issue with the Authenticator component (Next.js).  After I searched for examples on [Authenticator component document](https://ui.docs.amplify.aws/components/authenticator?platform=react), I noticed that all contents inside the Authenticator component are wrapped in a function. So if you write your content without a function, you will have this error.

### Code which generates error
```js
import { Authenticator } from '@aws-amplify/ui-react';

export default function Article() {
  return (
    <Authenticator>
      <>
        <h1 className="font-bold text-3xl mb-2">My Title</h1>
        <p className="content">Lorem ipsum......</p>
      </>
    </Authenticator>
  );
}
```

#### Result
<img width="400" alt="React Error" src="https://user-images.githubusercontent.com/25066964/161054983-8950fd11-8453-46e9-9d05-77dbe18f0612.png">



### Correct code
```js
import { Authenticator } from '@aws-amplify/ui-react';

export default function Article() {
  return (
    <Authenticator>
      {() => (
        <>
          <h1 className="font-bold text-3xl mb-2">My Title</h1>
          <p className="content">Lorem ipsum......</p>
        </>
      )}
    </Authenticator>
  );
}
```
### Result
<img width="371" alt="My title react" src="https://user-images.githubusercontent.com/25066964/161056859-48193d0b-711c-41bd-8410-48c817344b41.png">

**Comment by ErikCH** [comment]
Thanks @enes-sahin ! Yes that is true, you need to make sure you wrap the code.

Does that fix your problem @OlehObodin !

**Comment by wlee221** [comment]
Yep, as @ErikCH, Authenticator currently only allow render props as children. I think we should follow this up with allowing non-functions as children too.

**Comment by reesscot** [comment]
@OlehObodin Please feel free to reopen if the [solution provided](https://github.com/aws-amplify/amplify-ui/issues/1596#issuecomment-1084533104) doesn't solve your issue.
