### ISSUE TITLE
Extra Field When Customizing Issuer for Setup TOTP Screen

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#1599]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### Please describe your bug.

When I set the `formFields` property on Authenticator to: `{ setupTOTP: { QR: { totpIssuer: "My Web App" } } };` there is an extra field added to the setupTOTP form. See screenshot below. When I use Google Authenticator to add the TOTP it correctly changes the issuer name so that's good!

<img width="563" alt="image" src="https://user-images.githubusercontent.com/35735118/160668090-4f3093a9-8785-428b-aad4-9cd4173193ca.png">

HTML:
![image](https://user-images.githubusercontent.com/35735118/160668201-4b6a73da-79d0-413e-a016-c8d2001c1e4c.png)

### What's the expected behaviour?

Extra field is not added.

### Help us reproduce the bug!

See screenshot above.

**Comment by ErikCH** [comment]
Hi @bestickley !

I was able to reproduce this, and it's a quick fix. We should have it up soon!

**Comment by bestickley** [comment]
Thanks, @ErikCH!

**Comment by ErikCH** [comment]
This has been merged closing. Should be out in the next release
