### ISSUE TITLE
Customizing SetupTOTP issuer name results in an additional QR text field on setup

### ISSUE THREAD

**Issue by mroest** [aws-amplify/amplify-ui#1606]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Nextjs

### Please describe your bug.

When customizing the TOTP issuer like so:

`<Authenticator formFields={{ setupTOTP: { QR: { 'MyIssuer' } } }}/>`

Will result in an additional input field on the setuptotp page.
Next to the QR code image and the totp input field you get an additional input text field named 'QR'.

### What's the expected behaviour?

Customizing the issuer should not result in an additional input field

### Help us reproduce the bug!

Use the code snippet:

`<Authenticator formFields={{ setupTOTP: { QR: { 'MyIssuer' } } }}/>`

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

<img width="1505" alt="Screenshot 2022-03-31 at 17 46 08" src="https://user-images.githubusercontent.com/1062155/161100073-816e59b1-1327-4094-a772-eb51af8a9b75.png">

**Comment by ErikCH** [comment]
Hi @mroest ! Yes, this should be fixed in the release today. Related to #1599

**Comment by mroest** [comment]
> Hi @mroest ! Yes, this should be fixed in the release today. Related to #1599

Ah thanks! Sorry for creating a duplicate ticket. Searched for "open" issues. Anyways thanks for the fix!
