### ISSUE TITLE
Authenticator error in React - No such file or directory ENOENT

### ISSUE THREAD

**Issue by chstrong** [aws-amplify/amplify-ui#1613]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

When importing Authenticator:
`import { Authenticator } from '@aws-amplify/ui-react';`

This results in an empty white page after creating a user and logging in.

I get the following Error in the VS Code Terminal:
`...or: ENOENT: no such file or directory, open '/Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/src/i18n/dictionaries/authenticator/es.ts'
 @ ./node_modules/@aws-amplify/ui/dist/esm/i18n/dictionaries/index.js 4:0-52 20:14-15
 @ ./node_modules/@aws-amplify/ui/dist/esm/i18n/translations.js 3:0-242 4:14-15 15:6-7 16:6-7 17:6-7 18:6-7 19:6-7 20:6-7 21:6-7 22:6-7 23:6-7 24:6-7 25:6-7 26:6-7 27:6-7 28:6-7
 @ ./node_modules/@aws-amplify/ui/dist/esm/index.js 11:0-95 11:0-95 11:0-95 11:0-95 11:0-95
 @ ./node_modules/@aws-amplify/ui-react/dist/esm/index.js 8:0-74 8:0-74 8:0-74 8:0-74
 @ ./src/App.js 11:0-54 61:30-43
 @ ./src/index.js 7:0-24 14:33-36

WARNING in ./node_modules/@aws-amplify/ui/dist/esm/i18n/dictionaries/authenticator/fr.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/src/i18n/dictionaries/authenticator/fr.ts' file: Error: ENOENT: no such file or directory, open '/Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/src/i18n/dictionaries/authenticator/fr.ts'
 @ ./node_modules/@aws-amplify/ui/dist/esm/i18n/dictionaries/index.js 5:0-52 21:14-15
 @ ./node_modules/@aws-amplify/ui/dist/esm/i18n/translations.js 3:0-242 4:14-15 15:6-7 16:6-7 17:6-7 18:6-7 19:6-7 20:6-7 21:6-7 22:6-7 23:6-7 24:6-7 25:6-7 26:6-7 27:6-7 28:6-7
 @ ./node_modules/@aws-amplify/ui/dist/esm/index.js 11:0-95 11:0-95 11:0-95 11:0-95 11:0-95
 @ ./node_modules/@aws-amplify/ui-react/dist/esm/index.js 8:0-74 8:0-74 8:0-74 8:0-74
 @ ./src/App.js 11:0-54 61:30-43
 @ ./src/index.js 7:0-24 14:33-36

WARNING in ./node_modules/@aws-amplify/ui/dist/esm/i18n/dictionaries/authenticator/id.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/src/i18n/dictionaries/authenticator/id.ts' file: Error: ENOENT: no such file or directory, open '/Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/src/i18n/dictionaries/authenticator/id.ts'
 @ ./node_modules/@aws-amplify/ui/dist/esm/i18n/dictionaries/index.js 14:0-52 30:14-15
 @ ./node_modules/@aws-amplify/ui/dist/esm/i18n/translations.js 3:0-242 4:14-15 15:6-7 16:6-7 17:6-7 18:6-7 19:6-7 20:6-7 21:6-7 22:6-7 23:6-7 24:6-7 25:6-7 26:6-7 27:6-7 28:6-7
 @ ./node_modules/@aws-amplify/ui/dist/esm/index.js 11:0-95 11:0-95 11:0-95 11:0-95 11:0-95
 @ ./node_modules/@aws-amplify/ui-react/dist/esm/index.js 8:0-74 8:0-74 8:0-74 8:0-74
 @ ./src/App.js 11:0-54 61:30-43
 @ ./src/index.js 7:0-24 14:33-36

...`

### What's the expected behaviour?

No errors and authentication should work as expected.

### Help us reproduce the bug!

Follow your tutorial: https://docs.amplify.aws/start/q/integration/react/

### Code Snippet

```typescript
// Put your code below this line.
/* src/App.js */
import React, { useEffect, useState } from "react";
import { Amplify, API, graphqlOperation } from "aws-amplify";
import { createTodo } from "./graphql/mutations";
import { listTodos } from "./graphql/queries";

import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import awsExports from "./aws-exports";
Amplify.configure(awsExports);

const initialState = { name: "", description: "" };

const App = () => {
  const [formState, setFormState] = useState(initialState);
  const [todos, setTodos] = useState([]);

  useEffect(() => {
    fetchTodos();
  }, []);

  function setInput(key, value) {
    setFormState({ ...formState, [key]: value });
  }

  async function fetchTodos() {
    try {
      const todoData = await API.graphql(graphqlOperation(listTodos));
      const todos = todoData.data.listTodos.items;
      setTodos(todos);
    } catch (err) {
      console.log("error fetching todos");
    }
  }

  async function addTodo() {
    try {
      if (!formState.name || !formState.description) return;
      const todo = { ...formState };
      setTodos([...todos, todo]);
      setFormState(initialState);
      await API.graphql(graphqlOperation(createTodo, { input: todo }));
    } catch (err) {
      console.log("error creating todo:", err);
    }
  }

  return (
    <Authenticator>
      <div style={styles.container}>
        <h2>Amplify Todos</h2>
        <input
          onChange={(event) => setInput("name", event.target.value)}
          style={styles.input}
          value={formState.name}
          placeholder="Name"
        />
        <input
          onChange={(event) => setInput("description", event.target.value)}
          style={styles.input}
          value={formState.description}
          placeholder="Description"
        />
        <button style={styles.button} onClick={addTodo}>
          Create Todo
        </button>
        {todos.map((todo, index) => (
          <div key={todo.id ? todo.id : index} style={styles.todo}>
            <p style={styles.todoName}>{todo.name}</p>
            <p style={styles.todoDescription}>{todo.description}</p>
          </div>
        ))}
      </div>
    </Authenticator>
  );
};

const styles = {
  container: {
    width: 400,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: 20,
  },
  todo: { marginBottom: 15 },
  input: {
    border: "none",
    backgroundColor: "#ddd",
    marginBottom: 10,
    padding: 8,
    fontSize: 18,
  },
  todoName: { fontSize: 20, fontWeight: "bold" },
  todoDescription: { marginBottom: 0 },
  button: {
    backgroundColor: "black",
    color: "white",
    outline: "none",
    fontSize: 18,
    padding: "12px 0px",
  },
};

export default App;

```

### Additional information and screenshots

package.json file:

`{
  "name": "react-amplified",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^2.13.0",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^4.3.18",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

MacOS: Monterey

React index.js file:

`import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

import { Amplify } from "aws-amplify";
import awsExports from "./aws-exports";
Amplify.configure(awsExports);

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();`

**Comment by wlee221** [comment]
Hi @chstrong, it looks like you're on older version of `@aws-amplify/ui-react` at version 2. Can you try upgrading it to `3.x.x` it with `yarn add @aws-amplify/ui-react@latest`?

**Comment by chstrong** [comment]
Hi @wlee221,

I've tried installing the following way:

`npm install aws-amplify@4.3.18
npm install @aws-amplify/ui-react@3.4.1`

However, this resulted in a new error, which is also related to the Authenticator. As soon I remove the import Authenticator statement, the error disappears.

`ERROR in ./src/App.js 11:0-54
Module not found: Error: Can't resolve '@aws-amplify/ui-react' in '/Users/chstrong/Development/react-amplified/src'
resolve '@aws-amplify/ui-react' in '/Users/chstrong/Development/react-amplified/src'
  Parsed request is a module
  using description file: /Users/chstrong/Development/react-amplified/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/chstrong/Development/react-amplified/src/node_modules doesn't exist or is not a directory
      looking for modules in /Users/chstrong/Development/react-amplified/node_modules
        single file module
          using description file: /Users/chstrong/Development/react-amplified/package.json (relative path: ./node_modules/@aws-amplify/ui-react)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.jsx doesn't exist
        /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react doesn't exist
      looking for modules in /Users/chstrong/Development/node_modules
        single file module
          using description file: /Users/chstrong/Development/package.json (relative path: ./node_modules/@aws-amplify/ui-react)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/node_modules/@aws-amplify/ui-react.jsx doesn't exist
        /Users/chstrong/Development/node_modules/@aws-amplify/ui-react doesn't exist
      /Users/chstrong/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/chstrong/Development/react-amplified/node_modules
        single file module
          using description file: /Users/chstrong/Development/react-amplified/package.json (relative path: ./node_modules/@aws-amplify/ui-react)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react.jsx doesn't exist
        /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react doesn't exist
 @ ./src/index.js 7:0-24 14:33-36

ERROR in ./src/App.js 12:0-42
Module not found: Error: Can't resolve '@aws-amplify/ui-react/styles.css' in '/Users/chstrong/Development/react-amplified/src'
resolve '@aws-amplify/ui-react/styles.css' in '/Users/chstrong/Development/react-amplified/src'
  Parsed request is a module
  using description file: /Users/chstrong/Development/react-amplified/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/chstrong/Development/react-amplified/src/node_modules doesn't exist or is not a directory
      looking for modules in /Users/chstrong/Development/react-amplified/node_modules
        /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react doesn't exist
      looking for modules in /Users/chstrong/Development/node_modules
        /Users/chstrong/Development/node_modules/@aws-amplify/ui-react doesn't exist
      /Users/chstrong/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/chstrong/Development/react-amplified/node_modules
        /Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/ui-react doesn't exist
 @ ./src/index.js 7:0-24 14:33-36

webpack 5.71.0 compiled with 2 errors in 2716 ms
`

**Comment by wlee221** [comment]
Oh shoot, my apologies -- I've messed up the version myself. The version should be on `@aws-amplify/ui-react@2.x.x`. So the error on your original issue is correct. The error message 

> `...or: ENOENT: no such file or directory, open '/Users/chstrong/Development/react-amplified/node_modules/@aws-amplify/src/i18n/dictionaries/authenticator/es.ts'

is concerning -- it should be referencing `@aws-amplify/ui/src`, not `@aws-amplify/src`. We'll try to reproduce this on a fresh CRA.

**Comment by chstrong** [comment]
Thanks. Let me know once resolved, then I'll be happy to test again.

Please also let me know in case you know how I can report a bug for Amplify Studio (cloud formation update fails when deleting databases from the visual designer).

**Comment by Ismailhoucheimi** [comment]
You can try an older version of ui-react until this is resolved 

`npm install @aws-amplify/ui-react@2.10.3`

**Comment by chstrong** [comment]
Hi @Ismailhoucheimi,

Thanks, I tried modifying my current setup, and then setup again from scratch, but that throws another error, this time in the Browser Developer Console in Authenticator/Router/index.tsx line 44:

```
Uncaught TypeError: s is not a function
    at Router (bundle.js:86925:57)
    at renderWithHooks (bundle.js:314573:22)
    at updateFunctionComponent (bundle.js:318645:24)
    at beginWork (bundle.js:320621:20)
    at HTMLUnknownElement.callCallback (bundle.js:302533:18)
    at Object.invokeGuardedCallbackDev (bundle.js:302582:20)
    at invokeGuardedCallback (bundle.js:302644:35)
    at beginWork$1 (bundle.js:325448:11)
    at performUnitOfWork (bundle.js:324622:16)
    at workLoopSync (bundle.js:324536:9)
```

```
The above error occurred in the <Router> component:

    at Router (http://localhost:3000/static/js/bundle.js:86909:15)
    at InitMachine (http://localhost:3000/static/js/bundle.js:86984:15)
    at Provider (http://localhost:3000/static/js/bundle.js:48869:15)
    at Authenticator (http://localhost:3000/static/js/bundle.js:87004:15)
    at App (http://localhost:3000/static/js/bundle.js:50:84)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18525
```

package.json:
```
{
  "name": "react-amplified",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^2.10.3",
    "@testing-library/jest-dom": "^5.16.3",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^4.3.19",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.4"
```

**Comment by chrisbonifacio** [comment]
@chstrong in your app, change the rendered jsx to this

```jsx
  return (
    <Authenticator>
      {({ user, signOut }) => {
        return (
          <div style={styles.container}>
            <h2>Amplify Todos</h2>
            <input
              onChange={(event) => setInput("name", event.target.value)}
              style={styles.input}
              value={formState.name}
              placeholder="Name"
            />
            <input
              onChange={(event) => setInput("description", event.target.value)}
              style={styles.input}
              value={formState.description}
              placeholder="Description"
            />
            <button style={styles.button} onClick={addTodo}>
              Create Todo
            </button>
            {todos.map((todo, index) => (
              <div key={todo.id ? todo.id : index} style={styles.todo}>
                <p style={styles.todoName}>{todo.name}</p>
                <p style={styles.todoDescription}>{todo.description}</p>
              </div>
            ))}
          </div>
        );
      }}
    </Authenticator>
  );
  ```

**Comment by jimbol** [comment]
I'm getting similar behavior to the original issue when running my application locally. Mind you, the application runs just fine, its just giving me a bunch of warnings.

```
WARNING in ./node_modules/@aws-amplify/ui/dist/esm/validators/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/amplify-project/node_modules/@aws-amplify/src/validators/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/amplify-project/node_modules/@aws-amplify/src/validators/index.ts'
 @ ./node_modules/@aws-amplify/ui/dist/esm/machines/authenticator/signUp.js 6:0-63 341:23-24
 @ ./node_modules/@aws-amplify/ui/dist/esm/machines/authenticator/index.js 8:0-55 304:18-19
 @ ./node_modules/@aws-amplify/ui/dist/esm/index.js 12:0-79 12:0-79
 @ ./node_modules/@aws-amplify/ui-react/dist/esm/index.js 8:0-74 8:0-74 8:0-74 8:0-74
 @ ./src/App.js 4:0-58 58:21-38
 @ ./src/index.js 9:0-24 15:33-36
```

**Comment by jimbol** [comment]
I also started a new project from scratch and the errors were no longer there.

**Comment by wlee221** [comment]
Glad this is working now! We also made a significant optimization with React 18, so please upgrade to latest (`^2.14.1`) when you get the chance. Please let us know if you come across more frictions with CRA 🙏

**Comment by reesscot** [comment]
@jimbol The warning messages you mentioned should also be gone now on the latest version `^2.14.1` They were fixed by https://github.com/aws-amplify/amplify-ui/pull/1608
