### ISSUE TITLE
Unable to change background color of menu trigger button

### ISSUE THREAD

**Issue by layqnovo** [aws-amplify/amplify-ui#1614]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### Please describe your bug.

Using the Menu and MenuItem like this:
```
<Menu className='my-menu-content' triggerClassName='my-menu-trigger' >
<MenuItem onClick={/() => alert('Download)}<Download</MenuItem>
<MenuItem onClick={/() => alert('Copy)}<Copy</MenuItem>
</Menu>

```
with the following css config:
```
  .my-menu-content.amplify-menu-content {
	--amplify-components-button-color: rgb(255, 0, 0); /* font color, menu */
	--amplify-components-button-menu-focus-color: rgb(0, 255, 55); /* font color, hover, menu */
	--amplify-components-button-menu-focus-background-color: rgb(255, 251, 0); /* background color, hover, menu */
	--amplify-components-button-menu-background-color:  rgb(145, 179, 182); /* background color, menu */
  }

  .my-menu-trigger.amplify-menu-trigger {
	--amplify-components-button-border-color: rgb(250, 235, 26)  ; /* border color, trigger button */
	--amplify-components-button-hover-border-color: rgb(250, 26, 220)  ; /* border color, trigger button, hover */
	--amplify-components-button-color: rgb(72, 255, 0); /* icon color, trigger button */
	--amplify-components-button-hover-color: rgb(255, 255, 255); /* icon color, trigger button, hover */
	--amplify-components-button-background-color: rgb(206, 146, 198);  /* background color, trigger button  NO EFFECT */
	--amplify-components-button-hover-background-color: rgb(255, 0, 0); /* background color, trigger button, hover */
  }

```
I am not able to configure the background color of the trigger button. I can define the icon and border color as well as all colors on hover but not the background color in normal view. The button is transparent by default so shows the color of the app background. All colors in the menu content are configurable as well.

![image](https://user-images.githubusercontent.com/100163734/161533491-c0c047fb-7e3b-4bff-91b4-f85c9b32d043.png)

![image](https://user-images.githubusercontent.com/100163734/161533633-333e96d0-3dfc-4190-9b4f-2eed08ab566e.png)

### What's the expected behaviour?

By overriding the background color of the trigger button, the trigger button should change color.

### Help us reproduce the bug!

See the description

### Code Snippet

See description

**Comment by layqnovo** [comment]
I'm also not able to adjust the width or padding/margins of the content box. I tried the following:
```
--amplify-components-menu-max-width
--amplify-components-menu-item-padding-inline-end
```
under
`.my-menu-content.amplify-menu-content {`
with no effect.

**Comment by reesscot** [comment]
Hi @layqnovo,

I think one of the things you're running into is that we don't have CSS variables for all properties, just the ones with values in the default theme. 

You can add a background color using the following:

```css
.my-menu-trigger.amplify-menu-trigger {
  background-color: rgb(206, 146, 198);
}
```
To override the padding:

```css
.my-menu-content .amplify-menu-content__item {
  --amplify-components-menu-item-padding-inline-start: 20px;
}
```

I'm still researching why the `max-width` cannot be set and will get back to you.

**Comment by reesscot** [comment]
Oh I see what's going on. You may  need to set the min-with as well, since you cannot set a max-width that's smaller than the min-width. Try tweaking these numbers, lowering min-width as well as max-width to your desired range.

```css
.my-menu-content.amplify-menu-content {
  --amplify-components-menu-max-width: 30rem;
  --amplify-components-menu-min-width: 14rem;  
}
```

**Comment by layqnovo** [comment]
Amazing. Thank you Scott!
