### ISSUE TITLE
<Authenticator> Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### ISSUE THREAD

**Issue by ianzone** [aws-amplify/amplify-ui#1615]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

Unhandled Runtime Error
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

Call Stack
checkForNestedUpdates
node_modules/react-dom/cjs/react-dom.development.js (27084:0)
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js (25266:0)
dispatchSetState
node_modules/react-dom/cjs/react-dom.development.js (17342:0)
checkForUpdates
node_modules/use-subscription/cjs/use-subscription.development.js (96:0)
Object.setCurrentValue
node_modules/@aws-amplify/ui-react/node_modules/@xstate/react/es/useSelector.js (30:0)
eval
node_modules/@aws-amplify/ui-react/node_modules/@xstate/react/es/useSelector.js (66:0)
commitHookEffectListMount
node_modules/react-dom/cjs/react-dom.development.js (22969:0)
commitLayoutEffectOnFiber
node_modules/react-dom/cjs/react-dom.development.js (23081:0)
commitLayoutMountEffects_complete
node_modules/react-dom/cjs/react-dom.development.js (24461:0)
commitLayoutEffects_begin
node_modules/react-dom/cjs/react-dom.development.js (24447:0)
commitLayoutEffects
node_modules/react-dom/cjs/react-dom.development.js (24385:0)
commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js (26651:0)
commitRoot
node_modules/react-dom/cjs/react-dom.development.js (26517:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25956:0)
flushSyncCallbacks
node_modules/react-dom/cjs/react-dom.development.js (11982:0)
flushSync
node_modules/react-dom/cjs/react-dom.development.js (26040:0)
finishEventHandler
node_modules/react-dom/cjs/react-dom.development.js (3969:0)
batchedUpdates
node_modules/react-dom/cjs/react-dom.development.js (3987:0)
dispatchEventForPluginEventSystem
node_modules/react-dom/cjs/react-dom.development.js (9257:0)
dispatchEvent
node_modules/react-dom/cjs/react-dom.development.js (6435:0)
dispatchDiscreteEvent
node_modules/react-dom/cjs/react-dom.development.js (6410:0)

### What's the expected behaviour?

1. the login window should be centered 
2. shouldn't throw any error

### Help us reproduce the bug!

1. npx create-next-app Test --ts
2. go to Test and run amplify pull --appId ??????? --envName staging, while cognito should be set against it
3. npm i @aws-amplify/ui-react aws-amplify
4. replace pages/_app.tsx with the code snippet bellow
5. npm run dev
6. open http://localhost:3000 and click anywhere on the page

the dependencies are
    "@aws-amplify/ui-react": "^2.13.0",
    "aws-amplify": "^4.3.18",
    "next": "12.1.4",
    "react": "18.0.0",
    "react-dom": "18.0.0"

### Code Snippet

```typescript
// Put your code below this line.
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { Amplify } from 'aws-amplify';
import type { AppProps } from 'next/app';
import awsConfig from '../aws-exports';
// import '../styles/globals.css';
Amplify.configure(awsConfig);

function App({ Component, pageProps }: AppProps) {
  return (
    <Authenticator hideSignUp={true}>
      {({ signOut, user }) => {
        return <Component {...pageProps} signOut={signOut} user={user} />;
      }}
    </Authenticator>
  );
}
export default App;

```

### Additional information and screenshots

https://user-images.githubusercontent.com/20043230/161589514-8ea4b3e2-5711-4924-8a8d-4d5fca143b2b.mp4

**Comment by ianzone** [comment]
Found same issue #1602

**Comment by OlehObodin** [comment]
SO did it resolved?

**Comment by skobba** [comment]
Same issue with nextjs and Authenticator. Working with react-scripts 5.0.0 though.

**Comment by wlee221** [comment]
@OlehObodin and @skobba, this is being actively worked on and will be tracked on #1602 🙏
