### ISSUE TITLE
Minified React error 

### ISSUE THREAD

**Issue by OlehObodin** [aws-amplify/amplify-ui#1618]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

In production mode I have an error while trying to write email into field
`Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings`

### What's the expected behaviour?

Just fill the auth form and log in

### Help us reproduce the bug!

Next.js 12, React 18

### Code Snippet

```typescript
// Put your code below this line.

```
export default withAuthenticator(App ,{ hideSignUp: true })

**Comment by OlehObodin** [comment]
It may be link to this one https://github.com/aws-amplify/amplify-ui/issues/1602

**Comment by reesscot** [comment]
@OlehObodin Yes, this appears to link to the same error message. As a temporary workaround can you downgrade to React 17?
```
npm install react@17
```
We are actively working on a solution to get Authenticator working in React 18.

**Comment by OlehObodin** [comment]
@reesscot  Ok, thanks.

**Comment by reesscot** [comment]
Please update to the latest version of `@aws-amplify/ui-react`. This is fixed in `^2.14.1`. Please reopen if you're still having any issues with React 18.
