### ISSUE TITLE
core and ui-react trying to force react-native and react 18 deps

### ISSUE THREAD

**Issue by revmischa** [aws-amplify/amplify-ui#1621]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

I'm trying to use amplify for handling the frontend of cognito auth. It works fine but the dependencies it pulls in cause some problems. For example it really wants me to install React 18:
```
npm WARN While resolving: use-subscription@1.6.0
11:16:35.508 | npm WARN Found: react@17.0.2
11:16:35.508 | npm WARN node_modules/react
11:16:35.508 | npm WARN   peer react@"^0.14.9 \|\| ^15.3.0 \|\| ^16.0.0" from react-motion@0.5.2
11:16:35.508 | npm WARN   node_modules/@nivo/colors/node_modules/react-motion
11:16:35.508 | npm WARN     react-motion@"^0.5.2" from @nivo/colors@0.72.0
11:16:35.508 | npm WARN     node_modules/@nivo/colors
11:16:35.508 | npm WARN
11:16:35.508 | npm WARN Could not resolve dependency:
11:16:35.508 | npm WARN peer react@"^18.0.0" from use-subscription@1.6.0
11:16:35.509 | npm WARN node_modules/use-subscription
11:16:35.509 | npm WARN   use-subscription@"^1.3.0" from @xstate/react@1.6.3
11:16:35.509 | npm WARN   node_modules/@xstate/react
11:16:35.509 | npm WARN   1 more (react-native)
11:16:35.509 | npm WARN
11:16:35.509 | npm WARN Conflicting peer dependency: react@18.0.0
11:16:35.509 | npm WARN node_modules/react
11:16:35.509 | npm WARN   peer react@"^18.0.0" from use-subscription@1.6.0
11:16:35.509 | npm WARN   node_modules/use-subscription
11:16:35.509 | npm WARN     use-subscription@"^1.3.0" from @xstate/react@1.6.3
11:16:35.509 | npm WARN     node_modules/@xstate/react
11:16:35.509 | npm WARN     1 more (react-native)

...

platform@1.0.0 /Users/cyber/dev/platform
└─┬ frontend@0.5.0 -> ./packages/frontend
  └─┬ @aws-amplify/ui-react@2.13.0
    └── @xstate/react@1.6.3
```

Also, separately, `@aws-amplify/core` is pulling in react-native which I really don't want:
```
platform@1.0.0 /Users/cyber/dev/platform
└─┬ frontend@0.5.0 -> ./packages/frontend
  └─┬ @aws-amplify/core@4.5.0
    └─┬ @aws-sdk/client-cloudwatch-logs@3.6.1
      └─┬ @aws-sdk/middleware-retry@3.6.1
        └─┬ react-native-get-random-values@1.7.2
          └─┬ react-native@0.68.0
            └─┬ @react-native-community/cli@7.0.3
              └── react-native@0.68.0 deduped
```

### What's the expected behaviour?

Not try to force React 18 or react-native just to get the amplify/react package.

### Help us reproduce the bug!

`npm i npm>=7.0.0`
`npm i react@^17.0.0`
`npm i @aws-amplify/ui-react@2.13.0` (get mad warnings)

`npm ls react-native`

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by calebpollman** [comment]
Hi @revmischa the issue with _@aws-amplify/core_ bringing in `react-native` as a dependency is being tracked [here](https://github.com/aws-amplify/amplify-js/issues/9119).

Regarding the peerDeps of `use-subscription` attempting to bring in `react@18` in your project, assuming you are just trying to get rid of the warnings during installation, with `npm >= 8.3` you can leverage the `overrides` field in your _package.json_ to explicitly set `use-subscription@1.5.1` (which has a `react` peerDep of `^16.8.0 || ^17.0.0`) and meets the required version of `use-subscription` required by `@xstate/react` (which is `^1.3`), e.g.

```
"overrides": {
    "use-subscription": "1.5.1"
}
```

**Comment by revmischa** [comment]
Cool thanks

**Comment by revmischa** [comment]
> Hi @revmischa the issue with _@aws-amplify/core_ bringing in `react-native` as a dependency is being tracked [here](https://github.com/aws-amplify/amplify-js/issues/9119).

Oh yeah looks like I opened that six months ago lol

**Comment by calebpollman** [comment]
@revmischa Unless you have an objection, closing this ticket since there is not much we can do for the `use-subscription` peerDeps and the `react-native` issue is being tracked by the owning team. Feel free to reopen though!
