### ISSUE TITLE
No result found or custom component should be support in Collection's search Bar

### ISSUE THREAD

**Issue by jaythakor-ai** [aws-amplify/amplify-ui#1631]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### Please describe your bug.

Currently, the search filters in the Collection component is not showing any message or allow the rendering of the custom component when the searched value is not present in the Collection.

### What's the expected behaviour?

There should be a way to render the custom component or "No result Found" message while searched value is not present in the Collections

### Help us reproduce the bug!

Create a collection of any components and try to search for value from that collection.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by dbanksdesign** [comment]
Hey @jaythakor-ai thanks for raising this issue! We definitely want to address this and we are working on what the right developer experience should be.
