### ISSUE TITLE
AmplifyS3Album won't load images if the name has spaces

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-ui#1632]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Storage

### How is your app built?

CRA

### Please describe your bug.

<AmplifyS3Album/> only loads images that do not have spaces in them. Here are the images in my app:
![image](https://user-images.githubusercontent.com/2429410/162027095-858fa361-7925-4dc9-b78b-34764411be1d.png)

The UI only loads 2 of them:
![image](https://user-images.githubusercontent.com/2429410/162027190-aac5a964-02ec-4ab0-a232-0b649e13ffb0.png)

Now let's rename one of the `Screeshot..` images
![image](https://user-images.githubusercontent.com/2429410/162027317-f612954f-d702-44b4-b0f9-55a51ecb13b1.png)

UI now loads 3 images
![image](https://user-images.githubusercontent.com/2429410/162027412-7377f4f4-10e4-4e9b-87dd-e771168c7ecc.png)

### What's the expected behaviour?

Load all images in gallery

### Help us reproduce the bug!

Info provided

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by calebpollman** [comment]
`AmplifyS3Album` has been fully deprecated. Closing this issue
