### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'send')" when calling useAuthenticator

### ISSUE THREAD

**Issue by techandmedia** [aws-amplify/amplify-ui#1651]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

```code
TypeError: Cannot read properties of undefined (reading 'send')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

### What's the expected behaviour?

No error when calling useAuthenticator

### Help us reproduce the bug!

Error occured when using React v17 and v18

https://github.com/techandmedia/next-amplify-react18/tree/react18-useAuthenticator

### Code Snippet

```typescript
// Put your code below this line.
import { useEffect } from "react";
import { Amplify } from "aws-amplify";
import { Authenticator, useAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import awsExports from "../../aws-exports";

Amplify.configure({ ...awsExports, ssr: true });

export default function MyApp({ Component, pageProps }) {
  const { user, signOut } = useAuthenticator((context) => [context.user]);

  useEffect(() => {
    console.log("App", user);
    console.log("App", signOut);
  }, [user, signOut]);

  return (
    <main>
      <h1>Hello {user.username}</h1>
      <button onClick={signOut}>Sign out</button>
      <Component {...pageProps} />
    </main>
    // <Authenticator>
    //   {({ signOut, user }) => (
    //     <main>
    //       <h1>Hello {user.username}</h1>
    //       <button onClick={signOut}>Sign out</button>
    //       <Component {...pageProps} />
    //     </main>
    //   )}
    // </Authenticator>
  );
}

```

### Additional information and screenshots

Error occured when using React v17 and v18

```json
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^2.14.1",
    "aws-amplify": "^4.3.19",
    "next": "12.1.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@types/node": "^17.0.23",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "typescript": "^4.2.4"
  }
}
```

**Comment by ErikCH** [comment]
Hello @techandmedia !
Sorry you are running into these issues.

Could you try either wrapping your app in the `Authenticator` or the `Authenticator.Provider`. You can take at how to do this here. https://ui.docs.amplify.aws/components/authenticator#useauthenticator-hook

```
import { Authenticator } from '@aws-amplify/ui-react';

export default () => (
  <Authenticator.Provider>
    <App />
  </Authenticator.Provider>
);
```

Otherwise the `useAuthenticator` won't work properly

**Comment by techandmedia** [comment]
Thanks, it works. Not sure how I missed that Provide part
