### ISSUE TITLE
When login, refresh page, log out and then login again Authenticator crashes on formValues

### ISSUE THREAD

**Issue by jeroenmeulendijks** [aws-amplify/amplify-ui#1659]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App with react-app-wired to adjust webpack config

### Please describe your bug.

On login when pressing the 'Sign In' button it doesn't login and I can see the following error in the console logs (see attached screenshot)

This ONLY happens when you are logged in, refresh the page, log out and try to login again

### What's the expected behaviour?

That the user would be logged in normally without crashing

### Help us reproduce the bug!

- Open the application
- Login, which works as normal
- Refresh the page (F5)
- Log out
- Login again, but now the error is observed

### Code Snippet

```typescript
<Authenticator initialState="signIn" hideSignUp loginMechanisms={['email']}>
        {() => (
          <main>
            <AbilityContext.Provider value={currentAbilities}>
               .. Components ..
            </AbilityContext.Provider>
            <footer>
              <Footer />
            </footer>
          </main>
)}
</Authenticator>
```

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/13433769/162626205-fbe3b1e9-4dba-41d9-85a3-05ecc9a9ba04.png)

When looking at the code:
![image](https://user-images.githubusercontent.com/13433769/162626331-33337531-309b-4593-83fa-e234692e1d8c.png)

r.loginMechanisms is undefined in this situation while normally it contains ['email'] as defined in my authenticator.

**Comment by zacsonskaria** [comment]
Same issue here with Angular. Tried their basic example with the latest version.

**Comment by jussiniinikoski** [comment]
Same here with standard Create React App.

**Comment by zacsonskaria** [comment]
Please find the angular error message.

![image](https://user-images.githubusercontent.com/13000274/162754383-5ac5f03d-85fd-49be-88f4-cc6439961867.png)

**Comment by ErikCH** [comment]
Thanks for opening this up! We are working on this right now! This is also documented here -> https://github.com/aws-amplify/amplify-ui/issues/1623

**Comment by wlee221** [comment]
Hi all, we just merged and published the fix for this issue to the following versions:

```
@aws-amplify/ui-angular@2.3.10
@aws-amplify/ui-react@2.15.3
@aws-amplify/ui-vue@2.3.10
``` 

Please upgrade your dependency and let us know if the problem persists, thanks! 🙏

**Comment by jeroenmeulendijks** [comment]
Thanks. Issue is fixed!

**Comment by zacsonskaria** [comment]
Thanks. Tested it on angular and it works fine.
