### ISSUE TITLE
FR (Authenticator React): Support pre-filled value in formFields signIn username/password

### ISSUE THREAD

**Issue by therobwatson** [aws-amplify/amplify-ui#1669]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

I would like to provide a pre-filled value when configuring the `Authenticator` Sign Up username field.  That way, if I have the email/username of the last signed in user, then I could use that to pre-fill the input box for the sign in component.

Unless there is something I'm missing, it seems it's not possible to pre-fill the `Authenticator` `SignIn` component using the configuration options available for `Authenticator`.

### Describe the solution you'd like

Given the following basic customization, I'd like to pre-fill the `SignIn` component's username/email value.

```
const amplifyComponents = {
  SignIn: {
    Header: SomeCustomBannerComponent
  }
};

```

```
<AmplifyProvider theme={amplifyTheme} >
  <Authenticator
    loginMechanisms={['email']}
    components={amplifyComponents}
    formFields={{
      signIn: {
        username: { // <-- I tried email and username here
          value: 'prepopulatedEmail@example.com'
        },
      },
    }}
  ></Authenticator>
</AmplifyProvider>
```

### Describe alternatives you've considered

I tried to adapt the syntax I found here https://github.com/aws-amplify/amplify-js/issues/6097 to work with the documentation I found here https://ui.docs.amplify.aws/components/authenticator#form-field-customization; but the `value` property had no effect.

I also reviewed the docs example for adding a custom field to the `SignUp` component (https://ui.docs.amplify.aws/components/authenticator#sign-up-fields); but I couldn't find a way to actually customize the default fields in order to pre-fill the username/email field.

I couldn't seem to bridge the gap between the GitHub Issue 6097 syntax linked above with a configuration for the higher order(?) `Authenticator` component.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by schlumpyj** [comment]
I would like this feature for my Angular project! It would make my user's experience much simplier.

**Comment by rory-ferguson** [comment]
I would like to see this feature please.

**Comment by benjamineliott** [comment]
+1

**Comment by monscamus** [comment]
This would be really useful.

**Comment by schlumpyj** [comment]
It would also be awesome if I could prefill the sign-up field (in addition to the sign-in field as this issue mentioned). My use case is when a user refers a new user to our service. We already know the potential new user's email so we would like to prepopulate that value for them in the sign-up username field.

**Comment by EvolveDeveloper** [comment]
+1 👋
It would be great to have a pre-filled, especially when a "referred" user visits our login page with a query string in the url that helps pre-fill the text view.

**Comment by gillkyle** [comment]
Similar to the others in this thread, we hope to be able to prefill the email field (and even possibly the password field with a temporary password).

What would be enough for our use case would be something like forwarding a `ref` down to the inputs so we could set the value imperatively if we have to. I've tried hacking around things by manipulating the DOM with values I want but don't want to bail out of React (in our case) too much so would benefit from an extended API like this as well.

**Comment by andr3i4o** [comment]
It could be awesome to be able to prefill the form, yes!
It would also be awesome to be able to authenticate the user manually (let's say we have a separate screen to signup with a barcode and the BE is doing the authentication, but the application is wrapped with Authenticator and we can't buypass it).

**Comment by bryanmorganoverbey** [comment]
This worked for me:
  React.useEffect(() => {
    setTimeout(() => {
      const input = document.querySelector('input[name="username"]');
      if (input) {
        input.setAttribute("value", "billybobthornton");
      }
    });
  }, []);

**Comment by pro-backup** [comment]
+1 (and also let us set properties on the sign up form please)

**Comment by reesscot** [comment]
This is currently possible using the [formFields API](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#updating-labels-placeholders-required-fields-and-showing-labels). Here's an example using defaultValue to set a prepopulated value and make it readonly:
https://codesandbox.io/s/authenticator-prepopulated-readonly-email-8927cp?file=/src/App.js

![CleanShot 2023-02-07 at 12 02 37](https://user-images.githubusercontent.com/6165315/217340930-2e572025-a973-422d-b67d-f22f068272a6.gif)

Please let me know if this is what you're looking for @strongpauly @pro-backup @bryanmorganoverbey @andr3i4o @gillkyle @EvolveDeveloper @schlumpyj @monscamus @therobwatson @rory-ferguson @benjamineliott .

**Comment by strongpauly** [comment]
This does seem to work!  But, yes the types should be updated too
