### ISSUE TITLE
Update the generateIcons script

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-ui#172]
Some source SVGs have a multiple viewport sizes other than 24 x 24 (like 20 x 20), causing the icons to behave incorrectly because we aren't stripping out the `width` and `height` attributes on the SVG element. One example:

https://github.com/aws-amplify/amplify-ui/blob/2ac10ec8c34199a8daaa6a247d9e43ba476c56a7/packages/react/src/primitives/Icon/icons/IconVerified.tsx

That is happening because there are actually 20x20 and 24x24 versions of the icon in the source:

https://github.com/aws-amplify/amplify-ui/tree/main/material-design-icons/svg/action/verified/materialicons

**Comment by ericclemmons** [comment]
Is there any compelling reason not to instead have 1st class support for 3rd party icons like Material & resolve issues like these?
> https://app.asana.com/0/1200334286823427/1200892137185678/f
