### ISSUE TITLE
Using style prop overrides all styled properties (like `padding`)

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-ui#173]
Example:

```javascript
<View backgroundColor="blue" style={{padding: "2rem"}}>
{/* content */}
</View>
```

In this example the `style` object will override any styled props like `backgroundColor`, meaning `backgroundColor` will not have any effect on the above `<View>`.

**Comment by zchenwei** [comment]
We are doing a merge for styling props and style object now, and the former will take the precedence
