### ISSUE TITLE
Accessibility: Authenticator error messages should use `aria-errormessage`

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#1737]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React, Angular, Vue

### Which UI component?

Authenticator

### How is your app built?

N/A

### Please describe your bug.

When Authenticator fields are invalid and have `aria-invalid` equal to true, they should also have the `aria-errormessage` attribute which points to the error message text. This allows screenreaders to announce an error message on invalid field entry.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-errormessage

![Uploading Screen Shot 2022-04-20 at 8.03.31 PM.png…]()

### What's the expected behaviour?

`aria-errormessage` on invalid fields should point to DOM element which contain the corresponding error message. 

### Help us reproduce the bug!

1. Go to https://ui.docs.amplify.aws/components/authenticator#sign-up-attributes,  Sign Up Attributes section
2. Enter two passwords which don't match to trigger error
3. Inspect input element and see that no `aria-errormessage` is there.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
I think we should consider using aria-describedby to associate the error message to the input. I was googling around and found [this post](https://www.davidmacd.com/blog/test-aria-describedby-errormessage-aria-live.html) and [this page on a11ysupport.io](https://a11ysupport.io/tech/aria/aria-errormessage_attribute) which documents only JAWS supporting aria-errormessage. I tested with [this pen](https://codepen.io/hbuchel/pen/GRQEKRK/3799dd675f2c1e2498730b847a80bb52) and that seems to still be the case that NVDA and VoiceOver do not read out the associated error message :(

**Comment by wlee221** [comment]
@hbuchel, I could just confirm that with VoiceOver as well 😢 . I opened #1945 to use `aria-describedBy`.
