### ISSUE TITLE
SelectField text not visible on docs in dark mode (Chrome on Windows)

### ISSUE THREAD

**Issue by cwoolum** [aws-amplify/amplify-ui#1738]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

Docs

### Please describe your bug.

When opening a select list in dark mode on the docs, the select options are not themed. Not sure if this is only a docs issue.

https://ui.docs.amplify.aws/components/selectfield

![20279BCF-5311-4E7F-A391-3DE1CEA72BA3](https://user-images.githubusercontent.com/942415/164387194-ce75ba85-d652-453e-92e8-a35de6d29cc2.GIF)
d

### What's the expected behaviour?

The options be themed

### Help us reproduce the bug!

Open the docs, set the site to dark mode with any theme, open a select field anywhere on the page.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by zchenwei** [comment]
@cwoolum, which browser are you using? I don't see this issue happen in Chrome and FireFox

**Comment by cwoolum** [comment]
Chrome 100 on Windows. It seems to work fine in FireFox
