### ISSUE TITLE
Custom icon for password field at SignIn

### ISSUE THREAD

**Issue by Besyada** [aws-amplify/amplify-ui#1748]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I want to provide my custom icon to replace the default one to show/hide password.
![image](https://user-images.githubusercontent.com/97562985/164473856-79820821-f4a4-42d5-85de-8250afe738ec.png)

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@Besyada This was fixed with the recent addition of the IconProvider:
https://ui.docs.amplify.aws/react/components/passwordfield#icons
Please check it out!
