### ISSUE TITLE
`<Heading>` needs `display: block`

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-ui#175]
<img width="824" alt="CleanShot 2021-08-09 at 21 35 51@2x" src="https://user-images.githubusercontent.com/321279/128808900-bc9336a7-3a14-402a-88da-6be6ac965380.png">

**Comment by niteshseram** [comment]
Hi, I want to have a look. Are non-member allowed to contribute?

**Comment by ericclemmons** [comment]
This looks resolved:
> <img width="1306" alt="Screen Shot 2021-10-06 at 1 19 20 PM" src="https://user-images.githubusercontent.com/15182/136260679-86cce91a-dc0a-4d0a-bef9-0bad7cd17d7f.png">

@niteshseram Absolutely!  Feel free to ping me on our discord (https://discord.gg/amplify) for any assistance.  Plus, we actively maintain our https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md guide to help get started 🙏
