### ISSUE TITLE
NextJS/Authenticator error: "Missing getServerSnapshot, which is required for server-rendered content."

### ISSUE THREAD

**Issue by nickarocho** [aws-amplify/amplify-ui#1780]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create Next App

### Please describe your bug.

When scaffolding a new Next.js app via `npx create-next-app` and trying to use the `Authenticator` component as documented, the app immediately breaks with a `500` internal server error:
```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
```

![Screen Shot 2022-04-26 at 3 43 00 PM](https://user-images.githubusercontent.com/16296496/165406437-33fb2dd6-fadf-4bc9-85fd-e5b4a23a20e3.png)

### What's the expected behaviour?

The Authenticator component should render without any error and the app should build properly with `yarn dev`.

When the `Authenticator` is removed from `index.js` the app renders as expected.

Also, I tried both with/without wrapping `_app.js` with `Authenticator.Provider` and the error occurs in both approaches.

I feel like I'm maybe doing something wrong with my setup but can't put my finger on it. The [Amplify "Getting Started" docs for Next.js](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/#api-with-server-side-rendering-ssr) still uses `import { AmplifyAuthenticator } from '@aws-amplify/ui-react-v1'`, but I wanted to work on some use cases for the new Authenticator with Next and haven't found any relevant documentation on either the JS or UI docs site. I will update docs to use the new Authenticator component, but first want to make sure I am setting things up properly myself first.

Thanks for the help!

### Help us reproduce the bug!

1. `npx create-next-app@latest next-example`
2. `cd next-example && code .`
3. `yarn add aws-amplify @aws-amplify/ui-react`
4. `amplify add auth`
5. `amplify push`
6. `amplify init` (default options)
7. Import the Authenticator component into `index.js` (snippet attached)
8. `yarn dev`
9. The error occurs immediately

### Code Snippet

```js
// pages/index.js

import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

export default function Home() {
  return (
    <Authenticator>
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user.username}</h1>
          <button onClick={signOut}>Sign out</button>
        </main>
      )}
    </Authenticator>
  );
}
```

```js
// pages/_app.js

import { Amplify } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";

import "../styles/globals.css";
import "@aws-amplify/ui-react/styles.css"; // default theme
import awsExports from "../src/aws-exports";

Amplify.configure({ ...awsExports, ssr: true });

export default function App({ Component, pageProps }) {
  return (
    <Authenticator.Provider>
      <Component {...pageProps} />
    </Authenticator.Provider>
  );
}
```

### Additional information and screenshots

```
node -v
v16.14.2
```

```
{
  "name": "webpack-5-testing",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^2.15.5",
    "aws-amplify": "^4.3.20",
    "next": "12.1.5",
    "react": "18.0.0",
    "react-dom": "18.0.0"
  },
  "devDependencies": {
    "eslint": "8.14.0",
    "eslint-config-next": "12.1.5"
  }
}
```

**Comment by slaymance** [comment]
I've narrowed this issue down to React v18. We're working on this issue now. In the meantime, the fix is to downgrade to React 17:
```
npm install react@17 react-dom@17
```
or, using yarn:
```
yarn add react@17 react-dom@17

**Comment by nickarocho** [comment]
Nice, downgrading to React@17 fixed it for me. Thanks @slaymance!

**Comment by wlee221** [comment]
Hey @nickarocho and those who found this issue, we just merged a fix #1798 and will be in the next release. I'll let you know once it's released!

**Comment by slaymance** [comment]
Fixed in [@aws-amplify/ui-react@2.15.8](https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-react%402.15.8).

**Comment by wsasouza** [comment]
> Eu reduzi esse problema para React v18. Estamos trabalhando neste problema agora. Enquanto isso, a correção é fazer o downgrade para o React 17:
> 
> ```
> npm install react@17 react-dom@17
> ```
> 
> ou, usando fios:
> 
> ```
> yarn add react@17 react-dom@17
> ```
this solved it for me, thanks!

**Comment by ericabertan** [comment]
Is this problem already solved in React 18?
