### ISSUE TITLE
Missing possibility to translate text "Cannot modify an already provided phone number when SMS MFA is enabled."

### ISSUE THREAD

**Issue by mariusprehn** [aws-amplify/amplify-ui#1789]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Amplify

### Please describe your bug.

Unfortunately, it is not possible to translate the text into other languages.

"Cannot modify an already provided phone number when SMS MFA is enabled."

### What's the expected behaviour?

Have the possibility to translate this text as well.

### Help us reproduce the bug!

ForceNewPassword and then enter a number in the PhoneNumber field, although one already exists in Cognito.

### Code Snippet

```typescript
// ForceNewPassword.tsx Row 44
{error}
```

### Additional information and screenshots
![Bildschirmfoto 2022-04-28 um 12 34 45](https://user-images.githubusercontent.com/63093778/165734321-d0c238f5-66a0-4d02-8592-aaeea9c20aa5.png)

**Comment by ErikCH** [comment]
This new translation should now be in place @mariusprehn ! Please try again with the latest version of the `Authenticator`.
