### ISSUE TITLE
Bug: Radio field focus styling missing in Safari

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#1796]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

N/A

### Please describe your bug.

The focus styling present on Radio buttons in Firefox and Chrome is missing in Safari
![2022-04-28 16 51 01](https://user-images.githubusercontent.com/6165315/165865521-08e79fc0-10bc-4d8b-94d2-111bf8d94765.gif)

### What's the expected behaviour?

Focus styling on radio buttons should work in Safari

### Help us reproduce the bug!

Visit the docs site in Safari (Version 15.3): https://ui.docs.amplify.aws/components/radiogroupfield

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
I took a look at this and it looks like an issue with our docs example. We should wrap the radio group in a fieldset and use a legend; that fixed the issue for me in Safari (and also the issue of not being able to tab into the group in other browsers that I noticed while checking this in Chrome)

**Comment by hbuchel** [comment]
Bug report for <fieldset> issue: https://github.com/aws-amplify/amplify-ui/issues/1805
PR to fix non-unique name attributes in docs: https://github.com/aws-amplify/amplify-ui/pull/1803

**Comment by reesscot** [comment]
Closing, as this was actually an issue with the docs, not the Radio field.
