### ISSUE TITLE
Bug: RadioGroupField does not use a fieldset and legend to group and label options

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#1805]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Any

### Please describe your bug.

Currently, the RadioFieldGroup uses a `<div>` with a `<label>` to group and label its options. 

### What's the expected behaviour?

It should use a `<fieldset>` with a `<legend>` so that we can convey semantic meaning to assistive technologies. 

[Related WCAG guideline: 1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG21/quickref/#info-and-relationships) | [Examples](https://www.w3.org/WAI/WCAG21/Techniques/html/H71.html)

### Help us reproduce the bug!

Any example on the [RadioGroupField docs page](https://ui.docs.amplify.aws/components/radiogroupfield) and when used in example app.

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

Just a note that I tested a "quick fix" for this by updating the RadioGroupField component to add...

- `as="fieldset"` on its [Flex component](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/primitives/RadioGroupField/RadioGroupField.tsx#L70)
- and adding `as="legend"` on its [Label component](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/primitives/RadioGroupField/RadioGroupField.tsx#L80)

... this correctly updated the markup, however the gap properties of the parent Flex component were not being applied in Chrome, leading to no margin between the legend and the option group. `<fieldset>` elements still seem pretty finicky when applying display: flex to them (can find similar bug reports as to [this one in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=375693) scattered around) so that solution might require further debugging, or an alternate solution to applying the gap.

Also, note that `<legend>` must be a the first and direct descendant of its parent <fieldset>: https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element

**Comment by joebuono** [comment]
Taking a different approach to fix iOS bug

**Comment by joebuono** [comment]
Taking a different approach to fix iOS bug
