### ISSUE TITLE
Input Value in sign up for not setting from state

### ISSUE THREAD

**Issue by Bohemus307** [aws-amplify/amplify-ui#1826]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Currently extending Authenticator to use a custom sign up component with several fields added as well a search field. When a user creates a search and selects a result item then a on change handler is setting the value of the field in state. When form is submitted only user value initially typed in field is passed to Auth.signUp instead of current value in state. 

code in _app:

![Screen Shot 2022-05-04 at 9 01 40 AM](https://user-images.githubusercontent.com/57272247/166710743-03a593e6-6b48-4e28-8174-9ae7832a5621.png)

code in custom sign up:
![Screen Shot 2022-05-04 at 9 01 19 AM](https://user-images.githubusercontent.com/57272247/166710834-1734760c-aa88-4c1d-a3a5-920426d819c3.png)
![Screen Shot 2022-05-04 at 9 01 29 AM](https://user-images.githubusercontent.com/57272247/166710875-964daf82-25a9-408b-ba43-62fd4ca3070b.png)

### Please describe a solution you'd like.

Have dynamically set values in the sign up form be passed to form data before submit. 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
Hi @Bohemus307 !

This sounds like this might be a good use case for the service function overrides. 

https://ui.docs.amplify.aws/components/authenticator#override-function-calls

You can override the call to the `handleSignUp` with the exact values you want. Like this

```
  const services = {
    async handleSignUp(formData) {
      let { username, password, attributes } = formData;
      // custom username
      username = username.toLowerCase();
      attributes.email = attributes.email.toLowerCase();
      return Auth.signUp({
        username,
        password,
        attributes,
      });
    },
  };

  return (
    <Authenticator services={services} initialState="signUp">
      {({ signOut }) => <button onClick={signOut}>Sign out</button>}
    </Authenticator>
  );
```

Does that help you?

**Comment by Bohemus307** [comment]
I thought about using this process @ErikCH. But was a bit perplexed as to how to pass the services object from any component holding state to the actual authenticator props so i can preserve the state. After review with the team we decided a Auth form shouldn't really allow for input injections and we are going to change the process to happen after the user sign up or in. But i appreciate ur swift response and have really enjoyed using the tools.
