### ISSUE TITLE
Invalid QR code (SetupTOTP) when using custom issuer name that includes a space

### ISSUE THREAD

**Issue by mroest** [aws-amplify/amplify-ui#1837]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

We use the formfield props to customize the TOTP Issuer name. Like so
`formFields={{ setupTOTP: { QR: { totpIssuer: 'Some Space' } } }}`

When on IPhone and using the MsAuthenticator you get an error scanning the QR code. The error states that the QR code is invalid.

### What's the expected behaviour?

Allow a space and/or other chars in the issuer name.

### Help us reproduce the bug!

use `formFields={{ setupTOTP: { QR: { totpIssuer: 'Some Space' } } }}` on the authenticator. Setup the account on Iphone and use msAuthenticator app. Scan QR code.

### Code Snippet

```typescript
const formFields = {
  setupTOTP: {
        QR: {
          totpIssuer: 'test issuer',
        },
      },
  }

export default function App() {
  return (
    <Authenticator formFields={formFields}>
      {({ signOut }) => <button onClick={signOut}>Sign out</button>}
    </Authenticator>
  );
}
```

**Comment by ErikCH** [comment]
Hi @mroest !

Thanks for finding this. We tested on the Google Authenticator but not on the MS one. I was able to reproduce this, I'll push up a fix soon!

**Comment by ErikCH** [comment]
This fix should be in today's release, going to close. Please reopen if it still occurs.
