### ISSUE TITLE
Create React App Bug: Font family being reset to `Times` / `serif`

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#1875]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

CRA

### Please describe your bug.

We've seen an issue in CRA where our CSS is transpiled incorrectly and the font-family is being reset to `serif`. Using the latest version of CRA (5.0.1) and Amplify UI Theming with a custom font, the `font-family` is being reset to `serif` which is the `initial` value. Other CSS properties are also being reset incorrectly to `initial` instead due to incorrect  incorrect polyfill behavior coming from the postcss-plugin `unset` included in CRA 5.

### What's the expected behaviour?

Custom font should not be reset to `serif`.

### Help us reproduce the bug!

1. Create a CRA app using the latest version
2. Write an app using a custom font
3. Do a prod build (dev build will appear fine, since poyfills aren't run by default due to browserlist settings)
4. Notice the font family is `serif`

### Additional information and screenshots

**Temporary Workaround: 
You can temporarily fix this by modifying the browserslist in package.json to newer browsers until the `unset` property in our CSS from isn't being pollyfilled.

```
"browserslist": {
    "production": [
      "last 3 chrome version",
      "last 3 firefox version",
      "last 3 safari version",
      "last 3 edge version"
    ],
    "development": [
      "last 3 chrome version",
      "last 3 firefox version",
      "last 3 safari version",
      "last 3 edge version"      
    ]
  }
```

Long term fix:
I've submitted [an issue here](https://github.com/csstools/postcss-plugins/issues/371) and the [fix has been merged](https://github.com/csstools/postcss-plugins/pull/373). We'll now need to wait for CRA to update their `@csstools/postcss-plugins` dependency.

**Comment by benhurley** [comment]
following

**Comment by reesscot** [comment]
This is now fixed in the latest release of @csstools/postcss-unset-value (1.0.1). I tested it out by creating a new Create React App and am seeing the correct font-family being applied now in my Amplify UI App. 

@benhurley Can you please test on your end by updating your dependencies?
```
npm update
```

**Comment by reesscot** [comment]
Closing as this issue has been fixed upsream in `@csstools/postcss-unset-value` version `1.0.1`.
