### ISSUE TITLE
[react-native] New Authenticator UI coming to react-native?

### ISSUE THREAD

**Issue by MartijnGevaert** [aws-amplify/amplify-ui#1902]
### On which framework/platform would you like to see this feature implemented?

React, React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

The feature differences between the react-native and react-ui are becoming quite large.
Currently for my react-native application which is compiled to react-native for web as well, the authenticator needs to be implemented twice.

Aside from the higher chance of bugs and higher workload, it also makes it difficult to have a consistent style across native and web.
![image](https://user-images.githubusercontent.com/41551215/168425491-077f620b-cbc5-46a5-b72d-6d1d79d3c70d.png)

### Please describe a solution you'd like.

Ideally, the new style react-UI would become available on react-native as well.

I think some work has already been done regarding this:
- https://github.com/aws-amplify/amplify-ui/pull/41
- https://github.com/aws-amplify/amplify-ui/pull/3

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @MartijnGevaert! Yes, a React Native Authenticator is in the works. Thank you for letting us know your interest!

**Comment by calebpollman** [comment]
We have released the new Amplify UI `Authenticator` component for developer preview! Docs can be found [here](https://ui.docs.amplify.aws/react-native)
