### ISSUE TITLE
FR Allow for signUp specific redirects

### ISSUE THREAD

**Issue by vymao** [aws-amplify/amplify-ui#1909]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

There is an example in the Amplify UI docs that references how to [use Amplify UI Authenticator with a redirect.](https://ui.docs.amplify.aws/react/components/authenticator#access-auth-state). However, I'm wondering if it is possible to have a different redirect for signing in vs. signing up; signing in would route to the main page, and signing up would route to a different page upon completion. 

Right now, just looking at `route === 'authenticated'` doesn't distinguish these possibilities. 

### Please describe a solution you'd like.

After the user signs up and confirms their email, the user can be redirected to a route that is different than when the user signs up. Maybe have a value for `route` such as `authenticated_login` and `authenticated_signup`.

**Comment by vymao** [comment]
Bumping this to see if it is possible?

**Comment by reesscot** [comment]
Thank you for your feature request. We are closing this out as it's not a feature we plan to support.
