### ISSUE TITLE
Ionic: Authenticator Birthdate picker issue with Android

### ISSUE THREAD

**Issue by Guillermo1808** [aws-amplify/amplify-ui#1958]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Android

### Which UI component?

Authenticator

### How is your app built?

Ionic / Capacitor

### Please describe your bug.

We have the authenticator that works correctly in web version (including responsive design) but when we open the app in Android the birthdate picker doesn't look as it should.
![Screen Shot 2022-05-15 at 17 24 15](https://user-images.githubusercontent.com/36081005/169882471-e31716de-bd58-4600-8558-3ed5a6128942.png)
That is the Android Version

### What's the expected behaviour?

In the web version looks like this and that is how it should look like.
![Screen Shot 2022-05-15 at 17 03 13](https://user-images.githubusercontent.com/36081005/169882566-f47856db-2a4d-465f-9560-299dceca1e95.png)

### Help us reproduce the bug!

This is how the code looks in the html:
<img width="428" alt="Screen Shot 2022-05-19 at 15 43 37" src="https://user-images.githubusercontent.com/36081005/169882607-46656664-4d14-4872-a3fe-3ae008466928.png">

### Code Snippet

```typescript
// Put your code below this line.
<authenticator id="authenticator"
        :login-mechanisms="['username']"
        :sign-up-attributes="[
        'username',
        'email',
        'given_name',
        'family_name',
        'birthdate'
        ]"
        :services="services"
    >
```

**Comment by wlee221** [comment]
Hi, @Guillermo1808! Qq, which browser are you using in android? Chrome?

**Comment by Guillermo1808** [comment]
Chrome for web testing and Android Studio for the rest

**Comment by ErikCH** [comment]
Hi @Guillermo1808 !

Just wanted to let you know we are still looking at this. We pushed a different fix up for Ionic a little while ago. Can you test again to see if this is still occuring?

**Comment by ferrero1987** [comment]
the bug still occurs, but even with an iphone on both chrome and safari!

**Comment by ferrero1987** [comment]
How can I change the mask from dd/mm/yyyy to mm/dd/yyyy?

**Comment by reesscot** [comment]
@ferrero1987 Can you confirm that you are also using Ionic?

**Comment by reesscot** [comment]
This should be fixed by this PR: https://github.com/aws-amplify/amplify-ui/pull/3330 which will be released next week.
