### ISSUE TITLE
Error on create account after log out

### ISSUE THREAD

**Issue by rrhalim** [aws-amplify/amplify-ui#1968]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

Logout then go to "Create Account".  It shows blank space with error below:

![image](https://user-images.githubusercontent.com/100475670/169967055-823f3f5b-dc97-4d40-b153-b54fc3dbec4c.png)

### What's the expected behaviour?

It should show the create account panel

### Help us reproduce the bug!

Please see code snippet.
Using "@aws-amplify/ui-react": "^2.15.2".

### Code Snippet

import { withAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

function MainPage({ signOut, user }) {
  ...
  return (
      ...
      <button onClick={signOut}>Sign out</button>
      ...
 );
}
export default withAuthenticator(MainPage);

**Comment by ErikCH** [comment]
Hi @rrhalim !

I was not able to reproduce this, with our latest version of the Authenticator. Could you try again with our latest version `@aws-amplify/ui-react@2.18.2` and see if you can reproduce it.

And if so, can you share your `package.json` file?

**Comment by rrhalim** [comment]
Hi ErikCH,  It was fixed after updating to version 2.18.2.  Thank you.
