### ISSUE TITLE
Docs: bad links from Authenticator theming doc

### ISSUE THREAD

**Issue by teodoratrinca** [aws-amplify/amplify-ui#2000]
**Page**: [`https://ui.docs.amplify.aws/[platform]/theming/react`](https://ui.docs.amplify.aws/[platform]/theming/react)
**Feedback**:

**Comment by wlee221** [comment]
Hi @teodoratrinca, thanks for the report. How did you get to that broken link?

**Comment by wlee221** [comment]
Oh found it, it's from the five links in https://ui.docs.amplify.aws/react/components/authenticator#theme-provider-theme.
