### ISSUE TITLE
Customize AmplifyForgotPassword With Delivery State

### ISSUE THREAD

**Issue by mikaelapc** [aws-amplify/amplify-ui#2015]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

In the AmplifyForgotPassword component, there is the ability to override the `handleSend` method. In my use case, I want the Send button to point to my backend to check user status. However, since I'm overriding the built-in `handleSend`, the `delivery` state on the AmplifyForgotPassword does not get updated and the component does progress from the view prompting for the username to the view prompting for the code that was sent.

### Please describe a solution you'd like.

It would be great if the delivery state were exposed and able to be overridden.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
Hi @mikaelapc !

What version of the Authenticator are you using?

We have a newer Authenticator that may solve your problem.

https://ui.docs.amplify.aws/react/components/authenticator

We have a way to override function calls as well with the newer version.

https://ui.docs.amplify.aws/react/components/authenticator#override-function-calls

You may need to also use the `useAuthenticator` hook. 

https://ui.docs.amplify.aws/react/components/authenticator#useauthenticator-hook

Let me know if that helps.

**Comment by calebpollman** [comment]
@mikaelapc It looks like the functionality you are looking can be achieved via the `services.handleForgotPassword` prop ([docs](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls))> Please let us know if that does not cover your use case!
