### ISSUE TITLE
Underscore _ not being validated as a special character on Authenticator

### ISSUE THREAD

**Issue by jerocosio** [aws-amplify/amplify-ui#2052]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

The <Authenticator /> component isn't recognizing the underscore '_' as a special character when signing up a new account into Cognito.

When I add a test e-mail with a test password like 'Test_123' with the requirements of more than 8 characters, uppercase, lowercase and special character I get an error even though the password has all the requirements. I see that this only happens with the underscore. Because if I just add a dot '.' or other special character in the password then it validates it correctly.

![Uploading Screen Shot 2022-06-08 at 1.03.35 p.m..png…]()

### What's the expected behaviour?

To get the underscore as a valid special character.

### Help us reproduce the bug!

Try to sign up a new user with the mentioned password rules, and the underscore won't be accepted as one.

**Comment by wlee221** [comment]
Hi @jerocosio! We were able to reproduce and will roll out a fix shortly.

**Comment by wlee221** [comment]
We have merged the fix and will be released on next week (usually Tuesdays at 2:30 pm). 

If you want to verify this fix early, this is already to published to `@next` NPM tag 🙏

**Comment by jerocosio** [comment]
Amazing, thanks for the quick fix @wlee221!
