### ISSUE TITLE
`:login-mechanisms="[]"` broken sinces @aws-amplify/ui-vue@2.3.1

### ISSUE THREAD

**Issue by zorji** [aws-amplify/amplify-ui#2073]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### Please describe your bug.

Authenticator no longer works with empty login mechanisms since 2.3.1.

I have tested with the following versions and it works with `:login-mechanisms="[]"`
- 2.0.5
- 2.2.2
- 2.3.0

I am getting the following errors

```
[Vue warn]: Unhandled error during execution of beforeMount hook 
  at <Anonymous route="signIn" > 
  at <Anonymous disabled=false class="amplify-flex" style= {flex-direction: 'column'} > 
  at <Anonymous class="amplify-flex" style= {flex-direction: 'column'} > 
  at <Anonymous data-amplify-authenticator-signin="" onInput=fn<onInput> onSubmit=fn  ... > 
  at <Anonymous > 
  at <Anonymous key=0 onSignInSubmit=fn<onSignInSubmitI> ref=fn<ref> > 
  at <Anonymous login-mechanisms= [] social-providers= (2) ['apple', 'google'] > 
  at <App> 
  at <App>
```

By reading the code in 2.3.1, it looks like the `fieldName` provided to this function is undefined https://github.com/aws-amplify/amplify-ui/blob/%40aws-amplify/ui-vue%402.3.1/packages/ui/src/helpers/authenticator/formFields/defaults.ts#L26

### What's the expected behaviour?

It should not complain error and hide the default login mechanism and only allows for social providers

### Help us reproduce the bug!

Minimum code to reproduce

```vue
<script lang="ts" setup>
import { Authenticator } from '@aws-amplify/ui-vue'

</script>

<template>
  <Authenticator
    :login-mechanisms="[]"
    :social-providers="['apple', 'google']"
  >
    <template>
    </template>
  </Authenticator>
</template>
```

### Code Snippet

```vue
<script lang="ts" setup>
import { Authenticator } from '@aws-amplify/ui-vue'

</script>

<template>
  <Authenticator
    :login-mechanisms="[]"
    :social-providers="['apple', 'google']"
  >
    <template>
    </template>
  </Authenticator>
</template>
```

**Comment by wlee221** [comment]
Thanks for finding which version it broke! It's a regression from #1484, and we'll take a look asap.

**Comment by wlee221** [comment]
Hmm, I took a look at our previous implementation, but we never hid default login mechanisms even if `loginMechanisms` were empty. Here's the `Authenticator` I got with your code on `ui-vue@2.3.0`: 

![Screen Shot 2022-06-11 at 3 29 19 PM](https://user-images.githubusercontent.com/43682783/173206899-2549ea40-1f06-4c76-8608-9425e3e5d425.png)

Were you hiding the default login mechanism through some other means like css?

**Comment by zorji** [comment]
@wlee221 Yes, I also hid section below and the "Sign In/Create Account" tab on top with CSS. I think saw it from one of the guide before but I couldn't find it now as it was a long time ago.

I want to only allow social login and disable the rest, wondering is it still possible in the latest version?

**Comment by wlee221** [comment]
Gotcha! Yep, it's a bug that `:login-mechanisms=[]` is throwing a JS error and we'll fix it. Then you can use the same CSS workaround to hide form fields.

Until the fix, you can just fill it some dummy value like `:login-mechanisms=['username']` and just hide it with css.

**Comment by wlee221** [comment]
That said, we don't have an official way to only show social providers. Do you want to open a feature request? We'll keep this issue focused on fixing `:login-mechanisms="[]"` bug.

**Comment by zorji** [comment]
Thanks @wlee221 

TBH I am fine with `:login-mechanisms=['username']` and hide it with CSS so I guess you don't have to fix it if it wasn't meant to be work like that.

> That said, we don't have an official way to only show social providers. Do you want to open a feature request? We'll keep this issue focused on fixing :login-mechanisms="[]" bug.

I want a way to complete disable all other auth methods except social, I guess it's not really a frontend UI thing so I guess I'll pass for now.

Thanks for all the time and efforts looking into this, really appreciated.

**Comment by ErikCH** [comment]
Thanks @zorji ! Feel free to open another issue if you have any more problems
