### ISSUE TITLE
angular button sign in are too long

### ISSUE THREAD

**Issue by Deliana90** [aws-amplify/amplify-ui#2162]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

ng new

### Please describe your bug.

![1232121](https://user-images.githubusercontent.com/96174573/174706766-1bbe628c-c7b9-420d-ae6f-871a882b2f93.png)
forgot password button is full width which is doen't same as on the demo page

### What's the expected behaviour?

at this demo https://ui.docs.amplify.aws/angular/components/authenticator it's not full width

### Help us reproduce the bug!

I want to make demo on stackblitz but i got error "ngcc from @aws-amplify/ui-angular" there

ng new, then follow instruction
https://ui.docs.amplify.aws/angular/getting-started/installation
https://ui.docs.amplify.aws/angular/getting-started/troubleshooting
https://ui.docs.amplify.aws/angular/components/authenticator

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by Milan-Shah** [comment]
Hey @Deliana90, unfortunately we are unable to reproduce the issue on our end. We recommend you to try it out with the latest version of Angular. Please feel free to reopen or create a new issue if you are seeing the same problem! We are here to help :)
