### ISSUE TITLE
TextAreaField does not show line breaks properly by default

### ISSUE THREAD

**Issue by chenzhekl** [aws-amplify/amplify-ui#2173]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Parcel

### Please describe your bug.

By default, the TextAreaField component does not show line breaks properly. A custom CSS `white-space: pre-wrap;` is required to make it work.

### What's the expected behaviour?

Multi-line texts are shown as they are. That is, text on different lines should be put on different lines in TextAreaField.

### Help us reproduce the bug!

By typing some text with enters in the official demo page

https://ui.docs.amplify.aws/react/components/textareafield

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

Tested on Firefox 101.0.1

**Comment by chenzhekl** [comment]
I did a bit more test, and this issue is only reproducible on Firefox.

**Comment by slaymance** [comment]
Thanks @chenzhekl, I was able to reproduce this issue using Firefox v91.10.0. We'll get this prioritized to fix!
