### ISSUE TITLE
aws-amplify-react: User cannot be confirm. Current status is CONFIRMED

### ISSUE THREAD

**Issue by kennu** [aws-amplify/amplify-ui#219]
Scenario: User signs up with **aws-amplify-react** and enters the **Confirm Sign Up** view, where they are expected to enter the confirmation code from an email.

While in this view, let's say the user is simultaneously confirmed by an alternative method, such as link-based confirmation (which opens in another browser window).

In this situation the user will get stuck in the sign-up flow with this error:

    User cannot be confirm. Current status is CONFIRMED

If they try to resend the code, they get another error:

    User is already confirmed.

My proposal is that **aws-amplify-react** understands that the user has already been confirmed by an alternative method and moves them forward in the sign-up flow, instead of keeping asking for confirmation which cannot happen.

**Comment by nickordoodle** [comment]
I experience this error from Cognito hosted web authentication UI under the same conditions.  Is there a solution to avoiding this or redirecting or does this logic need to be handled manually?

**Comment by csrs** [comment]
@nickordoodle Maybe this helps: I had a similar problem but it went away after I did `amplify pull`, since I was using an outdated version of the amplify configs which were interfering with the signup code.
