### ISSUE TITLE
(FR) LocationSearch - expose change handlers in React

### ISSUE THREAD

**Issue by crnkyunicorn** [aws-amplify/amplify-ui#2190]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

Hi,
I'm looking for an example of how to get the selected location from the LocationSearch react component.  Are there events available on this component.  The documentation seems a bit thin.

Thanks

### Please describe a solution you'd like.

See the following, https://github.com/aws-amplify/amplify-ui/discussions/1931

### We love contributors! Is this something you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by phoenixbeats01** [comment]
Running into this too, I'm unable to figure out how to attach an onChange event handler to the component

**Comment by reesscot** [comment]
Thank you for your feature request, we are not planning on adding this to our roadmap.
