### ISSUE TITLE
Direct routeLink to subforms of <amplify-authenticator>

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-ui#220]
Is there a way to directly routeLink to the "Create new password" form of the `<amplify-authenticator>`

At the moment I have a button [Reset password] on the profile.html page and want to jump to the login page with the Create new password" form of the `<amplify-authenticator>` open without having to click an extra link.

**Comment by ErikCH** [comment]
Hi @sprucify !

In our new implementation of the Authenticator we have this new functionality.

If you like to directly link to this page, you can pass the `<authenticator>` a new prop called `initialState`. If you set this to `resetPassword` this will default the authenticator to open on that page. 

```
export default withAuthenticator(App, {
  initialState: 'resetPassword',
});
```
You can learn more about this feature [here](https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#initialstate).

Feel free to try out the new authenticator and let us know what you think. It's under the `@next` tag. 
https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react

**Comment by ErikCH** [comment]
I'll close this, please open if this does not resolve your issue.
