### ISSUE TITLE
Feature request: PhotoPicker should allow setting id

### ISSUE THREAD

**Issue by et304383** [aws-amplify/amplify-ui#221]
**Is your feature request related to a problem? Please describe.**
Yes, in that I cannot reference the PhotoPicker input element by getting the element by id and using the element to trigger upload by means of a separate submit button.

**Describe the solution you'd like**
The PhotoPicker object should support additional attributes and pass them through to the create of the input object in Picker.js

**Describe alternatives you've considered**
None

**Comment by Milan-Shah** [comment]
Marking this issue as closed since there hasn't been any activity on this for a while. If you still having an issue with your photopicker, please create a new issue!
