### ISSUE TITLE
Cannot disable SignUp or Greetings in Authenticator Component.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-ui#223]
**Describe the bug**
I am using an Authenticator Component in aws-amplify-react-native but cannot disable the SignUp component using the usual methods. It shows up every time.

**To Reproduce**
```
class AuthScreen extends React.Component {
  render() {
    return (
      <View style={Style.container}>
        <View style={Style.logoContainer}>
          <Image style={Style.logo} source={Images.logo} resizeMode={'contain'} />
        </View>
        <Authenticator hide={[Greetings, SignUp]} theme={rprTheme} />
      </View>
    )
  }
}

```

**Expected behavior**
Expecting to have the SignUp component hidden.

**Screenshots**
It just shows up as you would expect the standard component to show up with all of the usual components.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by ericclemmons** [comment]
I know it's been a while, but I'd like to understand the desired UX for having an Authenticator with Sign Up disabled.

(Is account creation disabled & only available to admins?)

**Comment by BrendonHudnell** [comment]
Is there any update on this ticket? I would like to be able to hide the Sign Up tab of the authenticator as well.

**Comment by Milan-Shah** [comment]
We have added new hide sign up prop [#1260](https://github.com/aws-amplify/amplify-ui/pull/1260). Please let us know if you have any questions.
