### ISSUE TITLE
Application error for Phone Number Field on docs site

### ISSUE THREAD

**Issue by atierian** [aws-amplify/amplify-ui#2233]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

N/A - docs related

### What browsers are you seeing the problem on?

Firefox, Safari

### Please describe your bug.

Navigating to the `Phone Number Field` primitive on the docs site results in an error. [[link](https://ui.docs.amplify.aws/react/components/phonenumberfield)]

#### Error message on docs site
`Application error: a client-side exception has occurred (see the browser console for more information).`

#### Console Error:
<details>
  <summary>Click to expand</summary>
  
```
[Error] [ERROR] 07:03.511 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
        
	error
	(anonymous function) (3505-69c3c928c1ed883bf172.js:1:205264)
	(anonymous function) (3505-69c3c928c1ed883bf172.js:1:206159)
	e (3505-69c3c928c1ed883bf172.js:1:65576)
	e (3505-69c3c928c1ed883bf172.js:1:65652)
	(anonymous function) (3505-69c3c928c1ed883bf172.js:1:105822)
	(anonymous function) (3505-69c3c928c1ed883bf172.js:1:92161)
	(anonymous function) (3505-69c3c928c1ed883bf172.js:1:69148)
	s (3505-69c3c928c1ed883bf172.js:1:67989)
	promiseReactionJob
```
</details>

### What's the expected behaviour?

I should be able to see the documentation for the `Phone Number Field` component.

### Help us reproduce the bug!

Navigate to https://ui.docs.amplify.aws/react/components/phonenumberfield on Safari or Firefox (didn't try Chrome).

### Code Snippet

N/A

**Comment by reesscot** [comment]
See https://github.com/aws-amplify/amplify-ui/pull/2230

**Comment by reesscot** [comment]
The fix has been released, closing
