### ISSUE TITLE
"username undefined" error in authenticator when user auto-confirmed

### ISSUE THREAD

**Issue by clintfoster** [aws-amplify/amplify-ui#2235]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

We are using `authenticator` in our Vue 3 frontend, and we have a pre-signup trigger Lambda function defined in our Amplify backend to auto-confirm username, email and phone. Thanks to authenticator's "zero config" behavior, when the user signs up it automatically skips the prompt to enter the code since it recognizes the user has been confirmed. This has been working for several months, and there have been no significant changes to our trigger or frontend code.

Recently we started getting an error after the user signs up and the authenticator dialog switches to the signin tab: `Cannot read properties of undefined (reading 'username')`. Screenshot:

![AuthenticatorUsernameUndefined](https://user-images.githubusercontent.com/1449737/176778831-116389a0-7816-4691-9f35-d1ce728e3f6e.jpg)

There are no errors in the javascript console.

Neither our frontend nor our trigger references `username`. There are no errors for the trigger function in the CloudWatch logs. The error seems to be harmless since the new user is able to sign in successfully.

If we remove the pre-signup trigger the problem goes away. But, of course, now Cognito sends a confirmation email and the authenticator dialog prompts for the confirmation code, which is not the desired behavior.

### What's the expected behaviour?

The authenticator dialog should not show a spurious error when the user is auto-confirmed by the pre-signup trigger.

### Help us reproduce the bug!

In Amplify set up a Cognito backend with a pre-signup trigger similar to [this example](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html#aws-lambda-triggers-pre-registration-example-2)  in the Amplify developer's guide to auto-confirm users, e.g.:

```js
exports.handler = async (evt) => {
    evt.response.autoConfirmUser = true
    evt.response.autoVerifyEmail = true
    evt.response.autoVerifyPhone = evt.request?.userAttributes?.phone_number?.length > 0
    return evt
}
```

Create a trivial Vue 3 frontend using authenticator similar to the example in the [Authenticator doc](https://ui.docs.amplify.aws/vue/connected-components/authenticator/configuration) per code snippet below.

Sign up in the app, and the error will be displayed when the dialog switches to the signin tab. However, you will still be able to sign in.

### Code Snippet

```html
  <authenticator>
    <template #default="{ user, signOut }">
      // trivial app here
    </template>
  </authenticator>
```

### Additional information and screenshots

package.json snippet

```json
  "dependencies": {
    "@aws-amplify/ui-components": "^1.9.6",
    "@aws-amplify/ui-vue": "^2.4.12",
    "@quasar/extras": "^1.14.2",
    "@types/luxon": "^2.3.2",
    "aws-amplify": "^4.3.26",
    "luxon": "^2.4.0",
    "quasar": "^2.7.4",
    "vue": "^3.2.37",
    "vue-router": "^4.0.16"
  },
```

**Comment by ErikCH** [comment]
Hi @clintfoster !

Thanks for opening this up. I am trying to reproduce this. So this only occurs occasionally?

**Comment by clintfoster** [comment]
Hi @ErikCH Thanks for looking at this issue. I removed the word "spurious" since it could be misinterpreted as "intermittent". The error is consistent, but apparently not an actual problem since the user is still able to sign in, despite the error. 

Let me know if you have problems reproducing it. I can't think of anything significant that changed in either our pre signup trigger (Amplify backend) or our use of the authenticator component (frontend), so I suspect something changed either in the Cognito service or authenticator causing this benign error to show up a few weeks ago. Benign is probably a better word. It happens after sign-up (2nd tab) when the user is redirected to the 1st tab to enter their new credentials and sign in. It looks serious, but sign-in proceeds normally if you ignore the error. On subsequent sign-ins the error is not displayed.

My best guess is something about the pre signup trigger confirming the user, email and phone is now triggering an event that causes the benign error. I tried rolling back authenticator 2 or 3 versions and it still happened. Possibly I didn't go back far enough. Let me now if you'd like me to try with a specific version or do a screen share.

**Comment by clintfoster** [comment]
This might be helpful: You might think authenticator wouldn't properly handle a trigger auto-confirming the user, and continue with the standard workflow to prompt for the code (which, of course, is never sent). However, that workflow has been working correctly for about 6 months. When I first implemented the pre signup trigger I expected I would need to configure authenticator not to prompt for the code. But, it worked out of the box, switching to prompting the user to sign in as soon as the trigger finished confirming them.

**Comment by ErikCH** [comment]
I was able to reproduce this problem. I'm working on a fix now!

**Comment by ErikCH** [comment]
I've created a fix for this. It should be in our next fix later this week.  Please reopen this @clintfoster if it does not fix your issue.
