### ISSUE TITLE
Vite Plugin Pages has wrong import in Vue

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#2246]
https://github.com/aws-amplify/amplify-ui/blob/80f11bab303f43cbff16e061eb87758b887c3035/examples/vue/src/router/index.ts#L3

@ErikCH - Hey Eric! Hope you've been well! 😎

So I'm diving back into developing w/ Vue + Amplify, and I noticed the that code (referenced above). Is that intentional? Is it supposed to be `import routes from 'virtual:generated-pages-react';` for vue3?

_Originally posted by @armenr in https://github.com/aws-amplify/amplify-ui/discussions/2193_

**Comment by armenr** [comment]
Thanks @ErikCH !
