### ISSUE TITLE
Two search bars on adding LocationSearch component in MapView

### ISSUE THREAD

**Issue by Mister-JP** [aws-amplify/amplify-ui#2253]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

brazil-build install

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

So My search barwhich came as a default with mapview was giving very zoomed in results which was not suitable for my usecase, I wanted less zoomed result so I asked it on #amplify-community-general-discussion which is in amazon internal slack channel. and I added <LocationSearch zoom={8} /> which worked but now I can see two search bars one with default zoom, and other with reduced zoom. my code is :
```
<Row style={{position: "absolute"}} id = "MapViewRow">
          <MapView 
                    initialViewState={{
                        longitude: -90.3381659,
                        latitude: 37.615686,
                        zoom: 3,
                    }}
                    style={{ width: "174vh", height: "110vh" }} 
                    id = "MapView"
                    >
                        
                        <Geocoder
                        pospupRender={(stuff: any)=>{
                        }}
                        />

                        {posts.map((loc: any)=>(
                            <MarkerWithPopup
                                key={loc.FcID.S}
                                latitude={loc.latitude.S}
                                longitude={loc.longitude.S}
                                pass={loc.pass}
                                fails = {loc.fails}
                                versions = {loc.SoftwareVersion}
                                myColor = {versionColorCode}
                                mode = {mode}
                            />
                        ))}
                        <LocationSearch zoom={8} />
                    </MapView>
<row>
```

### What's the expected behaviour?

It should have given a search bar with specified zoom level result.

### Code Snippet

```typescript
<Row style={{position: "absolute"}} id = "MapViewRow">
          <MapView //bonus feature: save last position and zoom level on the browser, resume from that zoom level pickup from they left off
                    initialViewState={{
                        longitude: -90.3381659,
                        latitude: 37.615686,
                        zoom: 3,
                    }}
                    style={{ width: "174vh", height: "110vh" }} 
                    id = "MapView"
                    >
                        
                        <Geocoder
                        pospupRender={(stuff: any)=>{
                            //console.log(stuff)
                            return "hello";
                        }}
                        />

                        {posts.map((loc: any)=>(
                            <MarkerWithPopup
                                key={loc.FcID.S}
                                latitude={loc.latitude.S}
                                longitude={loc.longitude.S}
                                pass={loc.pass}
                                fails = {loc.fails}
                                versions = {loc.SoftwareVersion}
                                myColor = {versionColorCode}
                                mode = {mode}
                            />
                        ))}
                        <LocationSearch zoom={8} />
                    </MapView>

```

### Additional information and screenshots

<img width="300" alt="Screen Shot 2022-07-05 at 3 20 49 PM" src="https://user-images.githubusercontent.com/63716051/177428338-1eff1982-7e83-4ac1-9405-a789e6b12b85.png">

**Comment by thaddmt** [comment]
Connected with @Mister-JP offline and resolved the issue. Problem was that they had both a `Geocoder` and a `LocationSearch component which are aliases for the same component, thus it was rendered twice.
