### ISSUE TITLE
Vue & React Authenticator with Ionic does not receive input on device simulator 

### ISSUE THREAD

**Issue by siegerts** [aws-amplify/amplify-ui#2254]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Ionic 

### Please describe your bug.

The Vue Authenticator component is not receiving the typed input (from simulator keyboard and local machine) when developing locally. 

### What's the expected behaviour?

The input populates.

### Help us reproduce the bug!

1. Create a Vue ionic app
2. wrap the router with the Amplify `Authenticator`
3. run the simulator with `ionic capacitor run ios -l --external`
4. select iPhone 12
5. try to fill in the inputs

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

https://user-images.githubusercontent.com/634958/177581434-db769317-428f-4889-b122-6d0b7e656611.mov

**Comment by ErikCH** [comment]
I was able to reproduce this. It seems the `ionic` components that wrap the vue3 app, have some effect on the inputs. I'll put this on our roadmap as a bug to fix.

**Comment by ErikCH** [comment]
This has been merged. @siegerts this will go out on next release!

**Comment by siegerts** [comment]
🙌🏻 Amazing work! Thank you!
