### ISSUE TITLE
Material UI bootstrapped

### ISSUE THREAD

**Issue by pspanchal** [aws-amplify/amplify-ui#226]
**Is your feature request related to a problem? Please describe.**
No sample UI framework for getting a jumpstart of javascript + Appsync

**Describe the solution you'd like**
Need material-ui bootstrap for react, appsync, graphql similar to https://material-ui.com/getting-started/example-projects/

**Describe alternatives you've considered**
DIY.

**Additional context**
An example similar to React+MaterialUI+Firebase 
Need material-ui bootstrap for react, appsync, graphql similar to https://material-ui.com/getting-started/example-projects/

**Comment by Milan-Shah** [comment]
We have released a newer version of [Authenticator](https://ui.docs.amplify.aws/components/authenticator) which has a getting started guide with an example app for how to use our UI components, we will also share example apps for primitives we have built in our UI library. If you have any more issues or suggestion on how we can make our UI library better, please let us know!
