### ISSUE TITLE
Tutorial: How to create an application with protected routes using the Authenticator component

### ISSUE THREAD

**Issue by lienas** [aws-amplify/amplify-ui#2266]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

checked out from github

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

1. I checked out the repo on [https://github.com/aws-amplify/amplify-ui](https://github.com/aws-amplify/amplify-ui)
2. I opened the app inside [https://github.com/aws-amplify/amplify-ui/tree/main/guides/react/protected-routes](https://github.com/aws-amplify/amplify-ui/tree/main/guides/react/protected-routes)
3. I ran `npm install`
4. I ran `npm start`
5. when I open `http://localhost:3000` I get a 404-page

### What's the expected behaviour?

Render the Layout-component

### Help us reproduce the bug!

see description

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

<img width="539" alt="Bildschirmfoto 2022-07-08 um 11 05 32" src="https://user-images.githubusercontent.com/8291992/177958205-862bf28d-1ea4-4b18-ab85-cd84ce495298.png">

My IDE cannot resolve Routes from 'react-router-dom'; see screenshot

**Comment by lienas** [comment]
Hi Erik,

unfortunately that still does not work.
Now I get the following error:
-------------------
***@***.*** protected-routes % npm run build

> ***@***.*** build
> react-app-rewired build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../../../../environments/auth-with-email/src/aws-exports.js' in '/Users/thomas/Development/aws/amplify-ui/guides/react/protected-routes/src'

Doe I first have run amlify init ??

Thomas Lucas

Von: Erik Hanchett ***@***.***>
Datum: Freitag, 8. Juli 2022 um 18:45
An: aws-amplify/amplify-ui ***@***.***>
Cc: Thomas Lucas ***@***.***>, Mention ***@***.***>
Betreff: Re: [aws-amplify/amplify-ui] Tutorial: How to create an application with protected routes using the Authenticator component (Issue #2266)

Hi @lienas<https://github.com/lienas> !

To get the sample app working you have to build it first.

npm run build
npm start

We should probably make that more explicit in our documentation, or add in a prebuild step. Does that help?

**Comment by rootbeerdan** [comment]
I can replicate this issue:

```
PS C:\Users\daniel\protected-routes> npm run build

> route-amplify-demo@0.1.0 build
> react-app-rewired build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../../../../environments/auth-with-email/src/aws-exports.js' in 'C:\Users\daniel\protected-routes\src'
```

**Comment by ErikCH** [comment]
Hi @lienas !

Yes, sorry I forgot to mention, you also need to have a valid `aws-exports` file to run the demo. If you want to just run it without error, but not see the demo, you can change the `index.js` file and remove the `aws_exports` line. Then
change the Amplify configure as seen below.

```
Amplify.configure({});
```

Otherwise you need to setup a valid authenticated Amlify back-end. We have instructs on that here.

https://github.com/aws-amplify/amplify-ui/tree/main/environments

Once you have the `aws-exports` file, then update the `index.js` file to point to it.

**Comment by ErikCH** [comment]
We've added a comment in the app to make this more clear on how to run the demo. I'll close this for now.
