### ISSUE TITLE
aws-amplify-react S3Image component ignores cache control

### ISSUE THREAD

**Issue by jguddas** [aws-amplify/amplify-ui#227]
**Describe the bug**
the S3Image component ignores cache control headers

**To Reproduce**
- add `<S3Image imgKey={keyToProtectedAndCacheControledResource}/>`
- open the network tab in your browser of choice
- see the image load from s3
- see that the image has cache control headers
- reload
- see the image load from s3 using a different uri(query string changed)

**Expected behavior**
loading of the image from the same uri every time

**Comment by jafreitas90** [comment]
The error persists, any feedback?

**Comment by jafreitas90** [comment]
Thank you aws for your support :)

**Comment by reesscot** [comment]
Closing this as the `S3Image` component has been deprecated.

**Comment by majirosstefan** [comment]
So what we should use now, if `S3Image` is now deprecated, please ?

**Comment by derekrsargent** [comment]
> So what we should use now, if `S3Image` is now deprecated, please ?

`import { AmplifyS3Image } from '@aws-amplify/ui-react';`

**Comment by anil1712** [comment]
@derekrsargent is it working for you?
