### ISSUE TITLE
useAuthenticator returns wrong user object in first MFA login with TOTP

### ISSUE THREAD

**Issue by marcos-boger** [aws-amplify/amplify-ui#2274]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Firefox, Chrome

### Please describe your bug.

This bug only happens in a user's first login with MFA using TOTP. The new user is prompted to change his temporary password and to register an MFA device. After registering the device and confirming the TOTP generated code, the useAuthenticator **route attribute** becomes 'authenticated' and the user is redirected to a private route. However, the useAuthenticator **user attribute** is still not correctly set and returns a wrong user object, resulting in a bug as parts of the page cannot access user information yet. Refreshing the page makes everything work normally again. 

### What's the expected behaviour?

That even in the first login attempt with MFA the route and user attributes are updated correctly and there is no need to refresh the page to make it work. 

### Help us reproduce the bug!

Create a private route with the code: 
```typescript
export const PrivateRoute = ({
  children,
  permission
}: PrivateRouteProps): JSX.Element => {
  const { route, user } = useAuthenticator((context) => [context.route]);
  const location = useLocation();

  if (route === 'authenticated') {
    return <>{children}</>;
  }

  return <Navigate to='/login' state={{ from: location }} replace />;
};
```

Make the private component access user information with **useAuthenticator** hook:
```typescript
export const privateComponent = (): JSX.Element => {
  const { user, signOut } = useAuthenticator((context) => [context.user]);
  const userInfo = user?.getSignInUserSession()?.getIdToken().decodePayload();

  return <p>{userInfo}<\p>;
}
```

Create a basic login page with the **Authenticator** component and make it navigate to the private component after checking that (route === 'authenticated'):
```typescript
export const LoginPage = (): JSX.Element => {
  const navigate = useNavigate();
  const location = useLocation();
  const { route } = useAuthenticator((context) => [context.route]);
  const locationState = location.state as LocationState;
  const from = locationState?.from?.pathname || '/';

  useEffect(() => {
    if (route === 'authenticated') {
      navigate(from, { replace: true });
    }
  }, [route, navigate, from]);

  return (
    <Authenticator hideSignUp={true} />
  );

}
```

### Code Snippet

Our workaround was this piece of code:

```typescript
export const PrivateRoute = ({
  children,
  permission
}: PrivateRouteProps): JSX.Element => {
  const { route, user } = useAuthenticator((context) => [context.route]);

  //Reload window because of first login with MFA bug
  if (user && typeof user.getSignInUserSession !== 'function') {
    window.location.reload();
  }

```

If the user goes to a private route but **user.getSignInUserSession** is not a function, reload the page. This works but it refreshes the page and we don't believe there should be the need to do that.

**Comment by ErikCH** [comment]
Hi @marcos-boger !

So the `user?.getSignInUserSession()?` is not a function when you first login for MFA? I'll try to reproduce this.

**Comment by ErikCH** [comment]
I was able to reproduce this, I'll get a fix in our next release.
