### ISSUE TITLE
Some texts in Authenticator are not translated to Japanese

### ISSUE THREAD

**Issue by tmokmss** [aws-amplify/amplify-ui#2299]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Microsoft Edge

### Please describe your bug.

Some texts in Authenticator are not translated yet. In the below image, `We emailed you` and `Your code is...` are missing translation.

![image](https://user-images.githubusercontent.com/7490655/179165817-3e8d724d-52c5-4e28-b03b-f653bdc4e17a.png)

### What's the expected behaviour?

All texts are translated.

### Help us reproduce the bug!

Just use translator with i18n enabled:
https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#internationalization-i18n

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
Hi @tmokmss thanks for filing this issue! I confirmed we are missing those translations from our [i18n file](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/ja.ts) Looks like we are missing these values (compared to others [like de.ts](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/de.ts#L61-L66)):

```
'We Emailed You': '',
'Your code is on the way. To log in, enter the code we emailed to': '',
'Your code is on the way. To log in, enter the code we texted to': '',
'It may take a minute to arrive.':''
```

Would you like to contribute translations (or a PR!) to add those? https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#contribution-process

**Comment by tmokmss** [comment]
@hbuchel Yes I can. I'll submit a PR for Japanese soon. Is there any reviewer for ja translation on your team?

**Comment by wlee221** [comment]
> I also think we need more thorough approach since some languages other than Japanese (e.g. [Korean](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/kr.ts)) do not still have the corresponding translation either.

Agreed! We can use TypeScript types to enforce all known string keys. It will be tougher to maintain though, because we're relying on contributors for the translations. Maybe we can use machine translated strings, which will be horrible, but can be improved by fluent contributors 🤔
