### ISSUE TITLE
Confirm New Password or View Password

### ISSUE THREAD

**Issue by marykatenawalaniec** [aws-amplify/amplify-ui#230]
**Is your feature request related to a problem? Please describe.**
After entering the temporary password, a user is prompted to enter a new, permanent password. However, there is no way for the user to view what they're typing or confirm the password by typing it twice. 

**Describe the solution you'd like**
Follow typical new password workflow:
- allow user the ability to toggle viewing actual text
- require user to type in password twice

**Describe alternatives you've considered**
- Instruct the user to reset the password if they can't login

**Additional context**
<img width="565" alt="Screen Shot 2020-01-16 at 2 49 47 PM" src="https://user-images.githubusercontent.com/52323101/72561777-801b0080-386f-11ea-9bdd-b647856f0ca6.png">

<img width="564" alt="Screen Shot 2020-01-16 at 2 49 52 PM" src="https://user-images.githubusercontent.com/52323101/72561776-801b0080-386f-11ea-9a67-ea2942efabe8.png">

**Comment by eddiekeller** [comment]
Hi @marykatenawalaniec , thanks for submitting this. Sorry there hasn't been any real communication on your request.

Both of your asks (being able to view an entered password and having a `confirm_password` box) have been included in our new version of the authenticator! Here are the docs for the new version - https://ui.docs.amplify.aws/ui . It is currently in a "developer preview", but the functionality you have mentioned is already done. If you want to try it out, just follow the instructions in those docs to get started, and let us know if they work well for you, or if any other changes need to be made.

**Comment by shkomg** [comment]
how I may disable/hide confirm_password? Want as simple registration as possible: Name, email, password. Thank you.

**Comment by ershovio** [comment]
@eddiekeller is it possible to hide and disable password confirmation?

**Comment by crorodriguezro** [comment]
Hi, I have the same question, is it possible to hide password confirmation?

**Comment by thaddmt** [comment]
@crorodriguezro At this time it is not possible to hide password confirmation but if that's a feature you're interested in please open up a feature request!
