### ISSUE TITLE
Bug: Hover styling for Password Reset "Send Code" with Vue3 Authenticator component

### ISSUE THREAD

**Issue by armenr** [aws-amplify/amplify-ui#2309]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Please describe your bug.

Authenticator component CSS appears to bug out on Reset Password.

Specifically the "Send Code" button w/ onHover behavior.

See below:

![SendCodeBug](https://user-images.githubusercontent.com/7662191/179922922-b1f7d17f-139d-4578-a910-932c1a2d1b40.gif)

### What's the expected behaviour?

The button shows its background & text is *visible*, when not being hovered over (as its intended).

### Help us reproduce the bug!

1. Clone this: https://github.com/antfu/vitesse
2. `pnpm i`
3. `pnpm i @aws-amplify/ui-vue aws-amplify`
4. Create new file --> `src/components/Auth.vue`
5. Follow this: https://ui.docs.amplify.aws/vue/connected-components/authenticator
6. `pnpm dev`
7. See bug

### Code Snippet

```typescript
<script setup>
import { Amplify } from 'aws-amplify'
import '@aws-amplify/ui-vue/styles.css'
import { Authenticator } from '@aws-amplify/ui-vue'
import awsconfig from '~/aws-exports'

Amplify.configure(awsconfig)
</script>

<template>
  <authenticator>
    <template #default="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">
        Sign Out
      </button>
    </template>
  </authenticator>
</template>

```

**Comment by knavels** [comment]
Yes same issue here

**Comment by joebuono** [comment]
Hi @armenr. You can fix this issue by commenting out this line in `src/main.ts`:

```
// import '@unocss/reset/tailwind.css'
import './styles/main.css'
import 'uno.css'
```

Uno is resetting Tailwind, which then somehow overrides the Amplify UI styles. 

Let us know if this works, thanks!

**Comment by armenr** [comment]
@joebuono - Thanks for providing the fix for the component. 

Unfortunately, this breaks all the other styling throughout the boilerplate/app. :-\ 

I know that's not technically your problem, but I guess the next question is whether there's some way we can override or work around that for this specific component/element/button?

**Comment by joebuono** [comment]
@armenr Looking into it now. This is the specific style that's causing the issue:

![Screen Shot 2022-07-20 at 2 53 14 PM](https://user-images.githubusercontent.com/48109584/180069726-c73c5928-45df-409d-9967-5c1c01ff7ab9.png)

I'll see if there's a way we can override it specifically

**Comment by joebuono** [comment]
@armenr Can you try adding this class to `src/styles/main.css`?

```
.amplify-button--primary {
  background-color: var(--amplify-components-button-primary-background-color);
}
```

**Comment by armenr** [comment]
@joebuono - JOE! Thank you!! Considering the fact we're using Uno, and doing something really specific, didn't have to help us figure it out, but you went the extra mile.  

I sincerely appreciate the Customer Obsession. I'm happy to close this now, as it is solved.  PS - tell my friend @ErikCH I said what's up  :-P
