### ISSUE TITLE
Version Compatability between Amplify Libraries

### ISSUE THREAD

**Issue by Rajan-Gupta1** [aws-amplify/amplify-ui#2317]
### On which framework/platform would you like to see this feature implemented?

Angular

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

To use the  "@aws-amplify/ui-angular": "^1.0.35" which is the last version of 1.x, how does one know which aws-amplify library to use along with the 1.0.35 of u-angular?

### Please describe a solution you'd like.

Document version compatibility map or use a version naming convention which is consistent across various amplify modules

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by wlee221** [comment]
To answer the question first,

- `@aws-amplify/ui-angular@1.x.x` support Angular 10 and up.
- `@aws-amplify/ui-angular@2.x.x` supports Angular 11 and up (and will support all [active versions](https://angular.io/guide/releases#support-policy-and-schedule)).

We however highly advise you to use version 2, as version 1 is no longer maintained and has some theming / accessibility limitations.

**Comment by Rajan-Gupta1** [comment]
Thanks Will. @wlee221 
What are version mapping of ui-angular@1.xx to amplify-angular and amplify-js? 
What are version mapping of ui-angular@2.xx to amplify-angular and amplify-js?

**Comment by wlee221** [comment]
Ahh sorry, I misunderstood you.

Both versions of `@aws-amplify/ui-angular` support `aws-amplify@3.x.x` and `aws-amplify@4.x.x`. They're both listed as peer dependencies -- for example 

https://github.com/aws-amplify/amplify-ui/blob/1ad2a4cc445e66c7f7b39b648e2b02e6a97bbcd1/packages/angular/projects/ui-angular/package.json#L18

**Comment by wlee221** [comment]
Note `aws-amplify-angular` package is very outdated and should not be used. `@aws-amplify/ui-angular` is its successor.

**Comment by Rajan-Gupta1** [comment]
@wlee221 I am still on angular 9 (I need to upgrade for sure), what version and coding pattern I can use with angular 9?

**Comment by wlee221** [comment]
With Angular 9, you could use `aws-amplify-angular`, but as mentioned it's very outdated. I'd highly suggest you upgrade to 12 or later, as 12 is the [official LTS](https://angular.io/guide/releases#support-policy-and-schedule) right now. We do not plan to support non-lts Angular versions.
