### ISSUE TITLE
PreSign Up trigger with autoConfirm user does not seem to work with Authenticator component

### ISSUE THREAD

**Issue by vchaddha** [aws-amplify/amplify-ui#234]
With the authenticator component, if I use the pre SignUp trigger to autoconfirm user, I am still able to see the confirmation code prompt, though I do not receive any verification email.
When I enter a garbage value it gives me an error message as follows:

```
User cannot be confirmed. Current status is CONFIRMED
```
I tried searching in git issues, though not able to find anything there on this behavior.
Closest was this:
https://github.com/aws-amplify/amplify-js/issues/2588

below is a simple lambda trigger I am testing with:
```
import json

def lambda_handler(event, context):
    event['response']['autoConfirmUser'] = True
    return event
```
I am able to see that the user comes out as CONFIRMED, though not able to understand how to remove the confirmation prompt.

Sample screenshot of the behavior here:
https://ibb.co/F06GQTJ

**Comment by ericclemmons** [comment]
At the very least, the verification step should be skipped when:
> User cannot be confirmed. Current status is CONFIRMED

**Comment by ErikCH** [comment]
Hi @vchaddha and @AdamGustavsson 

I am working on a solution for this with the new Authenticator. I'll be giving more updates shortly. 

You can find more about the new authenticator [here](https://ui.docs.amplify.aws/ui/getting-started/installation)

**Comment by ErikCH** [comment]
The updates in the new authenticator are now merged and in place. If you're using a PreSign up lambda trigger to auto confirm users, the authenticator will detect this and now skip the confirm verify page.

Please note that if the user is confirmed, but their email is NOT confirmed, the next time they sign in they will be asked if they'd like to confirm their email. They can opt to skip that if they like.

If you'd like a user to never confirm their email, then you'll need to setup the lambda trigger to confirm the email as well as the user. Like [this](https://github.com/aws-amplify/amplify-ui/blob/main/environments/auth-with-email-lambda-signup-trigger/README.md).

```
 exports.handler = async (event, context, callback) => {
    // Confirm the user
    event.response.autoConfirmUser = true;
    // Set the email as verified if it is in the request
    if (event.request.userAttributes.hasOwnProperty('email')) {
      event.response.autoVerifyEmail = true;
    }
    // Set the phone number as verified if it is in the request
    if (event.request.userAttributes.hasOwnProperty('phone_number')) {
      event.response.autoVerifyPhone = true;
    }
    callback(null, event);
  };

```

I'll close this issue, but feel free to create another one if this doesn't work for you. 

Here is the documentation to get started if you'd like to try this out

https://ui.docs.amplify.aws/ui/getting-started/installation
