### ISSUE TITLE
UI Components should support federated login on sign-up slots

### ISSUE THREAD

**Issue by thinknirmal** [aws-amplify/amplify-ui#236]
**Is your feature request related to a problem? Please describe.**
An accepted way of login is to present social login options even on sign-up forms (not just in sign-in), to encourage users to use the social logins.

**Describe the solution you'd like**
Allow `federated` property on sign-up slots.

**Comment by wlee221** [comment]
Hello, we are working on new Authenticator component at `@next` that shows federated buttons on sign-up by default. 

Please give it a try here:
- https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react
- https://ui.docs.amplify.aws/ui/components/authenticator?platform=react
