### ISSUE TITLE
Buttons with icons + text integrated

### ISSUE THREAD

**Issue by vogues** [aws-amplify/amplify-ui#2377]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

most mobile apps have buttons with icons/symbols to show it takes the user to a new page. 

### Please describe a solution you'd like.

in addition to text buttons, having the ability for a button to contain an icon L/R/C justification with text.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @vogues,
This is currently already possible by passing an icon component alongside your button text as children. See [button docs](https://ui.docs.amplify.aws/react/components/button#icon-buttons). Example below:

```jsx
        <Button>
          <IconSave /> Save
        </Button>
```
Note: IconSave can be your own Icon component or any React compatible icon library

Is this the functionality you were looking for?

**Comment by Milan-Shah** [comment]
@vogues Please let us know if the solution @reesscot has provided worked for you or not. Feel free to reopen the issue if you are still having trouble.
