### ISSUE TITLE
(React) UI Components don't support password managers

### ISSUE THREAD

**Issue by Purii** [aws-amplify/amplify-ui#239]
**Describe the bug**
Browsers don't recognize the input elements as Auth related.

-> No "password suggestion" on during account creation
-> No autofill during sign in
-> No prompt "save password?" during sign in

I'm not sure what details are necessary for this to work, but I tried setting the `name` attribute and others through `formFields`. But that didn't help solve this issue. (https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands)

-> Form is not part of a "form" element
-> The "sign in/up" buttons aren't labelled as type "submit"

**Comment by strugman** [comment]
This is great news! Is there any roadmap so we could see the timeline and plan accordingly?

**Comment by ericclemmons** [comment]
@strugman We're aiming to have the preview available within a few weeks, so late September 🙏

**Comment by eddiekeller** [comment]
Hi @strugman , we have added support for password managers to our new Authenticator, which is currently under the `@next` tag.

Link to our documentation - https://ui.docs.amplify.aws/ui/components/authenticator?platform=react

And a link to a small test checking for support - https://github.com/aws-amplify/amplify-ui/blob/main/packages/e2e/features/ui/components/authenticator/sign-up-with-username.feature#L30-L33

If you'd like, give it a try and see if the new version works better for you!

**Comment by markcarroll** [comment]
Glad this is close to resolution.  @eddiekeller is there a tracking issue for the move from `@next` to full release that we can follow?

**Comment by ericclemmons** [comment]
@markcarroll Yes we do! https://github.com/aws-amplify/amplify-ui/milestone/1

**Comment by tswacast** [comment]
Apologies for adding a comment to a closed thread, but am I correct in my understanding that the current @next version of @aws-amplify/ui-react should work with 3rd party password managers? I have a minimal react project where I implemented a basic workflow wrapping the App component in <AmplifyProvider> and then exporting default App using the withAuthenticator HOC. LastPass will autocomplete the username and password, but when I submit the form (sign in, sign up, or change password), LastPass does not detect and prompt me to save the username/password. The Firefox password manager is working properly, but LastPass doesn't ever prompt to save. I can include my code if helpful, or open a new thread, but for now I just want to make sure that with the current @next version that it _should_ be working.

**Comment by aaronfay** [comment]
For anyone coming into this thread struggling with Selenium, Cypress, or Ghost Inspector (et al) and trying to automate a sign in using these components, I've found the following workaround. The above `<amplify-auth-container>` suggestion adds a hidden form to the page which can be used to interact with the actual form:

#### Assign your username
Use this selector:
```
[name="username"]
```
#### Execute JavaScript to trigger the proper form change 
```js
document.querySelector('[name="username"]').dispatchEvent(new Event('input'))
```
#### Assign password
Use this selector:
```
[name="password"]
```
#### Execute JavaScript again to update the proper form 
```js
document.querySelector('[name="password"]').dispatchEvent(new Event('input'))
```
#### Click the submit button
This proved to be a little more complex, one more JavaScript is necessary:
```js
document.querySelector('amplify-authenticator')
  .shadowRoot.querySelector('amplify-sign-in')
  .shadowRoot.querySelector('amplify-form-section')
  .querySelector('.button').click()
```

Hope that helps anyone else struggling with test automation.
