### ISSUE TITLE
How to customize PreSignup error response text in amplify-authenticator

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-ui#240]
**Category** 

Auth

**Amplify CLI Version** 

```amplify --version
4.20.0
```

This is a Vuejs app.

My PreSignup handler ends with the following:

```
  if (!allowed) {
    callback("My error message", null);
  } else {
    callback(null, event);
  }
```

When I run: ```mock function myPreSignup```

Output is:

```
myPreSignup failed with the following error:
{ '0': 'M',
  '1': 'y',
  '2': ' ',
  '3': 'e',
  '4': 'r',
  '5': 'r',
  '6': 'o',
  '7': 'r',
  '8': ' ',
  '9': 'm',
  '10': 'e',
  '11': 's',
  '12': 's',
  '13': 'a',
  '14': 'g',
  '15': 'e' }
```

However in the browser the following is displayed in the amplify-toast:
> myPreSignup failed with the following error: My error message

How do I remove or change (or preferably translate using i18) the text: "myPreSignup failed with the following error:" ?

I have also tried something like this in my handler:
```
  if (!allowed) {
    callback({error: 'My error message'}, null);
  } else {
    callback(null, event);
  }
```

When I try mocking I get this output:
```
myPreSignup failed with the following error:
{ error: 'My error message' }
```

Then the coresponding message in the browser amplify-toast is something like:
> myPreSignup failed with the following error: [object, object]

Which is not very usefull

What is the correct way of dealing with this ?
Is it perhaps possible to overide the signUp() function ?
And shouldn't the mocking output error text look more like the toast output ? (Now it's confusing)

**Comment by ericclemmons** [comment]
@shomari asks in Discord (https://discord.com/channels/705853757799399426/708383821401161738/927239008185106452):

> is there anyway to customize the UI error message?  I mostly want to remove the first part about "PreSignUp failed with error" and only show my custom error message returned from lambda.
Not a huge deal but could be a little confusing for users wondering what PreSignUp is
> ![](https://cdn.discordapp.com/attachments/708383821401161738/927239007581143100/Screen_Shot_2022-01-02_at_10.35.15_AM.png)

The original bug for this issue may not be relevant, but customizing lambda messages are :)

**Comment by ErikCH** [comment]
You can now update all error messages with i18n translations.
https://ui.docs.amplify.aws/components/authenticator#labels--text

Please reopen this issue if you still have problems.
