### ISSUE TITLE
Allow Buttons to be a link with href prop

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#2400]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

It'd be great if Button could extend Link props to allow having a link that is styled like a button, in cases where you may want to use an actual `<a>` element as a call to action and get all of the UX of a link (right click open in new window, hover to see url, etc).

```
<Button href="https://ui.docs.amplify.aws/">I'm actually a link</Button>
```

### Please describe a solution you'd like.

In the [Button component](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/primitives/Button/Button.tsx#L48) we could detect if you passed an href and use an `<a>` as the base element instead of `<button>`
```
<View
  ...
  as={href ? a : button}
/>
```

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by zchenwei** [comment]
This should be fixed in 5.x release.
