### ISSUE TITLE
Design token missing for the SearchField Button background color

### ISSUE THREAD

**Issue by Orneeman** [aws-amplify/amplify-ui#2412]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

React 

### Please describe your bug.

Can’t change the button background color 

### What's the expected behaviour?

I want to change the button background color to white but it doesn’t work 

### Help us reproduce the bug!

Generate a new SearchField with a button 

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
The issue here is that we offer a design token for the background color in the hover, active, etc states, but we don't offer the base state, which is the default button. We need to offer a base background color for the SearchField component.
