### ISSUE TITLE
Error 'attachShadow' adding chatbot legacy component on ionic angular

### ISSUE THREAD

**Issue by developer-grupo-onetec** [aws-amplify/amplify-ui#2448]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular, Other

### Which UI component?

Chatbot

### How is your app built?

Ionic serve

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

When I try to launch on my localhost the ionic app, there is several errors with this message:

```
**./node_modules/@aws-amplify/ui-components/dist/components/index.js:**471:4-16 - **Error: export 'attachShadow' (imported as 'attachShadow') was not found in '@stencil/core/internal/client'** (possible exports: BUILD, Build, CSS, Cont
ext, Env, Fragment, H, HTMLElement, Host, NAMESPACE, STENCIL_DEV_MODE, addHostEventListeners, bootstrapLazy, cmpModules, connectedCallback, consoleDevError, consoleDevInfo, consoleDevWarn, consoleError, createEvent, defineCustomElem
ent, disconnectedCallback, doc, forceModeUpdate, forceUpdate, getAssetPath, getConnect, getContext, getElement, getHostRef, getMode, getRenderingRef, getValue, h, insertVdomAnnotations, isMemberInElement, loadModule, modeResolutionC
hain, nextTick, parsePropertyValue, plt, postUpdateComponent, promiseResolve, proxyComponent, proxyCustomElement, readTask, registerHost, registerInstance, renderVdom, setAssetPath, setErrorHandler, setMode, setPlatformHelpers, setP
latformOptions, setValue, styles, supportsConstructableStylesheets, supportsListenerOptions, supportsShadow, win, writeTask)
```

### What's the expected behaviour?

Launch app without errors

### Help us reproduce the bug!

1. Create new app with ionic. 
2. [Add amplify UI library to the project.](https://ui.docs.amplify.aws/angular/getting-started/installation)
3. Follow the [instructions on the official site](https://ui.docs.amplify.aws/angular/legacy-components/chatbot) from amplify to add chatbot component.

### Code Snippet

My package versions:

```
 "dependencies": {
    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@aws-amplify/ui-angular": "^2.4.17",
    "@capacitor/app": "4.0.1",
    "@capacitor/core": "4.0.1",
    "@capacitor/haptics": "4.0.1",
    "@capacitor/keyboard": "4.0.1",
    "@capacitor/status-bar": "4.0.1",
    "@ionic/angular": "^6.1.9",
    "@stencil/core": "^2.9.0",
    "aws-amplify": "^4.3.30",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
```

My app.module:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { LegacyAmplifyUiModule } from '@aws-amplify/ui-angular/legacy';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule, LegacyAmplifyUiModule],
  providers: [{ provide: RouteReuseStrategy, useClass: IonicRouteStrategy }],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

**Comment by developer-grupo-onetec** [comment]
Fixed adding dependency:
`npm install @stencil/core@2.9.0`

**Comment by developer-grupo-onetec** [comment]
Solved adding dependency:

`npm install @stencil/core@2.9.0`

**Comment by reesscot** [comment]
The legacy Chatbot component has been deprecated and is no longer supported.
