### ISSUE TITLE
Update Setup TOTP QR Issuer and Username not working on SignIn

### ISSUE THREAD

**Issue by senkevich33n** [aws-amplify/amplify-ui#2475]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Webpack 

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Used this tutorial 
https://ui.docs.amplify.aws/angular/connected-components/authenticator/customization#update-setup-totp-qr-issuer-and-username

0. copy pasted html and .ts
1. create user (in my case user was created on backend)
2. Sign In ( used temporary password -> added new password -> sign in)
3. Setup TOTP will appear
4. use google Authenticator to read QR code, title will be AwsCognito (username), should be **test issuer**

### What's the expected behaviour?

Issuer should be 'test issuer' not AwsCognito

### Help us reproduce the bug!

https://ui.docs.amplify.aws/angular/connected-components/authenticator/customization#update-setup-totp-qr-issuer-and-username

0. copy pasted html and .ts
1. create user
2. do Sign In
3. Setup TOTP will appear
4. use google Authenticator to read QR code, title will be AwsCognito (username), should be **test issuer**

### Code Snippet

```typescript
<amplify-authenticator [formFields]="formFields">
    <ng-template
      amplifySlot="authenticated"
      let-user="user"
      let-signOut="signOut"
    >
      <h2>Welcome, {{ user.username }}!</h2>
      <button (click)="signOut()">Sign Out</button>
    </ng-template>
  </amplify-authenticator>

 constructor() {
        Amplify.configure(environment.awsConfig);
      }
      public formFields = {
        setupTOTP: {
          QR: {
            totpIssuer: 'test issuer',
            totpUsername: 'amplify_qr_test_user',
          },
        },
      };

```

### Additional information and screenshots

    "@aws-amplify/auth": "^4.6.2",
    "@aws-amplify/interactions": "^4.0.49",
    "@aws-amplify/storage": "^4.5.2",
    "@aws-amplify/ui-angular": "^2.4.18",

![Screenshot 2022-08-18 115727](https://user-images.githubusercontent.com/83218378/185379139-2e643940-cb64-48c4-886d-9c5bd678a3c5.png)

webpack:///node_modules/@aws-amplify/ui-angular/fesm2015/aws-amplify-ui-angular.js
**looks like sortedFormFields and formOverrides missing in constructor**

**formOverrides is undefined**
any ideas?

**Comment by ErikCH** [comment]
Hi @senkevich33n !

Sorry for the delay. Yes, I was able to reproduce this. We will get it fixed soon!

**Comment by senkevich33n** [comment]
Hi Erik,
Did npm install to get "@aws-amplify/ui-angular": "^2.4.20"
used code from docs
all works as expected
thanks for your help!
