### ISSUE TITLE
Some translations are missing from all dictionaries

### ISSUE THREAD

**Issue by dJani97** [aws-amplify/amplify-ui#2479]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Any

### Which UI component?

Authenticator

### Please describe your bug.

I found some strings in the following file that are missing from most dictionaries, including english:

[`aws-amplify/amplify-ui/packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.ts`](https://github.dev/aws-amplify/amplify-ui/blob/ffba713cf34112f588a877bff73e1b7622b9e26e/packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.ts#L27)

These string are:

```
"We Sent A Code"
"We Emailed You"
"We Texted You"
"Your code is on the way. To log in, enter the code we emailed to"
"Your code is on the way. To log in, enter the code we texted to"
"Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive."
```

I had to find them in the source, because some of them like `"We Sent A Code"` are present in none of the dictionaries:
![image](https://user-images.githubusercontent.com/22769564/185372109-13ba9ae9-148a-4255-8018-e873b70fde81.png)

### What's the expected behaviour?

I expected a to find all dictionary keys in [en.ts](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/en.ts) file. But it's not the first time that I had to look through multiple dictionary files or the source code to find keys that are not present there.

I think there should be a convention to list of all possible keys in some file, so even if a new string doesn't get included in any specific dictionary, at least people can find it without digging into the source.

**Comment by slaymance** [comment]
Thank you for your bug report @dJani97. We'll prioritize this issue on our roadmap and consider your suggestion as part of our acceptance criteria for dictionary improvements.
