### ISSUE TITLE
[Feedback] S3 Image Picker On Completed Upload Trigger?

### ISSUE THREAD

**Issue by ucjallen** [aws-amplify/amplify-ui#249]
**Page**: [`/ui/storage/s3-image-picker/q/framework/angular`](https://docs.amplify.aws/ui/storage/s3-image-picker/q/framework/angular)

**Feedback**:

I have gotten the S3 Image Picker to work and when I click the button, it uploads to my S3 bucket, but then it just sits there. How do I know when the upload has completed and can direct back to another page? I noticed the S3 album has a handleOnLoad, is there something similar for the image picker?

**Comment by beedrill** [comment]
Seriously, amplify-s3-image-picker has ZERO documentation on its API options and how to use it.

**Comment by ucjallen** [comment]
Here is what my solution ended up looking like for a profile page image component in angular. It is mobile friendly as well

https://github.com/ucjallen/s3-image-picker/tree/master

**Comment by reesscot** [comment]
Closing out as the `S3Image` component has been deprecated.
