### ISSUE TITLE
useAuthenticator do not cause a re-render on user.attributes field change with enabled StrictMode

### ISSUE THREAD

**Issue by MadaShindeInai** [aws-amplify/amplify-ui#2495]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

In my React 18 project i use Amplify `"@aws-amplify/ui-react": "^2.17.1"`, `"aws-amplify": "^4.3.22"`, and i faced with unexpected behaviour on my localhost. (everything was as expected in deployed version).

I doing `import { useAuthenticator } from '@aws-amplify/ui-react';` into my component to get user data (issue exists with both approaches):

    const { user } = useAuthenticator();
    const { user } = useAuthenticator((context) => [context.user]);
    
I also do `import { Auth } from 'aws-amplify';` and make a function to update user attribute - `given_name`.

    const setAttr = async () => {
        const user = await Auth.currentAuthenticatedUser();
        await Auth.updateUserAttributes(user, { given_name: 'Eddie' });
        const res = await Auth.currentAuthenticatedUser();
        console.log(JSON.stringify(res.attributes));
      };
After running this function i see correct value in `console.log(JSON.stringify(res.attributes));` inside function.
But `const { user } = useAuthenticator();` still see values from initial render (old name). I checked it by declaring `setInterval(() => console.log(user.attributes), 1000);` and comparing values.   
So, value in context do not change => component do not re-render => i see old `given_name` until i reload page.

### What's the expected behaviour?

 After changing `given_name` field, `useAuthenticator` track this change and cause a rerender not only on deployed version, but also on localhost with enabled React.StrictMode.

### Help us reproduce the bug!

It probably should appear in any CRA + amplify setup with enabled React.StrictMode.

### Code Snippet

```typescript
// Put your code below this line.

```

#### The essence of the problem:  
Removing `<StrictMode>` from `index.tsx` in the root of a project solved the problem on localhost. However, [StrictMode](https://reactjs.org/docs/strict-mode.html) is important and helps avoid problems. So it will be cool, if Amplify UI will be compatible with it.
Original issue from stackoverflow:
https://stackoverflow.com/questions/73416383/aws-amplify-useauthenticator-hook-do-not-cause-a-re-render-on-user-attributes-f/73445435#73445435

**Comment by ErikCH** [comment]
Hi @MadaShindeInai !

Yes this is a known issue. We are in the process of adding more hub events, and this should be fixed in a future release!

**Comment by reesscot** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-ui/issues/1333. @MadaShindeInai Please track this issue there instead.
