### ISSUE TITLE
[ui-react] Manually to show hosted UI component

### ISSUE THREAD

**Issue by dfang** [aws-amplify/amplify-ui#250]
**Is your feature request related to a problem? Please describe.**

**WITHOUT customizing ui**,  

for hosted ui for @aws-amplify/ui-react,  How to put a sign in btn/link and sign up link/btn on the navbar, when user click sign up, show sign up component, when user click sign in link, show sign in component.

ui-react hosted ui should provide an easy way to cover this kind of use case .

**Describe the solution you'd like**
programmatic way to trigger to show vary components/pages based on auth state.

**Describe alternatives you've considered**

tried 

```
export default function CustomSignUp() {
  return (
      <AmplifyAuthenticator>
         <AmplifySignUp></AmplifySignUp>
      <AmplifyAuthenticator>
  )
}
```

in react-router and navlink to show this component, but it does not works.

**Additional context**
looked up sources code and samples, it seems you can only show it or hide it..

**Comment by ErikCH** [comment]
Hi @dfang !

With our new authenticator we have the ability to open the authenticator to the sign up or sign in page, by passing in the `initialState` prop. Here is example of how it works.

```
export default withAuthenticator(App, {
  initialState: 'signUp',
});
```
And here is more [documentation](https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#initialstate) on it.


Please try the new authenticator out and let us know if it solves your problem. It's under the `@next` tag.

https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react

I'll close this issue out for now, but feel free to reopen it, or create a new issue if needed.
