### ISSUE TITLE
AmplifyAuthenticator - Verify Contact Information Screen displays "your.adress@example.com"

### ISSUE THREAD

**Issue by liamaws** [aws-amplify/amplify-ui#252]
**Describe the bug**
After federated sign in, the verify contact information screen displays "your.adress@example.com" as the email address for verification

**To Reproduce**

1. Go to https://master.dw8p5s05jola3.amplifyapp.com/
2. Sign in using an external IdP (Google for example)
3. You will see an "Account recovery requires verified contact information" screen (screenshot below)

**Expected behavior**
This screen did not previously show up after federated sign in, so I am not sure the exact expected behavior. I found this issue https://github.com/aws-amplify/amplify-js/issues/6481 and this PR https://github.com/aws-amplify/amplify-js/pull/6508, so looks like this is verification screen is intended. However I think either "Email" or the users actual email address should show up as the option to select.

**Code Snippet**
Full code is [here](https://github.com/awslabs/aws-amplify-identity-broker) for those who have access
```
  <AmplifyAuthenticator usernameAlias="email" style={{ textAlign: 'center' }}>
            <AmplifyForgotPassword
              usernameAlias="email"
              slot="forgot-password"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
              ]}></AmplifyForgotPassword>
            <AmplifySignIn
              usernameAlias="email"
              slot="sign-in"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
                {
                  type: "password",
                  required: true,
                }
              ]}></AmplifySignIn>
            <AmplifySignUp
              usernameAlias="email"
              slot="sign-up"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
                {
                  type: "password",
                  required: true,
                },
                {
                  type: "phone_number",
                  required: false,
                },
                {
                  type: "locale",
                  value: this.state.lang,
                  inputProps: {
                    type: 'hidden',
                  }
                }
              ]}></AmplifySignUp>
            <div>
              {I18n.get("WAIT_REDIRECTION")}
              <AmplifySignOut />
            </div>
          </AmplifyAuthenticator>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/67014943/92030857-a5dd1300-ed35-11ea-979a-305ee2ed2d13.png)

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 59.58 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Firefox: 68.8.0
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/ui-react: ^0.2.15 => 0.2.15 
    @testing-library/jest-dom: ^5.11.4 => 5.11.4 
    @testing-library/react: ^10.4.9 => 10.4.9 
    @testing-library/user-event: ^12.1.3 => 12.1.3 
    aws-amplify: ^3.0.24 => 3.0.24 
    axios: ^0.20.0 => 0.20.0 
    jwt-decode: ^2.2.0 => 2.2.0 
    react: ^16.13.1 => 16.13.1 
    react-app-rewired: ^2.1.6 => 2.1.6 
    react-dom: ^16.13.1 => 16.13.1 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 3.4.3 => 3.4.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.28.1
    ask-cli: 2.13.0
    nodemon: 2.0.4
    npm: 6.14.8
    serve: 11.3.2
    serverless: 1.73.1

```

</details>

**Comment by eddiekeller** [comment]
Hey everyone, @liamaws , this shouldn't be a problem any longer in the new version of our authenticator (under the `@next` tag). Here are our docs if you want to take a look - https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react

Screenshot of what the `VerifyContact` screen should look like now - 
<img width="567" alt="Screen Shot 2021-10-14 at 11 30 33 AM" src="https://user-images.githubusercontent.com/17255334/137395153-df65b497-8b6c-40b3-b371-5415e53e2326.png">

If you'd like, you can give the new version a shot and see if it takes care of your issue for you.

**Comment by liamaws** [comment]
Ok great. I'm not actively working with Amplify anymore, but I'm wondering if this screen is still showing up after sign in with a federated identity?
