### ISSUE TITLE
@aws-amplify/ui-react cannot to be used as a webpack external

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-ui#253]
**Describe the bug**
`ui-react` is not setting the public path “on the fly,” which is necessary for CDN usage.
The creation of this issue is possible thanks to @joeldenning from [single-spa](https://single-spa.js.org) that analyzed a problem on my single-spa project.

**To Reproduce**
1. create a single-spa "root config" project
2. create a single-spa "application" project
3. add amplify libraries to root config project imports
4. add amplify libraries to the application project and use them as `externals` in webpack
5. try to use `AmplifyAuthenticator` in the application ui

**Expected behavior**
I expect `@aws-amplify/ui-react ` to load correctly using a CDN

**Description**
`aws-amplify/ui-react` is trying to load this file: https://unpkg.com/browse/@aws-amplify/ui-react@0.2.14/dist/5.js
webpack code splits and webpack dynamic import to do so, Webpack code splits are implemented with a thing called “webpack jsonp”. The URL to download the code splits is calculated by using the “wepack public path” as the prefix for the URL, however, **`ui-react` is not setting the public path “on the fly,” which is necessary for CDN usage.**

Ideally ui-react would set the public path to be the URL from which it was loaded via CDN (or it wouldn’t use webpack code splits at all) but it' not doing that

**Screenshots**
![image](https://user-images.githubusercontent.com/3852307/92243174-56c3e900-eec1-11ea-81a7-5382ba80a869.png)

**Additional context**
https://single-spa.js.org/
https://webpack.js.org/guides/public-path/#on-the-fly

**Comment by Milan-Shah** [comment]
@AlessandroAnnini We have released a new major version of @aws-amplify/ui-react@2.0.0 with support for custom styling, social sign in support, password manager support, custom sign up attributes, zero config and many others. We believe your issue has been fixed with the latest release. Please let us know if you are still seeing an issue on your end.
