### ISSUE TITLE
[missing-page] Components Authenticator

### ISSUE THREAD

**Issue by marcuslunn** [aws-amplify/amplify-ui#2531]
**Page**: [`https://ui.docs.amplify.aws/react/connected-components/components/authenticator`](https://ui.docs.amplify.aws/react/connected-components/components/authenticator)
**Feedback**: :Linked from https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#authenticator-provider in the 'Authenticator Provider' section.

**Comment by joebuono** [comment]
@marcuslunn Thanks for catching this broken link! We will push out a fix soon
