### ISSUE TITLE
Expose the Auth state to outside world

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-ui#254]
**Is your feature request related to a problem? Please describe.**

__WRITE:__

When using UI components (in React), I need to customize some aspect of the UI further than basic changes.
For example I use the `secondary-footer-content` web component slot of Sign-In component to create a custom Forgot password link.
But to override it with a link I build myself I need to have a way to change the authState without having access to `this` of the UI component:
```
<AmplifySignIn slot="sign-in">
                <span slot="secondary-footer-content">
                  <amplify-button
                    variant="anchor"
                    onClick={() => this.updateAuthState(AuthState.ForgotPassword)}
                  >
                    {"Forgot your password?"}
                  </amplify-button>
                </span>
</AmplifySignIn>
```
__note:__ `this` here is my app this not the `AmplifySignIn` `this`, therefore I cannot write the same code than in https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx and especially I cannot do `this.handleAuthStateChange(AuthState.ForgotPassword)`

__READ:__

Today to read the current AuthState I have to listen onAuthUIStateChange and persist the information of the authState myself (in my app state for example). It would have been easier to have access to the authstate directly.

**Describe the solution you'd like**

I like to have a simple way to invoke a AuthState change from outside. I found a workaround (see alternative) but this is not ideal.
Ideally I like to have `dispatchAuthStateChangeEvent` exported and usable from outside, as well as constants (in particular `UI_AUTH_CHANNEL` and `AUTH_STATE_CHANGE_EVENT`)

For the read, not sure what can be done? A static variable exposed? I tried using React Ref to access the information but it does not work.

**Describe alternatives you've considered**
I use the following workaround (which is inelegant and not safe):
```
import { Hub } from '@aws-amplify/core';

class App extends React.Component {

updateAuthState(nextAuthState){
    Hub.dispatch('UI Auth', {
      event: 'AuthStateChange',   <--- here is the trick I hardcoded the CHANNEL values
      message: nextAuthState
    });
  }

render() {
    return (
       <AmplifyAuthenticator usernameAlias="email" style={{ textAlign: 'center' }} initialAuthState={AuthState.SignIn}>
           <AmplifySignIn usernameAlias="email" slot="sign-in">
              <span slot="secondary-footer-content">
                  <amplify-button
                    variant="anchor"
                    onClick={() => this.updateAuthState(AuthState.ForgotPassword)}
                  >
                    {"Forgot your password?"}
                  </amplify-button>
                </span>
              </AmplifySignIn>

```

Hardcoding constants is risky and inelegant.

**Comment by wlee221** [comment]
Hello @xavierraffin, thank you for your detailed feature request! Looking over this now. This is something we want to support in our `@next` release as well!

For workaround while we polish up @next versions, you can update the current auth state directly through Hub events:

```
import { UI_AUTH_CHANNEL, AUTH_STATE_CHANGE_EVENT } from '@aws-amplify/ui-components';
import { Hub } from 'aws-amplify';

const onForgotPasswordClicked = () => {
  Hub.dispatch(UI_AUTH_CHANNEL, {
    event: AUTH_STATE_CHANGE_EVENT,
    message: AuthState.ForgotPassword,
  });
}
```

**Comment by wlee221** [comment]
You can try or track the progress of our next authenticator on 
1. https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react
2. https://ui.docs.amplify.aws/ui/components/authenticator?platform=react

Please let us know if you have any suggestions or feedbacks!

**Comment by wlee221** [comment]
Hi @xavierraffin, apologies to keep you waiting. With `@aws-amplify/ui-react@2.x.x`, you are now able to add custom forgot password link in the footer through https://ui.docs.amplify.aws/components/authenticator#headers--footers without `Hub` workarounds. I'll be closing this issue as that use case is now supported.

That said though, I understand that the premise of this issue is not resolved (particularly **read authState** part). We would like to understand this use case a little bit better before we commit to a globally available hook. Can you please try out the new authenticator, and open a new feature request with what could be improved for which use case? Thanks in advance!

**Comment by rory-ferguson** [comment]
This feature is much needed.

I'd like to customise the page the user is on depending on the state of the Authenticator.

It'd be really nice to expose state with the suggestion above, or the old `onAuthUIStateChange`

**Comment by wlee221** [comment]
Hi, came back to the issue! We just exposed `useAuthenticator` that you can use outside the authenticator to access or transition (ie. write) auth state. Please take a look and we gladly accept any feedbacks 🙏 

Documentation is here: https://ui.docs.amplify.aws/components/authenticator#useauthenticator-hook
