### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by younseoryu** [aws-amplify/amplify-ui#2542]
**Page**: [`https://ui.docs.amplify.aws/[platform]/components/authenticator/configuration`](https://ui.docs.amplify.aws/[platform]/components/authenticator/configuration)
**Feedback**:

**Comment by reesscot** [comment]
@younseoryu We cannot find a link to this bad URL anywhere. Do you know where you found it?

**Comment by younseoryu** [comment]
@reesscot unfortunately, I dont remember

**Comment by Milan-Shah** [comment]
@younseoryu Thanks for reporting the broken link behavior, we will correct it on our end. If you do come across it again, please let us know.
