### ISSUE TITLE
Get i18n error messages on @aws-amplify/ui-react

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-ui#255]
**Is your feature request related to a problem? Please describe.**

Error message are not translated when i18n lang changes when using UI from @aws-amplify/ui-react.
Plus there is no reliable list to know what possible message has to be translated.

There is an old list in _packages/aws-amplify-react/src/AmplifyI18n.tsx_ but it was for the legacy aws-amplify-react package.
The list is incomplete (Eric [said](https://github.com/aws-amplify/amplify-js/pull/4979)):
> The problem is that those languages have ~41 translated strings, while the new UI components have ~65, many new & others being different from what existed before.

Additionally errors from Cognito should have a way to be translated.
Example:
`1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6`

This type of message is complicated to translate.

**Describe the solution you'd like**

I like to have the full list of Translation string somewhere. (like amplify-ui-compomnents/src/common/Translation.tsx).

Having translation ready (like it was the case on _aws-amplify-react_ on _AmplifyI18n.tsx_) will be ideal.
And documenting the supported languages will be great.

Having error messages from Cognito reliably translated. Not directly displayed to user. Why not asking Cognito to return an error code and use that fro English and non English translation with string controlled on Amplify side

**Describe alternatives you've considered**

Painfully looking in the code and testing. Then adding translations.
So far I added:

```
export const strings = {
    fr: {
        "1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6": "Le mot de passe doit faire au moins 6 caractères.",
        "Username cannot be empty": "Le nom d'utilisateur doit être renseigné",
        "User does not exist." : "L'utilisateur n'existe pas.",
        "An account with the given email already exists.": "Un compte avec cette adresse couriel existe déjà.",
        "User is disabled.": "L'utilisateur est désectivé.",
        "Access Token has been revoked": "Le jeton d'accès a été révoqué"
    }
}
```

**Comment by eddiekeller** [comment]
This remains an issue, even in the new version of the authenticator. Cognito error messages do not get translated. Since user input is often included in the message, I'm guessing what we would have to hook in to is the error type. Off the top of my head, I'm not sure if Cognito reuses error types, though. If they do, then that would not be a reliable solution.

**Comment by ericclemmons** [comment]
This is also a short-coming of `I18n` being little more than a map.

Previous implementations relied on pattern-matching to translate errors:
> https://github.com/aws-amplify/amplify-js/blob/853adc7554f0a61922e3348d3626c73a5166266d/packages/aws-amplify-react/src/AmplifyMessageMap.tsx
