### ISSUE TITLE
Switch off Tab re-rendering

### ISSUE THREAD

**Issue by helmax-y** [aws-amplify/amplify-ui#2553]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I'm referencing [Tabs component](https://ui.docs.amplify.aws/react/components/tabs).
It would be nice to have an ability to stop re-rendering TabItems.

e.g. If consumer has some tab related requests, fetch will take place each time the tab is opened.

Alternatively consumer needs to raise logic to higher components, which is not always comfy

### Please describe a solution you'd like.

The prop, like `contentRerendering` can be provided

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by dbanksdesign** [comment]
To confirm, the behavior you are looking for is all TabItems are rendered once when the Tabs component renders, and switching between tabs does not remove anything from the DOM. How [Chakra UI tabs](https://chakra-ui.com/docs/components/tabs) works (changing an html attribute to show/hide content), and not how [MUI tabs](https://mui.com/material-ui/react-tabs/) work (removing/adding to the DOM).

I think that makes sense

**Comment by dbanksdesign** [comment]
This is now available! The new tabs component (in v6) renders all tab panels by default and hides them visually. There is an [`isLazy` prop](https://ui.docs.amplify.aws/react/components/tabs#lazy-loading-tabs) that turns on the old behavior of only rendering the contents when the tab is active!
