### ISSUE TITLE
Subtitle for AmplifyTotpSetup

### ISSUE THREAD

**Issue by udeeshaIS** [aws-amplify/amplify-ui#257]
**Is your feature request related to a problem? Please describe.**
I noticed there is a way to add subtitles to the SignIn and SignUp screens using header-subtitle slot. But which is missing in the AmplifyTotpSetup component. Is there a way to include subtitle with the current version, according to docs I can't find any.

**Describe the solution you'd like**

I would like the solution similar to the existing screens which looks like,

<AmplifyTotpSetup>
<div slot="header-subtitle">Header subtitle content</div>
</AmplifyTotpSetup>

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/3594652/99067744-2ea1e600-25e6-11eb-96fa-fbcac90c9d3b.png)

**Comment by ericclemmons** [comment]
To resolve this issue against `@next`, we should ensure all screens have a Header/Footer slot (outside the form) just like Sign In & Sign Up.

**Comment by calebpollman** [comment]
Hi @udeeshaIS You can achieve the addition of a subtitle on the `SetupTOTP` route by passing a using `Header` component. Documentation can be found [here](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#headers--footers)
