### ISSUE TITLE
Disable Signup UI and only allow SignIn for react native

### ISSUE THREAD

**Issue by AlexThomas90210** [aws-amplify/amplify-ui#2572]
### On which framework/platform would you like to see this feature implemented?

React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

The use case is similar to the Netflix app, if you submit to the app store and have an external process for taking payments during signup and do not want to use apple pay, you need to handle that off IOS, Netflix simply links signups to their website.

We would like to do the same, issue is that hideSignup seems to be only implemented in vue, react etc, not in react native

### Please describe a solution you'd like.

Allow ability to disable signup for react native UIs similar to other frameworks amplify supports

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment]
Hi @AlexThomas90210! We will be adding this as a feature in the new React Native `Authenticator`. Thank you for opening the request.
