### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by jschimpp** [aws-amplify/amplify-ui#2575]
**Page**: [[`https://ui.docs.amplify.aws/react/connected-components/authenticator/vue](https://ui.docs.amplify.aws/react/connected-components/authenticator/vue#signupattributes)

**Comment by joebuono** [comment]
@jschimpp Thanks for finding this invalid link. It should be:

 https://ui.docs.amplify.aws/vue/connected-components/authenticator/configuration#sign-up-attributes

Would you mind telling us where you found this link on our docs site?

**Comment by reesscot** [comment]
Located this bad link on the Authenticator Customization page 
<img width="1822" alt="image" src="https://user-images.githubusercontent.com/6165315/190025389-dfd1b019-7fda-490a-a20d-7080c634dcd7.png">

**Comment by jschimpp** [comment]
Thank you. I apologize but I lost the place where I found this link.
Hopefully I'll come across it again and I'll let you know.
