### ISSUE TITLE
FR (Authenticator): Support Federated Auth / Social sign on React Native

### ISSUE THREAD

**Issue by oscar-toohey** [aws-amplify/amplify-ui#2576]
**Which Specific Feature is your question related to?**
The wtihAuthenticator properties

**Provide additional details e.g. code snippets**
I want to. have social signins like google on the default ui page that gets presented using the withAuthenticator function.  There only seems to be support in react applications not react-native.  I'm not sure if I need to add so parameters to the function? I have set up the google sign in on the backend in the studio.

**Comment by Milan-Shah** [comment]
@oscar-toohey We currently have an implementation for React native Authenticator UI component work in progress, we are on track to launch a preview version for it by end of the year. We will keep you posted here :)

**Comment by michal-urbaniak** [comment]
@Milan-Shah any update on the topic?

**Comment by calebpollman** [comment]
Hi @michal-urbaniak! The new React Native Authenticator is available in dev preview (docs [here](https://ui.docs.amplify.aws/react-native/connected-components/authenticator)). While it does not support social sign in out of the box yet, this is a feature we are looking to add in the future

**Comment by ervibern** [comment]
Hi @calebpollman, it's nice to know you're working on Social Sign-in straight from Authenticator UI component. It's quite hard to setup all signins properly at the moment. Is there a rough timeline for this new feature?

**Comment by yang1fan2** [comment]
Hi @calebpollman , any updates? (friendly ping)

This feature is really important to us. Customized social sign-in implementation outside <Authenticator> will have bugs (e.g. context.authStatus not set up correctly). More details see this [issue](https://github.com/aws-amplify/amplify-ui/issues/1977).

**Comment by calebpollman** [comment]
As an update to this ticket, we are currently blocked on social sign in to the RN `Authenticator` on https://github.com/aws-amplify/amplify-js/issues/10507

**Comment by Reedeme** [comment]
Hey team! 👋 This would be an awesome feature to have around, I'm excited to see it being discussed! 
Can't wait to be able to configure Social Sign-in with the <Authenticator> component! 
Any further updates on the progress in this area? 👀 
cc @calebpollman @Milan-Shah

**Comment by alexkates** [comment]
I'm shocked this isn't supported yet.

**Comment by jasondavis87** [comment]
I've been able to successfully login using `Auth.federatedSignIn({provider: CognitoHostedUIIdentityProvider.Google})` and some custom buttons but the UI won't update after login. if i reload the app it goes to the right place without me having to login again so i know the keys are all saving correctly upon calling the function, but I'm not sure how to get the UI to reflect this. Any ideas?

**Comment by alexkates** [comment]
I'm having a similar issue, @jasondavis87.

**Comment by kabdelhalem** [comment]
@Milan-Shah Any updates?

**Comment by SilverLinings89** [comment]
Big blocker for us aswell

**Comment by calebpollman** [comment]
@Reedeme  @alexkates @jasondavis87  @kabdelhalem @SilverLinings89 Just wanted give a quik update here. While we do not have an exact date for release, we are actively working towards adding Federated Sign In support for the React Native `Authenticator` and will have some further updates to share soon!

**Comment by SilverLinings89** [comment]
Any news on this?

**Comment by Reedeme** [comment]
Heyo @calebpollman 👋  Any updates on this front?

**Comment by SilverLinings89** [comment]
> @Reedeme @alexkates @jasondavis87 @kabdelhalem @SilverLinings89 Just wanted give a quick update here. While we do not have an exact date for release, we are actively working towards adding Federated Sign In support for the React Native `Authenticator` and will have some further updates to share soon!

... is there an update by now?

**Comment by alexkates** [comment]
FYI for others that stumble across this.

I got tired of waiting, so I stopped using the authenticator HOC, and re-built the auth pages e.g., SignUp.tsx, SignIn.tsx, ForgotPassword.tsx, ResetPassword.tsx, ConfirmSIgnUp.tsx etc.

I used the Amplify JS library, but built my own screens.

It took a couple of hours and my designer was happy that he was able to do whatever layout he wanted.

I don't think this is coming :(

**Comment by calebpollman** [comment]
@Reedeme @alexkates @jasondavis87 @kabdelhalem @SilverLinings89 @neetable-abhilash  Support for Federated Provider sign in support for React Native `Authenticator` has been released starting in `@aws-amplify/ui-react-native@2.0.1` and later versions. 

To setup, you will need to configure your provider(s) (see guide [here](https://docs.amplify.aws/react-native/build-a-backend/auth/add-social-provider/)), and install the required dependencies in the Amplify UI React Native [Quick Start guide](https://ui.docs.amplify.aws/react-native/connected-components/authenticator#step-2-install-dependencies).

**Comment by jasondavis87** [comment]
@calebpollman Thanks so much!

**Comment by Reedeme** [comment]
@calebpollman Fantastic, thanks for letting us know!! 🪂

**Comment by ervibern** [comment]
That's nice @calebpollman! Just a follow-up question - will it ever be possible to get rid of this message?

<img width="369" alt="Screenshot 2023-11-24 at 21 13 03" src="https://github.com/aws-amplify/amplify-ui/assets/58375689/fc979328-85f7-41da-baa0-e662ee85b77c">

**Comment by calebpollman** [comment]
@ervibern Unfortunately the iOS native alert is not something we have control over from the Amplify UI side but suggest following up with the Amplify JS team (owning team of the `@aws-amplify/rtn-web-browser` package), you can open an issue [here](https://github.com/aws-amplify/amplify-js/issues)
