### ISSUE TITLE
Federated Buttons on Sign Up component(s)

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-ui#258]
**Is your feature request related to a problem? Please describe.**
The current sign up components don't support showing federated buttons (I think that's the right terminology?) like Google Login, etc.  I optimize the component state between sign up vs sign in depending on a localStorage value I manually set that determines whether that browser has ever allowed someone to login before.  However the sign up page doesn't show the federated buttons.

**Describe the solution you'd like**
Allow the same federated buttons on the **sign in** page on the **sign up** page.

**Describe alternatives you've considered**
Just show "Sign In" page first all the time.  But this would mean every **new** potential customer has to click "Sign Up"--an unnecessary step that'll reduce conversion.

**Comment by wlee221** [comment]
Hello, we are working on new Authenticator component `@next` that shows federated buttons on sign-up by default. 

Please give it a try here:
- https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react
- https://ui.docs.amplify.aws/ui/components/authenticator?platform=react

I'll be closing the issue as federated buttons are rendered by default, but please let us know if you need more customization beyond this.
