### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by jorenkennes** [aws-amplify/amplify-ui#2585]
**Page**: [`https://ui.docs.amplify.aws/angular/components`](https://ui.docs.amplify.aws/angular/components)
**Feedback**: 
Link on page  https://ui.docs.amplify.aws/angular/getting-started/migration in section 'Breaking changes' to 'components' returns 404

**Comment by reesscot** [comment]
@jorenkennes Thanks for reporting this broken link. We'll get a fix deployed to the UI Docs site shortly.
