### ISSUE TITLE
Footer section for legal text on UI Components

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-ui#259]
**Is your feature request related to a problem? Please describe.**
Right now there's no easy way to include a custom footer within the UI components that could be used to support legal text (privacy policy, terms, etc.)

**Describe the solution you'd like**
Add an additional slot to **sign up** and **sign in** that can be customized to include legal text.

**Describe alternatives you've considered**
Right now I've placed it below the authentication box, but it feels/looks disconnected.  The existing footer slots all **replace** necessary content/features because the components themselves use them.

**Comment by ericclemmons** [comment]
I'm thinking we can add a slot under the forms (outside the card), since this content should persist for all states.

> <img width="1306" alt="Screen Shot 2021-10-06 at 1 22 47 PM" src="https://user-images.githubusercontent.com/15182/136271990-db5822b2-de21-41fe-8e5b-26fd1354cad7.png">

**Comment by ericclemmons** [comment]
This is being published to the `@next` release via:
> https://github.com/aws-amplify/amplify-ui/pull/695

For example – https://github.com/aws-amplify/amplify-ui/blob/main/examples/next/pages/ui/components/authenticator/custom-slots/index.page.tsx
