### ISSUE TITLE
add select option in amplify authenticator sign up fields using angular ui

### ISSUE THREAD

**Issue by niloy369** [aws-amplify/amplify-ui#260]
Is there any way to add a select option dropdown in amplify-authenticator>amplify-sign-up component

**Comment by ericclemmons** [comment]
This is absolutely something that should be documented & supported. Cognito supports `gender` and several other attributes.

**Comment by ericclemmons** [comment]
This scenario is supported with the `@next` release!
> https://ui.docs.amplify.aws/components/authenticator#sign-up-fields

**Comment by balajigana** [comment]
HI, is there example code how to use select element with Authenticator component
