### ISSUE TITLE
How can I add a custom field in login?

### ISSUE THREAD

**Issue by juan-gomez-stellion** [aws-amplify/amplify-ui#2601]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I need to add a custom field in the login screen, currently I am using the login with email and password but I need to add a new custome field called "company" to do some things in my application.

this is my code 

```
function App({ signOut, user }) {
  user = { ...user, attributes: { ...user.attributes, project: "1" } };
  const navigate = useNavigate();
  useEffect(() => {
    navigate("/");
  }, []);

  return (
    <div>
      <AppRoutes signOut={signOut} user={user} />
    </div>
  );
}

export default withAuthenticator(App, {
  components: {
    Header,
  },
  hideSignUp: true,
  variation: "",
});
```

Is it possible?

thanks

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by wlee221** [comment]
Hi @juan-gomez-stellion, we will go ahead and close this given the response @ioanabrooks has provided. Please feel free to open this issue if you need more help, thanks!
