### ISSUE TITLE
TextField type='date' does not display correctly on mobile

### ISSUE THREAD

**Issue by MigeBill** [aws-amplify/amplify-ui#2602]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

create react app

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Please describe your bug.

TextField does not display correctly on android chrome when type is date
the field becomes visually split into 3 rows
start, text, end
![image](https://user-images.githubusercontent.com/105641225/190926705-405ee2d5-3dff-4560-8938-7ab70b0dffe8.png)

### What's the expected behaviour?

The field should display similarly to how it appears on a desktop ie on a single row
![image](https://user-images.githubusercontent.com/105641225/190926739-8de44a4f-6d58-4d09-8d91-cc2c51e04cbe.png)

### Help us reproduce the bug!

Bug can be seen in this minimal app
https://main.d3nu6n3lsn8380.amplifyapp.com/

source at https://github.com/MigeBill/date-issue

### Code Snippet

```javascript
// Put your code below this line.
export function App() {

  return (

      <View>
        <Text variation='primary'>amplify textfield date</Text>
        <TextField type='date' label=''></TextField>

        <Text>html input date</Text>
        <input type='date'></input>              

      </View>

  );

}```


### Additional information and screenshots

_No response_

**Comment by slaymance** [comment]
@MigeBill It appears that your mobile example is lacking any styling. Did you enable default stylings for the `@aws-amplify/ui-react` library? https://ui.docs.amplify.aws/react/getting-started/installation#styles

**Comment by MigeBill** [comment]
Hi @slaymance 
sorry, was attempting to create the simplest possible demonstration of the issue.
updated to add styling and use a ThemeProvider to confirm that is all working.
Behaviour is still the same..................

Desktop
![image](https://user-images.githubusercontent.com/105641225/192030126-22478e42-5d35-494b-86ce-1f033c0b8c60.png)


Mobile
![image](https://user-images.githubusercontent.com/105641225/192030238-12679990-5b02-47b0-9b92-6078273e538b.png)

**Comment by hbuchel** [comment]
Thanks @MigeBill for reporting this. I was able to [reproduce in the latest version](https://stackblitz.com/edit/react-ts-k1jz32?file=App.tsx) on Chrome/Android as well. Taking a further look...

<img src="https://user-images.githubusercontent.com/376920/192040015-c54c3df7-536a-4b15-bb0e-af32015eae3e.png" width="300"/>

**Comment by hbuchel** [comment]
@MigeBill Just an initial update, there is some difference with the display value for the native browser date picker between desktop and mobile. A _sort of workaround_ while we work on a fix is re-setting the display in some additional CSS like below: 
 
```
input[type="date" {
  display: inline-flex
}
```
It does not show the typical dropdown arrow like the native unstyled date picker does; or on desktop how it shows the native browser's calendar icon. On our side, we need to make some decisions about how we treat the missing appearance.

**Comment by MigeBill** [comment]
@hbuchel 
thanks, that work around is a great improvement :)
