### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by txnico** [aws-amplify/amplify-ui#2603]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Expo app

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Loading application components fail with: 

Error: Text strings must be rendered within a <Text> component.

Debugger shows pretty much every field within authenticator with this issue. I.e.: Sign in, Forgot password, Create account buttons. 

### What's the expected behaviour?

Component to load correctly

### Help us reproduce the bug!

Sample code from documentation reproduces this. 

import { Amplify } from 'aws-amplify';

import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';
Amplify.configure(awsExports);

function App({ isPassedToWithAuthenticator, signOut, user }) {
  if (!isPassedToWithAuthenticator) {
    throw new Error(`isPassedToWithAuthenticator was not provided`);
  }

  return (
    <>
      <h1>Hello {user.username}</h1>
      <button onClick={signOut}>Sign out</button>
    </>
  );
}

export default withAuthenticator(App);

export async function getStaticProps() {
  return {
    props: {
      isPassedToWithAuthenticator: true,
    },
  };
}

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

![Screen Shot 2022-09-18 at 10 31 18 PM](https://user-images.githubusercontent.com/68657787/190945514-53906d5f-f3b9-4b3b-815a-519be75ba27b.png)
![Screen Shot 2022-09-18 at 10 30 56 PM](https://user-images.githubusercontent.com/68657787/190945519-f23e3a95-e12c-48c3-a511-2f040873a09b.png)

**Comment by slaymance** [comment]
Hey @txnico, the `@aws-amplify/ui-react` library does not offer support for React Native. React Native support is a part of the team's [upcoming roadmap](https://ui.docs.amplify.aws/react/getting-started/introduction#roadmap) and I encourage you to follow the library's progress for React Native.

**Comment by txnico** [comment]
The documentation goes from one page supporting react-native to the next it doesn't.
