### ISSUE TITLE
Option to Auto-clear Error Messages Upon Success

### ISSUE THREAD

**Issue by jayanthbondi** [aws-amplify/amplify-ui#261]
Steps:
1) click on forgot password.
2) Enter inavild email and verify.
I see this toast message on the top of the page.
**"Username/client id combination not found."**
3) Now give valid email and verify.

I'm still able to see the above toast message.
Expected behaviour: Error toast message must be cleared when API call is successful for the second time.
![image](https://user-images.githubusercontent.com/35721161/99984696-6ae9f900-2dd3-11eb-9466-899650fe701e.png)

**Comment by ErikCH** [comment]
Hi @jayanthbondi 

With our new `authenticator` component error messages are now cleared.

Error messages no longer appear as `toast` messages. They are displayed below the input boxes.

![image](https://user-images.githubusercontent.com/65630/139954055-3ac3dd95-f99b-4153-bbe5-f7b654796a78.png)

After logging in the error disappears. Or the user can click the 'x' button.

Please try out this new authenticator, it's under the `@next` tag. 

https://ui.docs.amplify.aws/ui/getting-started/installation
https://ui.docs.amplify.aws/ui/components/authenticator?platform=react

**Comment by ErikCH** [comment]
I'll close this for now. Please let me know if this does not resolve your issue.
