### ISSUE TITLE
Flex props do not work for components

### ISSUE THREAD

**Issue by hein-j** [aws-amplify/amplify-ui#2612]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

If I put my `TextField` inside a `Flex` component and set the `grow` to 1, the property does not get set in the CSS. Same goes for other components like `SelectField`, etc.

### What's the expected behaviour?

According to the docs, `grow`, `flex`, and other flex properties should work for all UI React components.
[](https://ui.docs.amplify.aws/react/theming/style-props)

### Help us reproduce the bug!

1. Create jsx like so:
```
      <Flex direction={'row'} backgroundColor={'pink'}>
        <TextField label={'Label!'} grow={1}/>
      </Flex>
```
2. See that the TextField does not get stretched out.
3. See that the CSS is not applied

### Additional information and screenshots

Actual:
<img width="433" alt="Screen Shot 2022-09-20 at 11 56 39" src="https://user-images.githubusercontent.com/73264629/191341844-3590db62-d7eb-4cc5-8ff6-989e25d9fbd0.png">
<img width="1792" alt="Screen Shot 2022-09-20 at 11 56 14" src="https://user-images.githubusercontent.com/73264629/191341853-d8d198e6-acd5-47f4-80fa-83106e9fc18a.png">

Expected:
<img width="148" alt="Screen Shot 2022-09-20 at 11 56 57" src="https://user-images.githubusercontent.com/73264629/191341907-453dfed9-fadd-47f4-a699-2df8d9e8290d.png">
<img width="1196" alt="Screen Shot 2022-09-20 at 11 56 53" src="https://user-images.githubusercontent.com/73264629/191341912-1b89b704-ece3-4f96-9a02-76efd21c82b1.png">

**Comment by slaymance** [comment]
This fix will be part of the next major release of the `@aws-amplify/ui-react` package. You can track the progress of that release's work here: #2636

**Comment by dbanksdesign** [comment]
The style props being applied is one thing, which we are changing in the next major version in the above PR. To fix the problem of TextFields not stretching, you don't need `grow` on the TextField itself.

<img width="1709" alt="CleanShot 2022-09-23 at 15 54 23@2x" src="https://user-images.githubusercontent.com/321279/192066977-270c3998-4ce9-43eb-84e8-0c5e5845bcf1.png">

https://stackblitz.com/edit/nextjs-xegiy8?file=pages/index.js

**Comment by hein-j** [comment]
@slaymance,
Thank you for working on the fix!

@dbanksdesign,
Thanks for the suggestion. The issue is precisely that it doesn't work when the containing `Flex` has `direction=row`. If a customer wants to put 2 `TextField`s in one row and get them to stretch with the parent `Flex`, they cannot.

**Comment by dbanksdesign** [comment]
Ah I see the issue now. Yea we are applying the `grow` property onto the input instead of the wrapper element. A workaround before the next major version would be:

<img width="1710" alt="CleanShot 2022-09-23 at 16 40 24@2x" src="https://user-images.githubusercontent.com/321279/192069848-2c52b873-7a00-49aa-b56d-06cb0fddd35e.png">

**Comment by hein-j** [comment]
Ohh I didn't think of that. Good to know.

**Comment by hein-j** [comment]
@dbanksdesign @slaymance 
We were going to open another issue as a P1 on `display=none` not completely working on certain components.
I'm guessing it's addressed by this change, but just wanted to confirm. If not, I'll open a separate issue:

<img width="574" alt="Screen Shot 2022-09-23 at 17 23 10" src="https://user-images.githubusercontent.com/73264629/192071968-3be8aa5f-8729-4c94-9d8f-5a2ed8e76e2e.png">

<img width="432" alt="Screen Shot 2022-09-23 at 17 23 06" src="https://user-images.githubusercontent.com/73264629/192071971-e8f12cce-140c-47cc-b146-fd57a3d3b270.png">

**Comment by zchenwei** [comment]
@hein-j  Yes, that will be addressed together along with the change
