### ISSUE TITLE
View component does not have types

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-ui#2614]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

any

### Please describe your bug.

![CleanShot 2022-09-20 at 12 58 22](https://user-images.githubusercontent.com/321279/191356677-b4d56b4a-40f1-4cd3-9b8a-38c46ad176ba.gif)

### What's the expected behaviour?

![CleanShot 2022-09-20 at 12 59 29](https://user-images.githubusercontent.com/321279/191356652-83e289fa-113b-42da-8aa6-6afb9ffbfe2d.gif)

### Help us reproduce the bug!

Use the `View` component

### Code Snippet

```typescript
// Put your code below this line.
<View
// any props here
/>
```

**Comment by zchenwei** [comment]
This should be fixed in 5.x release.
