### ISSUE TITLE
Add HideSignIn property to SignUp

### ISSUE THREAD

**Issue by defish1962** [aws-amplify/amplify-ui#263]
**Is your feature request related to a problem? Please describe.**
Similar to how HideSignUp works with SignIn I would like to be able to hide the Have an account? Sign In link on the Sign up form. 

**Describe the solution you'd like**
See problem description above. Add a HideSignIn property to AmplifySignUp. Alternatively provide us with the ability to specify the link URL for Sign in and Sign Up. 

**Describe alternatives you've considered**
I have to create my own sign up and sign in forms for use with Cognito without this option. I do not want users to click on this link for Sign In because I have special Sign Up requirements and I want them to use my customized form. 

**Additional context**
See this link for an example of what I am requesting. https://github.com/aws-amplify/amplify-js/pull/6098

**Comment by defish1962** [comment]
Yes that would be a workable solution for me. Thanks!

**Comment by ErikCH** [comment]
Hi @defish1962 

With the new authenticator we have a lot of this solved.

As for your question on linking directly to the `Create Account / Sign Up page` that can be done with our `initialState` [prop](https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#initialstate). Basically, you can specify which state the authenticator should start in.

```
export default withAuthenticator(App, {
  initialState: 'signUp',
});
```

As for hiding the Sign in, we do have a way to hide both [tabs](https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#additional-css-styling). 

```
.amplify-tabs {
  display: none;
}
```

You could use this with the initial state so a user is unable to go to the signIn page. However, after the user signs up, and logs in, after they logout, they'll be redirected to the sign in page. 

Let me know if this works for you.

**Comment by ErikCH** [comment]
We've also added a slot to add in your own custom text! Documentation on that is forthcoming.

**Comment by ErikCH** [comment]
Closing this issue for now, if you need more assistance let us know!

**Comment by ErikCH** [comment]
I just merged this in! It should be available in our next release. There will be a new `hideSignUp` prop you can pass in, to hide the sign up page.

**Comment by defish1962** [comment]
Awesome! Thanks so much!
