### ISSUE TITLE
S3Image request to support non-signed urls (amplify-react)

### ISSUE THREAD

**Issue by dmoskovtsov** [aws-amplify/amplify-ui#264]
**Is your feature request related to a problem? Please describe.**
Usecase: we use S3Image to display images on the publicly available website (level: public). We also use prerendering service (prerender.io) to cache webpages to improve SEO. When prerender crawls our website, img src contains signed url that expires. It doesn't work in our case, as the img src url expires faster than our cache updates (every 3 days).

**Describe the solution you'd like**
Have an ability to use plain url and not signed one for public images. e.g Signed url: 
https://bucket.amazonaws.com/public/product-5412783053848.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential==........

Plain url:
https://bucket.amazonaws.com/public/product-5412783053848.jpg

**Describe alternatives you've considered**
We built our own image component where we strip the signed portion URL off. But hoping to use standard S3Image going forward. Happy to provide/implement code assuming there is an agreement on API. 

Cheers

**Comment by reesscot** [comment]
Closing out issue as the `S3Image` component has been deprecated.
