### ISSUE TITLE
Theming for font family is not overriding default font

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#2644]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Any

### Please describe your bug.

When I add custom font family declarations, the font family still shows as the font from the default theme. See example here where the text should show as the system default serif font. https://stackblitz.com/edit/react-ts-1tcypz?file=App.tsx

Note: Might need more investigation, but we set the font-family on the html element; we should verify if we should also set the font-family property on the [data-amplify-theme] selector? (see screenshots).

<img width="1184" alt="Screen Shot 2022-08-15 at 5 06 58 PM" src="https://user-images.githubusercontent.com/376920/192346734-fe2a48e6-99b9-41a4-b6aa-07b62a4c0824.png">

<img width="1237" alt="Screen Shot 2022-08-15 at 5 06 10 PM" src="https://user-images.githubusercontent.com/376920/192346741-298ad23f-01c6-4472-a078-79c2f7f18b59.png">

### What's the expected behaviour?

I'd expect to be able to follow these instructions to override the font-family via Theme object 

https://ui.docs.amplify.aws/react/theming#fonts

### Help us reproduce the bug!

https://stackblitz.com/edit/react-ts-1tcypz?file=App.tsx

**Comment by reesscot** [comment]
Fixed in https://github.com/aws-amplify/amplify-ui/pull/2767
