### ISSUE TITLE
UI component CSS overrides of amplify-toast/amplify-button/amplify-form-field/etc

### ISSUE THREAD

**Issue by cdunn** [aws-amplify/amplify-ui#265]
**Is your feature request related to a problem? Please describe.**
There is no easy way to style many(most?) parts of the current web components without js hacks it seems. The CSS variables support only covers a small surface area and does not seem to cover many cases (hover states/etc) to keep a consistent UI (rounded corners on federated auth buttons and square in SIGN IN with all caps for example).

Some examples:
- Styling the toast
- Centering the header
- Hover/active/focus states on inputs, input padding/sizing
- Button consistency
- Text-transform on buttons

**Describe the solution you'd like**
A supported method for overriding CSS styles of nested web components.  If more components could be exposed at a top level (amplify-form-field...amplify-button...etc) and add css ::part support to override styling of individual components.

**Describe alternatives you've considered**
For now, staying on the legacy components.

**Comment by Milan-Shah** [comment]
We have released a newer version of our [Authenticator UI component](https://ui.docs.amplify.aws/components/authenticator) with a support for custom styling and many more features. If you still have any issues with styling, please open an another issue on our UI repo!
