### ISSUE TITLE
Misleading Docs for Headless `useAuthenticator`

### ISSUE THREAD

**Issue by tannerabread** [aws-amplify/amplify-ui#2657]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

N/A

### Please describe your bug.

The docs for the [useAuthenticator hook](https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#useauthenticator-hook) do not make it clear that useAuthenticator cannot currently be used without the `<Authenticator />` component present somewhere in the app.

The linked section and the section below it, "Authenticator Provider", make it seem like the hook can be used without the Authenticator component as long as the application is wrapped with `Authenticator.Provider`

### What's the expected behaviour?

I would expect to gain the knowledge that an Authenticator component is required for the hook to work, and not just Authenticator.Provider

[This workaround](https://github.com/aws-amplify/amplify-ui/issues/1497#issuecomment-1063553150) is helpful if the reader finds it

### Help us reproduce the bug!

The use case for this was trying to use `toFederatedSignIn` and `useAuthenticator` in an app for custom auth flow without an `<Authenticator />` component

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

I recommend adding a note in the ["useAuthenticator Hook"](https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#useauthenticator-hook) section that explains the `Authenticator` component still needs to be present somewhere or rewording ["Authenticator Provider"](https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#authenticator-provider) to explain the same

**Comment by Milan-Shah** [comment]
@tannerabread That is a fair callout. Thank you for opening the issue, we will address it prior to our upcoming release on docs.

**Comment by tannerabread** [comment]
thank you @Milan-Shah !
