### ISSUE TITLE
UI Components always bundle storage, even if it is not used

### ISSUE THREAD

**Issue by atyshka** [aws-amplify/amplify-ui#267]
**Describe the bug**
Any use of the ui components necessitates the inclusion of the storage api, which takes up a whole megabyte. For those of us who do not use storage components but only things like auth components, this is a massive waste. 20% of my app bundle is now this storage api which I am not using.

**To Reproduce**

Import either the whole component library via `import "@aws-amplify/ui-vue";` or modularly by 
```
import {
  AmplifyAuthenticator,
  AmplifySignIn,
} from "@aws-amplify/ui-vue";
```

**Expected behavior**
The modular import, including only the authenticator and sign in, would not bundle the s3 storage dependency.

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)
```
import {
  AmplifyAuthenticator,
  AmplifySignIn,
} from "@aws-amplify/ui-vue";
```

**Screenshots**

![image](https://user-images.githubusercontent.com/19317207/103558693-09fa1a00-4e83-11eb-9e62-28566cac63ba.png)
The blue block on the right is the unnecessary inclusion of s3, comprising ~20% of the bundle size

**Comment by Milan-Shah** [comment]
@atyshka We have released a newer version of @amplify-ui/2.0.0. We are confident that the issue you previously opened has been fixed in the latest release. Please let us know if you have any issues!
