### ISSUE TITLE
@aws-amplify/ui-angular AmplifyUIAngularModule is incompatible with Jest

### ISSUE THREAD

**Issue by bmcilw1** [aws-amplify/amplify-ui#269]
**Describe the bug**

This is a duplicate of the closed issue https://github.com/aws-amplify/amplify-js/issues/3531.

**To Reproduce**
Work in progress, trying to reproduce outside of nx. See old issue for starting. If you have a preferred way to init a project, add jest, then add AmplifyUIAngularModule I'm happy to do it and post results. My current way is to use nx.

Here's how to reproduce with nx:

1. Create new project and add @aws-amplify/ui-angular. I'll use nrwl because it creates a project pre-configured for jest.

    ```bash
    mkdir amplify-jest
    cd amplify-jest
    npx create-nx-workspace test --appName=myapp --preset=angular --nx-cloud=false --style=css --linter=eslint
    npm install @aws-amplify/ui-angular
    cd test
    ```
2. Run tests `ng test`. They should be currently passing.

3. Add `AmplifyUIAngularModule` to `app.module.ts`

    * Add `import { AmplifyUIAngularModule } from '@aws-amplify/ui-angular';` to the top of the file.

    * Add `AmplifyUIAngularModule` to the imports array `imports: [ ... AmplifyUIAngularModule ]`.

4. Run tests `ng test`. They should now fail with the error below

**Expected behavior**

Jest should be able to process the AmplifyUIAngularModule in a TypeScript project.

```text
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/brianmcilwain/source/ah-applications-nx/node_modules/@aws-amplify/ui-angular/dist/fesm5.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { __decorate, __metadata } from 'tslib';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import { CommonModule } from '@angular/common';
      3 | import { TestComponentComponent } from './test-component/test-component.component';
    > 4 | import { AmplifyUIAngularModule } from '@aws-amplify/ui-angular';
        | ^
      5 | 
      6 | @NgModule({
      7 |   imports: [CommonModule, AmplifyUIAngularModule],
```

- Update: Added steps to reproduce

**Comment by wlee221** [comment]
Hello @bmcilw1, apologies on delayed response. We just released `@aws-amplify/ui-angular@2.x.x` that moved away from web components. Can you please give it a try and open a new issue if this persists? Thanks!

- https://ui.docs.amplify.aws/components/authenticator?platform=angular

**Comment by KOSSOKO** [comment]
@wlee221 same error with my project. I install the version 2 but got the following errors:

Error: node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui/dist/index.d.ts:37:44 - error TS2339: Property 'loginMechanisms' does not exist on type '{ loginMechanisms?: ("use
rname" | "email" | "phone_number")[] | undefined; signUpAttributes?: SignUpAttribute[] | undefined; socialProviders?: SocialProvider[] | undefined; } | undefined'.

37     loginMechanisms: AuthContext['config']['loginMechanisms'];
                                              ~~~~~~~~~~~~~~~~~


Error: node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui/dist/index.d.ts:38:44 - error TS2339: Property 'socialProviders' does not exist on type '{ loginMechanisms?: ("use
rname" | "email" | "phone_number")[] | undefined; signUpAttributes?: SignUpAttribute[] | undefined; socialProviders?: SocialProvider[] | undefined; } | undefined'.

38     socialProviders: AuthContext['config']['socialProviders'];
                                              ~~~~~~~~~~~~~~~~~


Error: node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui/dist/index.d.ts:49:44 - error TS2339: Property 'loginMechanisms' does not exist on type '{ loginMechanisms?: ("use
rname" | "email" | "phone_number")[] | undefined; signUpAttributes?: SignUpAttribute[] | undefined; socialProviders?: SocialProvider[] | undefined; } | undefined'.

49     loginMechanisms: AuthContext['config']['loginMechanisms'];
                                              ~~~~~~~~~~~~~~~~~


```
Error: node_modules/@aws-amplify/ui-angular/node_modules/@aws-amplify/ui/dist/index.d.ts:50:44 - error TS2339: Property 'socialProviders' does not exist on type '{ loginMechanisms?: ("use
rname" | "email" | "phone_number")[] | undefined; signUpAttributes?: SignUpAttribute[] | undefined; socialProviders?: SocialProvider[] | undefined; } | undefined'.

50     socialProviders: AuthContext['config']['socialProviders'];
                                              ~~~~~~~~~~~~~~~~~
```

**Comment by wlee221** [comment]
Ah got it @KOSSOKO, thanks for the feedback! Since the error looks more scoped now (which is a good news!), can you please open a new issue for it with repro steps? We'll work on getting it resolved right after then.

**Comment by KOSSOKO** [comment]
@wlee221 ok, i will create a new repo. But please do you have a workaround for the moment ? Because i have to deploy for tomorrow

**Comment by wlee221** [comment]
Did you try setting off your `strict` settings in `tsconfig`? Looks like it's related to `strict` settings with possibly `undefined` value.

**Comment by wlee221** [comment]
Ah I see you already created an issue #887, I'll communicate there.
