### ISSUE TITLE
Default colours do not meet contrast standards

### ISSUE THREAD

**Issue by anthonyhumphreys** [aws-amplify/amplify-ui#270]
**Describe the bug**
@aws-amplify/ui-react - default colours are inaccessible according to WCAG

**To Reproduce**
Assess colour contrast against WCAG standards

https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=FF9900

**Expected behavior**
The default colour scheme should always be an accessible palette

**Comment by Milan-Shah** [comment]
@anthonyhumphreys We have released a major version of @amplify-ui where we have put a lot of attention to accessibility for all our primitives and UI components like Authenticator. If you still have any issues, feel free to reopen or create a new issue. You can access our new UI doc site [here](https://ui.docs.amplify.aws/components).
