### ISSUE TITLE
Una vez le di un tema, pero no tenía clara la respuesta.

### ISSUE THREAD

**Issue by Masaki-G** [aws-amplify/amplify-ui#2707]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

vue.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

La última vez planteamos la siguiente cuestión, pero hay algunos puntos que no están claros
https://github.com/aws-amplify/amplify-ui/issues/2699#event-7539651159

Puedo resolver la vresión en 3.5.7 @aws-amplify/ui-react y esta vez el error está ocurriendo en @aws-amplify/ui-vue

### What's the expected behaviour?

Lo mismo que este tema aquí.
https://github.com/aws-amplify/amplify-ui/issues/2699#event-7539651159

### Help us reproduce the bug!

Lo mismo que este tema aquí.
https://github.com/aws-amplify/amplify-ui/issues/2699#event-7539651159

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by wlee221** [comment]
We'll track this issue in #2699, and close this one. Thanks!
