### ISSUE TITLE
Can't use HTML in FormField hint

### ISSUE THREAD

**Issue by lamvananh** [aws-amplify/amplify-ui#271]
**Is your feature request related to a problem? Please describe.**
look at this code:
I can't use JSX or HTML in 'hint' props of password (normal text is still working), each time i try, the default hint displayed insted of my expected element.
```jsx
  <AmplifySignIn
                formFields={[
                 {
                    type: 'username',
                    label: 'Username',
                    placeholder: 'enter username',
                    required: true,
                },
                  {
                    type: 'password',
                    label: 'password',
                    placeholder: 'enter password',
                    required: true,
                    hint: 'CUSTOM HINT',
                },
              ]}
              headerText="Login"
              hideSignUp
              submitButtonText="Signin"
              slot="sign-in"
            />
```

**Describe the solution you'd like**
i want this feature is available

**Describe alternatives you've considered**
none

**Additional context**
i look up in this file [https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx](url)
and fond this code at line 205:
```js
if (newField.type === 'password') {
          newField['hint'] = isHintValid(newField) ? (
            <div>
              {I18n.get(Translations.FORGOT_PASSWORD_TEXT)}{' '}
              <amplify-button
                variant="anchor"
                onClick={() => this.handleAuthStateChange(AuthState.ForgotPassword)}
                data-test="sign-in-forgot-password-link"
              >
                {I18n.get(Translations.RESET_PASSWORD_TEXT)}
              </amplify-button>
            </div>
          ) : (
            newField['hint']
          );
}
```
https://github.com/aws-amplify/amplify-js/blob/7b5b23f9fa6f1c4934c631ab6bfc363b8d3eeac2/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx#L205

it's make me curios that why you have to allow only  string in hint field

**Comment by ericclemmons** [comment]
What's an example of the `hint` you'd like to provide?

One thing we can do is also add a `SignIn.FormFields` slot so you have full control over this experience like we do for https://ui.docs.amplify.aws/components/authenticator#sign-up-fields
