### ISSUE TITLE
Access Design Token CSS Variable Names in a Type Safe Way Outside React Component

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#2739]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I’d like to be able to use @vanilla-extract/css with Amplify UI. In my example.css.ts file, I’d like to be able to reference the theme values I created in Amplify UI. I can reference Amplify UI CSS variables in my example.css.ts file manually with a string, but I’d prefer to have an object or something with type safety with better DX.
An alternative solution could be to access the CSS value, but I don’t think that will work since I’m outside of a React component and cannot access context.

### Please describe a solution you'd like.

Amplify UI export an object of design tokens where leaf values are css variable names (not the actual css value).

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by bestickley** [comment]
Example Current:
```ts
// MyComponent.css.ts
import { style } from "@vanilla-extract/css";
export const container = style({
  display: "flex",
  flexGap: "var(--amplify-space-medium)"
});
```

```ts
// MyComponent.ts
import * as styles from "./MyComponent.css.ts";
export function MyComponent() {
  return <div className={styles.container}>...</div>
}
```

Example Requested:
```ts
// MyComponent.css.ts
import { style } from "@vanilla-extract/css";
import { designTokens } from "@aws-amplify/ui-react";
export const container = style({
  display: "flex",
  flexGap: `var(${designTokens.space.small})`
});
```

```ts
// MyComponent.ts
import * as styles from "./MyComponent.css.ts";
export function MyComponent() {
  return <div className={styles.container}>...</div>
}
```

**Comment by reesscot** [comment]
Yes, you are correct, `theme.tokens.space.small` will contain the CSS variable for that token. Let us know if you have any further questions.

**Comment by bestickley** [comment]
Awesome. Thanks for confirming, @reesscot!
