### ISSUE TITLE
Processing legacy "View Engine" library - Angular 14 copile-time warning for @aws-amplify/ui-angular@2.4.24

### ISSUE THREAD

**Issue by eXpertise7** [aws-amplify/amplify-ui#2742]
### On which framework/platform would you like to see this feature implemented?

Angular

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

Hi,

I've warning on my Angular 14 project about @aws-amplify/ui-angular. Angular's compiler when serving the project locally tells me that @aws-amplify/ui-angular is still on View Engine library, not on Angular Ivy.

Could you publish an Ivy distribution?

Compiler's warning:

![image](https://user-images.githubusercontent.com/17203747/195825581-7ca27887-1f1d-41a2-b8bd-82c1373eec61.png)

Version refrence in yarn.lock:

![image](https://user-images.githubusercontent.com/17203747/195825964-bb2a1aba-ce3a-4226-895c-195540486785.png)

Thank You in advance.

Kind regards,
Robert Medved

### Please describe a solution you'd like.

Make the compiler warning disappear by publishing Angular's Ivy distrubition on @aws-amplify/ui-angular.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by wlee221** [comment]
Hi @eXpertise7 👋

We actually recently merged https://github.com/aws-amplify/amplify-ui/pull/2580 that will migrate our library to IVY engine. This will however be in the next major release (v4), because this is technically a breaking change. We'll keep this issue until we make the release!

**Comment by wlee221** [comment]
Hello, our major release has been published, and we have migrated to Ivy completely. Let us know if you have any concerns!

**Comment by eXpertise7** [comment]
Hello,

Just an advice for maintainers, document where are some interfaces that can be used directly/indirectly by the package.

![image](https://user-images.githubusercontent.com/17203747/203830307-84608532-775a-4cc2-87aa-f70cecf5f57d.png)

This has worked in v1 & v2, now in v3 newest version from where the screenshot it does not work.

Left side (before the local changes), yarn.lock file:

![image](https://user-images.githubusercontent.com/17203747/203830773-5fa18682-86fb-4cb0-b497-a2dd88a35f71.png)

For typed system I need CognitoUserInterface type and I've to find what were the properties from before in the interface, I don't want to have any type.

/cc @wlee221 

If you know where we can find interfaces feel free to tell me.

Kind regards,
Robert Medved

**Comment by eXpertise7** [comment]
Where are all of these stuff in v3, image below is from v2:
![image](https://user-images.githubusercontent.com/17203747/203834422-1553246e-cd2b-481a-954a-3f3e9f7bbfbe.png)
