### ISSUE TITLE
Amplify Signup fails on android unless using "desktop site"

### ISSUE THREAD

**Issue by Russ-K** [aws-amplify/amplify-ui#275]
**Is your feature request related to a problem? Please describe.**
A web app using react and amplify.
From the sign in / up screen, when the user chooses to sign up then fills in their username and password and clicks "Create Account", the wait cursor spins forever.
This only happens on Android (tested on chrome and brave)
Chrome on iOS & chrome for desktop works fine.

**Debugging**

There's a function: "class_6.prototype.signUp"
in a file: .../node_modules/@aws-amplify/ui-components/dist/esm-es5/amplify-confirm-sign-in_7.entry.js
Within this function there is a switch statement: `switch(_a.label)`
When case is 0 then there's an if statement:
`if (this.signUpAttributes.username.indexOf(' ') >= 0)`

In "desktop site" mode, username is the email that was typed in but in normal "mobile" mode, the username is blank.

This throws an exception "Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined"

**Describe the solution you'd like**
Users on android able to sign up / create account in normal "mobile" mode

**Describe alternatives you've considered**
Setting the mobile browser to "Desktop site" works.

**Additional context**
None

**Comment by Milan-Shah** [comment]
@Russ-K and @slewis77 - We have launched a new version of [Authenticator UI component](https://ui.docs.amplify.aws/components/authenticator) and a major version for @amplify-ui with the support for zero config, multiple sign up attributes, password manager support, custom styling and many more. Please reopen the issue if you still have any problem or if we can help with anything.
