### ISSUE TITLE
When used as link, Button shows Typescript error on `href` prop

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#2761]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

N/A

### Please describe your bug.

When using Typescript and using the `Button` component as a link:
```tsx
<Button  as="a" href="/page">Page</Button>
```
I get the following TS error:

```bash
Type '{ children: string; as: "a"; href: string; }' is not assignable to type 'IntrinsicAttributes & Pick<PrimitivePropsWithRef<ButtonProps, "button">, "children" | "as" | "area" | "form" | ... 347 more ... | "value"> & RefAttributes<...>'.
```

### What's the expected behaviour?

The HTMLAttributes from the `a` tag should be available on `Button` when the `as="a"` prop is set.

### Help us reproduce the bug!

See above

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
In dicussion with @dbanksdesign and @zchenwei, we decided that we should fix this by adding an option to style the Link component as a Button. This will make it unnecessary to use the as prop on Button.

**Comment by zchenwei** [comment]
This should be fixed in 5.x release.
