### ISSUE TITLE
Authenticator webpack import Error Messages

### ISSUE THREAD

**Issue by dannytszho** [aws-amplify/amplify-ui#2778]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

After a user login, the user is supposed to get redirect to the index page or the protected page depends on which page the user tries to login. However this only work half of the time.  On the other half of the time, the user doesn't get redirect and stayed in the login page with no rendering and the following error message is displayed to the user: 

```
Uncaught TypeError: (0 , _defaults_js__WEBPACK_IMPORTED_MODULE_0__.defaultFormFieldsGetters[r]) is not a function
    at e (formFields.js:1:1)
    at u (formFields.js:1:1)
    at f (formFields.js:1:1)
    at m (FormFields.js:1:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
```

### What's the expected behaviour?

the user is supposed to get redirect to the index page or the protected page depends on which page the user tries to login

### Help us reproduce the bug!

https://github.com/dannytszho/renoGuideFrontendReact

### Code Snippet

LogInPage.tsx
```typescript
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'
import React, { useEffect, useMemo } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { PreviousButton } from '../Utils/Button'
import Footer from '../Utils/Footer'

export const formFields = {
  signUp: {
    email: {
      order: 2,
      placeholder: 'Email',
      isRequired: true,
    },
    given_name: {
      order: 3,
      placeholder: 'Given name',
      isRequired: true,
    },
    family_name: {
      order: 4,
      placeholder: 'Family name',
      isRequired: true,
    },
    password: {
      order: 5,
    },
    confirm_password: {
      order: 6,
    },
  },
}

const LoginPage = () => {
  const { route } = useAuthenticator(context => [context.route])
  const navigate = useNavigate()
  const location = useLocation()

  const navigatePathName = useMemo(() => {
    const state = location.state as { from: Location }
    console.log(state)

    if (state && state.from) {
      return state.from
    }
    return '/'
  }, [location])

  useEffect(() => {
    if (route === 'authenticated') {
      navigate(navigatePathName, { replace: true })
    }
  }, [route, navigate, navigatePathName])
  
  return (
    <>
      <PreviousButton />
      <div className="auth-wrapper mt-28">
        <Authenticator
          formFields={formFields}
          socialProviders={['google']}
        ></Authenticator>
      </div>
      <br />
      <Footer />
      <br />
    </>
  )
}

export default LoginPage

```
App.tsx
```
import { HashRouter, Route, Routes } from 'react-router-dom'
import './index.css'
import HikingTrailsPage from './Components/Pages/HikingTrailsPage'
import HomePage from './Components/Pages/HomePage'
import { Authenticator } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'
import NavBar from './Components/Utils/NavBar'
import HikingTrailsPageGQL from './Components/Pages/HikingTrailsPageGQL'
import LoginPage from './Components/Pages/LoginPage'
import RequiredAuth from './Components/Utils/RequiredAuth'
import CreateTrailPage from './Components/Pages/CreateTrailPage'
import MyTrailPage from './Components/Pages/MyTrailPage'

function App() {
  return (
    <>
      <Authenticator.Provider>
        <HashRouter>
          <Routes>
            <Route path="/" element={<NavBar />}>
              <Route index element={<HomePage />} />
              <Route path="/hikingtrails" element={<HikingTrailsPage />} />
              <Route
                path="/hikingtrailsgql"
                element={
                  <RequiredAuth>
                    <HikingTrailsPageGQL />
                  </RequiredAuth>
                }
              />
              <Route
                path="/createtrail"
                element={
                  <RequiredAuth>
                    <CreateTrailPage />
                  </RequiredAuth>
                }
              />
              <Route
                path="/my-trail"
                element={
                  <RequiredAuth>
                    <MyTrailPage />
                  </RequiredAuth>
                }
              />
              <Route path="/login" element={<LoginPage />} />
            </Route>
          </Routes>
        </HashRouter>
      </Authenticator.Provider>
    </>
  )
}

export default App

```

**Comment by zchenwei** [comment]
Hi @dannytszho, thank you for reporting the issue. I pulled down your repo and run the app locally to test out the log in. I repeated the process by ~20 times and was able to see the same error. Could you confirm that the issue is still existing? Thanks!

**Comment by dannytszho** [comment]
Hi @zchenwei. Thank you for the response. Yes the error is still existing. Did you test out the log in with OAuth or email? The error only exists when the user log in with email. I apologize for not being specific enough earlier. Thanks!

**Comment by zchenwei** [comment]
Yeah, I use gmail to federated login. Maybe you can provide us a gif or video to see the entire process and what happen when the error pops up? Thanks!

**Comment by reesscot** [comment]
@dannytszho Are you still seeing this issue, or did you find a solution?

**Comment by dannytszho** [comment]
Hi @zchenwei @reesscot,

Yes the issue still existing. Please see this video for the error.
[](https://watch.screencastify.com/v/ggXwcgu2B0lT9PL1JiyZ)
Thanks!

**Comment by reesscot** [comment]
Closing out as we haven't heard back. Please let us know if you are still having this issue with a new Amplify Auth backend.
