### ISSUE TITLE
FR "Understanding the scale" for Amplify UI Theme

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#2790]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I'd like documentation provided for which color scale (10, 20, 40, ... 100) to use when developing components similar to Radix UI Colors [here](https://www.radix-ui.com/docs/colors/palette-composition/understanding-the-scale).

### Please describe a solution you'd like.

![image](https://user-images.githubusercontent.com/35735118/197591080-1bbb7544-ce04-4c8f-bdff-b38cabf62e51.png)

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Documentation has been updated here: https://ui.docs.amplify.aws/react/theming/default-theme/colors
