### ISSUE TITLE
Setup TOTP issue on code entering

### ISSUE THREAD

**Issue by m-bilal-dev9** [aws-amplify/amplify-ui#285]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
npx: installed 1 in 4.549s

  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 61.21 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 83.0
    Safari: 14.0.2
  npmGlobalPackages:
    eslint-plugin-prettier: 3.4.0
    npm: 6.14.11
    yarn: 1.22.10
```

</details>

### Describe the bug

TOTP Setup getting failed on entering authenticator app code. 

### Expected behavior

It should complete the TOTP setup without any error.

### Reproduction steps

I'm unable to reproduce this issue on development setup, but it's happening with some beta tester users on staging, and on refreshing the page they can setup TOTP again without any issue.

### Code Snippet

```javascript
 <AmplifyAuthenticator usernameAlias="email">
  <AmplifySelectMfaType
          MFATypes={{ TOTP: true }}
        />
        <AmplifySignIn
          slot="sign-in"
          usernameAlias="email"
        />
      </AmplifyAuthenticator>
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

iPhone

### Mobile Operating System

iOS

### Mobile Browser

Safari

### Additional information and screenshots

![IMG_2232](https://user-images.githubusercontent.com/77671366/116540830-1c053a00-a904-11eb-8a87-8f2535fea51b.JPG)

**Comment by Milan-Shah** [comment]
@m-bilal-dev9 We have released a new major version of @aws-amplify/ui-react@2.1.0 and have launched a brand new iteration of [Authenticator UI component](https://ui.docs.amplify.aws/components/authenticator) with the support for custom styling, zero config support, sign up attributes, parity across all web frameworks, password manager support and many more. Please let us know if you are still seeing the issue on your end. We are going to launch React Native Authenticator version in next few weeks!
