### ISSUE TITLE
Vue UI - Properties for Authenticator element not modifying UI

### ISSUE THREAD

**Issue by burnhamd** [aws-amplify/amplify-ui#2850]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Webpack 4

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

After recent release, authenticator component is no longer working with previous configuration.
Also customization made to the CSS is now not applying to the UI.

### What's the expected behaviour?

applying isSignUpDisplayed: false,

Should show no signup link.

### Help us reproduce the bug!

Implement component

add isSignUpDisplayed: false, to the properties for the component.

### Code Snippet

```typescript
// Put your code below this line.

<template>
      <amplify-authenticator v-bind:authConfig="authConfiguration">
        <amplify-sign-in>
        </amplify-sign-in>
      </amplify-authenticator>
</template>

authConfiguration: {
            signInConfig: {
            isSignUpDisplayed: false,
            header: '',
            },
            forgotPasswordConfig:{
            header: ''
            },
            requirenewPasswordConfig:{
            header: ''
            },        
            confirmSignInConfig:{
            header: ''
            },
            confirmSignUpConfig:{
            header: ''
            },                 
        }
        };
```

**Comment by thaddmt** [comment]
Hi @burnhamd is this app built with vue2? And it looks like you are using the [legacy ui components](https://github.com/aws-amplify/amplify-ui/tree/legacy/legacy/amplify-ui-vue) based off your code example. I noticed that for signup to be displayed as false our docs recommend using `hide-sign-up` attribute like this example below

```
<amplify-sign-in
    slot="sign-in"
    hide-sign-up="true"
  ></amplify-sign-in>
```

**Comment by reesscot** [comment]
Closing as the `@aws-amplify/ui-components` package has been deprecated. Please upgrade to the new Vue Authenticator: https://ui.docs.amplify.aws/vue/connected-components/authenticator. Also see the migration guide here: https://ui.docs.amplify.aws/vue/getting-started/migration#1x-to-2x
