### ISSUE TITLE
Creating a new account takes back to sign-in

### ISSUE THREAD

**Issue by agoldis** [aws-amplify/amplify-ui#286]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 433.00 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 90.1.24.85
    Chrome: 90.0.4430.212
    Edge: 81.0.416.68
    Firefox: 88.0.1
    Safari: 14.0
  npmPackages:
    "@aws-amplify/auth": "^3.4.29",
    "@aws-amplify/core": "^3.8.21",
    "@aws-amplify/interactions": "^3.3.29",
    "@aws-amplify/storage": "^3.3.29",
    "@aws-amplify/ui-react": "^1.2.0",
```

</details>

### Describe the bug

Code verification stage for creating a new account takes back to sign-in

### Expected behavior

Code verification stage for creating a new account should take back to sign-up

### Reproduction steps

Just use the Authenticator as described in guide

### Code Snippet

```javascript
<AmplifyAuthenticator
        usernameAlias="email"
        hideToast
        key={initialAuthState}
        initialAuthState={initialAuthState}
      >
        <AmplifySignUp
          slot="sign-up"
          usernameAlias="email"
          formFields={[
            {
              type: 'email',
              handleInputChange: (e) => setEmail(e.target.value),
              value: email,
            },
            {
              type: 'password',
              handleInputChange: (e) => setPassword(e.target.value),
              value: password,
            },
          ]}
        />
      </AmplifyAuthenticator>
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

https://user-images.githubusercontent.com/1637928/118720637-b60f2280-b7de-11eb-879c-3ace3a341c35.mp4

**Comment by ericclemmons** [comment]
So I can better understand if this should be a default behavior, what's the goal of having `Back to Sign In` from within the Sign Up flow?

**Comment by Milan-Shah** [comment]
@agoldis We have released a newer version of [Authenticator UI Component](https://ui.docs.amplify.aws/components/authenticator) that supports personal customization, new styling, parity across all of our web frameworks, zero-config, social sign in, and many more features like password manager support etc. Please let us know if you are seeing the same issue in our latest iteration. We are here to help :)
