### ISSUE TITLE
TOTP Issuer Name not being changed when customizing the setupTOTP formfield

### ISSUE THREAD

**Issue by delennpalmer** [aws-amplify/amplify-ui#2886]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Firefox, Chrome

### Please describe your bug.

When I set the `formFields` property on Authenticator to: `{ setupTOTP: { QR: { totpIssuer: "Company Name" } } };`, once scanning the QR code through the Google Authenticator application, the TOTP does not correctly change the issuer name. 

### What's the expected behaviour?

The issuer name on the authenticator application is customized to the preferred name.

### Help us reproduce the bug!

Utilizing the code snippet should suffice.

### Code Snippet

```javascript
// Put your code below this line.
import React from "react";
import { Amplify } from "aws-amplify";
import {
	Authenticator,
	useTheme,
	Heading,
} from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

import awsExports from "./aws-exports";

Amplify.configure(awsExports);

export default function App() {
	const components = {
		SetupTOTP: {
			Header() {
				const { tokens } = useTheme();
				return (
					<Heading textAlign="center" padding={tokens.space.large} level={3}>
						Please Scan QR Code:
					</Heading>
				);
			},
		},
	};

	const formFields = { setupTOTP: { QR: { totpIssuer: "Company Name" } } };

	return (
		<>
			<Authenticator components={components} formFields={formFields}>
				{({ signOut, user }) => (
					<h1>Welcome {user.username} to Company Name</h1>
				)}
			</Authenticator>
		</>
	);
}
```

**Comment by ErikCH** [comment]
Hi @delennpalmer ! Thanks for opening this ! I'm looking into it!

**Comment by ErikCH** [comment]
Hi @delennpalmer This should be fixed! Please try the latest `@aws-amplify/ui-vue` and it should be working. If not please reopen this bug.
