### ISSUE TITLE
Use Link component with React Router Dom v6.x

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-ui#2889]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Please describe your bug.

The `<Link>` component seems to be on a deprecation path.

However, somewhat recently React Router Dom has released a newer version 6.x that doesn't support the [recommended method](https://ui.docs.amplify.aws/react/components/link#routing-libraries) in the docs of:
```ts
<ReactRouterLink to="/" component={Link}>Home</ReactRouterLink>
```

As it stands, the only way that I found to use Amplify UI with React Router Dom v6.x is to pass an `href` prop to it, which causes the deprecation warning to show up.

At the moment it works, however if the component is to be deprecated the library should provide a path forward given the popularity of the routing library.

### What's the expected behaviour?

Reconsider the deprecation and/or provide guidance on how to use the `<Link>` component with the newer version of React Router Dom or how style a link using Amplify UI.

### Help us reproduce the bug!

Run `npm i react-router-dom` (v6.4.0) with the latest version of Amplify UI for React. Then create a link using the `<Link>` component from Amplify and pass a `href` prop.

Open the console & see the deprecation message:
![Uploading image.png…]()

### Code Snippet

```typescript
// Put your code below this line.
import React from "react";
import { useHref } from "react-router-dom";
import { Link as UiLink } from "@aws-amplify/ui-react";

export type MenuItemProps = {
  children?: React.ReactNode;
  to: string;
  label: string;
};

const MenuItem: React.FC<MenuItemProps> = ({ to, label }) => {
  const href = useHref(to);

  return (
      <UiLink href={href}>{label}</UiLink>
  );
};

export default MenuItem;
```

**Comment by dbanksdesign** [comment]
Thank you for bringing this to our attention. We will update our docs to reflect how the `Link` component in `react-router` works in v6.x. To answer your question though, you can use the `as` prop on the `Link` component in Amplify UI. I made a very simple demo to show this: https://stackblitz.com/edit/react-ts-fsk25s?file=index.tsx

**Comment by eriktim** [comment]
Thanks @dbanksdesign, the example works really well. Any change https://ui.docs.amplify.aws/react/components/link#routing-libraries will get updated as well?

**Comment by stepan-yudin-clearscale** [comment]
I agree w @eriktim , its definitely a time to update the docs
