### ISSUE TITLE
primitives(Flex): Event handlers for `Flex as="form"` are not typed properly

### ISSUE THREAD

**Issue by wlee221** [aws-amplify/amplify-ui#2891]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

CRA (TS)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Please describe your bug.

`onSubmit` handler isn' typed properly on `Flex as="form"` element.

Its `onSubmit` is typed as `FormEventHandler<HTMLDivElement>`, whereas it should be `FormEventHandler<HTMLFormElement>`.

### What's the expected behaviour?

(see above)

### Help us reproduce the bug!

https://codesandbox.io/s/recursing-bird-eewc0q?file=/src/App.tsx

**Comment by zchenwei** [comment]
This should be fixed in 5.x release.
