### ISSUE TITLE
Add hebrew translations

### ISSUE THREAD

**Issue by NivBraz** [aws-amplify/amplify-ui#2906]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Add Hebrew translations to authenticator

### Please describe a solution you'd like.

I have a PR for this new language

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
Thanks @NivBraz ! We'll take a look
