### ISSUE TITLE
Show Button Spinner When `isLoading` === true

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#2914]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

Currently, in order to show a spinner (no text) in `Button` to indicate loading, 2 props need to be set . `isLoading={true}` and `loadingText="Loading..."`. The docs below say that the spinner should still show if `loadingText` is not passed but this is not happening for me.

inline-intellisense docs:
>@description
The label to show in the button when loading is true If no text is passed, it only shows the spinner

### Please describe a solution you'd like.

See above.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by bestickley** [comment]
Actually, I think this should be a bug. I cannot change the label though.

**Comment by ErikCH** [comment]
Thanks @bestickley ! I'll take a look
