### ISSUE TITLE
Create a simple web application using AWS Amplify failing build due to geo/lib-esm error

### ISSUE THREAD

**Issue by rhyso** [aws-amplify/amplify-ui#2979]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Storage

### How is your app built?

Create react app

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

was playing around going through this AWS amplify tutorial (auth,S3, graphql setup)

https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-five/?e=gs2020&p=build-a-react-app-four

all working locally but fails CI (and local npm run build) due to the following error... any ideas boys and girls?

```
node_modules/@aws-amplify/geo/lib-esm/util.js: symbol.charCodeAt is not a function
    at Array.map (<anonymous>)
    at Array.forEach (<anonymous>)
```

running these versions :

    "@aws-amplify/ui-react": "^4.0.0",
    "aws-amplify": "^5.0.1",

### What's the expected behaviour?

The app to build correctly

### Help us reproduce the bug!

go through the demo https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-five/?e=gs2020&p=build-a-react-app-four

and the build doesnt pass due to the above error

### Code Snippet

```typescript
// Put your code below this line.
Creating an optimized production build...
Failed to compile.

./node_modules/@aws-amplify/geo/lib-esm/util.js
TypeError: /Users/ciaranthomas/code/sandbox/amplifyapp/amplifyapp/node_modules/@aws-amplify/geo/lib-esm/util.js: symbol.charCodeAt is not a function
    at Array.map (<anonymous>)
    at Array.forEach (<anonymous>)
```

**Comment by ioanabrooks** [comment]
Hi @rhyso,

Thank you for using amplify! To help us replicate the problem you discovered could you provide the `package.json` file for your project? Did you make any choices different from what is covered in the tutorial? I’m wondering if you used a package manager other than npm, or a different command than `npx create-react-app` to generate the project which might have a build system like Vite. And also what version of `create-react-app` did you use.

We’ll continue to look into this and any additional details you can provide would be very helpful.

**Comment by rhyso** [comment]
Hey Ioana - thanks for your swift response!

I think the only change I made was using npm instead of yarn when configuring the build settings.
I used  `create-react-app `v 3.4.1
Will attach my package.json here below also.

Many thanks

![image](https://user-images.githubusercontent.com/1149222/201911729-45bbecff-6559-4089-8f6b-9fc39e74eba0.png)

**Comment by rhyso** [comment]
Hey @ioanabrooks 
Your comments made me realise my node version was out of date, and I was using an old global version of create-react-app, so using npx instead picked up the right version when I ran through the tutorial again. All is good now. Thanks for your assistance
