### ISSUE TITLE
https://ui.docs.amplify.aws/react/legacy-components/chatbot[missing-page]

### ISSUE THREAD

**Issue by affanmirza1** [aws-amplify/amplify-ui#2987]
**Page**: [`https://ui.docs.amplify.aws/react/legacy-components/chatbot`](https://ui.docs.amplify.aws/react/legacy-components/chatbot)
**Feedback**:  Not working

**Comment by ioanabrooks** [comment]
Thanks @affanmirza1 for reporting this! Could you share where you found this broken link?
