### ISSUE TITLE
Error: The user is not authenticated

### ISSUE THREAD

**Issue by reeslabree** [aws-amplify/amplify-ui#2992]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-central-1:528185474776:apps/d213o5o0w1nmqu

### Region

eu-central-1

### Amplify Hosting feature

Access control

### Describe the bug

Can't use SSR on any pages - getting slammed with the "Error: The user is not authenticated" message.

This used to work locally - and after attempting to host on AWS works no more. I've walked back my commits to several points that I _know_ it was working at- and to no avail is this working again.

### Expected behavior

Normal application behavior.

### Reproduction steps

I wish I could provider reproduction steps -it seems as though the AWS mine tunnel has collapsed over the weekend and trapped my app in it.

### Additional information

I've tried:
- `amplify.configure` on each page
- `auth.configure` on each page
- checking for cookie storage (a common issue, but apparently my amplify backend environment doesn't use this anyways)
- in the _app.tsx: `export default withAuthenticator(myApp)`
- in every page.tsx: `export default withAuthenticator(page)`

**Comment by swaminator** [comment]
Transerring to Amplify UI as the issue is related to the Authenticator.

**Comment by reesscot** [comment]
@reeslabree Can you provide details of the `aws-amplify` version you are using? Also, are you using Next.js and React? If so, what versions of `@aws-amplify/ui-react` and Next.js are you using?

**Comment by reeslabree** [comment]
I think this issue resolved itself with Amplify support added for Next 12. I'll close.
