### ISSUE TITLE
Autocomplete field is broken

### ISSUE THREAD

**Issue by Alex-Github-Account** [aws-amplify/amplify-ui#3030]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Please describe your bug.

here is demo https://codesandbox.io/s/affectionate-bird-ssdsi5
I already mentoined this bug but got no attention
If you click autocomplete field - select options pops up (ok behavior)
then you select another window (not just defocus a field or select another tab, but entirely different OS window) - select options dissapear (ok)
then you try to click button right below autocomplete - NOPE. autocomplete select options poped up (who asked them?) and covered the button, thus user click lands on the autocomplete, not the button. This is intercepting user input! Facepalm 

### What's the expected behaviour?

When user clicks on something, nothing should appear right below cursor right before click out of nowhere

### Help us reproduce the bug!

I hope this works https://codesandbox.io/s/affectionate-bird-ssdsi5

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

screenshot will not help, need video.

**Comment by zchenwei** [comment]
@Alex-Github-Account, thanks for reporting those and I can see the behavior on my end. I think this is a browser behavior(unfocus the entire window and then click back, the focus will go back to the input field), not a specific component bug. You can try this behavior with a native `<input type="text" />`, the focus will go back to that input as well

**Comment by Alex-Github-Account** [comment]
nope. Browser built-in "input with autocomplete"  will not re-popup it's options on window been re-focused.  And for sure nothing will pop up right before user click right below cursor. Try it yourself:
`Default HTML component works flawlessly:
<label for="favorite_team">Favorite Team:</label>
<input type="text" name="team" id="favorite_team" list="team_list">
<datalist id="team_list">
  <option>Detroit Lions</option>
  <option>Detroit Pistons</option>
  <option>Detroit Red Wings</option>
  <option>Detroit Tigers</option>
  
</datalist>`
Also component onChange behaviour is not consistent with other amplifi-ui components - it passes event as parameter, not changed value as other components do. 
Your downplaying of the bugs does not add points to you **:)**

**Comment by zchenwei** [comment]
> nope. Browser built-in "input with autocomplete" will not re-popup it's options on window been re-focused. And for sure nothing will pop up right before user click right below cursor. Try it yourself: Default HTML component works flawlessly: <label for="favorite_team">Favorite Team:</label> <input type="text" name="team" id="favorite_team" list="team_list"> <datalist id="team_list"> <option>Detroit Lions</option> <option>Detroit Pistons</option> <option>Detroit Red Wings</option> <option>Detroit Tigers</option>  </datalist> Also component onChange behaviour is not consistent with other amplifi-ui components - it passes event as parameter, not changed value as other components do. Your downplaying of the bugs does not add points to you **:)**

Right, I am just mentioning about the same focus behavior. Of course we will address the menu issue, currently the open behavior is bound to focus event.
