### ISSUE TITLE
Autocomplete field events are unconsistent with other components events

### ISSUE THREAD

**Issue by Alex-Github-Account** [aws-amplify/amplify-ui#3035]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Please describe your bug.

on the https://ui.docs.amplify.aws/react/components/autocomplete
autocomplete's onChange passes event to handler
while other components, for example  
https://ui.docs.amplify.aws/react/components/sliderfield
passes new (changed) value to the onChange event handler
this dissalows usage of single onChange event handler for all the form fields, since value passed is unconsistant

### What's the expected behaviour?

If we build a library of unified components, their behaviour  should be at least consistant

### Help us reproduce the bug!

set onChange handler to the autocomplete component
then re-use this handler for the slider component - this would fail

### Code Snippet

```typescript
function log(smth){
console.log(smth.target.value)
}
<Autocomplete onChange={log}
<Slider onChange={log} //will fail

```

**Comment by zchenwei** [comment]
Thanks for opening this issue. Yeah, we should think about how to unify those to provide a better experience. Currently all text input components(`TextFIeld`, `SearchField`, `Autocomplete` etc.) takes in an event, while the `SliderField` is a bit special, it is a custom one and not emit a native change event so it return the updated value.
