### ISSUE TITLE
Checkbox shows pointer cursor when disabled

### ISSUE THREAD

**Issue by cwoolum** [aws-amplify/amplify-ui#3037]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

If you are using a checkbox and disable it, the incorrect cursor is shown that implies that is is still clickable.

![image](https://user-images.githubusercontent.com/942415/203119439-be883a65-e5be-45d2-896d-83f44a026461.png)

### What's the expected behaviour?

The checkbox should no longer use a pointer cursor so there is no confusion.

### Help us reproduce the bug!

See the code snippet below

### Code Snippet

```html

 <CheckboxField
      checked={item.showOnDashboard ?? false}
      label={""}
      name={""}
      value={""}
      disabled
    ></CheckboxField>
```

```


### Additional information and screenshots

```
"@aws-amplify/ui-react": "^4.0.0"
```

**Comment by joebuono** [comment]
Confirmed with customer offline that the above suggestion fixed the issue.
