### ISSUE TITLE
Chatbot component

### ISSUE THREAD

**Issue by adlershai** [aws-amplify/amplify-ui#3065]
**Which Specific Feature is your question related to?**
Interaction
I couldn't find any document or reference on how to add the Chatbot component
Was it removed? 

**Provide additional details e.g. code snippets**

**Comment by calebpollman** [comment]
Hi @adlershai! As mentioned above, the `AmplifyChatbot` component has been deprecated and is no longer documented, although you can still find the component [here](https://github.com/aws-amplify/amplify-js/blob/v4-stable/packages/amplify-ui-components/src/components/amplify-chatbot/readme.md)
