### ISSUE TITLE
Missing Localisation / Translation / Internationalisation is a breaking change

### ISSUE THREAD

**Issue by AndreasEK** [aws-amplify/amplify-ui#307]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Environment information

<details>

npx: Installierte 1 in 1.793s

  System:

>     OS: macOS 11.4
>     CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
>     Memory: 249.65 MB / 32.00 GB
>     Shell: 5.8 - /bin/zsh

  Binaries:

>     Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
>     npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm

  Browsers:

>     Chrome: 92.0.4515.159
>     Firefox: 91.0.1
>     Safari: 14.1.1

  npmGlobalPackages:

>     @aws-amplify/cli: 5.2.1
>     npm-check-updates: 11.7.1
>     npm: 6.14.12
>     serve: 12.0.0

</details>

### Describe the bug

When migrating from `aws-amplify-react` to `@aws-amplify/ui-react` I expected the replacement to be a drop-in exchange of components. 

I was surprised that the standard Authenticator dialogs were no longer localized (to German), and was wondering, if I made something wrong, when I was greeted with an "all english" UI experience.

The [documentation](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#breaking-changes-for-withauthenticator) describes, that some properties were deprecated, however the link to the [updated list of properties leads](https://docs.amplify.aws/ui/auth/authenticator.md/q/framework/react/#props-attr-amplify-authenticator/q/framework/react) to a 404, so I was unsure if I should inject the locale to the ui component somehow. 

After digging through some related issues, I just would like to emphasize that this *is a breaking change* for any ui component. It's not nice to have. If it has been localized before, it should still be localized. So at the very least, this bug is about the documentation, to make it easier for people to find out. 

As I understood, now *every* developer is expected to translate the strings by themselves, is that correct?

1. Use the [Amplify I18n component to putVocabulariesForLanguage](https://docs.amplify.aws/ui/customization/translations/q/framework/react/).
2.  Make sure you don't miss any of the necessary [Translations](https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/common/Translations.ts).
3. And while doing so, you can take a look at the [old translations from `aws-amplify-react`](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/AmplifyI18n.tsx), so you don't have to re-invent everything from scratch. 

If somebody could please confirm that breaking change, and the approach to take for every single developer with non-english speaking users, I'd be very grateful. 

### Expected behavior

`Authenticator` and `withAuthenticator` should still show localised dialogs by default. 

### Reproduction steps

1. npm uninstall aws-amplify-react
2. npm install @aws-amplify/ui-react

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by Milan-Shah** [comment]
@AndreasEK As @ericclemmons mentioned above, we have released a new major version of @aws-amplify/ui-react@2.1.0 which has a better support for internationalization and localization. You can learn more about our new [Authenticator UI component](https://ui.docs.amplify.aws/components/authenticator).If you have any suggestions or improvements our team can make to better enhance customer experience, please let us know!  We are here to help :)
