### ISSUE TITLE
Figma variants not working

### ISSUE THREAD

**Issue by matart15** [aws-amplify/amplify-ui#3093]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

react vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

This is my figma file.

![Screenshot 2022-11-27 at 21 12 31](https://user-images.githubusercontent.com/17027219/204134819-bd79f77b-fe62-4996-be20-48941a89ffd4.png)

IconButton component created. But even type="link", Amplify always render default.

this is amplify Admin UI

<img width="1096" alt="Screenshot 2022-11-27 at 21 18 46" src="https://user-images.githubusercontent.com/17027219/204134860-b3f16d58-7542-451a-bbf3-80f700e962f5.png">

this is react rendered ui
<img width="817" alt="Screenshot 2022-11-27 at 21 19 16" src="https://user-images.githubusercontent.com/17027219/204134875-4cb598dd-7b54-4f89-bd1b-aac9b9f3adf7.png">

### What's the expected behaviour?

type="link" to display link button

### Help us reproduce the bug!

just create empty amplify UI project and Fignma component with 2 variants

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

I added few console logs inside created component. 
![Screenshot 2022-11-27 at 21 21 04](https://user-images.githubusercontent.com/17027219/204134930-dfa957af-a644-4f1d-8eed-66f18f3798ed.png)

this is result
<img width="579" alt="Screenshot 2022-11-27 at 21 21 33" src="https://user-images.githubusercontent.com/17027219/204134949-e4466152-d00f-46e5-bc30-f2a814f627f1.png">

I think `getOverridesFromVariants` is not working

What the hell is [this code](https://github.com/aws-amplify/amplify-ui/blob/6dad658381/packages/react/src/studio/getOverridesFromVariants.ts) doing

**Comment by matart15** [comment]
I run this code.
```js
const props = { type: "link" }
const variants = [
  {
    overrides: {
      "Button Icon34623450": {},
      label: {},
      "Button Icon34623452": {},
      Button: {},
      IconButton: {},
    },
    variantValues: { type: "primary" },
  },
  {
    overrides: {
      "Button Icon34623450": {},
      label: {},
      "Button Icon34623452": {},
      Button: {},
      IconButton: {},
    },
    variantValues: { type: "link" },
  },
];

const variantValueKeys = [
  ...new Set(
    variants.flatMap((variant) => Object.keys(variant.variantValues))
  ),
];
console.log('variantValueKeys: ', variantValueKeys);

const variantValuesFromProps = Object.keys(props)
  .filter((i) => variantValueKeys.includes(i) && props[i])
  .reduce((acc, key) => {
    acc[key] = props[key];
    return acc;
  }, {});
console.log('variantValuesFromProps: ', variantValuesFromProps);

const matchedVariants = variants.filter(({ variantValues }) => {
  return (
    Object.keys(variantValues).length ===
    Object.keys(variantValuesFromProps).length &&
    Object.entries(variantValues).every(
      ([key, value]) => variantValuesFromProps[key] === value
    )
  );
});
console.log('matchedVariants: ', matchedVariants);

const result = matchedVariants.reduce((overrides, variant) => {
  console.log('overrides, variant: ', { overrides, variant });
  console.log('merge: ', { ...overrides, ...variant.overrides });
  return { ...overrides, ...variant.overrides };
}, {});

console.log('result: ', result);
```

this is the result
<img width="570" alt="Screenshot 2022-11-27 at 21 34 42" src="https://user-images.githubusercontent.com/17027219/204135442-44b8c478-4671-4a3d-b853-5b5737b529bf.png">

I am not sure what this code should return, Since it is finding the matchedVariants, maybe that merge part have some problem

**Comment by matart15** [comment]
Hope this hels and fix bug soon

**Comment by dbanksdesign** [comment]
@matart15 would you be able to post a link to the Figma file that is causing this issue?

**Comment by matart15** [comment]
Right. You need Figma file to debug this.

But Sorry. It is company job. I can't share it outside organization. 

I wil recreate issue with Public figma. If it happens. 

We were in hurry and manually overrided the created component.

For now, I am closing the issue.

**Comment by awinberg-aws** [comment]
Hi @matart15, I would still like to get to the bottom of this issue as manually overriding the generated component creates unnecessary work for your team since your overrides will continually need restoration after each pull. I understand the proprietary nature of working with internal designs and your inability to share the entirety of your figma file but if your company will allow it, just copying the IconButton and BreadCrumbs components shown in your screenshots to a new file for sharing should be enough to help us reproduce the issue and work on a proper fix.

**Comment by matart15** [comment]
@awinberg-aws  thank you. I will ask my manager
