### ISSUE TITLE
Add password validations for reset password screen

### ISSUE THREAD

**Issue by Swastik-achar** [aws-amplify/amplify-ui#3130]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Add password validations to the reset password screen similar to what we have in signup screen.

### We love contributors! Is this something you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by s-nikhil** [comment]
Hi @Swastik-achar , are you able to show password requirements while typing/ onBlur event on password field of Sigup page?
If yes, can you please help what i might be missing here.

**Comment by Swastik-achar** [comment]
> Hi @Swastik-achar , are you able to show password requirements while typing/ onBlur event on password field of Sigup page? If yes, can you please help what i might be missing here.

Try adding "aws_cognito_password_protection_settings" in your aws-exports

**Comment by reesscot** [comment]
This password validation logic appears to be missing on the forgot password screen as well.

**Comment by adi-ads** [comment]
@reesscot forgot password and reset password are the same screen aren't they? So PR #3158 should fix that or there is still another screen missing after the fix in the PR above as well?

**Comment by wlee221** [comment]
There are two different password reset screens: "force-new-password", and "reset-password" (ie. forgot password"). That said, #3158 is addressing both!

**Comment by reesscot** [comment]
Fixed by https://github.com/aws-amplify/amplify-ui/pull/3158
