### ISSUE TITLE
Change file names in the FileUploader component

### ISSUE THREAD

**Issue by wbrijesh** [aws-amplify/amplify-ui#3135]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Storage

### Please describe your feature-request in detail.

I would like to change file names before uploading them when using the FileUploader, I know I use the Storage function from amplify to do this but I want to use the prebuilt component

### Please describe a solution you'd like.

add another prop to FileUploader component which will let me change the files name

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
Hi @wbrijesh !

Thanks for using the FileUploader component! You can change the file before updating it. With the `pencil` icon.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/65630/205706726-1879c16e-5581-4868-84f5-af4fc09a2d97.png">

Click that icon and you can save a new name for the file. Can you try that? We don't have a prop though, that's something we can look into!

**Comment by reesscot** [comment]
@wbrijesh What is your particular use case? Are you looking to programmatically change the file name that customers specify somehow?

**Comment by luisbstudio** [comment]
@ErikCH @reesscot I have the same request. I would use FileUploader if I could (1) specify a file name and (2) specify a path within s3 where the file will upload. In terms of the file name, different customers may upload different (unique) files with the same file name. I need to assign a unique identifier as the file name before upload to prevent files from getting overridden. In terms of s3 path, the current level (i.e., public, private, etc) is not enough. I need to specify a subfolder within "public" in s3 where the file should upload (e.g., "public/imageUploads/")

**Comment by Nelsonindohaa** [comment]
Our particular problem we cant remove spaces in uploaded file name.

**Comment by brianlenz** [comment]
I created #3442 as a discussion starter for a possible implementation to address this...

**Comment by reesscot** [comment]
We released a new version of the FileUploader, now called the StorageManager, which has the full `processFile` functionality for you to programmatically change file keys before upload (or change file contents too): https://ui.docs.amplify.aws/react/connected-components/storage/storagemanager#pre-upload-processing

Check it out and let us know if this works for your use cases! We are publishing this new component from a new package so you will need to get the @aws-amplify/ui-react-storage package
