### ISSUE TITLE
Use FileUploader without Amplify CLI Backend

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#3148]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Storage

### Please describe your feature-request in detail.

Currently, the File Uploader component requires use of the Amplify CLI to setup storage and authentication. I'd like to use the component with my CDK app and use my separate API Gateway-Lambda backend to authenticate. I don't think the current File Uploader allows me to do this. Could this be supported?

### Please describe a solution you'd like.

File Uploader component that doesn't require Amplify CLI backend setup.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
You can use the File Uploader without the CLI. Please use these instructions to create your own `aws-exports` file you can pass into `Amplify.configure` https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#scoped-configuration

**Comment by bestickley** [comment]
Thanks, @ErikCH!
