### ISSUE TITLE
How to handle when the user cancels the auth?

### ISSUE THREAD

**Issue by therealtgd** [aws-amplify/amplify-ui#3152]
When the user cancels the login the `openAuth` method returns `type = cancel ` which isn't that helpful to me. I tried throwing an error when the `openAuth` returns cancel, but I can't catch it since the `urlOpener` is called within aws, and not manually by me. Because of that, I can't just use `try/catch`.

Here is the `urlOpener`.
```
const urlOpener = async (url, redirectUrl, settings) => {
  try {
    if (await InAppBrowser.isAvailable()) {
      const { type, url: newUrl } = await InAppBrowser.openAuth(
        url,
        redirectUrl,
        { ...inAppBrowserSettings, ...settings },
      );
      if (type === 'success') {
        Linking.openURL(newUrl);
      } else if (type === 'cancel' {
        throw new Error('Auth canceled');
      }
    } else {
      Linking.openURL(url);
    }
  } catch (error) {
    Alert.alert(error.message);
  }
};
```

So my question is how should I handle this scenario?

**Comment by ErikCH** [comment]
Hello @therealtgd ! Can you tell me a little more on the scenario you are using? Is this React native and are you using our aws amplify library?
