### ISSUE TITLE
React Native Authenticator - federatedSIgnIn succedes but Authenticator children components are not shown 

### ISSUE THREAD

**Issue by andreav** [aws-amplify/amplify-ui#3184]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome, Android (React Native)

### Please describe your bug.

I'm trying the new react native Authenticator component on Android.
I have an aws amplify project + auth category + social login google & facebook

I can login with internal (cognito) users without any problem.
After logging in, Authenticator shows its children components.
Everything is ok.

If I try federatedSignIn (both google & facebook) the flow works but Authenticator does not show its children components. (I continue seeing the SIgnIn Screen)
I know I'm logged in, because if I refresh the app while debugging (pressing 'r' button on metro console) the app reloads and right content is shown (i.e. Authenticator children components)

I tried federatedSignIn both with Chrome and with react-native-inappbrowser-reborn (as suggested [in amplify documentation](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples)  but the behaviour is the same.

I tried with DEBUG logs (putting window.LOG_LEVEL = 'DEBUG'; in my index.js) but I do not see any error.

### What's the expected behaviour?

After logging in after returning from federatedSIgnIn, Authenticator shows its children components

### Help us reproduce the bug!

Create a component like in the code snippet, try to login with Cognito and with FederatedSIgnIn
After logging with Cognito User,  LoginScreen is reaplced by Authenticator children components
After logging with federatedSignIn the screen does not change (always seeing LoginScreen)
If refreshing the app (button 'r' in metro console) LoginScreen is reaplced by Authenticator children components
 

### Code Snippet

```typescript

function SignOutButton() {
  const {signOut} = useAuthenticator();
  return <Button onPress={signOut} title="Sign Out" />;
}

function MySignInHeader() {
  return (
    <>
      <Button title="Open Hosted UI" onPress={() => Auth.federatedSignIn()} />
      <Button
        title="SingIn Google"
        onPress={() =>
          Auth.federatedSignIn({
            provider: CognitoHostedUIIdentityProvider.Google,
          })
        }
      />
      <Button
        title="SingIn Facebook"
        onPress={() =>
          Auth.federatedSignIn({
            provider: CognitoHostedUIIdentityProvider.Facebook,
          })
        }
      />
    </>
  );
}

const AuthenticatorTest = () => {
  return (
    <>
      <Text style={{color: 'black', marginTop: 100}}>
        This text is always visible
      </Text>
      <Authenticator
        components={{
          SignIn: props => (
            // will render only on the SignIn subcomponent
            <Authenticator.SignIn {...props} Header={MySignInHeader} />
          ),
        }}>
        <Text style={{color: 'black'}}>
          This text is visible ONLY when I'm logged
        </Text>
        <SignOutButton />
      </Authenticator>
    </>
  );
};

export default AuthenticatorTest;
```

### Additional information and screenshots

  "dependencies": {
    "@aws-amplify/ui-react-native": "^1.1.4",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/checkbox": "^0.5.13",
    "@react-native-community/netinfo": "^9.3.0",
    "@react-native-picker/picker": "^2.4.4",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "amazon-cognito-identity-js": "^5.2.10",
    "aws-amplify": "^5.0.6",
    "fastestsmallesttextencoderdecoder": "^1.0.22",
    "link": "^1.5.1",
    "react": "18.1.0",
    "react-error-boundary": "^3.1.4",
    "react-native": "^0.70.4",
    "react-native-animatable": "^1.3.3",
    "react-native-bootsplash": "^4.3.2",
    "react-native-countdown-circle-timer": "^3.0.9",
    "react-native-device-info": "^10.3.0",
    "react-native-exception-handler": "^2.10.10",
    "react-native-get-random-values": "^1.8.0",
    "react-native-localization": "^2.3.1",
    "react-native-localize": "^2.2.4",
    "react-native-modal": "^13.0.1",
    "react-native-popup-menu": "^0.16.1",
    "react-native-ratings": "^8.1.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.17.0",
    "react-native-sound": "^0.11.2",
    "react-native-svg": "^13.4.0",
    "react-native-toast-notifications": "^3.3.1",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-vision-camera": "^2.15.2",
    "react-native-webview": "^11.23.1"
  },
  "devDependencies": {
    "@aws-amplify/cli-extensibility-helper": "^2.4.5",
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.24",
    "@types/react-native": "^0.69.9",
    "@types/react-native-vector-icons": "^6.4.12",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.36.2",
    "@typescript-eslint/parser": "^5.36.2",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.72.1",
    "react-native-svg-app-icon": "^0.6.1",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  },

**Comment by ioanabrooks** [comment]
Hi @andreav, thanks for trying out our React Native components!

The `Header` component currently accepts only text props for customization, please see the documentation for customizing Authenticator sub-components [here](https://ui.docs.amplify.aws/react-native/connected-components/authenticator/customization).  Adding social providers to sign in/sign up screens is on our roadmap, stay tuned!

**Comment by andreav** [comment]
Well, I got it working (with still one problem, but working).

My previous error was related to a deep link misconifguration.
I'm using [react navigation](https://reactnavigation.org/) for routing.
I had to correctly configure [deep linking](https://reactnavigation.org/docs/5.x/deep-linking) in order to have redirect after  federatedSIgnIn working.

Here my working code.

Autenticator Test component:

```tsx
const AuthenticatorTest = () => {
  return (
    <>
      <Text style={{color: 'black', marginTop: 100}}>
        This text is always visible
      </Text>
      <Authenticator.Provider>
        <Authenticator
          // formFields={formFields}
          services={services}
          components={{
            SignIn: ({fields, ...props}) => (
              <>
                <FederatedProviderButtons
                  socialProviders={['google', 'facebook']}
                  toFederatedSignIn={provider => {
                    Auth.federatedSignIn({
                      provider:
                        provider.provider === 'google'
                          ? CognitoHostedUIIdentityProvider.Google
                          : CognitoHostedUIIdentityProvider.Facebook,
                    });
                  }}
                />

                <Authenticator.SignIn
                  {...props}
                  fields={fields.map(field => ({...field, isRequired: true}))}
                  Header={() => {}}
                />
              </>
            ),
          }}>
          <Text style={{color: 'black'}}>
            This text is visible ONLY when I'm logged
          </Text>
          <SignOutButton />
        </Authenticator>
      </Authenticator.Provider>
    </>
  );
};
```
  
I had to correctly configure Cognito redirect URLs. 
From aws-export.js:

```js
    redirectSignIn: 'myurl://startScreen',
    redirectSignOut: 'myurl://startScreen', 
```

Now the user can login successfully from this Test Page with federated identity and see the startScreen!

Thank you!
