### ISSUE TITLE
Module '"@aws-amplify/ui-react"' has no exported member 'AccountSettings'.

### ISSUE THREAD

**Issue by Alan-DeBell** [aws-amplify/amplify-ui#3191]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

Unable to load module 'AccountSetting' from @aws-amplify/ui-react and get the following error

Module '"@aws-amplify/ui-react"' has no exported member 'AccountSettings'.

### What's the expected behaviour?

Need to render

<AccountSettings.ChangePassword />

### Help us reproduce the bug!

refer to https://ui.docs.amplify.aws/react/connected-components/account-settings/change-password

### Code Snippet

```typescript
// Put your code below this line.

```
import { AccountSettings } from '@aws-amplify/ui-react';
const Security = () => {
return (
<AccountSettings.ChangePassword />
)
}

**Comment by reesscot** [comment]
@Alan-DeBell What version of `@aws-amplify/ui-react` do you have in your settings? The AccountSettings component was available as of 4.2.0. Please try upgrading to latest verision:
```bash
npm install @aws-amplify/ui-react@latest
```

**Comment by reesscot** [comment]
Validated that the following import is error free in `@aws-amplify/ui-react` version `4.2.0`
```
import { AccountSettings } from "@aws-amplify/ui-react";
```

**Comment by reesscot** [comment]
@Alan-DeBell Please reopen this ticket if you are still having this issue after upgrading your version.
