### ISSUE TITLE
FileUploader progress stays at "Uploading" for file with size 0

### ISSUE THREAD

**Issue by schana** [aws-amplify/amplify-ui#3195]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Storage (File Uploader)

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

When uploading a file with size 0, like an `__init__.py`, the progress never finishes, even though the file is successfully uploaded to S3.

### What's the expected behaviour?

The UI to display finished when the upload is complete.

### Help us reproduce the bug!

Use the component to upload a file with size 0.

### Code Snippet

```javascript
<FileUploader
  accessLevel="private"
  variation="drop"
  acceptedFileTypes={[".py"]}
  maxFiles={20}
  maxSize={10000}
/>
```

**Comment by ErikCH** [comment]
Thanks for opening this @schana ! I'll look at it!

**Comment by reesscot** [comment]
I was able to reproduce this:
![CleanShot 2022-12-20 at 16 31 51](https://user-images.githubusercontent.com/6165315/208786074-8fc39d90-ec66-4a98-b4d0-a70b1fac4558.gif)

**Comment by ErikCH** [comment]
Hi @schana ! My fix has been merged. It should be in the next major release. Or you can install it now using our `@aws-amplify/ui-react@next` tag

**Comment by ErikCH** [comment]
Please reopen if you have issues.
