### ISSUE TITLE
Client Side Weak Password Validation Not Showing With Angular <amplify-authenticator> Component When Not Using the Amplify CLI.

### ISSUE THREAD

**Issue by ustadji** [aws-amplify/amplify-ui#3196]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Create Angular App

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

According to this article: https://aws.amazon.com/blogs/mobile/8-new-features-in-the-amplify-authenticator-for-web-you-should-try/  where it talks about the authenticator being equipped with password validation out of the box., we’re using the Angular authenticator but I don't see the built in client side password strength support validation pre-emptively kicking in during the signup process.  This means that a user can enter a password that will fail validation but the user won’t receive any immediate feedback as the article suggests is part of the pre-built components.   Instead, a submission is required which will provide the user with a generic password failure message.  Even if I wanted to retrieve our pool’s password policy via API, its part of the user pool set of APIs which are not exposed directly within the Authenticator Service so having it baked in to the prebuilt component is great but just not working.
Because I've already setup and configured my pool, I'm not using the cli.  Instead, I'm making an explicit call to configure().  I’m hoping there is a property here that needs to be set to get what we’re after?
```
Amplify.configure({
  Auth: {
    region: environment.region, //ca-central-1
    userPoolId: environment.userPoolId, //ca-central-1_xxxxxxxx
    userPoolWebClientId: environment.userPoolWebClientId, //4cxxxxxxxxxxxxxxxxx
  })

```

Here is a snippet from my Angular component html:
```
 <amplify-authenticator [loginMechanisms]="['email']"
                         [signUpAttributes]="['family_name', 'given_name']"
                         [formFields]="formFields">
    <ng-template amplifySlot="header">
      <div style="text-align: center">
        <img class="myclass"
             alt="My logo"
             src="/assets/images/mylogo.png" />
      </div>
    </ng-template>
  </amplify-authenticator>

<div *ngIf="authenticatorService.authStatus === 'authenticated'">
  <app-home></app-home>
</div>
```

We’ve gone through all the documentation we could possibly find available on the AWS docs as well as ofcourse sources like SO… couldn’t find the answers to the above…

### What's the expected behaviour?

Password validation as defined in the pool should kick in on the client without having to submit to the Cognito service for server side validation.

### Help us reproduce the bug!

Fire up an Angular project as per my package.json below (NOT using the cli to configure), reproduce it by putting in a weak password and say, "by golly, he's right!"
As you can see in the screenshot, weak passwords are inputted, focus is off the fields but no weak password validation shown.  Note the only validation that _does show_ is when passwords don't match.

![image](https://user-images.githubusercontent.com/8106888/208719542-8e4d4a2d-6c83-4cec-8226-01ac472b0dad.png)

### Code Snippet

Below is from my packages.json.  Also note that I’m not using the Amplify cli to manage the configuration, and as such I don’t have an aws-exports.js file generated.

```typescript
// Put your code below this line.
"dependencies": {
    "@angular-devkit/architect": "^0.1500.0",
    "@angular-devkit/core": "^15.0.0",
    "@angular/animations": "~15.0.0",
    "@angular/cdk": "^15.0.0",
    "@angular/common": "~15.0.0",
    "@angular/compiler": "~15.0.0",
    "@angular/core": "~15.0.0",
    "@angular/forms": "~15.0.0",
    "@angular/material": "^15.0.0",
    "@angular/platform-browser": "~15.0.0",
    "@angular/platform-browser-dynamic": "~15.0.0",
    "@angular/router": "~15.0.0",
    "@aws-amplify/ui-angular": "^3.1.2",
    "aws-amplify": "^5.0.4",
    "rxjs": "^7.5.7",
    "tslib": "^2.2.0",
    "zone.js": "^0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.0",
    "@angular/cli": "^15.0.0",
    "@angular/compiler-cli": "~15.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "graphql": "^15.5.1",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "^4.8.2"
  }

```

**Comment by wlee221** [comment]
Hi @ustadji! So yes, it needs an explicit config. You can use Amplify CLI to autogenerate it, but if not, you can add these to your config:

```
{
   // ...
   "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
}
```
I'll also bring this up to the team and see if this can be a docs improvement.

**Comment by ustadji** [comment]
Hi @wlee221 thanks so much for the quick turn around....I just tried it but I still don't see the client validation coming in:
Here's a snippet from my modified call to configure made within my app.module.ts:

```
Amplify.configure({
  Auth: {
    region: environment.region,

    userPoolId: environment.userPoolId,

    userPoolWebClientId: environment.userPoolWebClientId,

    aws_cognito_password_protection_settings: {
      passwordPolicyMinLength: 8,
      passwordPolicyCharacters: [
        'REQUIRES_LOWERCASE',
        'REQUIRES_NUMBERS',
        'REQUIRES_SYMBOLS',
        'REQUIRES_UPPERCASE'
      ]
    }),

```

Do you see any issues with the above?  Also, I'm not using the cli as I already setup everything manually with the console and I couldn't really see how I can segregate test from production.  As you can see from above, I make references to environment variables so that when my Angular app is built, values can be resolved at build time.   Given my setup, should I be using the cli exclusively to generate the aws-exports.js?  How are values resolved at build time for dev/prod?

Thank you!

**Comment by wlee221** [comment]
Oh, `aws_congito_password_protection_settings` should be at the very top level of your `Amplify.configure()` object.

**Comment by wlee221** [comment]
For testing, you can create a sandbox AWS account and create resources on it with Amplify CLI, so that your production environment is not affected. 

If you're just write unit tests, mocking related Amplify JS APIs can work, but is not trivial. For integration or e2e tests, I suggest having a sandbox AWS account.

**Comment by ustadji** [comment]
Hey @wlee221 thanks for the quick update!  So I modified my config object as suggested to place the password settings as a top level element and it worked!:

```
Amplify.configure({
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      'REQUIRES_LOWERCASE',
      'REQUIRES_NUMBERS',
      'REQUIRES_SYMBOLS',
      'REQUIRES_UPPERCASE'
    ]
  },
  Auth: {
  .......
  }
```

I'm not sure I understood how I can segregate the dev/prod aws-exports file and have it resolve at build time from your explanation... its likely my lack of understanding.  In any event, so how can those who don't use the cli like me get an exhaustive list of the schema for the config object - in particular for authorization?  Can the docs be kept up to date?  I tried looking through the code but the config object is not strictly typed (type is 'any').
Thank you!
Hanif

**Comment by wlee221** [comment]
Hi! Sample configuration is available at https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource. That plus `aws_cognito_password_protection_settings` would be enough to operate Authenticator. And yes, type isn't available for those config -- I'd consider opening a feature issue on Amplify JS [repo](https://github.com/aws-amplify/amplify-js).

**Comment by ustadji** [comment]
Thanks @wlee221 , that is the documentation I had to refer to in order to construct my config object but as you noted in your earlier answer, the password policy definition maybe be a gap in the docs - perhaps you could suggest the update to the docs team?   I will also open a feature issue for the strong typing as you suggested.
Thanks for your prompt responses and help!

**Comment by wlee221** [comment]
Cool! Let me close this issue since the original issue is resolved, but I will bring this up to the docs team (I created an internal task to track).
