### ISSUE TITLE
Customize "Confirm TOTP" page

### ISSUE THREAD

**Issue by KMV-7** [aws-amplify/amplify-ui#3224]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Hello,

I am using Amplify for our react application. Currently, our users enter their username and password and then are:

- being prompted to setup MFA (Authentication App or SMS) if they don't have an active MFA
- being prompted to enter the code from their MFA in order to complete the login process

The second bullet option is where we have a problem. The user is presented with a modal which says "Confirm TOTP code" but we would like to make it more user-friendly by customizing the message, such as "Please enter your code".
Sadly, I haven't found a way to do so.

### Please describe a solution you'd like.

Please provide a way to customize the message when the user is prompted for his MFA code. This is not about the initial MFA setup but for the usage of the MFA at every login after that.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@KMV-7 You can do this using the Internationalization feature:
https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#internationalization-i18n

```
import { I18n } from 'aws-amplify';
import { translations } from '@aws-amplify/ui-react';
I18n.putVocabularies(translations);
I18n.putVocabularies({
  en: {
    'Confirm TOTP code': 'Please enter your code',
  },
});
```

**Comment by KMV-7** [comment]
@reesscot I wouldn't have thought to mutate the message through the internalization. It seems a bit like a workaround but works flawlessly ;)

**Comment by KMV-7** [comment]
@reesscot I have another question: wouldn't it be nice to give control over the components customization? For example, the modal that asks you for the code has up and down arrows. With the arrow you can enter a negative number, which is not an issue but is "bad taste" for a modern web app. It would be good if devs could remove the existence of those arrows, for example.
I can open another ticket but just wanted to ask you first if it is worth it, or maybe this level of customization exists already but I haven't found it in the docs ad the code.
![image](https://user-images.githubusercontent.com/94992793/209402806-6a1e8679-bfb2-4855-a582-e8a43d0781af.png)

**Comment by reesscot** [comment]
Hi @KMV-7,
The reason the arrows are there is because in HTML that field is `<input type="number">`. I confirmed that you can change the field type to `text` via the FormFields API, which removes the arrows.

```
const formFields = {
  confirmSignUp: {
    confirmation_code: {
      type: "text"
    },
  },
}

export default function App() {
  return (
    <Authenticator formFields={formFields}>
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user.username}</h1>
          <button onClick={signOut}>Sign out</button>
        </main>
      )}
    </Authenticator>
  );
}
```
![image](https://user-images.githubusercontent.com/6165315/209406780-67421988-5f41-4bd5-bbfe-c8cf1b00e302.png)

I don't think it makes sense to have that field default to a number type, since there's no use case where you would want to go up or down on a confirmation code. Can you please open a separate bug to change the default for this?

**Comment by KMV-7** [comment]
@reesscot Alright, thank you very much! My use case required to use confirmSignIn.
Thank you very much for the quick responses, you ve helped me a lot.

**Comment by nikronys** [comment]
The property name has changed to "Confirm TOTP Code".
