### ISSUE TITLE
React Native Authenticator - SingUp form hiding field

### ISSUE THREAD

**Issue by andreav** [aws-amplify/amplify-ui#3228]
### On which framework/platform would you like to see this feature implemented?

React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I would like to hide a field from SIngUp form.

In my use case, I added "Name" attribute during SIgnUp just for retrieving it from Identity Providers like Google or Facebook (please see [this issue](https://github.com/aws-amplify/amplify-cli/issues/11646) for more informations)

This let me retrieve user name from Identity Providers like Google or Facebook.
However now I have a new "Name" field in SignUp form (as expected) for Cognito Users.
I would like to hide this field in SingUp form because I'm using "UserName" login and so the form already has a "UserName" field. Having also a "Name" field could be confusing to new Users.
(Maybe I could also write a [Service](https://ui.docs.amplify.aws/react-native/connected-components/authenticator/customization#override-function-calls) on the Authenticator that copies "Username" into "Name" field during SignUp)

Thank you.

### Please describe a solution you'd like.

A field param like "isRequired" & co, named for instance: "hidden"

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment]
@andreav You can target and filter out a field passed to the `SignUp` subcomponent to avoid rendering it by overriding the `fields` prop of `Authenticator.SignUp`:
```
<Authenticator
  components={{
    SignUp: ({ fields, ...props }) => (
      <Authenticator.SignUp
        {...props}
        // replace `Name` with the field you would like to filter
        fields={fields.filter((field) => field.name === 'Name')}
      />
    ),
  }}
>
  <MyApp />
</Authenticator>
```

Let us know if that helps!

**Comment by andreav** [comment]
It works perfectly, thank you!

In my case a filtered out "name" field like this:

```js
fields={fields.filter(f => f.name !== 'name')}
```
