### ISSUE TITLE
React Native Authenticator - exporting FederatedProviderButtons

### ISSUE THREAD

**Issue by andreav** [aws-amplify/amplify-ui#3229]
### On which framework/platform would you like to see this feature implemented?

React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I'm using `FederatedProviderButtons` component and it works very well, however it seems not to be exported explicitly from the library.

When I import it from VSCode inside a react-native project created with 

    npx react-native init <my_proj_name_here> --template react-native-template-typescript

it is imported like this:

    import {FederatedProviderButtons} from '@aws-amplify/ui-react-native/dist/Authenticator/common';

note *dist* folder inside path.

Maybe it should be imported like this:

    import {FederatedProviderButtons} from '@aws-amplify/ui-react-native';

Thank you!

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ioanabrooks** [comment]
Hi @andreav thanks for expressing interest in this feature, supporting federated authentication is indeed on our roadmap for early next year!
