### ISSUE TITLE
React Native Authenticator - styling links

### ISSUE THREAD

**Issue by andreav** [aws-amplify/amplify-ui#3230]
Hello,
I cannot find a way to style only links (like "Forgot Password" or "Create Account" in SignIn Screen)

It looks like I can change their color overriding:
- tokens -> colors -> brand -> primary -> '80'
- tokens -> colors -> teal -> '80'

but when I change them, both the "links" and the "SignIn button" change.

Is it possible to style links and button differently?

Thank you

**Comment by ioanabrooks** [comment]
Hi @andreav, we don't officially support primitives and theming for the React Native platform yet, we're planning on releasing that in Q1 of next year.  
For your immediate needs what you can do to style the links individually through theming is to target the `textLink ` and/or `containerLink ` props on the button component. Please see an example below:

```
<ThemeProvider
      theme={{
        components: {
          button: {
            textLink: {
              color: '{colors.black}',
            },
            containerLink: {
              margin: '{space.xs}',
            },
          },
        },
      }}
    >
      <Authenticator.Provider>
        <Authenticator />
      </Authenticator.Provider>
    </ThemeProvider>
```

**Comment by andreav** [comment]
It works perfectly!
Thank you!

**Comment by abgupta-wfc** [comment]
This is not working for me

**Comment by abgupta-wfc** [comment]
I trying using components keys in my theme but its not working but overriding 
tokens -> colors -> brand -> primary -> '80' worked. Am I missing anything ?
