### ISSUE TITLE
Add Usage docs for Vite

### ISSUE THREAD

**Issue by micah-redwood** [aws-amplify/amplify-ui#3231]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

It'd be really nice if the Amplify UI docs had a section under "Usage" for "Vite", similar to the NextJS docs:
https://ui.docs.amplify.aws/react/getting-started/usage/nextjs

Currently there are some pretty tricky workarounds and it can take a while to pin down exactly what needs changed to get it working. See this Issue: https://github.com/aws/aws-sdk-js/issues/3673

The Vite ecosystem is actively maintained and growing, and it'd be great if it was easier to use Amplify in Vite projects. Thanks for considering!

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by wlee221** [comment]
Hi @micah-redwood, thanks for your interest! I agree with you on adding more vite guides. I will bring this up to the team 🙏

**Comment by reesscot** [comment]
This is a really good point @micah-redwood, Vite has already replaced CRA for many of us!

**Comment by charlieforward9** [comment]
Any update here?

**Comment by reesscot** [comment]
@charlieforward9 @micah-redwood We've added a Vite guide for React here: https://ui.docs.amplify.aws/react/getting-started/usage/vite
