### ISSUE TITLE
Fileuploader, override the key.

### ISSUE THREAD

**Issue by bmw46033** [aws-amplify/amplify-ui#3236]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Storage (File Uploader)

### Please describe your feature-request in detail.

Reviewing the implementation, it is apparent the key for the Storage.put is simply taken from filename of the file object itself.  This is fine for having all files stored in the same folder.  It would be ideal to have a callback or an opportunity to specify the key as a prefix for each file.

### Please describe a solution you'd like.

Perhaps extend the events so there could be a onFileUpload giving the opportunity to set or to override the fileupload handler with a custom handler that allows the implementor to issue the Storage.put command.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by jacob-nolley-work** [comment]
I would love this feature! Any updates on this becoming availabe?

**Comment by ErikCH** [comment]
Yes! We will implement this before our General availability release.

**Comment by em-xqm** [comment]
When is GA release? Need this feature asap

**Comment by brianlenz** [comment]
> it might be possible if you can extend `FileUploaderProps` with `fileName` because `fileUpload(...)`already has `fileName` arg and it's calling `Storage.put(fileName, ...)`

I took a look into this, but unfortunately I don't think it will work. The issue is that the `FileUploader` sets the `fileName` explicitly to `status.name` (which is on the `FileStatus`). I don't see any way to override the `fileName`.

I created #3442 as an initial attempt at supporting a configurable, custom S3 key.

**Comment by bmw46033** [comment]
Any update on this?  I'll be happy to test any PRs.

**Comment by brianlenz** [comment]
@bmw46033 we ended up using the `FileUploader` as-is and customized the post-processing via `onSuccess` to move the file via the S3 SDK to the final destination (via `Storage.copy()` and `Storage.remove()`). This was an acceptable solution for our simplified use case, so I wanted to throw it out there in case it might work for anyone else running into similar limitations.

**Comment by reesscot** [comment]
This feature was added to StorageManager via the processFile prop. See docs here: https://ui.docs.amplify.aws/react/connected-components/storage/storagemanager#pre-upload-processing
