### ISSUE TITLE
Fix Types For Tab Children

### ISSUE THREAD

**Issue by bestickley** [aws-amplify/amplify-ui#3256]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

See below TS error:
![image](https://user-images.githubusercontent.com/35735118/210607232-38026f5a-02b0-4368-b352-9442e43e2f55.png)

### What's the expected behaviour?

`<Tabs>` should accept `null` as child as documented [here](https://github.com/aws-amplify/amplify-ui/pull/1117#discussion_r784169204)

### Help us reproduce the bug!

Conditionally render `<TabItem>` within `<Tab>` and see TS error.

### Code Snippet

```typescript
let RequestTabItem: ReactElement | null = null;
  if (canViewRequests) {
    RequestTabItem = (
      <TabItem
        title={<RequestsBadge count={length} loading={isFetching} />}
        onClick={() => navigate("requests")}
      />
    );
  }
  return (
    <>
      <Tabs currentIndex={tab} onChange={handleChange} marginBottom="small">
        <TabItem title="Members" onClick={() => navigate("members")} />
        
        {RequestTabItem}
      </Tabs>
```

### Additional information and screenshots

Amplify UI does correctly not log warning message when `null`. This is just a TS issue.

**Comment by reesscot** [comment]
@bestickley Thanks for reporting this, we'll get it fixed!

**Comment by dbanksdesign** [comment]
This should be fixed in #3270 and go out in the next release!

**Comment by reesscot** [comment]
Fixed by https://github.com/aws-amplify/amplify-ui/pull/3270

**Comment by dandrei** [comment]
This seems to still be an issue in the React package? `@aws-amplify/ui-react 6.1.12`:

    TS2307: Cannot find module
    @aws-amplify/ui-react/dist/types/primitives/Tabs/TabsItem
    or its corresponding type declarations.
