### ISSUE TITLE
FileUploader component isn't setting content type of svg

### ISSUE THREAD

**Issue by rozhover** [aws-amplify/amplify-ui#3257]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Storage (File Uploader)

### How is your app built?

Next.js

### Please describe your bug.

I have a FileUploader component in Next.js app, and i'm trying to set the uploads to public read access. It works for jpegs and pngs, but not svgs. Svg metadata is being set to "binary/octet-stream" instead of "image/svg+xml". Only when i specifically set contentType="image/svg+xml" on the FileUploader component then it works, but not sure how to set that prop per file, if multiple upload types are allowed on the component.

### What's the expected behaviour?

Expected to detect svg mime type based on the file and save in the metadata

### Help us reproduce the bug!

`<FileUploader showImages={true} level="public" accessLevel="public" storageAccessLevel="public" acceptedFileTypes={["image/*"]} onSuccess={(res) => setNewUploads(res)} />`

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ErikCH** [comment]
Hi @rozhover !

Are you saying when you download the file back from S3, that it's not detecting it's an SVG file any more? I just ran a test, and the svg file downloaded back from S3 was an S3 image .

Also I am adding a new feature in the future that you can edit the files before they upload, including changing the file name, and run your own `Storage.put`

**Comment by rozhover** [comment]
Hi, thanks for the quick reply!
It does indeed work to download back, but it doesn't work to display in the browser when using an img tag. The difference i'm seeing is in the metadata, the Content-Type seems to be set as binary/octet-stream. But if I override it to set to image/svg+xml then it works to display in the image tag. 
That would be a great feature to edit files before upload. But it would be nice too if the uploader could detect svg and set the content type to image/svg+xml automatically.
Thanks for your help!

**Comment by ErikCH** [comment]
Hi @rozhover !

I've made an update to the file uploader, so now it will send the correct `contentType` with every upload. You can still override it though by passing in your own `contentType`. We are looking at ways of updating files before upload, that will be a seperate PR.

The release is now in our `@aws-amplify/ui-react@next` release. If you'd like to test it out. It will be in the full main release week.

**Comment by ErikCH** [comment]
I'm going to close this. Please re-open it if you have issues.
