### ISSUE TITLE
Verified users asked to verify email every time they log in

### ISSUE THREAD

**Issue by jwhiteley89** [aws-amplify/amplify-ui#3305]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Please describe your bug.

Email verified users are prompted to verify their email address every time they log in when logging into an application using aws-amplify/ui-react. This persists even after going into the user pool dashboard and setting the MFA and verifications tab to No verification. 

### What's the expected behaviour?

Congito user pool users with verified emails should not be asked to verify email during log in. 

### Help us reproduce the bug!

1. Install aws-amplify/ui-react": "^3.4.1"
2. Have an application wrapped in Authenticator with loginMechanisms set to ["email"] and hideSignUp set to true
3. Login with Cognito user pool credentials which have been marked verified already or the user has already entered the email verified code, and you'll be directed right into the "Account recovery requires verified contact information" form.

### Code Snippet

```typescript
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <Authenticator loginMechanisms={["email"]} hideSignUp={true}>
      <Main />
    </Authenticator>
  </React.StrictMode>
)

```

### Additional information and screenshots

<img width="1063" alt="Screenshot 2023-01-12 at 12 57 22 PM" src="https://user-images.githubusercontent.com/75508005/212432651-2a44510a-60a7-47b7-9f04-e68d7a1f1c78.png">
<img width="730" alt="Screenshot 2023-01-12 at 1 18 28 PM" src="https://user-images.githubusercontent.com/75508005/212432675-2d5f481b-ce7d-4038-8e61-45c1cf196173.png">

**Comment by joebuono** [comment]
Hi @jwhiteley89, I wasn't able to reproduce this bug. I see that you're using an outdated version of `@aws-amplify/ui-react`. Can you try updating to the latest version and let us know if that solves your issue? Thanks.

**Comment by jwhiteley89** [comment]
> Hi @jwhiteley89, I wasn't able to reproduce this bug. I see that you're using an outdated version of `@aws-amplify/ui-react`. Can you try updating to the latest version and let us know if that solves your issue? Thanks.

Thanks for the quick response, I have been trying to track this issue down for a few months now. I just updated to the latest(4.3.3), deleted the node_modules and reinstalled all dependencies. Unfortunately still getting the same issue.

**Comment by jordanwhiteley** [comment]
I spun up a brand new create-react-app and wrapped it in the Authenticator just to double check and I am seeing the same issue with this brand new project. Already verified emails are being asked to verify on every login.

**Comment by jwhiteley89** [comment]
I spun up a brand new create-react-app and wrapped it in the Authenticator just to double check and I am seeing the same issue with this brand new project. Already verified emails are being asked to verify on every login.

**Comment by joebuono** [comment]
Hi @jwhiteley89. I tried reproducing this bug again, but it appears to be functioning correctly for me. 

Instead of manually setting `Auth` in `Amplify.configure`, can you try importing `awsexports`?

```jsx
import awsExports from "./aws-exports";
Amplify.configure(awsExports);
```

Also, what is `WindowAuthStorage`?

**Comment by jwhiteley89** [comment]
Thanks for checking again, I just setup amplify configure and imported auth. Even configuring with the awsExports it is still asking to verify already verified emails. In my app I don't manually configure amplify, rather I use a constants file to switch between environments, I was just testing manual configuration to make sure that wasn't the issue. 

The WindowAuthStorage is just a local storage wrapper I use instead of chrome storage.

**Comment by jwhiteley89** [comment]
In the was-export file is shows the verification mechanisms
![image](https://user-images.githubusercontent.com/75508005/213314860-05d3b017-f948-4f1e-a6b1-e3c12ea1dc14.png)

If I go into AWS console and turn verifications to no verification and import auth I can see this verification mechanism array become empty.

**Comment by mojansen** [comment]
@jwhiteley89 make sure your app is allowed to read the "email_verified" attribute from Cognito. See https://github.com/aws-amplify/amplify-js/issues/2730#issuecomment-498425391

**Comment by reesscot** [comment]
@jwhiteley89, did @mojansen's [suggestion](https://github.com/aws-amplify/amplify-ui/issues/3305#issuecomment-1400588468) above fix your issue?

**Comment by jwhiteley89** [comment]
I don't use amplify cli to configure auth the way used in the post by @mojansen . I configure auth in amplify studio ui and connect it to my cognito pool then run the amplify pull command to import auth to the current project. 

My cognito pool app client settings include email for the allow OAuth scope, which if I am reading right includes the "email_verified" scope.
<img width="530" alt="image" src="https://user-images.githubusercontent.com/75508005/214640802-3fde92fd-a136-4f41-a671-220e2e650565.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/75508005/214640901-f2e0579f-7653-4945-af2c-685744e6f35a.png">



These are my current parameters.json in the local amplify auth folder
![image](https://user-images.githubusercontent.com/75508005/214638364-9c841fd3-1470-40e8-b84b-41376e0070cf.png)

**Comment by jwhiteley89** [comment]
if I unlink the imported auth and change the MFA and verifications to No verification and import auth again it removes the autoVerifiedAttributes from parameter.json

<img width="774" alt="image" src="https://user-images.githubusercontent.com/75508005/214642701-d006e801-2374-4d20-ad32-8878fea2ca6f.png">
 

![image](https://user-images.githubusercontent.com/75508005/214642420-00202597-4336-47ef-9770-601f52b78e0a.png)

**Comment by reesscot** [comment]
@jwhiteley89 So glad you figured it out! I will close this issue for now, but if you need anything else feel free to let us know!
