### ISSUE TITLE
Bug: `small` size not being applied to some field controls

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#3346]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

N/A

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

Reported on Discord by EricDAllen:

Hitting a bug with the SelectField in the 4.0.3 package.  Is this the best place to report it?
When setting the "size" attribute to "small", it looks like the "amplify-field--small" class should be applied to the outer <div> tag, but that isn't happening, so the field won't vertically line up with other controls like the TextField in the first attached image.  When I manually apply the class (second image), everything lines up nicely (third image).
<img width="366" alt="image" src="https://user-images.githubusercontent.com/6165315/214616620-bae65316-e1b1-4321-a5dd-9d063dbaffc1.png">

I've reproduced the customer issue here:
https://codesandbox.io/s/checkboxfield-k33slb?file=/src/App.js

### What's the expected behaviour?

Label should shrink based on the size

### Help us reproduce the bug!

See above

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by EricDAllen** [comment]
For the record, I believe I've reproduced this with RadioGroupField, Autocomplete, and SelectField.  When fixing this issue, it would probably be best to look at all controls and correct it across as many as feasible at once.
