### ISSUE TITLE
Hi, How to Change theme from flutter app?

### ISSUE THREAD

**Issue by M7MMAD-OMAR** [aws-amplify/amplify-ui#3348]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Flutter

### Which UI component?

Authenticator

### How is your app built?

Flutter

### Please describe your bug.

I am need change theme from flutter app

### What's the expected behaviour?

I am need change theme from flutter app

### Help us reproduce the bug!

I am need change theme from flutter app

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
Hi @M7MMAD-OMAR, theming for the Amplify Flutter Authenticator is handled by MaterialApps theming capabilities. You can find some more details on that here:  https://ui.docs.amplify.aws/flutter/theming Let us know if that helps.
