### ISSUE TITLE
Infinite error loop after sign out when using maps

### ISSUE THREAD

**Issue by cowjen01** [aws-amplify/amplify-ui#3367]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator, Geo (MapView)

### How is your app built?

Create React App

### Please describe your bug.

Hello, I'm using @aws-amplify/ui-react `Authenticator` component together with the `MapView` component and subcomponents from the `react-map-gl` package. After signing out using the built-in strategy I get an infinite error loop saying:

```
[DEBUG] 37:23.411 AuthClass - Failed to get user from user pool
ConsoleLogger.js:96 [DEBUG] 37:23.411 AuthClass - Failed to get the current user No current user
ConsoleLogger.js:86 [DEBUG] 37:23.411 AuthClass - getting guest credentials
ConsoleLogger.js:86 [DEBUG] 37:23.411 Credentials - setting credentials for guest
fetch-http-handler.js:47          POST https://cognito-identity.eu-west-1.amazonaws.com/ 400
ConsoleLogger.js:96 [DEBUG] 37:23.470 Credentials - Failed to load credentials Promise {<rejected>: NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
    at http…}
ConsoleLogger.js:96 [DEBUG] 37:23.470 Credentials - Error loading credentials NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
    at http://localhost:3000/static/js/bundle.js:53636:62
    at step (http://localhost:3000/static/js/bundle.js:244523:17)
    at Object.next (http://localhost:3000/static/js/bundle.js:244472:14)
    at fulfilled (http://localhost:3000/static/js/bundle.js:244431:24)
```

I found out there is a loop trying the refresh the credentials after sign out:

```js
Hub.listen("auth", (data) => {
      switch (data.payload.event) {
        case "signIn":
        case "signOut":
        case "tokenRefresh":
          this.refreshCredentialsWithRetry();
          break;
      }
    });

...

refreshCredentialsWithRetry = async (): Promise<void> => {
    try {
      const MAX_DELAY_MS = 5 * 60 * 1000; // 5 minutes
      await jitteredExponentialRetry(this.refreshCredentials, [], MAX_DELAY_MS);
...
```

The errors are repeating until I refresh browser. I use Cognito Pool with groups activated.

### What's the expected behaviour?

The credentials should not keep refreshing after signing out.

### Help us reproduce the bug!

1. Wrap the application to `<Authenticator loginMechanisms={['email']} />` component
2. Implement `<MapView initialViewState={{...}} />`
3. Sign out from the page with the map displayed
4. Check the console log for the errors

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

```
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 90.42 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.1
  npmGlobalPackages:
    eslint: 8.27.0
    insomnia-documenter: 0.5.4
    json-dynamo-putrequest: 1.0.0
    markdown-pdf: 11.0.0
    npm: 9.3.1
    prettier: 2.7.1
    serve: 14.1.1
```

**Comment by 0618** [comment]
Thanks @cowjen01 for reporting the issue. @sreeramsama and I both tried to reproduce it, but were not able to. 

Would you please provide more details?

Here's the testing app I used. Did I miss anything?

**Comment by cowjen01** [comment]
Thank you @0618  for investigating the issue. You mentioned the testing app - could you please provide me with a link / code?

**Comment by cowjen01** [comment]
Ok @0618, I pulled your project and created a new Amplify app to test the code out. I did not modify the components and left the `Authenticator` and `MapView` as it is. Regarding the Amplify app, I followed this procedure:

1. Add auth with one user pool group.
2. Init deployment.
3. Add map-view from the geo category and allow access for the single pool group.
4. Push the changes.
5. Create a new user and add him to that group.
6. Login as this user.
7. Wait until the map is loaded.
8. Click the sign-out button.

After this, the infinite loop of errors and Cognito API calls remain. I'm attaching my `backend-config.json`:

```json
{
  "auth": {
    "amplifyuidemo20230131adb6ec8": {
      "customAuth": false,
      "dependsOn": [],
      "frontendAuthConfig": {
        "mfaConfiguration": "OFF",
        "mfaTypes": [
          "SMS"
        ],
        "passwordProtectionSettings": {
          "passwordPolicyCharacters": [],
          "passwordPolicyMinLength": 8
        },
        "signupAttributes": [
          "EMAIL"
        ],
        "socialProviders": [],
        "usernameAttributes": [
          "EMAIL"
        ],
        "verificationMechanisms": [
          "EMAIL"
        ]
      },
      "providerPlugin": "awscloudformation",
      "service": "Cognito"
    },
    "userPoolGroups": {
      "dependsOn": [
        {
          "attributes": [
            "UserPoolId",
            "AppClientIDWeb",
            "AppClientID",
            "IdentityPoolId"
          ],
          "category": "auth",
          "resourceName": "amplifyuidemo20230131adb6ec8"
        }
      ],
      "providerPlugin": "awscloudformation",
      "service": "Cognito-UserPool-Groups"
    }
  },
  "geo": {
    "map09ca3cb6": {
      "accessType": "CognitoGroups",
      "dependsOn": [
        {
          "attributes": [
            "UserPoolId"
          ],
          "category": "auth",
          "resourceName": "amplifyuidemo20230131adb6ec8"
        },
        {
          "attributes": [
            "AdminsGroupRole"
          ],
          "category": "auth",
          "resourceName": "userPoolGroups"
        }
      ],
      "isDefault": true,
      "mapStyle": "VectorEsriLightGrayCanvas",
      "providerPlugin": "awscloudformation",
      "service": "Map"
    }
  }
}
```

**Comment by 0618** [comment]
Thanks for the detailed instruction @cowjen01 , we were able to reproduce the issue.

While we are fixing the issue, could you try the following workarounds?

- add guest access to Geo
- (Or) hide the Geo component after the user's signed out

Let me know if those help.

**Comment by cowjen01** [comment]
I'm sorry @0618  I did not provide the detailed instructions right-away at the beginning. I tried to add the guest access for the map resource and it helped! Thank you, this seems to be the least invasive walk-around.
