### ISSUE TITLE
The authenticator dictionary is missing Cognito errors for customization

### ISSUE THREAD

**Issue by avlisesac** [aws-amplify/amplify-ui#3368]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

The [authenticator dictionary](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/en.ts) is missing entries. I'm unsure of what all is missing, but I discovered that it is capable of handling at least password policy errors and incorrect username/password errors, but they're not in the documentation/dictionary.

Here are the ones I found and was able to customize. I tried to make a PR to add them, but I'm pretty new to open source contributions, so I couldn't get one made.

```
'Incorrect username or password.': 'Incorrect username or password.',
  'Password does not conform to policy: Password must have lowercase characters': 'Password does not conform to policy: Password must have lowercase characters',
  'Password does not conform to policy: Password must have uppercase characters': 'Password does not conform to policy: Password must have uppercase characters',
  'Password does not conform to policy: Password must have numeric characters': 'Password does not conform to policy: Password must have numeric characters',
  'Password does not conform to policy: Password must have symbol characters': 'Password does not conform to policy: Password must have symbol characters',
```

### What's the expected behaviour?

The dictionary should have all the relevant strings present.

### Help us reproduce the bug!

Nothing to reproduce.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hi @avlisesac, thank you for reporting this issue. You are correct that at this time it is not currently possible to customize the error messages that come from Amazon Cognito. We are working on making the error messages more customizable. 

Site note: I found a more complete list of the missing cognito messages here (look at code example near end of the article):
https://dev-classmethod-jp.translate.goog/articles/try-amplify-ui-angular-translations/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc

Related issue: https://github.com/aws-amplify/amplify-ui/issues/2733

**Comment by wlee221** [comment]
For the time being, you can also use service overrides to catch auth error messages and customize the error messages.

```
function App() {
  return (
    <Authenticator.Provider>
      <Authenticator
        services={{
          handleSignUp: async (data) => {
            try {
              return await Auth.signUp(data);
            } catch (e) {
              console.log('e', e);

              throw new Error('Custom Error!');
            }
          },
        }}
      >
        <View style={style.container}>
          <SignOutButton />
        </View>
      </Authenticator>
    </Authenticator.Provider>
  );
}
```
