### ISSUE TITLE
acces_token scopes do not come through when using react component Auth components with Cognito

### ISSUE THREAD

**Issue by david-saeger** [aws-amplify/amplify-ui#337]
I have a amplify project which uses Cognito to authenticate with additional scopes 'profile' 'openid'. When I use the hosted UI to sign in these scopes are on my returned Access Token but when I use Amplifys react components these scopes are unavailable and I am unable to authenticate to my API gateway endpoint.

**Comment by chrisbonifacio** [comment]
Closing this as a duplicate of https://github.com/aws-amplify/amplify-ui/issues/365
