### ISSUE TITLE
Setting `totpIssuer` to the the user's email addres

### ISSUE THREAD

**Issue by epicfaace** [aws-amplify/amplify-ui#3387]
Follow up to https://github.com/aws-amplify/amplify-ui/issues/3092.

@ErikCH @0618  How can I set `totpIssuer` to the the user's email address? I would like to set the totpIssuer to be equal to the user's email address. I only have access to the user's guid from using `useAuthenticator()`. In older versions of Amplify React, I was able to access the user's email address and set totpIssuer to be equal to it.

i.e., something like this:

```js
const { email } = useAuthenticator(); /// ?
const formFields = {
  setupTOTP: {
        QR: {
          totpIssuer: 'test issuer',
          totpUsername: email,
        },
      },
  }

export default function App() {
  return (
    <Authenticator formFields={formFields}>
      {({ signOut }) => <button onClick={signOut}>Sign out</button>}
    </Authenticator>
  );
}
```

**Comment by reesscot** [comment]
Hi @epicfaace,
You will need to wrap your application in the Authenticator.Provider in order to access the useAuthenticator hook and grab the user object. See: https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#useauthenticator-hook

**Comment by epicfaace** [comment]
@reesscot I was able to grab the user object, but it doesn't have the user's email address. It only has the user id.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/1689183/216829165-bd30fd07-defd-4a79-9668-e3e8f359ee13.png">

![image](https://user-images.githubusercontent.com/1689183/216829258-883e5dd7-dd2d-4a80-9e57-2c444539a254.png)

I also set `loginMechanisms={['email']}` as a prop for `Authenticator`, so the user has to enter their email and password when signing in / signing up. That's why I believe this library might need a code change in order to expose the user's email address in the `user` object.

**Comment by ioanabrooks** [comment]
Hi @epicfaace!

Did you surround your app with the [Authenticator.Provider](https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#authenticator-provider)?

The hook only has access to the context value that is provided by the context provider component so if the context provider is not used, the context value will not be set and the hook will have no value to reference.

**Comment by reesscot** [comment]
@epicfaace Assuming you're using the `Authenticator.Provider` and it's just not showing in your code example above, I think it is a race condition. What is your use case here? Once the Authenticator has been rendered, the formFields settings cannot be updated.

**Comment by reesscot** [comment]
Since we haven't heard back from you

**Comment by epicfaace** [comment]
Hi @reesscot , apologies for the delay. I am using `Authenticator.Provider`.

My use case is: I want to set the TOTP Username to be equal to the email address the user enters when they sign up.

I don't know the user's email in advance of rendering `<Authenticator>`, as the user will enter in their email upon login / sign up. So I need some way of either 1) updating formFields once Authenticator has been rendered so that the 2FA screen can be properly updated, or 2) configuring formFields so that it sets the TOTP Username equal to the email.

Note that this use case was entirely possible using older versions of aws-amplify, but seems to have regressed / become impossible with the latest upgrade -- see this sample code for what we were doing earlier -- we were able to hook into `onAuthUIStateChange` and then use the i18n functions to properly set the TOTP usernam equal to the email. https://github.com/cisagov/crossfeed/blob/92dd857d90a08e4fb81546d9e3a0a120236065cb~1/frontend/src/pages/AuthLogin/AuthLogin.tsx#L39-L59

**Comment by epicfaace** [comment]
@reesscot @ioanabrooks Any thoughts on this?
