### ISSUE TITLE
NextJS crashing - cannot resolve '@aws-amplify/geo' (this package is not used in the app)

### ISSUE THREAD

**Issue by APNSound** [aws-amplify/amplify-ui#3391]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

When running my Next.js app on an EC2 instance, it crashes after a moment with the following:

error - ./node_modules/maplibre-gl-js-amplify/lib/esm/AmplifyGeofenceControl/index.js:11:0
Module not found: Can't resolve '@aws-amplify/geo'

Import trace for requested module:
./node_modules/maplibre-gl-js-amplify/lib/esm/index.js
./node_modules/@aws-amplify/ui-react/dist/esm/components/Geo/MapView/index.mjs
./node_modules/@aws-amplify/ui-react/dist/esm/index.mjs
./pages/_app.js

### What's the expected behaviour?

My app doesn't use any Geo Location data or functions. I tried installing the packages just to kill the error, but after redeploy it persists. 

### Help us reproduce the bug!

This is not so different from this discussion, but I'm not sure if it's related (and it's closed as of this posting):

https://github.com/aws-amplify/amplify-ui/issues/1647

### Code Snippet

```typescript
// Put your code below this line.

```

"dependencies": {
  "@aws-amplify/geo": "^2.0.12",
  "@aws-amplify/ui-react": "^4.3.5",
  "@next/font": "^13.1.6",
  "mapbox-gl": "^2.12.0",
  "next": "13.1.6",
  "react": "18.2.0",
  "react-dom": "18.2.0"
}

**Comment by ioanabrooks** [comment]
Hi @APNSound, thank you for using `amplify-ui` and for reaching out! To help us debug this further, would you please provide the following:
* build tool and version you are using (Create React App, etc)
* package manager and version (npm, yarn, etc)
Lastly, does your app build and run locally?

**Comment by APNSound** [comment]
Hi, I think I found the issue.
I'm new... so... this is a new coder issue. The project I'm making requires more in depth use of services than what Amplify provides. I used Amplify where I could, and SDKs where I needed to. I didn't realize that apps destined for EC2 differ from Amplify apps. I was trying to deploy my Amplify solution to an EC2 instance. Now that I have removed Amplify, I'm able to run a Next app from an EC2. I think I'm better off  to use the other AWS products for this solution. I liked using Amplify, I can see implementing it for client solutions that aren't as ambitious as what I'm building. I did find it quite powerful for implementing a GraphQL API via AppSync, which unless there's a big gotcha I'm missing, should work great with my EC2 servers.

**Comment by ioanabrooks** [comment]
Hi @APNSound, I'm not familiar with your architecture, but from the information I have so far my recommendation would be to separate the frontend from the backend. The React web application (UI) can be an "Amplify app" - deployed serverless, while your service layer can live in EC2.

**Comment by APNSound** [comment]
That sounds like a viable way to go, but I'm sold on the NextJS system so I want to deploy it without splitting it up. I also want the control for security and scalability I can get from the EC2 route. It's all good, just a little redirect in my journey. I appreciate your input, thank you for following up with my question.

**Comment by ioanabrooks** [comment]
Sure thing. Here is blog about creating an Amplify Next.js app: https://aws.amazon.com/blogs/mobile/deploy-a-next-js-13-app-with-authentication-to-aws-amplify/, hope this helps!
