### ISSUE TITLE
AmplifyS3Image - Not available in latest react library

### ISSUE THREAD

**Issue by milindaj** [aws-amplify/amplify-ui#3428]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

I was looking to use _**AmplifyS3Image**_ component as per this below documentation but looks like this component is not available in the latest React package. Is there a plan to include this in near future? Is there a way I can still include and use it in my project? May be using legacy package?

https://docs.amplify.aws/ui/storage/s3-image/q/framework/react/ 

Error on `npm start`

`export 'AmplifyS3Image' (imported as 'AmplifyS3Image') was not found in '@aws-amplify/ui-react' (possible exports: AccountSettings, Alert, AmplifyProvider, Authenticator, Autocomplete, Badge, Button, ButtonGroup, Card, CheckboxField, Collection, ComponentClassNames, ComponentClassObject, ComponentPropsToStylePropsMap, ComponentPropsToStylePropsMapKeys, Divider, Expander, ExpanderItem, FieldGroupIcon, FieldGroupIconButton, FileUploader, Flex, Geocoder, Grid, Heading, HighlightMatch, Icon, Image, InAppMessageDisplay, InAppMessagingProvider, Link, Loader, LocationSearch, MapView, Menu, MenuButton, MenuItem, Pagination, PasswordField, PhoneNumberField, Placeholder, Radio, RadioGroupField, Rating, ScrollView, SearchField, SelectField, SliderField, StepperField, SwitchField, TabItem, Table, TableBody, TableCell, TableFoot, TableHead, TableRow, Tabs, Text, TextAreaField, TextField, ThemeProvider, ToggleButton, ToggleButtonGroup, View, VisuallyHidden, components, createTheme, defaultDarkModeOverride, defaultTheme, primitives, translations, useAmplify, useAuthenticator, useBreakpointValue, useInAppMessaging, usePagination, useTheme, withAuthenticator, withInAppMessaging)`

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@milindaj The `AmplifyS3Image` has been deprecated and I would advise against using it at this time since it depends on an older version of `aws-amplify`. However, it is possible to use it with the previous version of @aws-amplify/ui-react (version 3) and `aws-amplify` (version 4). 

We have made a note of this feature request for a new Storage UI Image component on our roadmap

**Comment by shcpj** [comment]
looking for this as well, thanks.

**Comment by reesscot** [comment]
@shcpj Thanks for your interest. Can you help me understand what features of the AmplifyS3Image you were using? Were you primarily using it to generate the presigned URL to display an image from S3?

**Comment by reesscot** [comment]
This is now available in the StorageImage component: https://ui.docs.amplify.aws/react/connected-components/storage/storageimage

**Comment by milindaj** [comment]
Awesome! I am just about to start with another project. This feature will be very helpful!
