### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by myatniy** [aws-amplify/amplify-ui#3430]
**Page**: [`https://ui.docs.amplify.aws/react/connected-components/authenticator/react/guides/auth-protected`](https://ui.docs.amplify.aws/react/connected-components/authenticator/react/guides/auth-protected)
**Feedback**: 
<img width="702" alt="Screenshot 2023-02-16 at 12 18 24" src="https://user-images.githubusercontent.com/25590279/219321876-67bc02fa-a9d1-4c79-8c4f-d88f61b80e12.png">

**Comment by reesscot** [comment]
Hi @myatniy, thank you for reporting this issue. Do you know where you found the link that led you to this URL?

**Comment by myatniy** [comment]
@reesscot 

[Headless Usage](https://ui.docs.amplify.aws/react/connected-components/authenticator/headless), Cmd/Ctrl + F in the browser and paste text below:
For a full example of useAuthenticator, see the [protected routes guide](https://ui.docs.amplify.aws/react/connected-components/authenticator/react/guides/auth-protected)

**Comment by reesscot** [comment]
Thank you @myatniy, we'll get this fixed.

**Comment by reesscot** [comment]
Fix was merged [in https://ui.docs.amplify.aws/react/guides/auth-protected](https://github.com/aws-amplify/amplify-ui/pull/3435)
