### ISSUE TITLE
withAuthenticator broken cannot scroll ui fields behind keyboard

### ISSUE THREAD

**Issue by philipheinser** [aws-amplify/amplify-ui#3444]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Xcode/ Metro

### What browsers are you seeing the problem on?

iOS (React Native)

### Please describe your bug.

withAuthenticator broken cannot scroll ui fields behind keyboard. if I tap on a field that's on the lower half the keyboard appears over the textfield and I cannot see what im typing. the ui is complete unusable...

also the German translations are only used for half of the labels:

### What's the expected behaviour?

login and signup form to at least be somewhat useable 

### Help us reproduce the bug!

make an react native app use the withAuthenticator component and ry to create an account 

### Code Snippet

```typescript
I18n.putVocabularies(translations);
I18n.setLanguage('de');

export default withAuthenticator(MyView, {
  loginMechanisms: ['username', 'email'],
  signUpAttributes: [],
});

```

### Additional information and screenshots

![IMG_A69BEA77BA21-1](https://user-images.githubusercontent.com/3705499/219959220-c38cabc3-ec1a-499a-b0ea-7d8cdfb7a659.jpeg)

**Comment by philipheinser** [comment]
looked at the code and its because `const KEYBOARD_VERTICAL_OFFSET = platform.IS_IOS ? -160 : -80;` why is that done? the -160 makes the textfield and button appear behind the keyboard and unreachable

**Comment by calebpollman** [comment]
Hi @philipheinser, thanks for opening this. The React Native `Authenticator` is currently in developer preview while we continue to make some improvements, and feedback is appreciated. 

After thinking through it a bit, we've decided to move forward with removing the offset value entirely (see https://github.com/aws-amplify/amplify-ui/pull/3446) which should be in our next release. Additionally, you can override the `Container` component containing the `KeyboardAvoidingView` with a custom element by passing a `Container` prop to the `withAuthenticator` options, for example:
```tsx
import React from 'react';
import { View } from 'react-native';

import { Amplify } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react-native';

import awsconfig from './aws-exports';
Amplify.configure(awsconfig);

// ...App component stuff

const MyContainer = ({ children }: { children: React.ReactNode }) => (
  <View>{children}</View>
);
export default withAuthenticator(App, { Container: MyContainer });
```

**Comment by philipheinser** [comment]
I added my own container and fixed the issue with keyboard overlap this way. My second issue is with the translations. I saw that there is a de translation file so I'm not sure why only some fields are translated. Is the translation file not complete? Where can I find a list of the keys that I have to provide by hand?

**Comment by calebpollman** [comment]
@philipheinser The translation values for `de` can be found [here](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/de.ts). You may need to provide missing key/values to achieve  full translation through out the `Authenticator`.

**Comment by philipheinser** [comment]
@philipheinser All placeholders are missing form that file also from the other translation files like `Enter your Confirmation Code`  https://github.com/aws-amplify/amplify-ui/blob/270d7553652592d0d419ee708043b8292c63336c/packages/ui/src/helpers/authenticator/constants.ts#L18 https://github.com/aws-amplify/amplify-ui/blob/270d7553652592d0d419ee708043b8292c63336c/packages/ui/src/i18n/dictionaries/authenticator/en.ts#L3
