### ISSUE TITLE
AmplifyConfirmSignup username variable state issue with dialCode variable

### ISSUE THREAD

**Issue by maxventer00** [aws-amplify/amplify-ui#345]
**React
Authentication**

We want our users to confirm their signup with a code being sent to their phone number.

Which we have working using the AmplifyConfirmSignup component, but our issue is that we operate in New Zealand so we want our dial code to be set automatically as +64.

When i edited our code for the <AmplifyConfirmSignup /> component I have written in the form fields so that it auto displays as +64

But the payload in the post api when clicking submit records it as "+1XXXXXXXX". The only way to make the component record the +64 dialCode and append it to the beginning of the username is for the user to, when the page loads, select another countries dial code (eg. +1) and then click back to the +64 code. 

**Expected behavior**

It should be updating the username in the payload for the post api to be "+64XXXXXXX" on load as the UI indicates (displays the +64 to the user).

**Reproduction steps**

Using the amplify confirm signup component like below
Signup and when prompted to enter phone number and confirmation code that was sent to the number click on submit and you'll recieve and error message "Username/Client ID combination not found". Click into the networking tab in chrome and you will be able to see that the username in the payload reads Username: "+1XXXXXXXXXX" and not Username: "+64XXXXXXXXXX"

**Code Snippet**

```javascript
// Put your code below this line.

          <AmplifyConfirmSignUp
            slot="confirm-sign-up"
            usernameAlias="phone_number"
            formFields={[
              {
                type: 'phone_number',
                label: 'NZ Phone Number',
                placeholder: 'Enter your phone number',
                dialCode: '+64',
                value: '278008668'
              },
              {
                type: 'code',
                label: 'Confirmation code',
                placeholder: 'Enter your code',
              },
            ]}
          />

**Comment by ErikCH** [comment]
Hi @maxventer00 !

Our new React Authenticator that is under the new `next` tag fixes this. The `ConfirmSignUp` component no longer asks you to enter your phone number in again to confirm it. It will only ask you to enter the code you received either by email or by your number depending on how you setup your account.

![image](https://user-images.githubusercontent.com/65630/137815824-f579561b-4074-43ec-9a93-76eed9ea3415.png)

We also have a new phone number drop down which more easily allows you to select your country code, without having to type it in.

![image](https://user-images.githubusercontent.com/65630/137815964-47fc1762-5607-469a-9422-3f2107ca241e.png)


If you like to change the text, you can simply update the text using our `I8n` internationalization helper.

```
I18n.putVocabulariesForLanguage('en', {
  ['Enter your code']: 'Enter The Code From Your Phone',
  ['Confirm Sign Up']: 'Confirm your NZ Phone Number',
});
```

![image](https://user-images.githubusercontent.com/65630/137816364-e5fc5694-9b71-4852-b4cb-9f9f987d5b40.png)

Please try this out and let us know if you have any feedback!
Here is the documentation to get started if you like to give it a try.

https://ui.docs.amplify.aws/ui/getting-started/installation?platform=react
https://ui.docs.amplify.aws/ui/components/authenticator?platform=react

**Comment by ErikCH** [comment]
I'll close this issue, but if you have any more problems, feel free to reopen this issue.
