### ISSUE TITLE
AmplifyS3Image not found in '@aws-amplify/ui-react

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-ui#3451]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

604030104789

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Question

Hi,

I'm trying to use AmplifyS3Image in my react-app to render images from S3 but I got the flowing error: export 'AmplifyS3Image' (imported as 'AmplifyS3Image') was not found in '@aws-amplify/ui-react' (screenshot of the error attached). I read that AmplifyS3Image was depricated in ws-amplify/ui-react version 4 but I don't know it was replaced with another framework, if not, how can I render images from S3 using key name? 

here is my Amplify packages and versions: 
 "@aws-amplify/ui-react": "^4.3.6",
 "aws-amplify": "^5.0.12",

thanks,
Atef
<img width="956" alt="Screenshot 2023-02-21 at 1 59 03 PM" src="https://user-images.githubusercontent.com/110037539/220353757-ec6d654b-db15-46b3-836e-278063ec0b83.png">

**Comment by calebpollman** [comment]
Hi @atef-abdellatif Thanks for opening the ticket!

`AmplifyS3Image` has been deprecated and we advise against using it at this time since it depends on an older version of `aws-amplify`. However, it is possible to use it with the previous version of `@aws-amplify/ui-react` (version 3) and `aws-amplify` (version 4).

We have made a note of this feature request for a new Storage UI Image component on our roadmap

**Comment by calebpollman** [comment]
Going to close this issue in favor of the existing feature request [here](https://github.com/aws-amplify/amplify-ui/issues/3428#issuecomment-1433717252)
