### ISSUE TITLE
[missing-page]

### ISSUE THREAD

**Issue by olivier65** [aws-amplify/amplify-ui#3455]
**Page**: [`https://ui.docs.amplify.aws/react/connected-components/authenticator/react/guides/auth-protected`](https://ui.docs.amplify.aws/react/connected-components/authenticator/react/guides/auth-protected)

The page exists but is at a [different URL](https://ui.docs.amplify.aws/react/guides/auth-protected). It is linked to on the [Headless page](https://ui.docs.amplify.aws/react/connected-components/authenticator/headless).

**Comment by calebpollman** [comment]
Thanks for catching this @olivier65 We will take a look asap!

**Comment by calebpollman** [comment]
Link was fixed in https://github.com/aws-amplify/amplify-ui/pull/3435 which has since been released. Resolving the issue. but please let us know if we missed anything and we can re-open.
