### ISSUE TITLE
[FR] Authenticator required fields handling

### ISSUE THREAD

**Issue by ioanabrooks** [aws-amplify/amplify-ui#3458]
### On which framework/platform would you like to see this feature implemented?

React, React Native, Angular, Vue

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Improve developer and end-user experience with Authenticator required fields across web and React Native platforms.

For React Native add visual indicators of required fields and don't allow forms to submit with empty values, offloading checks to the sdk, and sending unnecessary calls over the network.

For web allow customers to override the HTML5 behavior for required input fields.

### We love contributors! Is this something you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment]
Related: https://github.com/aws-amplify/amplify-ui/issues/3452

**Comment by reesscot** [comment]
We should also update the required field handling in Angular and Vue as well
https://github.com/aws-amplify/amplify-ui/issues/3928
