### ISSUE TITLE
Close-Icon in SearchField and Autocomplete is not aligned correctly

### ISSUE THREAD

**Issue by mrtzdev** [aws-amplify/amplify-ui#3465]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### Please describe your bug.

The Close-Icon in SearchField and AutoComplete is is not aligned correctly when the size prop is used: 

```
<SearchField label="search" size="small" />
<SearchField label="search" size="large" />
```
<img width="525" alt="search-close-icon" src="https://user-images.githubusercontent.com/6218025/220965653-7780a6e0-1a19-4ffa-8d0d-85fc32857890.png">

```
<Autocomplete
      label="Autocomplete size example"
      size="small"
    /> 
<Autocomplete
    label="Autocomplete size example"
    size="large"
  />

```
<img width="598" alt="autocomplete-close-icon" src="https://user-images.githubusercontent.com/6218025/220965950-6cf724a9-cd2a-46bc-99b3-eb020337db01.png">

### What's the expected behaviour?

The icon should be centered  like this: 

<img width="457" alt="search-close-icon-right" src="https://user-images.githubusercontent.com/6218025/220966477-dbd048d7-cdb0-47d1-9fb7-1a7a607b7b79.png">

### Help us reproduce the bug!

``` 
import { SearchField, Flex } from '@aws-amplify/ui-react';

export const SizeSearchFieldExample = () => (
  <Flex direction="column">
    <SearchField label="search" size="small" />
    <SearchField label="search" />
    <SearchField label="search" size="large" />
  </Flex>
); 


### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

The reason is the style width and height element span .amplify-icon. It uses the css var  --amplify-space-large: 1.5rem;   The IconSearch  uses only width: 1em height: 1em. 
https://github.com/aws-amplify/amplify-ui/blob/9b9682be9709ae9ff81ca1c300556b8647d9515c/packages/react/src/primitives/Icon/icons/IconSearch.tsx#L17

IconClose: 
`<View
      as="span"
      width={size || '1em'}
      height={size || '1em'} ...`
https://github.com/aws-amplify/amplify-ui/blob/9b9682be9709ae9ff81ca1c300556b8647d9515c/packages/react/src/primitives/Icon/icons/IconClose.tsx#L17

We could change the close icon to {'1em'} and remove size and is centered.   But this could affect other components ?
On the Button Component Icons will adapt to the surrounding font-size. For the SearchField the icon size is  always the same 1em (16px). Is that intended ? It would be better if the size of the icon adjusts to the font size of the field ( different sizes for the variants small, default, large ).

Maybe I can change this.

**Comment by mrtzdev** [comment]
@calebpollman  Yes I am interested in contributing.  I can create a pr the next days, if that's ok.

**Comment by calebpollman** [comment]
@mrtzdev That would be awesome, thanks for your interest in contributing!

**Comment by reesscot** [comment]
Fixed by https://github.com/aws-amplify/amplify-ui/pull/3478
