### ISSUE TITLE
Some Authenticator translations are missing from Dutch i18n

### ISSUE THREAD

**Issue by buremer** [aws-amplify/amplify-ui#3477]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

NX / Webpack 5

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

I've found some strings in the following file that are missing from the Dutch dictionary. The strings were related to the Password policy and showing up in English instead of Dutch.

https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/dictionaries/authenticator/nl.ts

### What's the expected behaviour?

That the Password policy errors would be in the correct language.

### Help us reproduce the bug!

- Implement `<Authenticator />` in React app
- Go to Signup
- Try the Password policy steps (First letters only, then 1 number etc.)

### Code Snippet

```typescript
I18n.putVocabularies({
    nl: {
      'Reset Password': 'Wachtwoord resetten',
      'Enter your Username': 'Vul je gebruikersnaam in',
      'Enter your Password': 'Vul je wachtwoord in',
      'New Password': 'Nieuw Wachtwoord',
      'Please confirm your Password': 'Bevestig je wachtwoord',
      'Your passwords must match': 'Je wachtwoorden moeten overeenkomen',
      'Password did not conform with policy: Password not long enough':
        'Wachtwoord voldoet niet aan de vereisten: Wachtwoord is niet lang genoeg',
      'Password did not conform with policy: Password must have uppercase characters':
        'Wachtwoord voldoet niet aan de vereisten: Wachtwoord moet hoofdletters bevatten',
      'Password did not conform with policy: Password must have numeric characters':
        'Wachtwoord voldoet niet aan de vereisten: Wachtwoord moet nummers bevatten',
      'Password did not conform with policy: Password must have symbol characters':
        'Wachtwoord voldoet niet aan de vereisten: Wachtwoord moet symbolen bevatten',
      'Attributes did not conform to the schema: email: The attribute is required\n':
        'Attributen zijn niet conform het schema: email: Het attribuut is verplicht\n',
    },
  });
```

**Comment by reesscot** [comment]
Hi @buremer,
Did you try translating them using the [i18n plugin](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#internationalization-i18n)? If you're interested in contributing translations, you can find the translations here: https://github.com/aws-amplify/amplify-ui/tree/main/packages/ui/src/i18n/dictionaries/authenticator

**Comment by thaddmt** [comment]
Just linking the PR in question to this issue - https://github.com/aws-amplify/amplify-ui/pull/3476
