### ISSUE TITLE
Object.fromEntries not working on Chrome 71 on MacOS

### ISSUE THREAD

**Issue by ysabri** [aws-amplify/amplify-ui#3489]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

On Chrome 71 and Mac OS 10 we're getting Object.fromEntries is not a function error when a user tries to signin. I tried to reproduce this using the same Chrome version on windows but it worked fine, not sure why that's the case. Looks like Chrome added support for this method from 73 onwards.

I believe this is the method responsible for this issue: (https://github.com/aws-amplify/amplify-ui/blob/d7cc72c72844733d42a9504aa2ae1f2249abc178/packages/react/src/helpers/utils.ts#L37)

### What's the expected behaviour?

Use is able to sign in with no errors.

### Help us reproduce the bug!

Use Chrome 71 or older on Mac OS. 

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by thaddmt** [comment]
Hi @ysabri unfortunately Amplify follows the same support model as the AWS Console so we only officially support the latest three major versions of chrome - https://aws.amazon.com/premiumsupport/knowledge-center/browsers-management-console/
