### ISSUE TITLE
Uncaught ReferenceError: global is not defined on Vue3 + Vite app

### ISSUE THREAD

**Issue by erodriguezds** [aws-amplify/amplify-ui#3501]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

I've just scaffolded a new vue3+typescript with Vite, followed all the steps listed [here](https://ui.docs.amplify.aws/vue/connected-components/authenticator) and the app just crashes. logging the following error in the console:

```
Uncaught ReferenceError: global is not defined
    at node_modules/buffer/index.js (index.js:43:30)
    at __require2 (chunk-TFWDKVI3.js?v=fa5e53e6:18:50)
    at AuthenticationHelper.js:6:24
```

### What's the expected behaviour?

I expect the examples from the official documentation to work!

### Help us reproduce the bug!

Scaffold a new Vue3+Typescript project with Vite, and follow the steps listed on [the Authenticator component documentation](https://ui.docs.amplify.aws/vue/connected-components/authenticator)

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hello @erodriguezds,
This is a known issue in the `aws-amplify` library that is being worked on, but the workaround is detailed in our troubleshooting guide: https://ui.docs.amplify.aws/vue/getting-started/troubleshooting#vite

**Comment by erodriguezds** [comment]
Thank you so much @reesscot, that worked out! I think that, since Vite is becoming so popular for scaffolding Vue3 projects (and even React projects!), these steps should be listed on the [installation](https://ui.docs.amplify.aws/vue/getting-started/installation) page and [the Authenticator component quick start](https://ui.docs.amplify.aws/vue/connected-components/authenticator) page, right after the `npm install` step. Otherwise, users may get a bad first impression of the library.

Thanks again!

**Comment by reesscot** [comment]
@erodriguezds Completely agree, we will get the installation page updated with Vite polyfill instructions for Vue and React platforms!

**Comment by reesscot** [comment]
@erodriguezds We've added a new Vite guide here: https://ui.docs.amplify.aws/react/getting-started/usage/vite. Please let us know what you think or have any feedback.

**Comment by reesscot** [comment]
Update: We have updated the React Vite guide, but still need to update the Vue installation page.
