### ISSUE TITLE
Amplify Map component not loading map image

### ISSUE THREAD

**Issue by jeff-accountably** [aws-amplify/amplify-ui#3558]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Geo (MapView)

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Please describe your bug.

The map component does not render the map image tiles after it has been deployed. 

It works locally when running npm start connecting to localhost, after deployment through the CI/CD it no longer works.

The error in the console is
```
Uncaught ReferenceError: g is not defined
    at 11b3f79f-182a-4b30-a441-df3ec0b766c5:1:6514
    at 11b3f79f-182a-4b30-a441-df3ec0b766c5:1:345645
```

It does not make network requests to the maps api as expected, or as it does when running on localhost.

I have confirmed that the resources are deployed in the AWS account (as it works locally) the team-providers.js has geo.
In the network tab I set requests succeeding:

```
https://maps.geo.us-east-1.amazonaws.com/maps/v0/maps/mapbea76632-dev/sprites/sprites@2x.json?x-amz-user-agent=aws-amplify%252F5%25252E1%25252E2%2520js&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<CREDS>%2F20230317%2Fus-east-1%2Fgeo%2Faws4_request&X-Amz-Date=20230317T000520Z&X-Amz-Security-Token=<TOKEN>&X-Amz-SignedHeaders=host&X-Amz-Signature=ffa7968f2321ecfe4b2f49e754a6ad9ca01fc6a5d9a750199014849c6933420f
```

But, unlike when running locally, no subsequent calls happen to get the map tiles.

### What's the expected behaviour?

The map works.

### Help us reproduce the bug!

Using  "aws-amplify": "^5.0.19", and "@aws-amplify/ui-react": "^4.4.0",

Snippet:

```
<MapView
          initialViewState={{
            latitude: externalTransaction?.location.lat,
            longitude: externalTransaction?.location.lon,
            zoom: 14,
          }}
          interactive={false}
          style={{ width: "100%", height: "450px" }}
        >
          <Marker
            latitude={externalTransaction?.location.lat}
            longitude={externalTransaction?.location.lon}
          >
            <Popup
              latitude={externalTransaction?.location.lat}
              longitude={externalTransaction?.location.lon}
              offset={{ bottom: [0, -40] }}
              style={{ width: "150px" }}
              closeButton={false}
              closeOnMove={false}
              closeOnClick={false}
            >
              <Heading level={6}>{externalTransaction?.merchant_name}</Heading>
              <Text>{externalTransaction?.location.address}</Text>
              <Text>{externalTransaction?.location.city}</Text>
              <Text>{externalTransaction?.location.region}</Text>
              <Text>{externalTransaction?.location.postal_code}</Text>
              <Text>{externalTransaction?.location.country}</Text>
              {/* Link to google maps with Lat/Long */}
              <a
                href={`https://www.google.com/maps/search/?api=1&query=${externalTransaction?.location.lat},${externalTransaction?.location.lon}`}
                target="_blank"
                rel="noreferrer"
              >
                {I18n.get("Open Google Maps ➶")}
              </a>
            </Popup>
          </Marker>
          <Marker
            latitude={externalTransaction?.location.lat}
            longitude={externalTransaction?.location.lon}
          ></Marker>
        </MapView>
```

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
@jeff-accountably Please take a look at our troubleshooting guide. This sounds like an issue we've seen with maplibre-gl:
https://ui.docs.amplify.aws/react/getting-started/troubleshooting#create-react-app

**Comment by jeff-accountably** [comment]
> @jeff-accountably Please take a look at our troubleshooting guide. This sounds like an issue we've seen with maplibre-gl and CRA: https://ui.docs.amplify.aws/react/getting-started/troubleshooting#create-react-app

This fixed the issue, thanks! I suggest updating https://ui.docs.amplify.aws/react/connected-components/geo with a troubleshooting section. It's great the solution is listed at the link you shared, but there's no way to I would have looked at a create-react-app troubleshooting page to find a solution for this.

**Comment by reesscot** [comment]
I'm glad you got it working! Yes, that's a good callout @jeff-accountably, we will get a section added around create-react-app for the Geo docs as you mentioned.
