### ISSUE TITLE
Using async result in UI element creation

### ISSUE THREAD

**Issue by flying-mojo** [aws-amplify/amplify-ui#3577]
### Which Specific Feature is your question related to?

Auth, Content, Data

### Question

Hi!
My use case is that i would like to pass some information (current user name) to a UI element on the creation of the element.
I can obtain the username using Auth.currentAuthenticatedUser() which works fine, however it is an async call.

The App function is synchronous (and making it async returns a bunch of errors) so my question is:
how can I somehow wait (in the sync App function) to get the result of the async currentAuthenticatedUser(), before I create a UI element (say a navbar))?

```
function App({ signOut }) {
  [......]
  return (
      <NavBar
        marginBottom='20px' width='100%'
        /* use result of async call to currentAuthenticatedUser() */
      />
)
}
```
What's the best way to do this? (i.e. pass current user name to NavBar ?)

**Comment by ioanabrooks** [comment]
Hey @flying-mojo you're on the right track, `withAuthenticator` hook should cover your usecase. Please check out https://ui.docs.amplify.aws/react/connected-components/authenticator/headless#useauthenticator-hook for samples and how to prevent re-renders. Let us know if you have additional questions!

**Comment by reesscot** [comment]
Please let us know if you have additional questions. Closing out for now as we haven't heard back.
