### ISSUE TITLE
React PasswordField Error State Style Inconsistency

### ISSUE THREAD

**Issue by calebpollman** [aws-amplify/amplify-ui#3581]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

The `PasswordField` toggle password visibility button border color does not match the input container border color
<img width="317" alt="image" src="https://user-images.githubusercontent.com/15002885/227069430-21956cef-10b3-4fc9-9fee-cdc7542c498d.png">

### What's the expected behaviour?

Toggle password visibility button border color should match the container border color when in an error state

### Help us reproduce the bug!

```
<PasswordField hasError label="Example" />
```

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by Rogue-striker** [comment]
can i work on this?

**Comment by Rogue-striker** [comment]
How can i test my fix?
