### ISSUE TITLE
Add error messages customizing or error container hiding

### ISSUE THREAD

**Issue by vladyer** [aws-amplify/amplify-ui#3616]
### On which framework/platform would you like to see this feature implemented?

React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

If something goes wrong, the error messages are not user-friendly (For example: `Cannot read property 'username' of undefined` if the email and password fields are empty).

Also, since I18n does not work for the error messages, there is no way to localize them.

### Please describe a solution you'd like.

It would be helpful to have the option to either hide these error messages and handle them somehow else (show a toast) or replace the message texts the same way as for all the Authenticator fields (using I18n). 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Related to https://github.com/aws-amplify/amplify-ui/issues/3452

**Comment by reesscot** [comment]
@vladyer Closing out this issue in favor of #3452. I'll add your details to that ticket.
