### ISSUE TITLE
Selection color in Authenticator inputs is not transparent

### ISSUE THREAD

**Issue by tyndria** [aws-amplify/amplify-ui#3618]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Not applicable to this issue

### What browsers are you seeing the problem on?

Android (React Native)

### Please describe your bug.

Selection color of Authenticator inputs on android is not transparent. 

It's possible to set another color through tokens _(`theme.tokens.colors.font.primary`, I also found [where in the code](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-native/src/primitives/TextField/TextField.tsx#L67) `selectionColor` is set)_, but this color token is used not only for selection, but also for the text inside input itself.
That's why I can't change this token to color with transparency, because text inside input will be hardly visible.

P.S. I don't see a such problem for iOS.

### What's the expected behaviour?

Or it should be possible to configure `selectionColor` or at least some transparency should be put to the `selectionColor`.

### Help us reproduce the bug!

It's a raw usage of Authenticator component on android without ThemeProvider.

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

https://user-images.githubusercontent.com/17138916/228791405-6471affd-fd6f-4a70-9cad-6e22fd47e179.mp4

**Comment by reesscot** [comment]
Thank you for reporting this issue! It looks like we need to look into adding another token for selection text.

**Comment by tyndria** [comment]
@reesscot thanks for the quick reply! is there some communication with internal designer needed? I'm asking because maybe this could be fixed by external contributor and I wonder what's needed here :)

**Comment by calebpollman** [comment]
@tyndria Thanks for reporting this. Will be fixed in our next release
