### ISSUE TITLE
No way to override width property on  <AccountSettings.ChangePassword>-created <form>

### ISSUE THREAD

**Issue by stuartlangridge** [aws-amplify/amplify-ui#3619]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

Using `<AccountSettings.ChangePassword>` (https://ui.docs.amplify.aws/react/connected-components/account-settings/change-password) actually creates a `<form>` element in the page. There's no way to set properties on that `<form>` element, as far as I can tell; in particular, I'd like to set the width of it. But  `<AccountSettings.ChangePassword width="unset">` or `<AccountSettings.ChangePassword width="100%">` do not result in HTML of `<form class="amplify-accountsettings-changepassword" style="width: unset">`.

### What's the expected behaviour?

There should be some way to affect the styling of the created `<form>`.

### Help us reproduce the bug!

Use `<AccountSettings.ChangePassword width="unset" />` in a page, and see that the created `<form>` does not receive the `width` style property, and there's no documented way to actually add style properties to the created `<form>`.

**Comment by reesscot** [comment]
@stuartlangridge The default theme for `<AccountSettings.ChangePassword/>` is designed to grow to full width of its container by default, which means you can simply wrap in in another component with a width constraint. Here's an example:

```js
        <View  width="300px">
            <AccountSettings.ChangePassword />
        </View>
```

Alternatively, you can target the form with CSS:

```css
.amplify-accountsettings-changepassword {
  width: 300px;
}
```

**Comment by reesscot** [comment]
Closing as we haven't heard back. Please let us know if you are still having issues.

**Comment by stuartlangridge** [comment]
That works fine, thank you!
