### ISSUE TITLE
Error integrating MapView and AmplifyGeofenceControl

### ISSUE THREAD

**Issue by fcolomas** [aws-amplify/amplify-ui#3639]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Geo (MapView)

### How is your app built?

Create React App npx

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Please describe your bug.

Exactly the same problem as:

https://github.com/aws-amplify/amplify-ui/issues/2270

But now with AmplifyGeofenceControl, happens that the **useControl hook** is on the react-map-gl package so you need to include it on the react-map-gl following exactly this example: 

https://docs.amplify.aws/lib/geo/geofences/q/platform/js/#manage-geofences-in-your-application

Error:

ERROR
Cannot destructure property 'map' of 'context' as it is null.
TypeError: Cannot destructure property 'map' of 'context' as it is null.
    at http://localhost:3000/static/js/bundle.js:116054:7
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:109363:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:110856:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:110828:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:110818:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:110808:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:112693:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:112645:18)
    at http://localhost:3000/static/js/bundle.js:112460:13
    at workLoop (http://localhost:3000/static/js/bundle.js:121606:38)

### What's the expected behaviour?

The Control is added to the MapView, but this error is thrown:

ERROR
Cannot destructure property 'map' of 'context' as it is null.
TypeError: Cannot destructure property 'map' of 'context' as it is null.
    at http://localhost:3000/static/js/bundle.js:116054:7
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:109363:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:110856:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:110828:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:110818:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:110808:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:112693:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:112645:18)
    at http://localhost:3000/static/js/bundle.js:112460:13
    at workLoop (http://localhost:3000/static/js/bundle.js:121606:38)
ERROR
Cannot destructure property 'map' of 'context' as it is null.
TypeError: Cannot destructure property 'map' of 'context' as it is null.
    at http://localhost:3000/static/js/bundle.js:116054:7
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:109363:30)
    at invokePassiveEffectMountInDEV (http://localhost:3000/static/js/bundle.js:111052:17)
    at invokeEffectsInDev (http://localhost:3000/static/js/bundle.js:112951:15)
    at commitDoubleInvokeEffectsInDEV (http://localhost:3000/static/js/bundle.js:112934:11)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:112707:9)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:112645:18)
    at http://localhost:3000/static/js/bundle.js:112460:13
    at workLoop (http://localhost:3000/static/js/bundle.js:121606:38)
    at flushWork (http://localhost:3000/static/js/bundle.js:121584:18)
ERROR
Cannot destructure property 'map' of 'context' as it is null.
TypeError: Cannot destructure property 'map' of 'context' as it is null.
    at http://localhost:3000/static/js/bundle.js:116054:7
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:109363:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:110856:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:110828:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:110818:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:110808:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:112693:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:112645:18)
    at http://localhost:3000/static/js/bundle.js:112460:13
    at workLoop (http://localhost:3000/static/js/bundle.js:121606:38)

### Help us reproduce the bug!

Follow this AWS official guide:

https://docs.amplify.aws/lib/geo/geofences/q/platform/js/#manage-geofences-in-your-application

And you will get the problem, is explicitly ask to add the package that 2270 ask to remove and doesn't work other way

### Code Snippet

```javascript
// Put your code below this line.

import React from "react";
import {Amplify} from "aws-amplify";
import { MapView, withAuthenticator } from "@aws-amplify/ui-react";
import { useControl } from "react-map-gl";
import { AmplifyGeofenceControl } from "maplibre-gl-js-amplify";
import "@aws-amplify/ui-react/styles.css";
import "maplibre-gl/dist/maplibre-gl.css";
import "maplibre-gl-js-amplify/dist/public/amplify-ctrl-geofence.css";
import awsconfig from "../src/aws-exports";
Amplify.configure(awsconfig);

function Geofence() {
    useControl(() => new AmplifyGeofenceControl());

    return null;
}

function App({ signOut }) {
    return (
        <div className="App">
            <MapView
                initialViewState={{
                    latitude: 37.8,
                    longitude: -122.4,
                    zoom: 14,
                }}
            >
<Geofence></Geofence>
            </MapView>
        </div>
    );
}

export default withAuthenticator(App);

package.json

{
  "name": "admin-front",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "aws-amplify": "^5.0.23",
    "@aws-amplify/ui-react": "^4.4.3",
    "maplibre-gl": "^2.4.0",
    "maplibre-gl-js-amplify": "^3.0.5",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "react-map-gl": "^7.0.21",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}


### Additional information and screenshots

Already checked trying to add the react-map-gl 7.0.15 version to match the dependency from the amplify rect ui package but then it breaks saying the control doesn't implement the IControlInterface

**Comment by sreeramsama** [comment]
Tried to reproduce the error but it works well with `v7.0.15` of `react-map-gl`.

Here is the package.json I've used:
```
{
  "name": "amplify-ui-demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "aws-amplify": "^5.0.22",
    "@aws-amplify/ui-react": "^4.4.3",
    "maplibre-gl-js-amplify": "^3.0.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "react-map-gl": "7.0.15",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```
Used the same App.js as mentioned above.

Did not see any error related to IControlInterface.

Here's the screenshot of UI:

![SCR-20230403-jc8](https://user-images.githubusercontent.com/12038441/229625574-6d4a34ec-0b82-41a3-b098-ff5382f4306d.png)

**Comment by fcolomas** [comment]
In the link if you add the latest react-map-gl, not the 7.0.15 version that I investigated is being used by the library, then you have the error.

**Comment by sreeramsama** [comment]
Please note that `react-map-gl` is already installed via `@aws-amplify/ui-react` and should not be a direct dependency of your application.

**Comment by reesscot** [comment]
@fcolomas Can you please confirm that removing react-map-gl from your dependencies fixes the issue? Is there any reason why you need to add it as a direct dependency?

**Comment by fcolomas** [comment]
Hi! Removing, cleaning the node modules and the package.json.lock solve the issue, I added the package because the AWS tutorial mentioned in the bug asked to add it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sreeramsama** [comment]
Is this the guide you are referring to?
https://docs.amplify.aws/lib/geo/geofences/q/platform/js/#manage-geofences-in-your-application

**Comment by reesscot** [comment]
@fcolomas It looks like `react-map-gl` is mentioned, but I don't see instructions to install it. Do you think we need a note there saying that you already have `react-map-gl` through `@aws-amplify/ui-react`?
![image](https://user-images.githubusercontent.com/6165315/231206115-3fae05b5-8a19-4fac-84d6-5d3eeae3a9f8.png)

**Comment by reesscot** [comment]
@fcolomas Thanks again for calling this out! We've added a note to the docs:

> Note: When using the [Amplify React MapView component](https://ui.docs.amplify.aws/react/components/geo) you can use the [useControl hook from react-map-gl](https://visgl.github.io/react-map-gl/docs/api-reference/use-control) to render the Geofence control component. The [react-map-gl](https://visgl.github.io/react-map-gl) dependency is already installed through @aws-amplify/ui-react, you do not need to install it manually.

https://docs.amplify.aws/lib/geo/geofences/q/platform/js/#manage-geofences-in-your-application

**Comment by fcolomas** [comment]
Awesome guys! Thanks a lot for the clarification it would save me a ton of hours and I'm sure it will save a lot of time too!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
