### ISSUE TITLE
React Native stuck in Configuring state

### ISSUE THREAD

**Issue by Nikola-Milovic** [aws-amplify/amplify-ui#3640]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Expo

### What browsers are you seeing the problem on?

Android (React Native)

### Please describe your bug.

When using Expo, Expo router and trying to setup auth, the Auth is always in configuring state and never changing.

The setup is as follows. 

1. In main `index.js` file, the entrypoint to Expo router, initialize Amplify
1. In the top-level layout (the Expo router uses layouts, basically its the same as putting the code inside App.js, main.js, index.js in react/ vanilla react-native), put the ` <Authenticator.Provider>` and wrap the entire app inside it
1. Log the authState from the `useAuthenticator` hook and see that we're stuck in configuring state

Related issues, but not quite what I am encountering, their auth isn't being updated when they login/ logout, while I don't even get to that point https://github.com/aws-amplify/amplify-ui/issues/1497

### What's the expected behaviour?

I'd be in  'authenticated' or 'unauthenticated' state instead of stuck in `configuring`

### Help us reproduce the bug!

I created [a repo to reproduce the issue ](https://github.com/Nikola-Milovic/expo-amplify-issue), clone it and add the `.env` file

Create the `.env` file with the following entries

```
COGNITO_REGION=eu-xxx-1
COGNITO_USER_POOL_ID=eu-xxxxxx-1_xxxxxxx
COGNITO_USER_POOL_WEB_CLIENT_ID=5da2xxxxxxxxxxxxxxxx53
```

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

I am using manual setup for Amplify not using the CLI, I setup my infra with CDK, and then manually set it up in React Native to connect to those services.

Might not be an issue related to `amplify-ui` but rather amplify auth so I can repost this issue elsewhere if needed

**Comment by reesscot** [comment]
@Nikola-Milovic Are you using the `Authenticator` UI component? The `Authenticator.Provider` only works with the Authenticator UI Component as mentioned in the documentation:
https://ui.docs.amplify.aws/react-native/connected-components/authenticator/headless#useauthenticator-hook

**Comment by reesscot** [comment]
I reviewed [your reproduction repo](https://github.com/Nikola-Milovic/expo-amplify-issue) and can see that the Authenticator component is not in use. We are tracking a feature request to create a hook that works without the Authenticator UI, please follow this issue: https://github.com/aws-amplify/amplify-ui/issues/2634

In the meantime, if you want to use the Auth API directly without the component, you might consider wrapping the Auth hub listener in a hook:
https://docs.amplify.aws/lib/auth/auth-events/q/platform/js/
