### ISSUE TITLE
Angular optimization bailout warnings

### ISSUE THREAD

**Issue by siiulan** [aws-amplify/amplify-ui#3644]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Angular CLI (maybe, Idk)

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

I followed [troubleshoot page](https://ui.docs.amplify.aws/angular/getting-started/troubleshooting) and add whatever is in the Github repo content from `allowedCommonJsDependencies` to `projects.architect.build.options`. It resolved most warnings, but there are still four warnings left even though I added them all
```
Warning: .\Angular\node_modules\@aws-amplify\ui\dist\esm\helpers\authenticator\utils.mjs depends on 'xstate/lib/waitFor.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: .\Angular\node_modules\@aws-amplify\ui\dist\esm\theme\createTheme.mjs depends on 'style-dictionary/lib/utils/deepExtend.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: .\Angular\node_modules\@aws-amplify\ui\dist\esm\theme\createTheme.mjs depends on 'style-dictionary/lib/utils/flattenProperties.js'. CommonJS or AMD dependencies can cause optimization bailouts.  
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: .\Angular\node_modules\@aws-amplify\ui\dist\esm\theme\utils.mjs depends on 'style-dictionary/lib/utils/references/usesReference.js'. CommonJS or AMD dependencies can cause optimization bailouts. 
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Moreover, considering the warning source files, I felt like this cause a error on the display of the the Authenticator component: my Authenticator component on build webpage does not act normal: all the textField(box) which display direct text were displayed in a black underground and the box size shrinks compares to the box that hide the passwords

If you unhide the password, the box will dynamically shrink
![image](https://user-images.githubusercontent.com/54810735/229577714-119b33fc-3877-4eef-a50d-a2aae896c871.png)
![image](https://user-images.githubusercontent.com/54810735/229578064-0d85e1ea-3f97-48cf-bbbf-16b8b6f969b8.png)
This is not the same as what I saw on the Amplify UI webpage, do you feel like the warning message relate to this display discrepancy? If not, I can open another issue specifically for this display error.

Sorry, this is my first time writing a bug report in my life. I am also a beginner in Amplify Services and Angular, so please let me know if you need further info from me :) 

### What's the expected behaviour?

There should be no warning messages generated after developer resolve it by following steps on Amplify UI Webpage and Github repo.

(If this problem is related to the display discrepancy, the UI components should looks normal and functional after resolved the warning messages)

### Help us reproduce the bug!

This is my Angular version:
Angular CLI: 12.1.4
Node: 14.17.3      
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cdk                    12.2.13
@angular/cli                    12.1.4
@angular/material               12.2.13
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5

and my Amplify Version is 11.0.3

I followed whatever [Amplify docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#set-up-backend-resources) specify on adding the Authentication. and I successfully pushed it. However, this step doesn't produce any auth components and services in my local Angular project (weird point).

Then I followed steps configured my apps, then I got the error

### Code Snippet

In side angular.json I have
```typescript
// Put your code below this line.
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "cli": {
    "analytics": false
  },
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "myProject": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "myProject",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "allowedCommonJsDependencies": [ 
              "@aws-crypto/crc32",
              "@aws-crypto/sha256-browser",
              "@aws-crypto/sha256-js",
              "crypto-js/sha256",
              "axios",
              "buffer",
              "camelcase-keys",
              "crypto-js/core",
              "crypto-js/enc-base64",
              "crypto-js/hmac-sha256",
              "crypto-js/lib-typedarrays",
              "fast-xml-parser",
              "isomorphic-unfetch",
              "js-cookie",
              "lodash",
              "lodash/get",
              "lodash/isEmpty",
              "lodash/isEqual",
              "qrcode",
              "ulid",
              "style-dictionary/lib/utils/deepExtend",
              "style-dictionary/lib/utils/flattenProperties",
              "style-dictionary/lib/utils/references/usesReference",
              "url",
              "uuid",
              "xstate/lib/actions",
              "xstate/lib/waitFor",
              "zen-observable"
             ],
            "outputPath": "dist/myProject",
            "index": "src/index.html",
            "baseHref": "/index.html/",
            ....
```

**Comment by sreeramsama** [comment]
We are able to reproduce the optimization bailouts warnings with a setup similar to yours, but **not seeing** any odd behavior on text fields of the Authenticator.

Are you using any custom css or importing any css files?

**Comment by siiulan** [comment]
I am actually using .scss in my Angular project, but I thought scss is a superset of css so that wouldn't be the problem. Would that be where the issue comes from? and Yes I did defined some global styles of components in styles.scss, do you know what perhaps the name of this textbox is so that I can check whether if I defined something under the same name that cause the conflicts

**Comment by sreeramsama** [comment]
Checkout for 'amplify-input' class, or 'input' element type

**Comment by siiulan** [comment]
I'll check. By the way, do you know how to cancel off these optimization bailouts warnings that you guys also ran into? Is it safe to leave it there? That was odd because I have already included them.

**Comment by sreeramsama** [comment]
We are looking into fixing those optimization bailouts warnings.

**Comment by reesscot** [comment]
@siiulan Can you try adding the following to your angular config to remove the optimization warnings?

```
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
     "allowedCommonJsDependencies": [
        "style-dictionary",
        "xstate"
     ]
     …
   }
   …
},
```
