### ISSUE TITLE
Amplify has not been configured correctly

### ISSUE THREAD

**Issue by zain1629** [aws-amplify/amplify-ui#3653]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Create React App

### Please describe your bug.

Using withAuthenticator to signUP or signIn i am getting the error, i do see the UI but when i try to create a user i get the following error. However, when i try to manually signup using just the Amplify auth library it works.

` [ERROR] 29:05.773 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.`

### What's the expected behaviour?

I get a UI asking user to signUp or signIn 

### Help us reproduce the bug!

Use withAuthenticator function for aws ui library for react native.

### Code Snippet

```typescript
// Put your code below this line.
`import 'react-native-gesture-handler';
import { NavigationContainer } from '@react-navigation/native';
import * as eva from '@eva-design/eva';
import { ApplicationProvider, IconRegistry } from '@ui-kitten/components';
import { default as theme } from './theme.json';
import { EvaIconsPack } from '@ui-kitten/eva-icons';
import Amplify, {Auth} from 'aws-amplify'
import {
  withAuthenticator,
} from '@aws-amplify/ui-react-native';
import awsconfig from './src/aws-exports'
import RootStack from './app/navigators';

const App = () => {
  Amplify.configure(awsconfig);
  Auth.configure(awsconfig);
  return (
    <>
      <IconRegistry icons={EvaIconsPack} />
      <ApplicationProvider {...eva} theme={{ ...eva.dark, ...theme }}>
        <NavigationContainer>
          <RootStack />
        </NavigationContainer>
      </ApplicationProvider>
    </>
  );
}

export default withAuthenticator(App)`

```

**Comment by reesscot** [comment]
@zain1629 Closing out as we haven't heard back. Please let us know if you have any further questions.
