### ISSUE TITLE
@aws-amplify/angular-ui: "Verify" component is not working

### ISSUE THREAD

**Issue by slaymance** [aws-amplify/amplify-ui#366]
The [e2e tests for "verify user"](https://github.com/aws-amplify/amplify-ui/blob/main/packages/e2e/features/ui/components/authenticator/verify-user.feature) are not functioning for Angular. When a user with an unverified status signs in, the "VerifyUser" component never loads.

**Comment by slaymance** [comment]
Fixed in [PR 369](https://github.com/aws-amplify/amplify-ui/pull/369).

**Comment by wlee221** [comment]
Thanks @slaymance!
