### ISSUE TITLE
submitForm from useAuthenticator does not return a success or failed response

### ISSUE THREAD

**Issue by yannickrocks** [aws-amplify/amplify-ui#3666]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React, React Native

### Which UI component?

Authenticator

### How is your app built?

Create React App Native

### What browsers are you seeing the problem on?

iOS (React Native)

### Please describe your bug.

Hi there

I have created a custom SignIn component and added it to the Authenticator component override. I am also using the `useAuthenticator` hook

The issue isn't getting a successful login. It is being able to detect a failed login which I would then like to display: 'failed email or password'

```typescript
  const handleSignIn = () => {
        submitForm({
          type: 'SIGN_IN',
          username: email,
          password,
        });

        // AWAIT SOME RESPONSE FROM SUBMIT FORM???
  };
```

The code about is a snippet from my component where `handleSignIn` is attached to a Button Component. 

Is there a way for `submitForm` to return a response if it has succeeded or not? 

 

### What's the expected behaviour?

Some success or failed response from the SubmitForm method.

### Help us reproduce the bug!

1. Build a custom signin Component and override it in the Authenticator component
2. Launch and try to make the login fail.

**Comment by wlee221** [comment]
I would suggest you use [service override](https://ui.docs.amplify.aws/react-native/connected-components/authenticator/customization#override-function-calls) and use `Auth.signIn` directly. So this would be:

```tsx
import { Auth } from "aws-amplify";

const MySignIn = () => {
  const { submitForm } = useAuthenticator((context) => [
    context.submitForm
  ]);

  // attached to your button
  const handleClick = () => {
    submitForm({
      username: email,
      password,
    });
  };

  return (
    <View>...</View>
  );
};

const MyApp = () => {
  // service override
  const handleSignIn = async (formValues) => {
    try {
      return await Auth.signIn(formValues);
    } catch (e) {
      // you can do any parsing here
      throw "Some Custom Error Message";
    }
  };

  return (
    <Authenticator.Provider>
      <Authenticator
        components={{ SignIn: MySignIn }}
        services={{ handleSignIn }}
      />
    </Authenticator.Provider>
  );
};

**Comment by wlee221** [comment]
Note that you're doing a full subcomponent override, you can also just use `error` from `useAuthenticator`, and do any error message mapping there. This is simpler, and I would recommend this unless you want to do more with service overrides.

```ts
const { error } = useAuthenticator(context => [context.error]);

// do some parsing against `error`, and render that instead.
```

**Comment by yannickrocks** [comment]
> Note that since you're doing a full subcomponent override, you can also just use `error` from `useAuthenticator`, and do any error message mapping there. This is simpler, and I would recommend this unless you want to do more with service overrides.
> 
> ```ts
> const { error } = useAuthenticator(context => [context.error]);
> 
> // do some parsing against `error`, and render that instead.
> ```

I will give this a go. Thanks for the reply @wlee221 
I will update if successful :D

**Comment by yannickrocks** [comment]
Hi @wlee221 
This is what I have come up with for now.
```  
/** When signing in, if it fails, an error will be present.
   * A failed error will say "Incorrect username or password" but we use email so changed the wording
   */
  useEffect(() => {
    if (error) {
      setPasswordError('Invalid email or password');
    }
  }, [error]);

  const handleSignIn = () => {
    if (!email || !password) {
      setPasswordError('Please enter your email and password');
    } else {
      if (!validEmail.test(email)) {
        setEmailError('Please enter a valid email');
        return;
      }

      submitForm({
        type: 'SIGN_IN',
        username: email,
        password,
      });
    }
  };
```

As you can see, I submit the form and then awaiting if the error changes. If it does, then I know something went wrong. 

Otherwise, it was successful. Thoughts?

**Comment by yannickrocks** [comment]
Hi @wlee221 
This is what I have come up with for now.
```  
/** When signing in, if it fails, an error will be present.
   * A failed error will say "Incorrect username or password" but we use email so changed the wording
   */
  useEffect(() => {
    if (error) {
      setPasswordError('Invalid email or password');
    }
  }, [error]);

  const handleSignIn = () => {
    if (!email || !password) {
      setPasswordError('Please enter your email and password');
    } else {
      if (!validEmail.test(email)) {
        setEmailError('Please enter a valid email');
        return;
      }

      submitForm({
        type: 'SIGN_IN',
        username: email,
        password,
      });
    }
  };
```

As you can see, I submit the form and then awaiting if the error changes. If it does, then I know something went wrong. 

Otherwise, it was successful. Thoughts?

**Comment by wlee221** [comment]
Hi @yannickrocks! 

I'm assuming you have `useAuthenticator` above your code snippet to get the code snippet. What you have looks good, other than that `submitForm` doesn't need `type` in its parameter object. Just `username` and `password` should be fine.

But otherwise, looks good! I'll close this issue, but feel free to tag me if you have further questions.
