### ISSUE TITLE
Vue 3, instructions for changing colors don't work

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-ui#3667]
Here's my style block in app.vue of my nuxt app:
```
<style>

:root {
    --amplify-primary-color: #00796B;
    --amplify-primary-tint: #008c7c;
    --amplify-primary-shade: #005a50;
}

</style>
```

But the colors in the UI remain unchanged.  I've tried moving that :root block to my login.vue page as well, without success.  How do you change these colors?  I'm fine hardcoding values in however it needs to get done.  Just need a solution.

nuxt: 3.3.3
vue: 3.2.47
@aws-amplify/ui-vue: 3.1.12

https://docs.amplify.aws/ui/customization/theming/q/framework/vue/

dev tools image:
![image](https://user-images.githubusercontent.com/3038809/230206924-bcda17f9-3044-4023-ad13-9c838201aded.png)

**Comment by hbuchel** [comment]
Hi @camhart, it looks like that docs page is out of date, sorry about that. Please see https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#css-style for css custom properties you can override to theme the component. You can also find more available tokens here: https://ui.docs.amplify.aws/vue/theming/default-theme#explore-theme-tokens

Here is an example: https://codesandbox.io/p/sandbox/nostalgic-marco-4y249l?file=src%2FApp.vue

Let us know if that helps!

**Comment by reesscot** [comment]
@camhart Please let us know if the fix didn't work for you. Closing for now as we haven't heard back.
