### ISSUE TITLE
@aws-amplify/angular-ui: Set up TOTP QR code doesn't display

### ISSUE THREAD

**Issue by slaymance** [aws-amplify/amplify-ui#367]
The QR code for the Angular TOTP component doesn't display.

![Screen Shot 2021-09-13 at 10 55 24](https://user-images.githubusercontent.com/26472139/133133107-00d5bfd5-37b6-4a55-a1df-f2af370d1b49.png)

**Comment by wlee221** [comment]
#370 closes this 🚀
