### ISSUE TITLE
useAuthenticator - authStatus not updating past `configuring`

### ISSUE THREAD

**Issue by smozely** [aws-amplify/amplify-ui#3729]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

Have an application where there is some things a user can do before logging in, and then pages / components that change once they are logged in. And what I need to do is know if the user is authenticated before attempting some API calls

So I was trying to use this ... 
https://ui.docs.amplify.aws/react/connected-components/authenticator/advanced#authentication-check

And look at `authStatus` to wait and see if the user is authenticated. 

But `authStatus` will only go to `configuring` if the user is unauthenticated. If they are authenticated already (and refreshing the page) it will end up at `authenticated` state.

### What's the expected behaviour?

That it would go to `unauthenticated` state

### Help us reproduce the bug!

See snippet. Subtly different from the example linked above, but seems because it doesn't render the <Authenticator> component we get this behaviour.

Will only display `Loading`

### Code Snippet

```typescript
  const { user, authStatus, route } = useAuthenticator();
  return (
    <>
      {authStatus ? (
        'configuring' && <div>Loading...</div>
      ) : authStatus === 'authenticated' ? (
        <div>FOO</div>
      ) : (
        <div>BAR</div>
      )}
    </>
  );

```

**Comment by vasylnt** [comment]
+1. Facing the same issue:

authState is not updated past **configuring** when user is not logged in.

I am using federatedSignIn via Cognito Hosted UI (OAuth2)

The app is wrapped in Authenticator.Provider
       
```
<Authenticator.Provider>
    <App />
</Authenticator.Provider>

```

Checking  authState in App

```
const { authStatus, isPending } = useAuthenticator(context => [context.authStatus, context.isPending]);
const isAuthenticated = (authStatus === 'authenticated')
const isUnauthenticated = (authStatus === 'unauthenticated')
const isLoading = (isPending || authStatus === 'configuring')
.........

```

If user is not logged in, authStatus never changes from **configuring** causing loading last forever.

I have also tried to use 'toFederatedSignIn' hook but it does not redirect to federated signin. Nothing happens when clicking on the button. Therefore using _Auth.federatedSignIn()_ instead

```
const LoginButton = () => {
  const {toFederatedSignIn} = useAuthenticator()
  return <Button onClick={toFederatedSignIn}>Log in</Button>
}

```

**Comment by calebpollman** [comment]
@smozely  @vasylnt  We merged a commit (https://github.com/aws-amplify/amplify-ui/pull/3806) that updates `useAuthenticator.authStatus` on sign in events performed directly via `Auth.signIn`. You can try it out by installing `@aws-amplify/ui-react` using the `next` tag:
```sh
npm install @aws-amplify/ui-react@next
```
