### ISSUE TITLE
@aws-amplify/ui-react: PayloadTooLarge / Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by datgreatkhan** [aws-amplify/amplify-ui#3738]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Expo Project

### What browsers are you seeing the problem on?

iOS (React Native)

### Please describe your bug.

Whether I use `withAuthenticator` or just the normal `Authenticator` component, the app will crash on load due to "Text strings must be rendered within a <Text> component" being spammed and additionally a "PayloadTooLarge" error as well.

I am using Expo CLI with React Native.

If I use `aws-amplify-react-native` instead (which I initially was), `Authenticator`/`withAuthenticator` works with no issue.

### What's the expected behaviour?

I expect to be able to use Authenticator/withAuthenticator without these issues.

### Help us reproduce the bug!

1. Have Auth / API set up on backend.
2. Follow setup guide here for front-end Authenticator: https://ui.docs.amplify.aws/react/connected-components/authenticator
3. Start app with `expo start`
4. App crashes with dozens of `Text strings must be rendered within a <Text> component`, then a `PayloadTooLarge` error

### Code Snippet

```typescript
import { Amplify, Auth } from 'aws-amplify';
import awsconfig from './app/aws-exports';
Amplify.configure(awsconfig);

import { Authenticator } from '@aws-amplify/ui-react';

....App function...

export default withAuthenticator(App);
```

### Additional information and screenshots

Logs:

![image](https://user-images.githubusercontent.com/129341569/232180150-89f9842d-bd07-46e0-902e-dbfc37212a89.png)

**Comment by calebpollman** [comment]
Hi @datgreatkhan Can you try installing `@aws-amplify/ui-react-native` updating the import? Example:
```
import { withAuthenticator } from '@aws-amplify/ui-react-native';

....App function...

export default withAuthenticator(App);
```

**Comment by datgreatkhan** [comment]
> 

Lol. That worked - thank you. I didn't realize the imports were platform specific and it was confusing me.

How do I allow it to have the "Sign in with Google" button too?

**Comment by datgreatkhan** [comment]
> 

Thank you.

I'll look to implementing my own page for federated sign in for the meantime.
