### ISSUE TITLE
useBreakpointValue is set to `base` on first render despite size of the screen

### ISSUE THREAD

**Issue by Bryson14** [aws-amplify/amplify-ui#3744]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

CRA

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

when using `useBreakpointValue`, the `base` or smallest breakpoint is used on the first render of the screen on Chrome. 

At first, I was thinking something was wrong with my code, but then I realized even visiting the [responsive design page](https://ui.docs.amplify.aws/react/theming/responsive#usebreakpointvalue), the error can be seen:

![Chrome, full screen seeing `base` content](https://user-images.githubusercontent.com/43580701/232773182-51fce081-9b6f-4ea0-b4b9-9d13f5f43d0c.png)

However visiting this page on Firefox, I see the appropriate content based on the size of my screen.

![image](https://user-images.githubusercontent.com/43580701/232773409-ee3ebf34-c77b-4405-bd4d-e6c9b0b0d1dd.png)

To fix this on Chrome, I had to open dev tools, resize the screen, then exit dev tools. This triggered the hook to start working and then show the appropriate `xlarge` breakpoint.

### What's the expected behaviour?

On Chrome, `usebreakpoint` doesn't display the `large` or `xlarge` breakpoint value when showing the component. After the screen width changes, then the hook works.

Chrome on iPhone (webkit) doesn't have the same issue.

### Help us reproduce the bug!

I am using chrome Version 112.0.5615.121 on Windows 10

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

https://user-images.githubusercontent.com/43580701/232774900-d2643145-c160-4199-a3e6-73b619e4bd42.mp4

**Comment by calebpollman** [comment]
Thanks for reporting this @Bryson14! Was unable to replicate the issue, is it possible that you may have a chrome extension installed that may be interfering? You should be able to quickly test by attempting to replicate in a private chrome window

**Comment by Bryson14** [comment]
I tried to reproduce it also, but perhaps it was a configuration on my browser. I'll close the issue.
