### ISSUE TITLE
How to import AuthStatus type?

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-ui#3766]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I am using React with Typescript

When I use used the following line from the Authenticator [doc](https://ui.docs.amplify.aws/react/connected-components/authenticator/advanced#authentication-check) 
{authStatus !== 'authenticated' ? <Authenticator /> : <Home />}, I got this Typescript error:

```
This comparison appears to be unintentional because the types '{ authStatus: AuthStatus; }'      
and 'string' have no overlap.
```

How do I import AuthStatus type?

### Please describe a solution you'd like.

I would like to import AuthStatus type and also other types that need to be exported

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by Jun711** [comment]
@calebpollman 

```
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { AuthStore } from "../stores/auth";
import AuthenticatedPage from ".";

const formFields = {
  signIn: {
    username: {
      label: 'Email',
      placeholder: 'Enter your email',
    },
  },
  signUp: {
    username: {
      label: 'Email',
      placeholder: 'Enter your email',
    },
  }
}

const LoginPage: React.FC = () => {
  const authStore = AuthStore.useContainer();
  const { user, signOut } = useAuthenticator((context) => [context.user]);
  const { authStatus } = useAuthenticator(context => [context.authStatus]);
  console.log('user ', user, 'authStatus ', authStatus)

  // this part will have the error
  if (authStatus == 'authenticated' || authStatus == 'confirmSignUp') {

  }

  return (
    <>
      {authStatus !== 'authenticated' ? <Authenticator /> : <AuthenticatedPage />}
    </>
  );
};

export default LoginPage;
```

**Comment by Jun711** [comment]
Hi @calebpollman, btw is it expected that the authStatus event is fired twice?
console log would print 2 times when I sign up and log in.

<img width="1192" alt="Screen Shot 2023-04-29 at 5 37 36 PM" src="https://user-images.githubusercontent.com/6880939/235329952-03fda8c6-b1c4-4fbf-8133-383ad0b630d5.png">

<img width="1187" alt="Screen Shot 2023-04-29 at 5 38 53 PM" src="https://user-images.githubusercontent.com/6880939/235329978-ea690346-e01c-4bb1-9072-8d50ba10d52a.png">

**Comment by calebpollman** [comment]
@Jun711 Are you still running in to issues with the types?

Regarding the double `console.log`, not entirely sure what `authStore` is doing, it it possible that it (or the parent component rendering `LoginPage`) is causing an additional render?

**Comment by Jun711** [comment]
@calebpollman 
Yes, the code to get the type error is above https://github.com/aws-amplify/amplify-ui/issues/3766#issuecomment-1528905059

specifically this part:
```
  // this part will have the error
  if (authStatus == 'authenticated' || authStatus == 'confirmSignUp') {

  }
```

**Comment by calebpollman** [comment]
The `authStatus` string union does not include `confirmSignUp`, so the type error is to be expected.

**Comment by Jun711** [comment]
@calebpollman 
I see, yea confirmSignUp is under route. 
Anyway, It is the same with just 'authenticated'. I had to do authStatus.toString() to make that TypeScript error disappear.
It is better to have the type exported, right?

```
// this part will have the error
  if (authStatus == 'authenticated') {

  }
```

**Comment by wlee221** [comment]
Hmm, that should not be the case. What if you use `===` instead of `==`? I tried to repro this, but this was working this as expected for me. 

My code: https://codesandbox.io/s/useauthenticator-authstatus-p1xzej?file=/src/App.tsx:436-485. 

Not disagreeing exporting `AuthStatus` would make this easier, but we want to first make sure the code you have is working.

**Comment by reesscot** [comment]
+1 to @wlee221 comment. I'm able to see the `AuthStatus` type showing up in CodeSandbox:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/6165315/236079961-f4778b39-4647-4a01-a3b2-7ca23c5cce78.png">

**Comment by Jun711** [comment]
@wlee221 @reesscot 
I removed toString() just now and there was no such error.
Sorry, I guess I must have had a typo or comparing with the wrong value.

Would it be good to have AuthStatus exported so that users can use it for comparison like this
```
function App() {
  const { authStatus } = useAuthenticator((context) => [context.authStatus]);
  useEffect(() => {
    // eslint-disable-next-line
    if (authStatus == AuthStatus.unauthenticated) {
      console.log("do something here");
    } else if (authStatus === AuthStatus.authenticated) {
      console.log("do something else here");
    }
  }, [authStatus]);

  return <Authenticator>Hello</Authenticator>;
}
```

**Comment by wlee221** [comment]
@Jun711 FYI, you can get the type of `authStatus` by:

```ts
const authStatus: ReturnType<typeof useAuthenticator>['authStatus'] = 'authenticated'
```

for the time being.
