### ISSUE TITLE
vue3 slots documentation outdated?

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-ui#3795]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

nuxtjs (vue)

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Documentation at https://ui.docs.amplify.aws/vue/connected-components/authenticator/advanced doesn't work.  I'm thinking it may be outdated (as other docs there have been outdated as well).  How do I put a footer slot in?

### What's the expected behaviour?

footer slot should work

### Help us reproduce the bug!

...

**Comment by reesscot** [comment]
@camhart Can you please provide some sample code of what you are trying to do? We have integration tests for the custom slots and I also fired up our example app. I'm seeing the slots show up:

```
    <template v-slot:sign-in-footer>
      <div style="text-align: center">
        <button
          @click="toResetPassword"
          class="amplify-button amplify-field-group__control"
          data-fullwidth="false"
          data-size="small"
          data-variation="link"
          type="button"
          style="font-weight: normal"
        >
          Reset Password
        </button>
      </div>
    </template>
```
https://github.com/aws-amplify/amplify-ui/blob/main/examples/vue/src/pages/ui/components/authenticator/custom-slots/index.vue#L96-L110

![image](https://user-images.githubusercontent.com/6165315/235270000-b458c919-be7d-48f1-a934-71175637ed83.png)


Did you see this documentation? https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#headers--footers
