### ISSUE TITLE
useAuthenticator hook doesn't have confirmSignUp success route 

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-ui#3797]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

According to the document, I can use useAuthenticator hook to access route string that represents the current authState
https://ui.docs.amplify.aws/react/connected-components/authenticator/advanced#access-auth-state

However, there doesn't seem to be a state for confirmSignUp success. I want to receive a state change when the user successfully verify their email

The state seems to transition from `confirmSignUp` to `transition` and then `authenticated` during the confirmSignup with code process. 
When I log in, the state is also `authenticated`

### Please describe a solution you'd like.

I would like useAuthenticator hook to return a route right when confirmSignUp with code is successful. This is probably the same for reset password process. 

### We love contributors! Is this something you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by wlee221** [comment]
Hi @Jun711, thank you for opening this feature request!

`useAuthenticator.route` is expected to show the current state, but not necessarily represent its related success or failure events. What is your use case for these events? We can consider potential solutions or workarounds.

**Comment by wlee221** [comment]
For that use case, I'd recommend using [`Hub`](https://docs.amplify.aws/lib/utilities/hub/q/platform/js/) from `aws-amplify`. You could listen to its `auth` [channel](https://docs.amplify.aws/guides/authentication/listening-for-auth-events/q/platform/js/), and respond to `confirmSignUp` [event](https://github.com/aws-amplify/amplify-js/blob/c682c5eb5189bd90ac3b05305056aeb91fe69176/packages/auth/src/Auth.ts#L560-L561).

So in React, you could do something like

```tsx
import { useEffect } from "React";
import { Hub } from "aws-amplify";

const App = () => {
  useEffect(() => {
    const unsubscribe = Hub.listen("auth", (data) => {
      switch (data.payload.event) {
        case "confirmSignUp":
          // do something
          break;
      }
    });
    return () => unsubscribe();
  });
  // ...
};
```

We are not considering extending `route` for the time being, but please let us know if this does not work or other concerns.

**Comment by Jun711** [comment]
@wlee221 I see. I will use Hub instead then, I thought `useAuthenticator` hook was meant for such use case.

1) is `useAuthenticator` hook only meant for React UI? 
2) on the `useAuthenticator` hook page, there is no link to Hub, maybe it would be good to add a related document link?

**Comment by wlee221** [comment]
1. Yes, you're absolutely right. This is a common confusion that the docs really hasn't made it clear. 
2. Point taken! I'll bring it up to the team.

I'll close this issue since a solution using JS library has been proposed. Please feel free to ask any further question or open a new issue 🙏

**Comment by waltermvp** [comment]
@wlee221 is this still the case? I just ran into the same issue and expected the transition to occur automatically and to show my custom ConfirmSignUp component.
