### ISSUE TITLE
FR (Storage Manager): Expose top-level files prop for clearing selected files

### ISSUE THREAD

**Issue by kwwendt** [aws-amplify/amplify-ui#3856]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Storage (File Uploader)

### Please describe your feature-request in detail.

Currently, there is no way to override the list of displayed files in the `StorageManager` component (at least that I've found). This is not ideal for cases where you need to reset the selected files to an empty array. For example, when using `StorageManager` in a form, if a user successfully uploads the files and submits, we perform a form clear but the files that were part of the upload still remain until the entire component is refreshed.

### Please describe a solution you'd like.

A `useImperativeHandle` would be ideal here to give users control over the existing files and clear them as needed.

Cloudscape `FileUpload` component has this capability with an `onChange` prop and a `value` props that can be specified by the user. [Reference](https://cloudscape.design/components/file-upload/?tabId=playground).

This would allow a user to reset the Storage Manager after the uploads are complete without having to click X on each file.

### We love contributors! Is this something you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
This was released in `@aws-amplify/ui-react-storage` version 2.0.0 🚀
https://www.npmjs.com/package/@aws-amplify/ui-react-storage
