### ISSUE TITLE
Need to create React UI with amplify add auth command

### ISSUE THREAD

**Issue by jagrutishah12345** [aws-amplify/amplify-ui#3877]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

 Iam facing error in implementing Authentication using Amplify in React App.Below  link that I am Following for implementing but when Iam updating index.js and app.js showing error
.aws/exports can not be resolved
https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/
Please help here

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ioanabrooks** [comment]
Hi @jagrutishah12345, were you able to create the authentication service successfully, with no errors? If so, the CLI should have created the `aws-exports.js` file in the src directory of our project, which you need to import in your index.js: `import config from './aws-exports';`. Please check if the file exists, if not, provide any errors encountered in the CLI, omitting sensitive information.

**Comment by jagrutishah12345** [comment]
Hi,
, after adding authentication component showing *uncaught runtime error* in
browser,  When previewing the React application,
also i am using Cloud9

[image: image.png]

**Comment by ioanabrooks** [comment]
@jagrutishah12345 I am not able to reproduce the issue when following the steps in the tutorial you provide in cli. To assist you further, please provide us with more details about the issue, specifically commands you ran in Cloud9 terminal, error messages while setting up Auth.
