### ISSUE TITLE
Auto upload in StorageManager and FileUploader

### ISSUE THREAD

**Issue by DannielMts** [aws-amplify/amplify-ui#3906]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Storage (File Uploader)

### Please describe your feature-request in detail.

I am currently using FileUploader but I noticed that it will be discontinued and we will use StorageManager.

Is there a way to disable auto upload in StorageManager?

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ioanabrooks** [comment]
Hi, @DannielMts thanks for using File Uploader! 
Storage Manager does not support this feature at the moment, but we don't plan to deprecate File Uploader until reaching feature parity.
Will resolve this ticket in favor of this [one](https://github.com/aws-amplify/amplify-ui/issues/3796) tracking  the same feature request. Let us know if you have other questions!
