### ISSUE TITLE
FR (Primitives): Allow Divider color, width and border style to be customized via style prop

### ISSUE THREAD

**Issue by ioanabrooks** [aws-amplify/amplify-ui#3945]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Primitive components

### Please describe your feature-request in detail.

The Divider primitive supports customization through the `border` prop:

```
<Divider border="5px solid pink" />
```

It would be great if color, width and border style could also be supported independently, such that if I only want to change the color I don't have to specify all border properties.

For additional context, there are other ways to customize color, through `borderColor` design token and css variable `--amplify-components-divider-border-color`.

### Please describe a solution you'd like.

Add `borderColor`, `borderWidth` and `borderStyle` style props for additional ways to style the Divider.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by paras11917** [comment]
I may be able to implement this feature request.

**Comment by paras11917** [comment]
I have created PR please respond. This is my first time so please guide me if I made any mistakes I will try to improve

**Comment by shachargiladi** [comment]
Is it still relevant?

**Comment by judygab** [comment]
I raised a PR to modify style props to include customizable border props but it isn't specific to the divider:
https://github.com/aws-amplify/amplify-ui/pull/3965

**Comment by hbuchel** [comment]
Closing as this was addressed in the contributor PR that was merged here: https://github.com/aws-amplify/amplify-ui/pull/4161
