### ISSUE TITLE
Angular Authenticator: Calling a function after a successful login

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#3950]
<sup>Originally posted by **@Rajan-Gupta1** July 19, 2022</sup>
```
<amplify-authenticator>
  <ng-template
    amplifySlot="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
  </ng-template>
</amplify-authenticator>
```
In the above template, I would like a function to be called after a successful login so that I can do retrieve information from backend and then navigate to a route using the angular router. I have looked at the documentation but could not find a way to call a function after a successful login. 
I wish there was a sample integration of amplify auth with a sample app like https://github.com/changhuixu/angular-material-admin
Any help on how to call a function after a successful login?

**Comment by wlee221** [comment]
Hi! We'll be closing this issue since this has been answered in #2314 and #2324. Please let us know if you're looking for more help, and I'll be happy to assist.
