### ISSUE TITLE
Bug(Docs): Table of Contents does not update properly when navigating between pages

### ISSUE THREAD

**Issue by tjleing** [aws-amplify/amplify-ui#3969]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

N/A

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

On the UI docs site, certain page configurations cause ToC issues when navigating between platforms.  For example, checking out commit hash `66995a43896963fe91772f1a45e8cc411479bd3b` from [this PR](https://github.com/aws-amplify/amplify-ui/pull/3892) will display the previous page's ToC when switching from the Android platform to React on the page at path `react/connected-components/liveness/troubleshooting`.

Going directly from a page without a ToC to that React path displayed the following:
![image](https://github.com/aws-amplify/amplify-ui/assets/9170787/1168cbc4-bfb7-44c2-9bee-6d726b897d4d).  Going from Android to React instead will simply maintain the Android page's added headers instead of trimming them down to only the ones relevant to React.  These errors are not seen when navigating around other pages from basic testing, but may have missed some use cases.

Technical details:
- Going from Android to React doesn’t trigger the table of contents’ `updateHeaders` observer (in the `Layout` component), but going the other way does.  This lifecycle event is supposed to be called when the DOM finishes compilation (`React.useLayoutEffect`).
- Removing `return () => observer.disconnect` from that lifecycle event fixes the issue but at the cost of constantly registering new observers that listen to all the DOM changes.
- Adding a blank file (as seen in the PR) fixes the problem, so the issue is likely some interaction between React or Next.js that shortcuts a lifecycle hook or similar event when they can just move the DOM around.  This would explain why Android -> React causes the issue but React -> Android doesn't -- since the Android content is a superset of the content on the React page, React/Next.js has to go through the entire process of building the page, which successfully calls the hook.

### What's the expected behaviour?

ToC is updated to match the headings on the page in all scenarios.

### Help us reproduce the bug!

Check out `66995a43896963fe91772f1a45e8cc411479bd3b` from [this PR](https://github.com/aws-amplify/amplify-ui/pull/3892); `yarn && yarn docs dev`; go to `react/connected-components/liveness/troubleshooting` and switch between Android and React; see incorrect ToC headers.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
Thanks @tjleing for the investigation. We've had issues on other pages we fixed with a similar work around https://github.com/aws-amplify/amplify-ui/pull/3722 and https://github.com/aws-amplify/amplify-ui/pull/3549 Will leave this open as a reminder for us to fix :)

**Comment by tjleing** [comment]
Ohh that makes a lot more sense, static content doesn't trigger the hook.  Thanks for the context!  I'll leave the issue open too.

**Comment by jordanvn** [comment]
This is able to be solved with a workaround, but any new static pages will still require the same workaround. Closing as a "won't fix"
