### ISSUE TITLE
No Loader primitive in Figma

### ISSUE THREAD

**Issue by stuartlangridge** [aws-amplify/amplify-ui#4018]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

create-react-app

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

https://docs.amplify.aws/console/uibuilder/figmatocode/#step-1-set-up-figma-file says:

> Primitives: Primitives are building-block components such as alerts, buttons, and badges. These primitives correspond to the [Amplify UI primitives](https://ui.docs.amplify.aws/react/components) and get exported to code with all the primitive properties.

However, [Loader](https://ui.docs.amplify.aws/react/components/loader) is a primitive, but doesn't seem to exist in Figma. How does one add a Loader component to an existing larger component in Figma?

Possibly the way to do this is to add a placeholder component in Figma, such as a Frame, and then add a Loader to this Frame (which becomes a `<Flex>` in React) from code with something like `<MyLargerComponent overrides={{myframe: {children: <Loader />}}} />`, but this doesn't work because a Flex doesn't allow overriding children.

### What's the expected behaviour?

Loader exists in the Figma primitives.

### Help us reproduce the bug!

Look in the Figma primitives :-)

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by dbanksdesign** [comment]
I am working on a fix for this, and the next version of the Figma file should have the Loader primitive in it. We are planning to ship the next version of the Figma file late next week.

**Comment by dbanksdesign** [comment]
The new version of the Figma file is live with the Loader and Placeholder primitives! https://www.figma.com/community/file/1047600760128127424/AWS-Amplify-UI-Kit 

Feel free to re-open or open a new issue if you have any problems.
