### ISSUE TITLE
Automatic Sign In does not work with phone number

### ISSUE THREAD

**Issue by wlee221** [aws-amplify/amplify-ui#404]
Automatic signin has not been working with phone number because `signInActor` does not have the country code information to login after confirm sign up stage. [[Asana](https://app.asana.com/0/1200334286823427/1201022646170709/f])]

**Comment by eddiekeller** [comment]
I believe this works now. Just tried it out locally. Still an issue for you, @wlee221 ?

**Comment by eddiekeller** [comment]
Confirmed on Slack that this is fixed. Closing!
