### ISSUE TITLE
Amplify React Cognito - Loader Persisting After Backing Out from Google SSO Sign-in

### ISSUE THREAD

**Issue by AkashWeybee** [aws-amplify/amplify-ui#4059]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

In react cognito amplify login register google sso

> I clicked on 'sign in with with google'
> loader by cognito amplify is there and says 'Signing in'
> list of google account is displayed
> When i click back button => loader is still there, it should not be there

### What's the expected behaviour?

When a user initiates the 'Sign in with Google' process and then decides to back out (by clicking the back button or otherwise cancelling the sign-in), the loading indicator provided by Amplify should be dismissed, and the UI should return to its initial state, indicating that no sign-in process is currently taking place

### Help us reproduce the bug!

> I clicked on 'sign in with with google'
> loader by cognito amplify is there and says 'Signing in'
> list of google account is displayed
> When i click back button => loader is still there

Also try on mobile browser, android IOS, 
I've tried on iPhone 14 pro and on desktop, it's there

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

"@aws-amplify/ui-react": "^4.3.8"

**Comment by roque510** [comment]
> Hi @AkashWeybee, we are looking into this. We could reproduce this in Next.js, but not in CRA. Do you have some minimal repro repo that we could use by any chance?

was this fixed in Next.js? or what is the status on it? still an issue for me

**Comment by calebpollman** [comment]
@AkashWeybee @roque510  This issue has been fixed in `@aws-amplify/ui-react@6.0.2`, please upgrade to get the fix
