### ISSUE TITLE
Social Providers for React Native Authenticator

### ISSUE THREAD

**Issue by Reedeme** [aws-amplify/amplify-ui#4080]
### On which framework/platform would you like to see this feature implemented?

React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

The Authenticator component allows Social providers for React, but not React Native it would seem? Could you make this functionality available to React Native too please?

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @Reedeme, 
Thank you for your feature request. There's an existing Feature Request tracking this here https://github.com/aws-amplify/amplify-ui/issues/2576

Please follow progress on this on #2576 and add a comment or +1. Closing this out as duplicate.
