### ISSUE TITLE
Icon used in Rating component is obscured after setting value

### ISSUE THREAD

**Issue by gamename** [aws-amplify/amplify-ui#4089]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

NextJS

### What browsers are you seeing the problem on?

Chrome, Safari

### Please describe your bug.

Background:
I am using a single icon to represent a percentage.  The higher the percentage, the more the icon is filled in with color.  In other words, a value of 50% would mean the icon is half filled with color.  The icon is very large.

Bug:
When I set the Rating value to anything other than 1, the icon shrinks and is partially obscured.  (see attached screen shots)

### What's the expected behaviour?

The icon should stay visible and be filled with color to approximate the percentage value set in the `value` property.

### Help us reproduce the bug!

Use the included code to reproduce it. 

### Code Snippet

```Javascript
import {Card, Collection, Flex, Icon, Rating, Text, View} from "@aws-amplify/ui-react";
import {ImVideoCamera} from "react-icons/im";
import {Spacer} from "@nextui-org/react";

const arts = [
    {
        title: "Danzan Ryu",
        link: "./dzr/Home",
        coverage: 40
    }
]

export default function Home() {

    return (
        <>
            <Spacer/>
            <View padding="1rem">
                <Text
                    fontSize="5rem"
                    fontWeight="bold"
                    textAlign="left">
                    Arts</Text>
                <Spacer/>
                <Collection
                    type="list"
                    items={arts}
                    gap="2.0rem"
                    alignItems="center">
                    {(item, index) => (
                        <View
                            key={index}
                            width="100%"
                            onClick={() => {
                                window.location.href = item.link;
                            }}>
                            <Card
                                width={"40rem"}
                                variation={"elevated"}
                                key={index}
                                padding="1rem"
                                textAlign={"left"}
                                backgroundColor={"blue.20"}
                                whiteSpace="nowrap"
                                fontSize={"4rem"}>
                                {item.title}
                                <Rating
                                    padding="2rem"
                                    size="large"
                                    maxValue={1}
                                    value={item.coverage * .01}
                                    icon={
                                        <ImVideoCamera
                                            fontSize="7rem">
                                        </ImVideoCamera>
                                    }/>
                            </Card>
                        </View>
                    )}
                </Collection>
            </View>
        </>
    )
}
```

### Additional information and screenshots

![value_set_to_percentage](https://github.com/aws-amplify/amplify-ui/assets/42153/3c260ef0-99b7-4879-abd0-a3509ac68218)
![value_set_to_one](https://github.com/aws-amplify/amplify-ui/assets/42153/47e58aa1-d70b-4d69-8d99-7accea141a0d)

**Comment by hbuchel** [comment]
Hi @gamename Try putting the fontSize on the Rating element itself. This should work:

```
<Rating
  padding="2rem"
  maxValue={1}
  value={0.4}
  fontSize="7rem"
  icon={<ImVideoCamera></ImVideoCamera>}
/>
```

See example here: https://codesandbox.io/p/sandbox/amplify-ui-triage-forked-4tzrsk?file=%2Fsrc%2FApp.tsx%3A8%2C7-14%2C9

**Comment by gamename** [comment]
@hbuchel That worked! Thanks. :)
