### ISSUE TITLE
FR (Authenticator): Upgrade version of @xstate/react used in packages

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#4094]
### On which framework/platform would you like to see this feature implemented?

React, React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

This is a feature request to upgrade @xstate/react to the latest version as requested by @kachkaev [here](https://github.com/aws-amplify/amplify-ui/pull/4027#issuecomment-1578627682)

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment]
The version of `@xstate/react` used by the `Authenticator` now points to `^3.2.2` (current `latest`) as of `@aws-amplify/ui-react@6.0.1`
