### ISSUE TITLE
Bug(Docs): Clicking on Size on Ratings docs takes you to select dropdown instead of Size section

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#4096]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

n/a

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Clicking on Size in the table of contents on the [Rating docs page](https://ui.docs.amplify.aws/react/components/rating) takes you to the size select dropdown in the demo instead of the Size documentation section. The [id on the Select dropdown](https://github.com/aws-amplify/amplify-ui/blob/main/docs/src/pages/%5Bplatform%5D/components/rating/RatingPropControls.tsx#L75) can be removed because it conflicts with the url fragment #size.

### What's the expected behaviour?

Clicking on Size should scroll you down to the Size section under Usage.

### Help us reproduce the bug!

Click on Size in the table of contents.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by saketverma-03** [comment]
completely removing `id="size"` from ` <SelectField >` works well as `id="size"` is serving no purpose there.
I'm new to opensource i don't know if should i open a PR or this issue is only for first time contributors .

**Comment by hbuchel** [comment]
@saketverma-03 you're right, we're not actually using that specific id for anything so the id could just be removed from that select field. "good first issue" are for anyone really; we use them as issues that are more accessible to get started with for people who want to start contributing more for open source and to Amplify UI! Let us know if you'd like us to assign this issue for you.

**Comment by saketverma-03** [comment]
@hbuchel OK i understand I'll like to fix this please assign me
