### ISSUE TITLE
Trim user inputs

### ISSUE THREAD

**Issue by SilverLinings89** [aws-amplify/amplify-ui#4121]
### On which framework/platform would you like to see this feature implemented?

Angular

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

It would be nice to have the ability to automatically trim user inputs in form fields. I am not aware of this currently being possible (if so, please let me know) but needing it would require building the signup mechanisms oneself. 

### Please describe a solution you'd like.

A preferred solution would be to have an option for field values to be trimmed and to have the authenticator do this. This would have to be configured on a field-level basis because while email addresses can always be trimmed, passwords might not.
The logic would be: 
When sign-in or sign-up is triggered, iterate all form fields, and check config if they should be trimmed. If so, update the value to the trimmed version.

### We love contributors! Is this something you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by SilverLinings89** [comment]
If you give me some pointers on where to start, I may be able to implement this.

**Comment by zchenwei** [comment]
Hey @SilverLinings89, thanks for submitting the feature request! To trim user input on sign-in or sign-up, you can try to override the function calls. Please check [here](https://ui.docs.amplify.aws/angular/connected-components/authenticator/customization#override-function-calls)

**Comment by SilverLinings89** [comment]
HI @zchenwei Thank you very much for this update. I must have read past that part of the docs; I hadn't seen it. This solves the question completely. It makes the solution a bit more prone to breakage with possible API changes in the future but that should be alright. Thank you!
