### ISSUE TITLE
"SyntaxError: Cannot use import statement outside a module" in jest when importing AmplifyAuthenticatorModule in standalone app

### ISSUE THREAD

**Issue by mikelhamer** [aws-amplify/amplify-ui#4125]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

ng build

### Please describe your bug.

When I run `ng test` to run my jest tests of my 100% standalone app, I get the following error
"SyntaxError: Cannot use import statement outside a module"

This is due to me importing this in my app.component.ts
`import {AmplifyAuthenticatorModule} from '@aws-amplify/ui-angular';`

Which I have to do to use the amplify-authenticator in my template. 

Note that this works fine when actually running the app, it's only an issue when running the test.

### What's the expected behaviour?

That it doesnt throw this error when I run my tests

### Help us reproduce the bug!

1. Create a new Angular v16 app with a 100% standalone app config
2. Use amplify-authenticator in your app.component template
3. Run the generated spec file using jest

**Comment by zchenwei** [comment]
Hi @mikelhamer, thank you for reporting the issue. We are working on reproducing the issue. It would be helpful if you can publish a repo with your code for us to reproduce the issue. Thanks!

**Comment by wlee221** [comment]
Hi @mikelhamer! Just an update, we do support Angular 16 but to be transparent we really haven't tested against standalone apps.

As @zchenwei has mentioned, we do have a major release coming soon that bumps the minimum supported version to Angular 14 that introduces standalone components. We'll be taking a look at standalone components support along with that release.

**Comment by mikelhamer** [comment]
> Hi @mikelhamer! Just an update, we do support Angular 16 but to be transparent we really haven't tested against standalone apps.
> 
> 
> 
> As @zchenwei has mentioned, we do have a major release coming soon that bumps the minimum supported version to Angular 14 that introduces standalone components. We'll be taking a look at standalone components support along with that release.

Thank you! Love this.

**Comment by wlee221** [comment]
@mikelhamer Looked into this more, I could actually get jest working with 100% standalone app. Getting jest config was frustrating though (they have a troubleshooting [here](https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting/)), so maybe that's maybe where the errors are coming from.

Here's my repo: 
- https://github.com/wlee221/angular-16-amplify-authenticator-standalone-jest

Here're the commits that I wrote from scratch:
- set up Amplify: https://github.com/wlee221/angular-16-amplify-authenticator-standalone-jest/commit/77d090f036c5cc544ff1fe746bfea826561caa71
- setup jest: https://github.com/wlee221/angular-16-amplify-authenticator-standalone-jest/commit/efab203519b86e0152d32eef4bedc9701c7d1211

Hopefully that helps!

**Comment by mikelhamer** [comment]
> @mikelhamer Looked into this more, I could actually get jest working with 100% standalone app. Getting jest config was frustrating though (they have a troubleshooting [here](https://thymikee.github.io/jest-preset-angular/docs/guides/troubleshooting/)), so maybe that's maybe where the errors are coming from.
> 
> Here's my repo:
> 
> * https://github.com/wlee221/angular-16-amplify-authenticator-standalone-jest
> 
> Here're the commits that I wrote from scratch:
> 
> * set up Amplify: [wlee221/angular-16-amplify-authenticator-standalone-jest@77d090f](https://github.com/wlee221/angular-16-amplify-authenticator-standalone-jest/commit/77d090f036c5cc544ff1fe746bfea826561caa71)
> * setup jest: [wlee221/angular-16-amplify-authenticator-standalone-jest@efab203](https://github.com/wlee221/angular-16-amplify-authenticator-standalone-jest/commit/efab203519b86e0152d32eef4bedc9701c7d1211)
> 
> Hopefully that helps!

Thank you!!! Im pouring through this trying to find differences between this and my app, copying over changes bit by bit, but so far having no luck. This is a great help though, thanks!

**Comment by wlee221** [comment]
Feel free to post your repo too, I'll be glad to help 👍

**Comment by mikelhamer** [comment]
It's a private repo for some enterprise stuff so I can't share, but I'll see if I can recreate in a new project. Might just hold out for the new major version though, it's not like eliminating the last remaining module (app.module) actually benefits anything, more of a "I want to destroy all the modules!" thing lol. Just because I can.

**Comment by mikelhamer** [comment]
Unfortunately 4.0.0 didn't magically fix the issue, looks like I'll have to tear my project apart and reconfigure everything jest / typescript related if I want it to work. Thanks for the support!
