### ISSUE TITLE
Missing code in AWS Doc - solution suggested

### ISSUE THREAD

**Issue by neurocaience** [aws-amplify/amplify-ui#4130]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

React

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari, iOS (React Native), Android (React Native)

### Please describe your bug.

In your tutorial: 
https://ui.docs.amplify.aws/react/guides/auth-protected#adding-in-a-requireauth-component

Critical missing code: 
In index.js, 
You are missing the line of code: 
import {Amplify} from 'aws-amplify'; 
Without this line of code I get an error that 'Amplify' is not defined.  

Non-Critical issues that would make the code easier to follow:

- It is confusing that "RequireAuth.js" is not in the "Components" folder. You placed it in between two other files that are in the components folder, so that gave me an error when I first ran the code because my RequireAuth.js file was in the wrong folder. I suggest having that section be before the other files that are in the components folder. 

- I suggest having a sentence clarifying the convention is to put 'components' folder inside the 'src' folder. Beginners might not know the convention to put 'components' folder inside the 'src' folder. 

- The tutorial mentions that Auth.currentAuthenticatedUser() accomplishes the same thing... I would be curious to see this example. 

Thanks for the tutorial!  I think the above changes to the tutorial could save people 20 mins of debugging. 

### What's the expected behaviour?

NA

### Help us reproduce the bug!

NA

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by zchenwei** [comment]
Hi @neurocaience, we apologize for the confusion and inconvenience the docs may cause and appreciate all the great feedback here!

**Comment by neurocaience** [comment]
Glad I can help and thank you for providing the helpful tutorial to begin with!
