### ISSUE TITLE
MapView not loading after splitting into `@aws-amplify/react-ui-geo` (request transformer error)

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-ui#4142]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Geo (MapView)

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### Please describe your bug.

I am trying to display a `MapView` using the new-ish `@aws-amplify/react-ui-geo` package and I'm not able to. Looking at the logs (see below) it seems that the request transformer from the Amplify Maplibre module is not handling/reading some configs properly, causing the request to never be sent.

I can confirm that the same exact code (except for the import change) works with older versions of Amplify UI (up until it was broken down into a separate package).

### What's the expected behaviour?

The `MapView` should render normally.

### Help us reproduce the bug!

You can use this minimal repro sample I have created: https://github.com/dreamorosi/amplify-ui-issue

If not:
- create a blank Vite app
- then install `aws-amplify`, `@aws-amplify/react-ui`, and `@aws-amplify/react-ui-geo` (all latest)
- create the map resources (or copy an existing `aws-exports.js` in the `src` folder
- try adding a map (see code below)
- start the app & observe error in the console + blank screen

### Code Snippet

```js
// Put your code below this line.
import React from "react";
import { MapView } from "@aws-amplify/ui-react-geo";
import { NavigationControl } from "react-map-gl";

const App = () => {
  return (
    <MapView
      initialViewState={{
        longitude: -115.17077150978058,
        latitude: 36.12309017212961,
        zoom: 15,
      }}
      style={{
        width: "100vw",
        height: "100vh",
      }}
    >
      <NavigationControl position={"top-left"} />
    </MapView>
  );
};


export default App;
```

### Additional information and screenshots

![image](https://github.com/aws-amplify/amplify-ui/assets/7353869/dd2f0fe4-176f-47b1-bd62-b49d9fd52c65)

Logs:

```
[vite] connecting...
[vite] connected.
react_devtools_backend_compact.js:2367 TypeError: str.replace is not a function
    at urlEncodePeriods (utils.js:62:16)
    at AmplifyMapLibreRequest.transformRequest [as _transformRequestFn] (AmplifyMapLibreRequest.js:80:86)
    at r2.transformRequest (request_manager.ts:24:25)
    at ie.loadURL (style.ts:220:50)
    at Map._updateStyle (map.ts:1442:24)
    at Map.setStyle (map.ts:1395:25)
    at new Map (map.ts:464:33)
    at Mapbox._initialize (mapbox.ts:546:22)
    at new Mapbox (mapbox.ts:438:10)
    at map.tsx:103:22
```

**Comment by zchenwei** [comment]
Hi @dreamorosi, thank you for your patient. We digged into the dependency graph a bit and  found that this was because recent updates to `maplibre-gl-js-amplify` broke our code. We will release a fix real quick. In the meantime, you could pin the dependency to `3.1.0` in `package.json` and I think the `MapView` component will be loading again.

```json
// if you are using npm
"overrides": {
    "maplibre-gl-js-amplify": "3.1.0"
  }

// if you are using npm
"resolutions": {
    "maplibre-gl-js-amplify": "3.1.0"
  }
```

**Comment by zchenwei** [comment]
Hi @dreamorosi, we've just release `@aws-amplify/ui-react-geo@1.0.1` which should include the fix. Could you please download the latest version and help us verify if that fixes the issue? Thanks!

**Comment by dreamorosi** [comment]
Hi @zchenwei, thank you for the quick reply and fast release.

I have just tested the new version and can confirm that it works on my side.

You can close the issue as resolved.
