### ISSUE TITLE
FR (Studio): No Expander Primitive in Figma

### ISSUE THREAD

**Issue by JuanMreno** [aws-amplify/amplify-ui#4154]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Primitive components

### Please describe your feature-request in detail.

I'm building a React Web App using Amplify and an integration with Figma. 

I need to use the Primitive [Expander](https://ui.docs.amplify.aws/react/components/expander) , and I duplicate the last [AWS Amplify UI Kit](https://www.figma.com/community/file/1047600760128127424/AWS-Amplify-UI-Kit) template Figma File. But I dont find the Expander Primitive in the Figma File. 

### Please describe a solution you'd like.

It's posible to import or create the Expander Primitive to the Figma File, to create a new component ussing this Primitive?
Or exists any other AWS Amplify UI Kit that contains the Expander primitive?

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [X] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Thank you for your feature request. We are not planning on adding this functionality at this time.
