### ISSUE TITLE
Error: Package path ./theme.css is not exported from node_modules/@aws-amplify/ui-angular in version 4.0.0

### ISSUE THREAD

**Issue by mikelhamer** [aws-amplify/amplify-ui#4157]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Other

### How is your app built?

ng build

### Please describe your bug.

Angular: v16
"@aws-amplify/ui-angular": "^4.0.0",
"aws-amplify": "^5.3.1",

In my global scss file I am importing the UI Angular theme like this

`@import '@aws-amplify/ui-angular/theme.css';`

After updating to UI Angular v4.0.0, I get this error when I build the app. I was previously on 3.2.10 and this worked fine.

```
./src/global.scss - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Package path ./theme.css is not exported from package myproject/node_modules/@aws-amplify/ui-angular (see exports field in myproject/node_modules/@aws-amplify/ui-angular/package.json)

./src/global.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~@aws-amplify/ui-angular/theme.css' in '/myproject/src'

```

### What's the expected behaviour?

I can import the theme.css

### Help us reproduce the bug!

Create an Angular 16 project with Amplify UI Angular. Import theme.css as shown above.

**Comment by wlee221** [comment]
Hi @mikelhamer, thanks for trying out the component so quickly! So our docs is in middle of deployment... 😅 , but going forward you should import css using `angular.json`.

So instead of 

```css
@import '@aws-amplify/ui-angular/theme.css';
```

in your global css file, open your `angular.json` file, and add `node_modules/@aws-amplify/ui-angular/theme.css` to `styles` array in your `angular.json`. This array is located in `projects.<project-name>.architect.build.options`.

```diff
"styles": [
+  "node_modules/@aws-amplify/ui-angular/theme.css",
  "src/styles.css"
],
```

I'll let you know once the doc is updated!

**Comment by mikelhamer** [comment]
@wlee221 that worked, thanks! Im curious if you have any insights, why is this required now?

**Comment by wlee221** [comment]
I don't have too much insight to be honest, other than this is some internal change with how Angular loads CSS files. I however think this is the more idiomatic pattern that I've seen from other libraries.

**Comment by zchenwei** [comment]
Hi @mikelhamer, our [docs site](https://dev.ui.docs.amplify.aws/angular/getting-started/migration#update-and-usage) have been updated! Thanks for reporting the issue to us! 😄

**Comment by CynanX** [comment]
Also had this error. It would be beneficial if this had been in the release notes, rather than having to hunt the reason down. Can this be aded into the release notes? Thanks.

**Comment by wlee221** [comment]
@CynanX, thanks for the suggestion, we've updated https://github.com/aws-amplify/amplify-ui/releases/tag/%40aws-amplify%2Fui-angular%404.0.0. 

With that and https://dev.ui.docs.amplify.aws/angular/getting-started/migration updated, we'll go ahead and close this issue. Thanks!
