### ISSUE TITLE
bug (Authenticator): Allow PasswordSettings to pass through to the form validation rules when SignUp component is rendered

### ISSUE THREAD

**Issue by alettieri** [aws-amplify/amplify-ui#4162]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I noticed that the AuthenticatorComponent accepts the PasswordSettings configuration, but isn't actually forwarded to the state machine. It would be great to have the PasswordSettings available so that we can run password validation on the client rather than wait for the server.

### Please describe a solution you'd like.

It would be great if we pass the PasswordSettings configuration through to the state machine initializer.

https://github.com/aws-amplify/amplify-ui/blob/2e4dc9fa82f1e4c16f962c691d0b3c08f2d2ee9a/packages/react/src/components/Authenticator/Authenticator.tsx#L60

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by calebpollman** [comment]
@alettieri Thanks for opening this! The `passwordSettings` prop is going to be deprecated in a future major version release of the `Authenticator`.

Adding additional validation for input events in the `Authenticator` is on our roadmap for the next major version release of the `Authenticator`. Have added a feature request [here](https://github.com/aws-amplify/amplify-ui/issues/4167) for tracking, feel free to add any thoughts on validation events you may have there.

As the `passwordSettings` prop is to be deprecated going to close the issue, but again thank you for highlighting the issue.
