### ISSUE TITLE
Docs: Document borderColor, borderWidth, and borderStyle style props

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#4166]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Primitive components

### Please describe your feature-request in detail.

We recently merged in changes to allow for borderWidth, borderStyle, and borderColor style props. We should document them on the Style Props docs page. https://ui.docs.amplify.aws/react/theming/style-props#border-styles

### Please describe a solution you'd like.

- Add rows for borderStyle, borderWidth, and borderColor to the table. You can see how the others are added [here](https://github.com/aws-amplify/amplify-ui/blob/main/docs/src/pages/%5Bplatform%5D/theming/style-props/examples/BorderStyles.tsx#L3): 
- Add example usage to the existing example [here](https://github.com/aws-amplify/amplify-ui/blob/main/docs/src/pages/%5Bplatform%5D/theming/style-props/examples/BorderExamples.tsx).

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by saketverma-03** [comment]
Hi @hbuchel  can you please assign this issue to me

**Comment by calebpollman** [comment]
Hi @saketverma-03! Thanks for your interest in picking up this issue, assigned 😄

**Comment by hbuchel** [comment]
Thanks @saketverma-03! Fixed in https://github.com/aws-amplify/amplify-ui/pull/4257
