### ISSUE TITLE
Problem：I want to get support for Amazon Rekognition Face Liveness technology.

### ISSUE THREAD

**Issue by GeneralLHW** [aws-amplify/amplify-ui#4184]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I want to get support for Amazon Rekognition Face Liveness technology. I followed the amplify UI document to access it with react, and I can open the video, but there is no process of verifying the connection, and there is no countdown, and an error requesting this address appears in the browser console: https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file, I followed the amplify document, the code is also the code in the document, the document Link: https://ui.docs.amplify.aws/react/connected-components/liveness. so how do i do this? Very anxious, looking forward to reply, thank you

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by hbuchel** [comment]
Hi @GeneralLHW, can you please include the exact error you are seeing in the browser console? Can you please also include the code where you are importing and using `<FaceLivenessDetector />`? Are you using any custom configuration, like demonstrated [here](https://ui.docs.amplify.aws/react/connected-components/liveness/customization#custom-cdn)?

**Comment by GeneralLHW** [comment]
> Hi @GeneralLHW, can you please include the exact error you are seeing in the browser console? Can you please also include the code where you are importing and using `<FaceLivenessDetector />`? Are you using any custom configuration, like demonstrated [here](https://ui.docs.amplify.aws/react/connected-components/liveness/customization#custom-cdn)?

The error in the browser console is as follows:
`GET https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file net::ERR_CONNECTION_RESET
platform_browser.ts:33 
 GET https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file net::ERR_CONNECTION_RESET
platform_browser.ts:33 
 GET https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file net::ERR_CONNECTION_RESET
platform_browser.ts:33 
 GET https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file net::ERR_CONNECTION_RESET`
There is no response to this request。
Additional supplement: In addition, I also saw this address in the custom CDN part of the document, but this address is really unreachable...

My test code is as follows, and the request interface for obtaining the result has not been written yet：
`import React from "react";
import { FaceLivenessDetector } from "@aws-amplify/ui-react-liveness";
import { Loader, ThemeProvider } from "@aws-amplify/ui-react";
import Axios from "axios";
export function LivenessQuickStartReact() {
  const [loading, setLoading] = React.useState(true);
  const [createLivenessApiData, setCreateLivenessApiData] =
    React.useState(null);

  React.useEffect(() => {
    const fetchCreateLiveness = async () => {
      /*
       * This should be replaced with a real call to your own backend API
       */

      let res = await Axios.get(
        "http://192.168.1.28:8066/api/web/faceLive/createSession"
      ).then((r) => {
        console.log("RRR>>>>", r.data.data);

        const mockResponse = { sessionId: r.data.data };
        const data = mockResponse;

        setTimeout(() => {
          setLoading(false);
          setCreateLivenessApiData(data);
        });
      });
    };

    fetchCreateLiveness();
  }, []);

  const handleAnalysisComplete = async () => {
    /*
     * This should be replaced with a real call to your own backend API
     */
    // const response = await fetch(
    //   `/api/get?sessionId=${createLivenessApiData.sessionId}`
    // );
    // const data = await response.json();

    /*
     * Note: The isLive flag is not returned from the GetFaceLivenessSession API
     * This should be returned from your backend based on the score that you
     * get in response. Based on the return value of your API you can determine what to render next.
     * Any next steps from an authorization perspective should happen in your backend and you should not rely
     * on this value for any auth related decisions.
     */
    // if (data.isLive) {
    //   console.log("User is live");
    // } else {
    //   console.log("User is not live");
    // }
  };

  return (
    <ThemeProvider>
      {loading ? (
        <Loader />
      ) : (
        <>
          <div>{createLivenessApiData.sessionId}</div>
          <FaceLivenessDetector
            sessionId={createLivenessApiData.sessionId}
            region="us-east-1"
            onAnalysisComplete={handleAnalysisComplete}
            onError={(error) => {
              console.error(error);
            }}
          />
        </>
      )}
    </ThemeProvider>
  );
}
`
I requested the above method in another script：
`function App() {
  const [count, setCount] = useState(0)

  return (
    <>
       <LivenessQuickStartReact/>
    </>
  )
}

export default App`

**Comment by thaddmt** [comment]
Hey @GeneralLHW it looks like the CDN address from tfhub is unreachable for you. Are you able to visit their website yourself https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1 or on another computer? If so you can download the model.json file and host it yourself per our instructions in the documentation https://ui.docs.amplify.aws/react/connected-components/liveness/customization#custom-cdn

If that doesn't work we can send you the model.json file direclty for self hosting

**Comment by GeneralLHW** [comment]
thank you @thaddmt . Through the document address: https://ui.docs.amplify.aws/react/connected-components/liveness/customization#custom-cdn, I can access it after hosting it myself. However, I encountered another problem. After the face recognition, the video is directly stuck at the Verify... step, so I wonder why? I also followed the operation of the document, but the steps of the document are less than my steps. In the amplify add auth step of Configure Auth, my operations are much more than the documents. So is this the cause? How should I solve the Verify authentication step?

**Comment by thaddmt** [comment]
If you are referring to the UI, it will just continue to show `verifying...` but the callback `onAnalysisComplete` should be fired and you should be able to show a different ui based on the results - https://ui.docs.amplify.aws/react/connected-components/liveness#facelivenessdetectorprops

As long as you are able to get a result in this call back by calling the `GetFaceLivenessSessionResults` (https://docs.aws.amazon.com/rekognition/latest/dg/face-liveness-backend-example.html) then you should be able to continue. Please let us know if you need more assistance here!

**Comment by reesscot** [comment]
Closing this issue as we haven't heard back. Please open a new issue if you have further questions.

**Comment by GeneralLHW** [comment]
@thaddmt  Thank you very much for solving my problem. Recently, I often encounter the problem in the picture below. Can you explain why? Thanks
![WechatIMG17](https://github.com/aws-amplify/amplify-ui/assets/7157829/f098e708-969d-4e5d-ab8c-97e0d557194e)
