### ISSUE TITLE
Bug(primitive): Show password button SVG icon is not accessibly labelled

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#4190]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

n/a

### Please describe your bug.

The icon used in the Show Password button is not accessibly labelled. 

<img width="871" alt="Accessibility tree in Chrome highlighting the SVG icon which shows 'Not specified' for all of the label options" src="https://github.com/aws-amplify/amplify-ui/assets/376920/8251b69a-54e9-42b9-88b5-ab0751e879e5">

### What's the expected behaviour?

Since the button includes visually hidden text already, we should accessibly hide [the icon](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/primitives/PasswordField/ShowPasswordButton.tsx#L47-L49) with an `aria-hidden="true"`

### Help us reproduce the bug!

Inspect the SVG icon for the ShowPassword button on https://ui.docs.amplify.aws/react/components/passwordfield 

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by Akash1965** [comment]
Hi @hbuchel can you please assign this issue to me

**Comment by Akash1965** [comment]
Can you please tell me in which file is it located??

**Comment by hbuchel** [comment]
@Akash1965 https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/primitives/PasswordField/ShowPasswordButton.tsx#L47-L49

**Comment by mdixon47** [comment]
I would like to take this on too. I have the link above.
