### ISSUE TITLE
Bug(primitive): Not able to pass down className to wrapping elements in Tabs primitive

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#4191]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

React

### Please describe your bug.

When applying a className at the top level to the <Tabs /> primitive, it's a little misleading where it ends up. Instead of applying to an element wrapping the container, we apply it to our <Flex /> element that wraps the tab buttons.
<img width="1298" alt="Screenshot 2023-06-30 at 10 29 24 AM" src="https://github.com/aws-amplify/amplify-ui/assets/376920/48573cfb-4380-4b27-844f-7478df90039a">

### What's the expected behaviour?

I would either expect a way to pass a className down to the parent level element or to have classes on those elements to make styling them easier.

### Help us reproduce the bug!

Pass a className to the Tabs primitive:
```
<Tabs className="my-tabs-class">
  <TabItem title="Tab 1">
    <View className="my-tab-content-class">Tab 1 Content</View>
  </TabItem>
  <TabItem title="Tab 2">Tab 2 Content</TabItem>
</Tabs>
```    

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by dbanksdesign** [comment]
THIS IS FIXED NOW IN v6!!!
