### ISSUE TITLE
[React Liveness Component] `ReadableStreamDefaultController is not in a state where chunk can be enqueued`

### ISSUE THREAD

**Issue by bradjones1** [aws-amplify/amplify-ui#4196]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Expo web (Webpack 5)

### What browsers are you seeing the problem on?

Safari

### Please describe your bug.

My application monitoring is logging [uncaught exceptions](https://not-vanilla-llc.sentry.io/share/issue/c12cfa202db34936835eed907c7e8927/) with message `ReadableStreamDefaultController is not in a state where chunk can be enqueued` from https://github.com/aws-amplify/amplify-ui/blob/0b4fdaf6e6632997fe42852dfcbccec3ccdef732/packages/react-liveness/src/components/FaceLivenessDetector/service/utils/videoRecorder.ts#L86

Interestingly, I have noted that this is logged to Sentry during my own testing sessions where I experience no error bubbling up to the UI or triggering on the `onError` callback, so while it is logged as uncaught it doesn't appear to affect the UX?

### What's the expected behaviour?

No exception is thrown or the application fails gracefully.

### Help us reproduce the bug!

Start a liveness session inside Safari browser. Right now I am seeing Safari 16 only (a few different majors and minors, but always 16.)

### Code Snippet

I am invoking the liveness component pretty generically:

```tsx
<FaceLivenessDetector
  sessionId={sessionId}
  region='us-west-2'
  onAnalysisComplete={handleAnalysisComplete}
  onError={onError}
/>
```

**Comment by bradjones1** [comment]
Also seeing `Cannot enqueue into a stream that is already closed.` from the same code.

**Comment by thaddmt** [comment]
Hey @bradjones1 does this uncaught exception effect the liveness experience? I'm curious if this occurs during the session and is causing errors with completion or occurs after the session ends and is possibly a bug with the way we are handling closing the connection.

**Comment by thaddmt** [comment]
Hm that is possible. Can I ask what device were you testing this on? At least in testing on my Macbook with safari 16 I wasn't able to recreate this error. At the very least it seems like it's not affecting your session experience but I definitely understand it's annoying those logs showing up.

Also did you perform this check recently? We recently just put out a PR that should address some of those websocket warning messages - https://github.com/aws-amplify/amplify-ui/pull/4138

**Comment by bradjones1** [comment]
@thaddmt Thanks for continuing to look into this.

> Can I ask what device were you testing this on? At least in testing on my Macbook with safari 16 I wasn't able to recreate this error.

My Sentry events are mostly Safari 15/16, though I do see an entry for mobile Chrome and Firefox as well, which at least invalidates the idea that it's exclusively a Safari issue.

I think I should have the code from the PR you linked as I'm running `1.0.5.`:

```
├─ @aws-amplify/ui-react-liveness@1.0.5
│  ├─ @aws-amplify/ui-react@5.0.3
│  ├─ @aws-amplify/ui@5.6.6
```

Not sure if it's related or not but I am also encountering the uncaught exceptions detailed at https://github.com/aws-amplify/amplify-ui/issues/4203

**Comment by bradjones1** [comment]
Also have a log entry for a very similar `Failed to execute 'enqueue' on 'ReadableStreamDefaultController': Cannot enqueue a chunk into a closed readable stream`:

https://not-vanilla-llc.sentry.io/share/issue/475e4ef501044193b4d5d44eaf8c27b3/

**Comment by thaddmt** [comment]
@bradjones1 I'm guessing you were testing on an iphone since it's a React native app? Wondering if it's a special case with react native

**Comment by thaddmt** [comment]
@bradjones1 Also I believe that change was only recently included in v1.0.6 - https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-liveness/CHANGELOG.md#106

**Comment by bradjones1** [comment]
@thaddmt 

> I'm guessing you were testing on an iphone since it's a React native app? Wondering if it's a special case with react native

This is in production so these are live users on both Android and iOS devices.

> Wondering if it's a special case with react native

This is not React Native, it's all on web. I only noted RN because there is currently no RN binding for Liveness so my flow is to redirect users from RN to a web experience to do liveness, and then those users are redirected back to the RN app.

**Comment by bradjones1** [comment]
@thaddmt FYI still getting this on release with `1.0.6`, so whatever changes that contained didn't address this. https://not-vanilla-llc.sentry.io/share/issue/c12cfa202db34936835eed907c7e8927/ All on Safari both desktop and mobile, versions 15 and (mostly) 16.

I have not, however, seen the issue described in #4203 lately.

**Comment by thaddmt** [comment]
Gotcha, will update here when i've tested safari more to see where this is coming from

**Comment by reesscot** [comment]
@bradjones1 Are you still seeing this error on the latest version of `@aws-amplify/ui-react-liveness`?

```
npm install @aws-amplify/ui-react-liveness@latest
```

**Comment by reesscot** [comment]
Closing this out as we haven't heard back. Please open a new issue if you're still having this problem.
