### ISSUE TITLE
Bug (authenticator, vue): when user sets bad initial password, the alert is not shown, and user is redirected back to the sign in page

### ISSUE THREAD

**Issue by malinoff** [aws-amplify/amplify-ui#4198]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

webpack

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

When users set up their initial password, which does not comply with the password policy, they do not see the error message, and are redirected back to the sign in page, silently.
<img width="484" alt="Screenshot 2023-07-03 at 15 00 00" src="https://github.com/aws-amplify/amplify-ui/assets/1702083/ca22fd41-ab7e-42d3-bb8c-0d09bd382b2e">

The functionality exists, for example, when resetting a forgotten password:
<img width="481" alt="Screenshot 2023-07-03 at 14 59 17" src="https://github.com/aws-amplify/amplify-ui/assets/1702083/4997bde8-367b-4258-9aa2-83d2a8cf0263">

### What's the expected behaviour?

Users see the error message, are able to fix their initial password, and re-submit.

### Help us reproduce the bug!

Here's the versions of related libraries we use:

```
    "@aws-amplify/auth": "^5.3.6",
    "@aws-amplify/core": "^5.3.0",
    "@aws-amplify/ui-vue": "^3.1.15",
    "aws-amplify": "^5.2.1",
```

**Comment by malinoff** [comment]
Indeed, we have custom validation rules
<img width="831" alt="Screenshot 2023-07-10 at 15 56 01" src="https://github.com/aws-amplify/amplify-ui/assets/1702083/53c2850f-85b2-423f-8394-cb15390adf9e">

**Comment by wlee221** [comment]
Got it, thanks.

Can you share your `aws-exports` **after** redacting any sensitive information? I'm mostly interested in seeing `aws_cognito_password_protection_settings` field in there. Also, are you doing any custom validation from your application side?

**Comment by malinoff** [comment]
We don't use `aws-exports`. Here's how we configure amplify:

```javascript
import * as AmplifyAuth from '@aws-amplify/auth'
import { Amplify, Logger, I18n } from '@aws-amplify/core'

function configureAmplify() {
    const config = {
      Analytics: { disabled: true },
      aws_project_region: process.env.AWS_REGION,
      aws_content_delivery_bucket: process.env.AMPLIFY.CONTENT_DELIVERY_BUCKET,
      aws_content_delivery_bucket_region: process.env.AWS_REGION,
      aws_content_dlivery_url: process.env.AMPLIFY.CONTENT_DELIVERY_URL,
      aws_cognito_region: process.env.AWS_REGION,
      aws_user_pools_id: process.env.COGNITO.USER_POOL_ID,
      aws_user_pools_web_client_id: process.env.COGNITO.USER_POOL_WEB_CLIENT_ID,
      oauth: {},
    }
    Amplify.configure(config)
```

So no custom validation, not custom password protection settings.

**Comment by calebpollman** [comment]
@malinoff Based on the code snippets you have provided it does not appear that `Amplify.configure` is called with the generated _aws-exports.js_ file, which is required by the `Authenticator` to understand what how to populate the UI and its properties. Can you try running the `Authenticator` after passing the _aws-exports.js_ file to `Amplify.configure`?

**Comment by malinoff** [comment]
As I mentioned, we don't have/use `aws-exports.js`. I've found the solution in https://github.com/aws-amplify/amplify-ui/issues/4423
