### ISSUE TITLE
[React Liveness Component] `Cannot destructure property 'videoMediaStream' of 'e.videoAssociatedParams' as it is undefined.`

### ISSUE THREAD

**Issue by bradjones1** [aws-amplify/amplify-ui#4203]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Expo web (Webpack 5)

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Uncaught exception `Cannot destructure property 'videoMediaStream' of 'e.videoAssociatedParams' as it is undefined.`

E.g.: https://not-vanilla-llc.sentry.io/share/issue/cca3222dbec54e00b67896bb6374fa7c/

This also seems to (at least sometimes, if not always) be preceded with

`TypeError: Cannot read properties of undefined (reading 'height')`

E.g.: https://not-vanilla-llc.sentry.io/share/issue/d4d5fc852f1442ecb315be44b2fbdda6/

Related code appears to be

https://github.com/aws-amplify/amplify-ui/blob/d863667456850c52a3afe489715e2e463836133d/packages/react-liveness/src/components/FaceLivenessDetector/service/machine/index.ts#L765-L769

### What's the expected behaviour?

No uncaught exception during liveness sessions.

### Help us reproduce the bug!

Initiate liveness session.

**Comment by thaddmt** [comment]
Debugging in - https://github.com/aws-amplify/amplify-ui/issues/4196

**Comment by thaddmt** [comment]
As stated in https://github.com/aws-amplify/amplify-ui/issues/4196 seems like this has been resolved for now

**Comment by bradjones1** [comment]
@thaddmt Unfortunately just saw this again in the wild; seems like it's just less common than the linked issue. Please re-open.

https://not-vanilla-llc.sentry.io/share/issue/cca3222dbec54e00b67896bb6374fa7c/
