### ISSUE TITLE
Failed to upload json files with StorageManager 

### ISSUE THREAD

**Issue by yang1fan2** [aws-amplify/amplify-ui#4205]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Storage (Storage Manager)

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

aws-us-west-2

### Please describe your bug.

I'm using StorageManger to upload files to S3:
```
<StorageManager
      isResumable
      maxFileCount={1}
      maxFileSize={10000000} // in bytes
      variation="drop"
      acceptedFileTypes={['*']}
      accessLevel="public"
/>
```
It works with other file types (e.g. txt, png), but it failed with json files (e.g. test.json). See the attached screenshot for the error message.
<img width="496" alt="Screenshot 2023-07-06 112244" src="https://github.com/aws-amplify/amplify-ui/assets/4648013/694138fa-8c9a-4cd0-b786-35cecefe23db">

If I rename the same file to a different file extension (e.g. test.txt). It works.

> 

### What's the expected behaviour?

Upload json file successfully with StorageManager

### Help us reproduce the bug!

- Run the web application locally.
- upload a json file with filename like test.json
- Unable to upload the json file.

### Code Snippet

```typescript
// Put your code below this line.
      <StorageManager
        isResumable
        maxFileCount={1}
        maxFileSize={10000000} // in bytes
        variation="drop"
        acceptedFileTypes={['*']}
        accessLevel="public"
      />
```

**Comment by yang1fan2** [comment]
My dependency is `"@aws-amplify/ui-react-storage": "^2.0.0",`

**Comment by reesscot** [comment]
Seems related to https://github.com/aws-amplify/amplify-js/issues/11308#issuecomment-1529988913

**Comment by reesscot** [comment]
I was able to reproduce this and found that this is an issue with the JS API. Can reproduce using the following code and trying to upload a json file:

```js
async function onChange(e) {
  const file = e.target.files[0];
  try {
    await Storage.put(file.name, file, {
      contentType: 'application/json', // this causes the failure
      resumable: true,
    });
  } catch (error) {
    console.log('Error uploading file: ', error);
  }
}

export function App() {
  return (
    <>
      <input type="file" onChange={onChange} />;
    </>
  );
}


```

**Comment by AllanZhengYP** [comment]
Hi @yang1fan2, that's the size of the JSON file you are uploading? 

The StorageManager uses a different S3 API (putObject) for files < 5 MB and `resumable` set to false. You can unset the `resumable` option in your StorageManager and it should work with smaller JSON files, as a short-term workaround, while we are working on a long-term fix.

**Comment by yang1fan2** [comment]
Hi @AllanZhengYP , thanks for the suggestion.

After removing `isResumable`, I'm able to upload small JSON file, but not for large JSON file (see the error below):
<img width="363" alt="Screenshot 2023-07-07 102215" src="https://github.com/aws-amplify/amplify-ui/assets/4648013/0dc35e92-e782-4890-aae6-bb5a5a9407a1">

**Comment by reesscot** [comment]
@yang1fan2 You are correct, the workaround doesn't work for larger JSON files (over 5MB). We are working on a fix to address this.

**Comment by elorzafe** [comment]
This issue is fixed on latest version of the library `aws-amplify@5.3.4`, please confirm this solved the problem.

**Comment by reesscot** [comment]
@yang1fan2 Please confirm that the fix is working for you:
```
npm install aws-amplify@latest
```
