### ISSUE TITLE
Authenticator components. ForceNewPassword Header and Footer not working

### ISSUE THREAD

**Issue by Pixcell** [aws-amplify/amplify-ui#4220]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Which region are you seeing the problem in?

NA

### Please describe your bug.

Specifying the Header and Footer functions inside components for `ForceNewPassword` does not work, default HTML is still rendered.

Specifying it for other keys like SignIn, ResetPassword, etc. works fine.

However, specifying `ForceNewPassword.FormFields` works fine.

### What's the expected behaviour?

Specifying ForceNewPassword.Header function should overwrite the header when forcing a new password selection.

### Help us reproduce the bug!

Create an application with react 18.2.0 and @aws-amplify/ui-react 5.0.4 and aws-amplify 5.2.5

### Code Snippet

```typescript
// Put your code below this line.
const components = {
  SignIn: {
    Header() {
      return <DRHeader padding title="Sign in to Datarock" subtitle="Sign in with your email and password" />;
    }
  },
  ConfirmSignIn: {
    Header() {
      return (
        <div style={{ marginBottom: '1rem' }}>
          <DRHeader title="Two factor authentication" subtitle="Authenticate with your app-generated code" />
        </div>
      );
    }
  },
  ConfirmResetPassword: {
    Header() {
      return (
        <div style={{ marginBottom: '1rem' }}>
          <DRHeader title="Reset your password" subtitle="Enter the code received by email and chose a new password" />
        </div>
      );
    }
  },
  ResetPassword: {
    Header() {
      return (
        <div style={{ marginBottom: '1rem' }}>
          <DRHeader title="Reset your password" subtitle="Enter your email to receive a code" />
        </div>
      );
    }
  },
  ForceNewPassword: {
    // For some unknown reason, Header and Footer are not working for ForceNewPassword
    // But FormFields is working
    Header() {
      return (
        <div style={{ marginBottom: '1rem' }}>
          <DRHeader title="Change password" subtitle="Select a new password" />
        </div>
      );
    },
    FormFields() {
      return (
        <>
          <div style={{ marginBottom: '1rem' }}>
            <DRHeader title="Change password" subtitle="Select a new password" />
          </div>
          <Authenticator.ForceNewPassword.FormFields />
          <div>Hello</div>
        </>
      );
    }
   }
  }


...

<Authenticator components={components}>
 ...Rest of tthe app
 </Authenticator>
 
...
```

### Console log output

there is no relevant console output

### Additional information and screenshots

SignIn Header is working fine

![image](https://github.com/aws-amplify/amplify-ui/assets/4005291/24969017-0296-4da3-9ea2-b69bf5b6bfb4)

ForceNewPassword Header is ignored, but FormFields are working

![image](https://github.com/aws-amplify/amplify-ui/assets/4005291/3d4a4403-3d83-4bd6-961e-6c7c5205d0b3)

I strongly suspect the issue comes from here:
https://github.com/aws-amplify/amplify-ui/blob/d0b76eda2b38c50b307f9122d5df0817af9a0d8e/packages/react/src/components/Authenticator/hooks/useCustomComponents/defaultComponents.tsx#L67C22-L67C22

Where only FormFields are used and not Header and Footer like the other components

**Comment by dbanksdesign** [comment]
Working on this today!
