### ISSUE TITLE
Should I need Node.js Polyfills to use  @aws-amplify/ui-react-liveness or bug?

### ISSUE THREAD

**Issue by HiroshiOHSUGA** [aws-amplify/amplify-ui#4228]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Webpack5

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

not used yet.

### Please describe your bug.

Importing @aws-amplify/ui-react-liveness causes 'ReferenceError: process is not defined' on browser.

It looks this line.
https://github.com/aws-amplify/amplify-ui/blob/15f57d73b6d202bafbd39815aaf31bf3a36e5f09/packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts#L31

Is this bug ?
or

* Does FaceLivenessDetector support only Node.js runtime ?
* Does FaceLivenessDetector require some polyfill about process.env for browser runtime?
* If `process.env` was required, What value should I set to NEXT_PUBLIC_STREAMING_API_URL ?

### What's the expected behaviour?

* Importing @aws-amplify/ui-react-liveness without runtime error on browser runtime.
* Showing some UI by FaceLivenessDetector

### Help us reproduce the bug!

Only importing package and run on browser.

### Code Snippet

```typescript
// main.tsx
// only import
import { FaceLivenessDetector } from "@aws-amplify/ui-react-liveness";

console.log(FaceLivenessDetector); // just avoiding tree shaking.
```

### Console log output

```Uncaught ReferenceError: process is not defined
    at ../node_modules/@aws-amplify/ui-react-liveness/dist/esm/components/FaceLivenessDetector/service/utils/streamProvider.mjs (streamProvider.mjs:1:528)
    at __webpack_require__ (bootstrap:19:1)
    at ../node_modules/@aws-amplify/ui-react-liveness/dist/esm/components/FaceLivenessDetector/service/machine/index.mjs (FaceLivenessDetectorProvider.mjs:1:405)
    at __webpack_require__ (bootstrap:19:1)
    at ../node_modules/@aws-amplify/ui-react-liveness/dist/esm/components/FaceLivenessDetector/FaceLivenessDetector.mjs (seedrandom|crypto:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at node module decorator:5:1
    at main.js:130461:3
    at main.js:130463:12
 ```

### webpack config

```ts
import webpack from "webpack";
import * as path from "path";
import CopyPlugin from "copy-webpack-plugin";

const outPath = path.join(__dirname, "./dist/client");
const sourcePath: string = path.join(__dirname, "./src");

const generator = function (): webpack.Configuration {
  return {
    mode: "development",
    bail: false,
    devtool: "inline-source-map",
    context: sourcePath,
    entry: {
      app: ["./client/main.tsx"],
    },
    output: {
      path: outPath,
      publicPath: "/web_assets/",
      filename: "main.js",
    },
    target: "web",
    resolve: {
      extensions: [".js", ".ts", ".tsx"],
      mainFields: ["module", "browser", "main"],
    },
    module: {
      rules: [
        // .ts, .tsx
        {
          test: /\.tsx?$/,
          exclude: [/^.*test\.tsx?$/],
          use: [
            {
              loader: "babel-loader",
            },
          ],
        },
      ],
    },
    plugins: [
      new CopyPlugin({
        patterns: [{ from: "assets/index.ssr.ejs", to: "index.ssr.html", force: true }],
      }),
    ],
  };
};

export default generator;

```

### Babel config

```json
{
  "presets": [
    [
      "@babel/preset-typescript",
      {
        "isTSX": true,
        "allExtensions": true
      }
    ],
    [
      "@babel/preset-react",
      {
        "runtime": "automatic"
      }
    ]
  ]
}
```

### packages

```
    "@aws-amplify/ui-react": "5.0.4",
    "@aws-amplify/ui-react-liveness": "1.0.6",
    "copy-webpack-plugin": "11.0.0",
    "webpack": "5.88.1",
    "webpack-cli": "5.1.4",
    "@babel/core": "7.22.5",
    "@babel/preset-react": "7.22.5",
    "@babel/preset-typescript": "7.22.5",
```

**Comment by thaddmt** [comment]
Hey @HiroshiOHSUGA thanks for putting this on our radar, this is a bug on our side. We'll work on a fix for this but in the meanwhile you should be able to fix this by adding some default values for process like so https://stackoverflow.com/questions/30030031/passing-environment-dependent-variables-in-webpack

**Comment by reesscot** [comment]
@HiroshiOHSUGA You may also need to look at polyfilling `process` for the `aws-amplify` dependency. See: https://ui.docs.amplify.aws/react/getting-started/troubleshooting#webpack-5-uncaught-referenceerror-process-is-not-defined

**Comment by HiroshiOHSUGA** [comment]
Ah thanks guys!

I understand followings.

1. this is bug and it will be fixed
2. There is a workaround about this.

@thaddmt Thanks for describing!
@reesscot Thanks for suggesting that document! I'll try it.

**Comment by reesscot** [comment]
Closing out as this was released in `@aws-amplify/ui-react-liveness` version `2.0.9`: https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-liveness/CHANGELOG.md#patch-changes
