### ISSUE TITLE
[React Liveness Component] `Cannot read properties of undefined (reading 'height')` in `useMediaStreaminVideo`

### ISSUE THREAD

**Issue by bradjones1** [aws-amplify/amplify-ui#4249]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Expo web (Webpack 5)

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

It appears that `videoConstraints` can be undefined in the constructor at

https://github.com/aws-amplify/amplify-ui/blob/78fdfd6c8268c56204f905402162ad8cb40a0c8e/packages/react-liveness/src/components/FaceLivenessDetector/hooks/useMediaStreamInVideo.ts#L14

Sentry log:

https://not-vanilla-llc.sentry.io/share/issue/beb24914031d41f0ab4ffbb5bec9e5db/

### What's the expected behaviour?

No exception thrown.

### Help us reproduce the bug!

This is from my production error logging and I have not been able to reproduce myself.

**Comment by calebpollman** [comment]
Hi @bradjones1! Reading how your app is built it sounds like you may be using React Native Web, can you confirm?

**Comment by bradjones1** [comment]
@calebpollman Confirmed. The app also runs on React Native, however since there aren't RN bindings yet for Liveness I redirect those users over to a set of pages on the RN Web experience to complete the liveness check. Those who start on the RN Web UI stay there, obviously.

**Comment by calebpollman** [comment]
Thanks for confirming @bradjones1. @thaddmt Do you have any ideas here?

**Comment by reesscot** [comment]
@thaddmt Let's add a check for `videoConstraints` before accessing `height`

**Comment by thaddmt** [comment]
This should be addressed in the latest release
