### ISSUE TITLE
Support for Autocapitalize Setting on Form Fields

### ISSUE THREAD

**Issue by zbarbuto** [aws-amplify/amplify-ui#4292]
### On which framework/platform would you like to see this feature implemented?

Angular

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

There is currently no way to override the "autocapitalize" HTML attribute on form fields - only autocomplete.

This can cause issues on mobile devices as users may enter their email address with a capital letter by mistake and then try to login without the capital on desktop which will not work (as the default Cognito settings has case sensitive emails)

### Please describe a solution you'd like.

It should be possible to override the "autocapitalize" setting for form fields and, ideally, the email one should default to `"off"`.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
  - Would contribute to Angular but I think this should probably be implemented for React/Vue etc. as well.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @zbarbuto,
Thank you for opening this issue. According to the MDN docs the `autocapitalize` attribute is always off for fields with a type of `email`. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

I tested on iPhone and am not seeing the behavior of the email address being capitalized. Can you confirm what fields and what device you are seeing this issue on?

<img width="440" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/6165315/5e0f5c3e-a44e-4714-b408-d405fec44dd1">

**Comment by zbarbuto** [comment]
You are right, my bad, something else must have been going on. Have been unable to reproduce this on iOS or Android after further testing. Thanks for the quick response.
