### ISSUE TITLE
FR (Primitive): Fieldset primitive

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#4306]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Primitive components

### Please describe your feature-request in detail.

Let's add a `<FieldSet />` primitive which includes default styling for legend tag. (Similar to RadioGroup implementation)

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by hbuchel** [comment]
Completed in https://github.com/aws-amplify/amplify-ui/pull/4348
