### ISSUE TITLE
FR (Liveness): Option to switch camera

### ISSUE THREAD

**Issue by sinkaryogita** [aws-amplify/amplify-ui#4326]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Liveness

### Problem Statement
Presently, the FaceLiveliness component automatically selects the stream from the system's default front-facing camera to assess facial liveliness. There is **no way to switch to a different camera in real-time**.  
(The only way to switch to a different camera depends on the system's capacity to allow the selection of a preferred default camera. This option is not available on all devices and does not work for our specific use-case.) 

### Why is this a problem?
Customers using our web-app perform face capture in many different ways. In some journeys like an investment account opening flow, customers use their own phone to take photos of themselves using their selfie camera.  In other journeys, like branch based lending flows, the rear camera on the branch manager's phone, or an external camera on the desktops in the branch are used.  For the app to be effectively used on the ground, **customers need to have the ability to switch to the appropriate camera in real-time.**

### Solution
The proposed feature suggests expanding the camera functionality within the Face Liveliness component by introducing an option for users to select any available camera source. (_any camera source that matches the requirements needed to effectively assess face liveliness_). 
This enhancement would allow users the ability to choose from all cameras, including front-facing, rear-facing, and external cameras, on devices that support multiple camera setups.

As an alternative suggestion,  if you don't want to introduce a dropdown within the Liveliness component, you can allow the Parent component to pass device information (deviceId) as a prop, which the Liveliness component can then use as the selected source of stream. 

### Please describe a solution you'd like.

We would like the liveliness component to additionally have a dropdown that lists all the available camera's that meet the requisite criteria for accurate face liveliness assessment. It can initially be set to the system's default user-facing camera.  The user can then opt for the camera of their preference.

This is a small demo of expected functionality.
Demo: https://sinkaryogita.github.io/select-webcam/
Code: https://github.com/sinkaryogita/select-webcam

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@sinkaryogita This is now supported in the latest version of ui-react-liveness. Please upgrade:
```
npm install @aws-amplify/ui-react-liveness@latest
```

**Comment by luisbytes** [comment]
@reesscot 
Hello, how are you, I don't see documentation about it, could you tell me how it works?

**Comment by reesscot** [comment]
Hi @luisbytes,
There isn't any documentation because it's enabled by default. If you run the latest version with two cameras attached to your computer, you should see an dropdown to select a camera.

**Comment by luisbytes** [comment]
Should this work on a mobile device?

**Comment by reesscot** [comment]
No, this feature was focused on use case of desktop users using external webcams. What is the use case on a mobile device?

**Comment by luisbytes** [comment]
@reesscot Depending on the use case, it is useful to use the rear camera on the mobile device, for example for a process assisted by an agent, said agent is the one who does the entire process from the mobile device and he is the one who would take the image for the liveness. end customer in front.

**Comment by alejandro-sisteya** [comment]
> @sinkaryogita This is now supported in the latest version of ui-react-liveness. Please upgrade:
> 
> ```
> npm install @aws-amplify/ui-react-liveness@latest
> ```

Hi @reesscot , I have the same problem in a desktop app. I have upgraded to to the last version (3.0.21) and it still doesn't work for me, If I want to use a specific camera I have to disable the other one. It never ask me for camera selection with both enabled. I appreciate if you can help me.

![image](https://github.com/aws-amplify/amplify-ui/assets/115958997/b68225fc-7fc7-40d9-aacc-651ef996fc02)

**Comment by zchenwei** [comment]
@alejandro-sisteya I was able to select a camera with the latest version. The dropdown should appear down below(screenshot attached). Could you share what browser you are using?

![Screenshot 2024-05-16 at 5 10 44 PM](https://github.com/aws-amplify/amplify-ui/assets/40295569/c0a3e147-bcf0-41bf-ad5c-02465500443c)

**Comment by alejandro-sisteya** [comment]
> @alejandro-sisteya I was able to select a camera with the latest version. The dropdown should appear down below(screenshot attached). Could you share what browser you are using or did you by any chance disable the start screen?
> 
> ![Screenshot 2024-05-16 at 5 10 44 PM](https://private-user-images.githubusercontent.com/40295569/331419364-c0a3e147-bcf0-41bf-ad5c-02465500443c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNTg2OTYsIm5iZiI6MTcxNjE1ODM5NiwicGF0aCI6Ii80MDI5NTU2OS8zMzE0MTkzNjQtYzBhM2UxNDctYmNmMC00MWJmLWFkNWMtMDI0NjU1MDA0NDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDIyMzk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZDljNmYyYjI3YjkxOTlhMjYwZjhkZGE4OGNiMmVjNGUzMGUzNDcwNDNlZjYwMWEzNGM5YTgzMTQ4NTY3ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wr3cWcdz4KWH35WD60R6U3of5cFixq8FcLpQuVqR914)

Thank you very much, I was using the "disableStartScreen" property since I use a custom instruction screen. Looking at the screenshot you shared I could see where the option appears, I just had to remove the property for the camera selection to appear and customize it. Thanks for the help
