### ISSUE TITLE
Bug(ui): PasswordField ShowPassword button does not have correct tokens for hasError state

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#4410]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

The ShowPassword button for PasswordField does not have correct theme tokens for its error state. 

Example button focused:
<img width="487" alt="Screenshot 2023-09-01 at 11 21 56 AM" src="https://github.com/aws-amplify/amplify-ui/assets/376920/d57020aa-4b41-4d82-b518-0eef3a402104">

Now that Button can have an error colorTheme, as part of a breaking change*, we should:

- In [ShowPasswordButton](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/primitives/PasswordField/ShowPasswordButton.tsx#L49), we should use `colorTheme="error"` when `hasError` is true

Then, to allow the ShowPassword button to have it's own theming options we should:

- In [PasswordField button theme definition](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/theme/tokens/components/passwordField.ts#L22) we should add `error: {}` tokens that reference the outlined error colorTheme:
```
button: {
  // default state tokens
  error: { 
    color: { value: '{components.button.outlined.error.color.value}' } ,
    backgroundColor: { value: '{components.button.outlined.error.backgroundColor.value}'},
    borderColor: { value: '{components.button.outlined.error.backgroundColor.value}'},
  },
  _focus: {
    color: { value: '{components.button.outlined.error.color.value}' } ,
    backgroundColor: { value: '{components.button.outlined.error.backgroundColor.value}'},
    borderColor: { value: '{components.button.outlined.error.backgroundColor.value}'},
  }
  // hover, active, etc states
}
```
Then, we can add those css variable overrides in [passwordField.scss](https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/theme/css/component/passwordField.scss)

*probably a breaking change? I think this would be disruptive to developers who may have themed the PasswordField especially since it is part of Authenticator. 

### What's the expected behaviour?

ShowPassword button should have correct token theming for `hasError` state.

### Help us reproduce the bug!

Hover and focus the ShowPassword button in this validation error styling example https://ui.docs.amplify.aws/react/components/passwordfield#validation-error-styling

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by esauerbo** [comment]
Closing with https://github.com/aws-amplify/amplify-ui/pull/4789
