### ISSUE TITLE
1693778720548 is too large (or, if negative, too small) to represent as an Int64

### ISSUE THREAD

**Issue by HurgotDev** [aws-amplify/amplify-ui#4411]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Next.js 12

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

I have configured AWS Rekognition Faceliveness in my app. In my local development environment, everything works perfectly fine, but in production, I'm encountering the following error:

Error: 1693778720548 is too large (or, if negative, too small) to represent as an Int64
    at Il.fromNumber (https://*******/_next/static/chunks/455-5b3503bfe0192017.js:6183:84611)
    at Ic.formatHeaderValue (https://*******/_next/static/chunks/455-5b3503bfe0192017.js:6183:86230)
    at Ic.format (https://*******/_next/static/chunks/455-5b3503bfe0192017.js:6183:85203)
    at IQ.signMessage (https://*******/_next/static/chunks/455-5b3503bfe0192017.js:6183:95482)
    at IQ.sign (https://*******/_next/static/chunks/455-5b3503bfe0192017.js:6183:94875)
    at Object.transform (https://*******/_next/static/chunks/455-5b3503bfe0192017.js:6192:13422)

### What's the expected behaviour?

I expect an OK response from the server

### Help us reproduce the bug!

1. Create app with Next.js 12
2. Configure Amplify and Faceliveness
3. Build production
4. Start production project

### Code Snippet

```typescript
const LivenessCamera: FC<{
  onConfirm?: (imageSource: string) => void
  onCancel?: () => void
}> = ({ onConfirm, onCancel }) => {
  const [loading, setLoading] = React.useState(true)
  const [createLivenessApiData, setCreateLivenessApiData] = React.useState<{
    sessionId: string
  } | null>(null)

  const loadingRef = React.useRef(false)

  const toBase64 = async (imageBytes: number[]): Promise<string> => {
    return await new Promise((resolve, reject) => {
      const byteArray = new Uint8Array(imageBytes)
      const blob = new Blob([byteArray])
      const reader = new FileReader()

      reader.onload = function () {
        resolve(reader.result as string)
      }

      reader.onerror = () => {
        reject('Cannot convert blob to base64')
      }

      reader.readAsDataURL(blob)
    })
  }

  const handleAnalysisComplete = async () => {
    const res = await verificationService.getFaceLivenessSessionResults(
      createLivenessApiData.sessionId,
    )

    if (res.Confidence < 70) {
      Swal.fire({
        title: 'Verificación de presencia fallida',
        text: 'Lo sentimos, no pudimos confirmar tu presencia en este momento. Por favor, inténtalo de nuevo.',
        showCancelButton: false,
        confirmButtonText: 'Intentar de nuevo',
        confirmButtonColor: '#1A9EF6',
      }).then(() => {
        onCancel?.()
      })
    } else {
      const bytes: number[] = Object.values(res?.ReferenceImage?.Bytes || {})

      const base64Image = await toBase64(bytes)

      onConfirm?.(base64Image)
    }
  }

  React.useEffect(() => {
    const fetchCreateLiveness = async () => {
      if (loadingRef.current) return
      loadingRef.current = true
      await verificationService
        .createFaceLivenessSession()
        .then((res) => {
          setCreateLivenessApiData({
            sessionId: res.SessionId,
          })
          setLoading(false)
        })
        .finally(() => {
          loadingRef.current = false
        })
        .catch((err) => {
          console.log(err)
        })
    }

    fetchCreateLiveness()
  }, [])

  return (
    <LivenessCameraWrapper>
      {loading ? (
        <Loader />
      ) : (
        <FaceLivenessDetector
          disableInstructionScreen
          region="us-east-1"
          sessionId={createLivenessApiData.sessionId}
          onAnalysisComplete={handleAnalysisComplete}
          onError={(error) => {
            console.log(error)
          }}
          onUserCancel={() => {
            onCancel?.()
          }}
        />
      )}
    </LivenessCameraWrapper>
  )
}

```

**Comment by HurgotDev** [comment]
I upgraded Next.js, Typescript to the latest versions and everything worked great.

But the problem still persists in Next.js 12.

**Comment by hbuchel** [comment]
Hi @HurgotDev Glad you found a work around. We show an image in our example app (Next.js@11) for liveness; wondering if this method for getting the base64 string works for your Next.js 12 install? 

```
var base64string = Buffer.from(
    new Uint8Array(Object.values(auditImageBytes))
  ).toString('base64');
```

https://github.com/aws-amplify/amplify-ui/blob/main/examples/next/pages/ui/components/liveness/components/LivenessInlineResults.tsx#L17-L19

**Comment by reesscot** [comment]
@HurgotDev Are you still seeing this error?

**Comment by HurgotDev** [comment]
No, after upgrading to Next.js 13, I no longer have the error. It seems to have been resolved with the update. Thank you!
