### ISSUE TITLE
In the documentation in the dark mode we cannot see the variant types in the dropdown

### ISSUE THREAD

**Issue by Pavan-Rajesh** [aws-amplify/amplify-ui#4455]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

No the issue is in the documentation

### What browsers are you seeing the problem on?

Chrome in windows

### Which region are you seeing the problem in?

Asia

### Please describe your bug.

![amplifydraw](https://github.com/aws-amplify/amplify-ui/assets/90332218/bba9ca88-101c-40a4-ad07-cf5f75f421d3)

In the variations dropdown I cannot see the words they are  **mixed with the background**

### What's the expected behaviour?

We should be able to see the variants clearly and the white background should be removed and they are mixed with each other
![amplifydraw](https://github.com/aws-amplify/amplify-ui/assets/90332218/dc52b989-7fad-4794-9f92-fa0039d426e2)

### Help us reproduce the bug!

got to this link and switch to dark mode [docs of amplify ui](https://ui.docs.amplify.aws/react/components/badge)  and checkout the variants dropdown

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by lavr001** [comment]
Thank you for bringing it up. It will be fixed in our next release this week.

**Comment by hbuchel** [comment]
@Pavan-Rajesh Closing as this was fixed in yesterday's doc release.
