### ISSUE TITLE
FR (Account Settings): Add translation strings in the ChangePassword React component 

### ISSUE THREAD

**Issue by jerocosio** [aws-amplify/amplify-ui#4466]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Account Settings

### Please describe your feature-request in detail.

Allow translation for Account Setting Components like the ChangePassword component. 

I understand that it's still under development and I can see a TODO item around adding the strings to AccountSettingsTextUtil as I could see [here](https://github.com/aws-amplify/amplify-ui/blob/b3f4b6c7b2243e06ff874633a438d3d70b13b93c/packages/react/src/components/AccountSettings/ChangePassword/ChangePassword.tsx#L41), so I just wanted to know if it's something that's on the radar or in the next roadmaps, as it's really hard to use it on my Spanish language as I would need to redo almost all the components just to change the strings :).

### Please describe a solution you'd like.

To add all the required strings into the translation files so that we can use them easily in non-english websites. 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ioanabrooks** [comment]
Hi @jerocosio,

Thanks for reaching out! This is on our roadmap and will be part of our upcoming major release, stay tuned!

**Comment by reesscot** [comment]
Hi @jerocosio,
The ability to customize the strings has been updated in the latest version of the ChagnePassword component!
https://ui.docs.amplify.aws/react/connected-components/account-settings/change-password#text-and-labels

**Comment by jerocosio** [comment]
That's great @reesscot ! But unfortunately I changed my back-end services a couple of months ago, as AWS was slowing me a little bit down, but I'm sure this will help a lot of people!
