### ISSUE TITLE
CSS warning when building production mode with nuxt 3

### ISSUE THREAD

**Issue by lephuongbg** [aws-amplify/amplify-ui#4484]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Nuxt 3

### Please describe your bug.

Building with Nuxt in production mode current spewing following warning:

```
 WARN  warnings when minifying css:
Warning: G] Expected ";" but found "}" [css-syntax-error]

    <stdin>:1:280680:
      1 │ ...ta-amplify-spacer]{@apply flex-1}[data-amplify-lostcode]{@apply ...
        │                                    ^
        ╵                                    ;


Warning: G] Expected ";" but found "}" [css-syntax-error]

    <stdin>:1:280737:
      1 │ ...@apply flex flex-col items-start}[data-amplify-select]{@apply bl...
        │                                    ^
        ╵                                    ;


Warning: G] Expected ";" but found "}" [css-syntax-error]

    <stdin>:1:280927:
      1 │ ...lias-label]{@apply flex flex-col}.amplify-authenticator__font{fo...
        │                                    ^
        ╵                                    ;
```

### What's the expected behaviour?

There should be no warning

### Help us reproduce the bug!

In `layouts/default.vue` simply have this:

```vue
<script lang="ts">
import {Authenticator} from '@aws-amplify/ui-vue'
import '@aws-amplify/ui-vue/styles.css'
//...
</script>
```

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ioanabrooks** [comment]
Hi @lephuongbg thank you for opening this issues, investigating!
