### ISSUE TITLE
not all the authenticator login options are being populated

### ISSUE THREAD

**Issue by eayyar-qs** [aws-amplify/amplify-ui#4518]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

create react app

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Which region are you seeing the problem in?

east

### Please describe your bug.

We have set up cognito properly for social authentication (Google/Facebook) and also standard authentication. When we render the hosted UI from Cognito, we are able to see all the authentication options and all of them are working exactly as expected. 

In our react app, we used the Authenticator object as explaned in this link however we dont see the social media options that are enabled in Cognito. 

https://aws.amazon.com/blogs/mobile/amplify-uis-new-authenticator-component-makes-it-easy-to-add-customizable-login-pages-to-your-react-angular-or-vue-app/

We tried to force the social media icons to appear with The buttons appear in the login form but nothing happens when they are clicked.

We are able to get a valid token when typing in the user name and password for a registered user or are able to register a user properly.

We tried to research a lot of documentation, several examples and could not find anything in this regard.

Wasnt sure if we are missing something or there is an issue.

### What's the expected behaviour?

We used this documentation to get this working and were hoping it to work as detailed here - It says that 

**Zero-config setup with the Admin UI and CLI: The Authenticator UI automatically detects your deployed authentication settings and displays the relevant login mechanisms – in this case Email Facebook, and Google.**

https://aws.amazon.com/blogs/mobile/amplify-uis-new-authenticator-component-makes-it-easy-to-add-customizable-login-pages-to-your-react-angular-or-vue-app/

### Code Snippet

```typescript
// Put your code below this line.

//default - only shows username and password and it works as expected but no social media login options
         <Authenticator>
    {({ signOut, user }) => (
      <main>
        <h1>Hello {user.username}</h1>
        <button onClick={signOut}>Sign out</button>
      </main>
    )}
  </Authenticator>



or 

//force the social media buttons to render - clicking on the buttons does nothing other than the sign in button circling.
 <Authenticator socialProviders={['facebook', 'google']}>
    {({ signOut, user }) => (
      <main>
        <h1>Hello {user.username}</h1>
        <button onClick={signOut}>Sign out</button>
      </main>
    )}
  </Authenticator>

```

### Console log output

Pls see above. we used the code from the link as is to create a small test application

https://aws.amazon.com/blogs/mobile/amplify-uis-new-authenticator-component-makes-it-easy-to-add-customizable-login-pages-to-your-react-angular-or-vue-app/ 

### Additional information and screenshots

Login screen with Authenticator

<img width="498" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/146374938/2f6d53de-7876-4e59-b65b-c94292328545">

Login screen with social media buttons forced (but does nothing when clicking on those buttons)

<img width="563" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/146374938/70229688-dc56-478e-8834-eefcf1546c39">

**Comment by reesscot** [comment]
@eayyar-qs I tested the steps in the article and was able to setup social signin with Google successfully:
<img width="489" alt="CleanShot 2023-10-09 at 13 01 13@2x" src="https://github.com/aws-amplify/amplify-ui/assets/6165315/6386892a-d1cd-4a29-a503-d728e4b2325c">

You must setup Google and Facebook OAuth via either the Amplify CLI or via Amplify Studio.  Where are you setting up Google and Facebook? 

![CleanShot 2023-10-09 at 12 52 10@2x](https://github.com/aws-amplify/amplify-ui/assets/6165315/53cf7d2d-e4ef-4fd0-b465-4262740bb6db)

Also see:
https://docs.amplify.aws/lib/auth/social/q/platform/js/#oauth-and-federation-overview

**Comment by eayyar-qs** [comment]
Thank you so much for your response. In our case, we have done this in AWS Amplify however we used an existing pool that was already created in Cognito which had Google, Facebook authentication options available. 
I did also perform a amplify pull however this time around, we get the following message - No AppSync API configured. Please add an API. I am going to try and unlink the existing Cognito pool and try to create the pool with the 2 authentication options enabled or try it in a sample application like you have done able. Please give me a day to try out and respond.

**Comment by reesscot** [comment]
Closing this out as we haven't heard back and were not able to reproduce the issue. Please open a new issue if you're still having a problem as we don't monitor closed tickets.
