### ISSUE TITLE
liveness component tfjs blazeface is deprecated 

### ISSUE THREAD

**Issue by hariharansuresh** [aws-amplify/amplify-ui#4535]
### On which framework/platform would you like to see this feature implemented?

React, React Native

### Which UI component is this feature-request for?

Liveness

### Please describe your feature-request in detail.

tfjs/blazeface is used for detection of face information in liveness check. 
tfjs/blazeface is deprecated and its advised to use tfjs/facedetection.

Please advice the impact of the deprecated component with the liveness checks.

### Please describe a solution you'd like.

Integrate tfjs/facedetection 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @hariharansuresh, thank you for reporting this issue. We are aware of it and are working on a fix.

**Comment by thaddmt** [comment]
We recently upgraded to MV 3.0.0 which includes the update from blazeface to mediapipe - https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-liveness/CHANGELOG.md#300
