### ISSUE TITLE
Social-only Sign In / Up

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#454]
When creating a backend with only social providers, the `username` + `password` fields still show:

> ![Screen Shot 2021-09-30 at 11 22 35 AM](https://user-images.githubusercontent.com/15182/135493774-4fd23b1d-18ce-4717-871a-b032adb65fdf.png)
 
```js
export default () => <Authenticator loginMechanisms={["google"]}>
  {props => <App {...props} />}
</Authenticator>
```

**Comment by eddiekeller** [comment]
Amplify requires either phone number / username / email. Closing issue.

**Comment by ericclemmons** [comment]
![Screen Shot 2021-10-04 at 2 09 22 PM](https://user-images.githubusercontent.com/15182/135910119-f13106a7-aa59-4133-9e85-422dfc31c4da.png)
