### ISSUE TITLE
Is it possibile to have the Authenticator sign-in button to trigger a custom function?

### ISSUE THREAD

**Issue by Andrea-Dispe** [aws-amplify/amplify-ui#4550]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Would be awesome (if it doesn't exist already) to be able to trigger a custom function on the Authenticator sign-in button. For example to send a custom event to be tracked by GA4.
So far I didn't find a way to get the sign-in button to trigger a custom function.``

### Please describe a solution you'd like.

Click on sign-in button and trigger a custom function

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by esauerbo** [comment]
Hey @Andrea-Dispe, thanks for raising this! Our Authenticator component does currently allow you to override the signup function (as well as a few other functions). Here's the relevant [documentation](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls). I'm gonna close this issue but feel free to open it if this doesn't address your use-case.
