### ISSUE TITLE
[react native]: Could not find a declaration file for module 'aws-amplify-react-native'. 

### ISSUE THREAD

**Issue by ysael** [aws-amplify/amplify-ui#458]
![image](https://user-images.githubusercontent.com/1785595/135503969-e2b3f159-0ff9-4dc7-af05-b3a2029d8583.png)
using version 5.0.3

![image](https://user-images.githubusercontent.com/1785595/135504093-48892d80-42c0-4e9e-887b-83ad8cc0ad64.png)

**Comment by calebpollman** [comment]
Hi @ysael! `aws-amplify-react-native` is no longer actively maintained beyond critical updates, and is in the process of deprecation. There is a new React Native UI package in the works in the [Amplify UI](https://github.com/aws-amplify/amplify-ui) repo, the discussion can be tracked [here](https://github.com/aws-amplify/amplify-ui/discussions/945).
