### ISSUE TITLE
LivenessCameraModule not compatible with bootstrap 5

### ISSUE THREAD

**Issue by marcelcaferati** [aws-amplify/amplify-ui#4597]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

CRA

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari, iOS (React Native), Android (React Native)

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

When using bootstrap 5 the Freshness Canva wont show up, the screen wont flash the colors which will reduce the Confidence level in about 25-30 points.

The error happens because the [this](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-liveness/src/components/FaceLivenessDetector/LivenessCheck/LivenessCameraModule.tsx) component has a "hidden" property in the line 176

Bootstrap has a CSS property inside their reset module which adds display block to every component with the "hidden" property

### What's the expected behaviour?

The amplify liveness component is supposed to work without being affected by other libraries, since aws launched their face liveness feature, people will start integrating it inside their existing aplications.

### Help us reproduce the bug!

Import the default and complete boostrap and run the example from this tutorial
https://ui.docs.amplify.aws/react/connected-components/liveness

### Code Snippet

```css
[hidden] {
  display: none !important;
}

```
```
<View
  as="canvas"
  ref={freshnessColorRef}
  className={LivenessClassNames.FreshnessCanvas}
  hidden
/>
```

**Comment by reesscot** [comment]
@marcelcaferati See: https://github.com/aws-amplify/amplify-ui/issues/4413#issuecomment-1707167935 for a workaround

I'm going to mark this as closed without a plan to fix. We do try to be good "neighbors" with other design systems/tooling but the issue here is really with Bootstrap css overreaching with its hidden attribute !important styling. Please feel free to open a new issue if there is anything else we can help with.

**Comment by radimvaculik** [comment]
@marcelcaferati Hi, did you solve it somehow? Any workaround? Thanks!
