### ISSUE TITLE
Authenticator doesn't stay authenticated

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#470]
When running the <http://localhost:3000/ui/components/authenticator/withAuthenticator> example (`yarn next-example dev`), refreshing the page **doesn't** show my app, but instead shows the Authenticator again.

**Comment by eddiekeller** [comment]
Would this be unique to `withAuthenticator` for some reason? This doesn't happen when I use the `<Authenticator>` component.

**Comment by ericclemmons** [comment]
I'll double-check!  Good callout, because I was also about to update the other examples to use `withAuthenticator`.

**Comment by ericclemmons** [comment]
@eddiekeller Wait, I think the bug came from a bad merge when I did #453

**Comment by eddiekeller** [comment]
Approved the pull request, but yeah, still not seeing the bug. I normally use the `federated` example, but I didn't see it with `phone-number` either.
