### ISSUE TITLE
formFields are not applied to forgotPassword page

### ISSUE THREAD

**Issue by MauriceHeinze** [aws-amplify/amplify-ui#4766]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

The custom form fields are not applied to the reset password page.

### What's the expected behaviour?

I expect to see my custom label ("Your Email Address") on the reset password page.

### Help us reproduce the bug!

Copy paste my code and click on "forgot your password?"

### Code Snippet

import { useAuthenticator, View, useTheme, Authenticator, Button, Flex, Heading, Image, Text } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { Amplify } from 'aws-amplify';
import awsExports from '../aws-exports';
import { useEffect } from 'react';

Amplify.configure({
  Auth: {
    region: awsExports.REGION,
    userPoolId: awsExports.USER_POOL_ID,
    userPoolWebClientId: awsExports.USER_POOL_APP_CLIENT_ID
  }
})

const components = {
  Header() {
    const { tokens } = useTheme();

    return (
      <View textAlign="center" padding={tokens.space.large}>
        <Image
          alt="Amplify logo"
          src="../src/assets/logo.svg"
        />
      </View>
    );
  },

  SignIn: {
    Header() {
      const { tokens } = useTheme();

      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Sign in to your account
        </Heading>
      );
    },
  },
};

const formFields = {
  signIn: {
    username: {
      placeholder: '',
      isRequired: true,
      label: 'Email:'
    },
    password: {
      placeholder: '',
      isRequired: true,
      label: 'Password:'
    },
  },
  forgotPassword: {
    username: {
      placeholder: '',
      isRequired: true,
      label: 'Your Email Address'
    },
  },
  forceNewPassword: {
    password: {
      placeholder: '',
      isRequired: true,
      label: 'New Password:',
    },
    confirm_password: {
      placeholder: '',
      isRequired: true,
      label: 'Repeat New Password:',
    }
  },
  confirmResetPassword: {
    confirmation_code: {
      placeholder: '',
      isRequired: true,
      label: 'Confirmation Code:',
    },
    password: {
      placeholder: '',
      isRequired: true,
      label: 'New Password:',
    },
    confirm_password: {
      placeholder: '',
      isRequired: true,
      label: 'Repeat New Password',
    },
  },
  setupTotp: {
    QR: {
      totpIssuer: 'test issuer',
      totpUsername: 'amplify_qr_test_user',
    },
    confirmation_code: {
      placeholder: '',
      isRequired: true,
      label: 'Confirmation Code:',
    },
  },
  confirmSignIn: {
    confirmation_code: {
      placeholder: '',
      isRequired: true,
      label: 'MFA code',
    },
  },
};

function App() {

  return (
    <div>
      <Authenticator slot="sign-in" hideSignUp formFields={formFields} components={components}>
        {({ signOut, user }) => (
          <main>
            <h1>Hello {user?.username}</h1>
            <Button
              variation="primary"
              onClick={signOut}>Sign out</Button>
          </main>
        )}
      </Authenticator>
    </div>
  );
}

export default App;

**Comment by MauriceHeinze** [comment]
Hi @calebpollman,

Thanks for the info! For some reason installing the Amplify UI via the command on the website (npm i @aws-amplify/ui-react aws-amplify) results in version 5.3.2

npm list @aws-amplify/ui-react         
amplify-ui-demo@0.0.0 /Users/mauriceheinze/Desktop/repos/tco_frontend_admin
└── @aws-amplify/ui-react@5.3.2

**Comment by ioanabrooks** [comment]
@MauriceHeinze going to close this, let us know if you have any other issues!
