### ISSUE TITLE
Reset password form does not work properly

### ISSUE THREAD

**Issue by IngaFrontend** [aws-amplify/amplify-ui#4772]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

webpack

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### Which region are you seeing the problem in?

Europe (eu-central-1)

### Please describe your bug.

The user initiates the process of resending a verification code by clicking the "Resend code" button in the reset password form. The button's label dynamically changes from its initial state (e.g., "submit") to "submitting"  which means the resend process is in progress. However, the described problem is that after the button label changes to indicate submission, the process stalls, and the code is not resent.  The browser console displays the following warning: "utils.js:509 Warning: No service found for invocation 'resetPassword' in machine 'forgotPasswordActor'."  Also is it possible to prevent the submit button text from changing to "submitting" after pressing the "Resend Code" button? 

### What's the expected behaviour?

The expected behavior would be for the resend code to be processed, and the user should receive a new verification code.

### Help us reproduce the bug!

Use the <Authenticator/> component and try to reproduce the issue.

### Code Snippet

```typescript
// Put your code below this line.

```

### Console log output

1. Warning: No service found for invocation 'resetPassword' in machine 'forgotPasswordActor'.
2. Warning: React does not recognize the `data-amplify-authenticator-Forgotpassword` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-amplify-authenticator-forgotpassword` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by esauerbo** [comment]
Hi @IngaFrontend, sorry you're experiencing this issue. Can you provide a relevant code snippet and your `package.json` so we can try to reproduce this?

**Comment by esauerbo** [comment]
@IngaFrontend we were able to reproduce this with the latest version of `@aws-amplify/ui-react`. Thanks for bringing this to our attention, we'll be working on a fix.

**Comment by esauerbo** [comment]
Hey @IngaFrontend please upgrade to the latest version of `@aws-amplify/ui-react` for the fix. 
https://www.npmjs.com/package/@aws-amplify/ui-react/v/6.0.3
