### ISSUE TITLE
[missing-page] On search "withAuthenticator" first link is broken

### ISSUE THREAD

**Issue by kevinhdz97** [aws-amplify/amplify-ui#4779]
**Page**: `https://ui.docs.amplify.aws/react/guides/auth-protected`

**Comment by esauerbo** [comment]
Hi @kevinhdz97 thanks for raising this, and we'll work on getting a fix out for that link. In the meantime you can find docs on using `withAuthenticator` [here](https://ui.docs.amplify.aws/react/connected-components/authenticator#step-3-add-the-authenticator).

**Comment by reesscot** [comment]
This has been fixed
