### ISSUE TITLE
React Face Liveness component in iOS 15.x all browser occurred websocket errror, component version 2.0.11

### ISSUE THREAD

**Issue by yoruponder** [aws-amplify/amplify-ui#4825]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Create React App 

### What browsers are you seeing the problem on?

Chrome, Safari

### Which region are you seeing the problem in?

ap-northeast-1

### Please describe your bug.

user can not connect aws websocket, and throw this error, via sentry we collection this information
![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/7548d343-a070-4ce7-99a7-f3d90676ba68)

in user side they show this dialog
<img width="389" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/9858714/98fe9f58-04b8-4e44-b874-911039caa563">

here is sentry tag
![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/ba153e46-daa3-482a-a23c-ea4d5bec00de)

User-Agent 
Mozilla/5.0 (iPhone; CPU iPhone OS 15_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Mobile/15E148 Safari/604.1

![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/64a4f316-f761-4409-b08e-93c6f4d39d2d)

### What's the expected behaviour?

iOS user can use liveness service normally

### Help us reproduce the bug!

when use the iOS 15.x device run liveness component in browser may reproduce the error

### Code Snippet

```typescript

<FaceLivenessDetector
          sessionId={createLivenessApiData ? createLivenessApiData.sessionId : ''}
          region="ap-northeast-1"
          onAnalysisComplete={handleAnalysisComplete}
          disableInstructionScreen={disableInit}
          onUserCancel={() => {
            setLoading(true);
            userCancel();
          }}
          onError={(error) => {
            // -------------------- I send component error to sentry write here --------------------
            console.log('<FaceLivenessDetector>', error)

            if(uid){
              Sentry.setTag("uid", uid);
            }
            
            Sentry.setTag("component", "FaceLivenessDetector");
            let sentry_context = {
              uid,
              type: 'component',
              client,
              access_token,
            }
            if(createLivenessApiData){
              sentry_context.session_id = createLivenessApiData ? createLivenessApiData.sessionId : '';
            }
            Sentry.setContext("Custom-error", sentry_context);
            Sentry.captureException(error);
            Sentry.captureMessage(`<FaceLivenessDetector>-${error.state}`);
          }}
       .....
     />
```

### Additional information and screenshots

user  devices
![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/13eef5a5-1776-477b-8c99-81ae773aba25)

**Comment by yoruponder** [comment]
![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/13eef5a5-1776-477b-8c99-81ae773aba25)
user  devices

**Comment by esauerbo** [comment]
Hi @yoruponder, are you also seeing this error with the [latest version](https://www.npmjs.com/package/@aws-amplify/ui-react-liveness) of `@aws-amplify/ui-react-liveness`?

**Comment by yoruponder** [comment]
Hi @esauerbo , I found v3 version react-liveness UI had change, maybe some unknow api also been change, I couldn't update react-liveness to v3 by myself, need to contact and confirm with other team member, it's not easy things 😞, Is it v2 version fix this problem？

**Comment by yoruponder** [comment]
v3 react-liveness components prop did not have **customization Instructions**, react-liveness docs also change, and could not find v2 docs, our product need this api to tell user be ready for face check😅😅

**Comment by yoruponder** [comment]
Hi @esauerbo, thank you for response.
I saw sentry it still occur this error, our `@aws-amplify/ui-react-liveness` version is 2.0.11

![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/908fd4ef-b87d-428c-8adf-ba2145280e3b)

**Their devices totally are iPhone**, and error from 861184 change to 1721344

![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/94b684bb-fc3c-43b6-b975-d779de337feb)

Our team has no plan to Upgrading `@aws-amplify/ui-react-liveness` in the near future 😂

**Comment by yoruponder** [comment]
Hi @esauerbo, thank you for response.
I saw sentry it still occur this error, our `@aws-amplify/ui-react-liveness` version is 2.0.11

![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/fd432368-6c2a-4714-8875-c24a37ebf6bb)

**Their devices totally are iPhone**, and error from 861184 change to 1721344

![image](https://github.com/aws-amplify/amplify-ui/assets/9858714/94b684bb-fc3c-43b6-b975-d779de337feb)

Our team has no plan to Upgrading `@aws-amplify/ui-react-liveness` in the near future 😂

**Comment by yoruponder** [comment]
```bash
react-liveness
├── @aws-amplify/ui-react-liveness@2.0.11 -----------------> 2.0.11
├── @babel/plugin-proposal-private-property-in-object@7.21.11
├── @sentry/react@7.85.0
├── @testing-library/jest-dom@5.17.0
├── @testing-library/react@13.4.0
├── @testing-library/user-event@13.5.0
├── aws-amplify@5.3.7 -------------------> 5.3.7
├── env-cmd@10.1.0
├── http-proxy-middleware@2.0.6
├── react-dom@18.2.0
├── react-scripts@5.0.1
├── react@18.2.0
├── sass@1.65.1
└── web-vitals@2.1.4
```

**Comment by reesscot** [comment]
Hi @yoruponder,
There was a change made on the service side that should have resolved this issue. Can you please let us know if you are still seeing this issue?

**Comment by yoruponder** [comment]
Hi @reesscot , In sentry console, It seen like never occur this error again.
Thank you!!

**Comment by reesscot** [comment]
@yoruponder So glad to hear that, and thank you for letting us know! I'll close this out now.
