### ISSUE TITLE
Issues using `withAuthenticator` in Next React typeScript boilerplate project

### ISSUE THREAD

**Issue by traysonkelii** [aws-amplify/amplify-ui#4835]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

I am trying to setup a simple login page leveraging Cognito (created with CDK) and a simple react frontend to test the authentication. I wanted to integrate the `withAuthenticator` hook into the latest Next React 14 project. I assume there must be some dependency issues, but I can't seem to fix it. I used basic boiler plate `cli` commands. I am at a loss...

Here is the error I am seeing: 
```
./node_modules/@aws-amplify/ui-react-core/dist/esm/components/FormCore/FormProvider.mjs
./node_modules/@aws-amplify/ui-react-core/dist/esm/index.mjs
./node_modules/@aws-amplify/ui-react/dist/esm/index.mjs
./src/app/layout.tsx
 ⨯ ./node_modules/@aws-amplify/ui-react-core/dist/esm/components/FormCore/FormProvider.mjs
Attempted import error: 'useForm' is not exported from 'react-hook-form' (imported as 'useForm').
```

I am wrapping my layout (most outer component) with the basic Amplify setup. Code snippet below

```
import { Amplify } from "aws-amplify";
import awsconfig from "../aws-exports";
import "@aws-amplify/ui-react/styles.css";
import { withAuthenticator } from "@aws-amplify/ui-react";

Amplify.configure(awsconfig);

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <StyledComponentsRegistry>
          <Navbar />
          {children}
          <GlobalStyles />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

export default withAuthenticator(RootLayout);
```

And here is the `package.json` file:
```
{
   ....
  "dependencies": {
    "@aws-amplify/ui-react": "^6.0.5",
    "aws-amplify": "^6.0.6",
    "next": "14.0.2",
    "react": "^18",
    "react-dom": "^18",
    "styled-components": "^6.1.1"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "18.2.23",
    "@types/react-dom": "18.2.8",
    "eslint": "^8",
    "eslint-config-next": "14.0.2",
    "typescript": "^5.3.3"
  }
}
```

And finally my `tsconfig.json`: 

```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

### What's the expected behaviour?

The `node_modules` of the `@aws-amplify/ui-react` wouldn't throw any errors. I cannot even pull up the UI. When I remove the `withAuthenticator` hook the error is gone and the UI works as expected.

### Help us reproduce the bug!

Following commands below reproduces the issue:
- ` npx create-next-app@latest --ts ` (fill out default values)
- For ease of testing you can skip the whole backend resource allocation
- `npm install aws-amplify @aws-amplify/ui-react` 
- Modify the boiler plate code with the hoc implementation as demonstrated [here](https://docs.amplify.aws/nextjs/build-a-backend/auth/set-up-auth/#:~:text=the%20wrapped%20component.-,Usage,-TypeScript)
- Then run the code `npm run dev` 

### Code Snippet

```typescript
import Image from "next/image";
import styles from "./page.module.css";
import {
  WithAuthenticatorProps,
  withAuthenticator,
} from "@aws-amplify/ui-react";

export function Home() {
  return (
    <main className={styles.main}>
      <h1>Test</h1>
    </main>
  );
}

export default withAuthenticator(Home);
```

### Console log output

```
 ⨯ ./node_modules/@aws-amplify/ui-react-core/dist/esm/components/FormCore/FormProvider.mjs
Attempted import error: 'useForm' is not exported from 'react-hook-form' (imported as 'useForm').

Import trace for requested module:
./node_modules/@aws-amplify/ui-react-core/dist/esm/components/FormCore/FormProvider.mjs
./node_modules/@aws-amplify/ui-react-core/dist/esm/index.mjs
./node_modules/@aws-amplify/ui-react/dist/esm/index.mjs
./src/app/page.tsx
 ⨯ ./node_modules/@aws-amplify/ui-react-core/dist/esm/components/FormCore/FormProvider.mjs
Attempted import error: 'useForm' is not exported from 'react-hook-form' (imported as 'useForm').

Import trace for requested module:
./node_modules/@aws-amplify/ui-react-core/dist/esm/components/FormCore/FormProvider.mjs
./node_modules/@aws-amplify/ui-react-core/dist/esm/index.mjs
./node_modules/@aws-amplify/ui-react/dist/esm/index.mjs
./src/app/page.tsx
```

### Additional information and screenshots

package.json
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^6.0.5",
    "aws-amplify": "^6.0.6",
    "next": "14.0.4",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.0.4",
    "typescript": "^5"
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by JoseeWouters** [comment]
Running into the same problem, also tried using `<Authenticator>` component and downgrading to an earlier version of the package, but both give the same error.

**Comment by traysonkelii** [comment]
I did verify that it works with the regular React app (i.e. `npx create-react-app app-name --template typescript`) this seems to be an issue with NextJs I believe.

**Comment by JoseeWouters** [comment]
I found [this](https://github.com/vercel/next.js/issues/56041)  on the Next.js Github, wondering if this would solve it for us too. Didn't have the chance of trying it out yet, but wanted to leave this here for you @traysonkelii

**Comment by traysonkelii** [comment]
Thanks @JoseeWouters I tried messing around with some of the solutions provided there, no luck. I'm not too deep into my application yet and I'll probably pivot away from Next for the time being :/ at least until the issue gets resolved.

**Comment by gulloa91** [comment]
Try changing the component to a client component by adding:

"use client";

at the top of the page

**Comment by traysonkelii** [comment]
Thanks @gulloa91! That fixed it. I am curious how did you know to do that? What was the reasoning?

**Comment by gulloa91** [comment]
Sure, in the amplify docu (https://ui.docs.amplify.aws/react/getting-started/usage/nextjs) it says: "Amplify UI components are interactive and designed to work on the client side. To use them inside of Server Components you must wrap them in a Client Component with "use client"

**Comment by traysonkelii** [comment]
brilliant, I totally overlooked that. Thank you!
