### ISSUE TITLE
dark mode not working? 

### ISSUE THREAD

**Issue by booboothefool** [aws-amplify/amplify-ui#4837]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator, Storage (Storage Manager)

### How is your app built?

next.js

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

us-west-1

### Please describe your bug.

I am expecting this to enable dark mode but it is still white. Are there steps I am missing? 

```
    <ThemeProvider colorMode="dark">
      <Card>
        <Button>Hello</Button>
        <Text variation="primary">Primary text</Text>
        <Text variation="secondary">Secondary text</Text>
        <Text variation="tertiary">Tertiary text</Text>
      </Card>
    </ThemeProvider>
```

### What's the expected behaviour?

Expect components to be dark instead of white. 

### Help us reproduce the bug!

I cannot get any component to use dark mode.

**Comment by ioanabrooks** [comment]
Hi @booboothefool, are you passing a dark theme override to the `ThemeProvider`? Amplify UI has one that you can use, see an example [here](https://ui.docs.amplify.aws/react/theming/dark-mode#default-dark-mode).

**Comment by booboothefool** [comment]
> Hi @booboothefool, are you passing a dark theme override to the `ThemeProvider`? Amplify UI has one that you can use, see an example [here](https://ui.docs.amplify.aws/react/theming/dark-mode#default-dark-mode).

Oh, I didn't realize I needed `overrides: [defaultDarkModeOverride]` because I was already specifying `colorMode="dark"`. That worked, thank you!

```
<ThemeProvider
  theme={{
    name: 'my-theme',
    overrides: [defaultDarkModeOverride]
  }}
  colorMode="dark"
>
```
