### ISSUE TITLE
Cognito signup not rendering signup attributes

### ISSUE THREAD

**Issue by RushiPardeshi** [aws-amplify/amplify-ui#4850]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Safari

### Which region are you seeing the problem in?

us-west-2

### Please describe your bug.

I have mentioned "Name" as the signup attribute in Authentication in my AWS Amplify Studio. In fact I also checked my amplifyconfiguration.json file:

```json
"aws_cognito_signup_attributes": [
    "NAME"
  ],
```
But it is rendered as follows:
<img width="1271" alt="Screenshot 2023-12-14 at 1 46 32 AM" src="https://github.com/aws-amplify/amplify-ui/assets/90044303/ceac259e-ca64-4ec5-adf7-14be015d462a">

### What's the expected behaviour?

It should also ask for the name.

### Help us reproduce the bug!

1. Deploy Authentication with Name as a signup attribute.
2. `amplify pull` the generated command.
3. Run the frontend.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by calebpollman** [comment]
@RushiPardeshi Can you please confirm that the configuration inside _amplifyconfiguration.json_ is being passed directly to `Amplify.configure`?

**Comment by calebpollman** [comment]
@RushiPardeshi  We have merged a fix for the issue [here](https://github.com/aws-amplify/amplify-ui/pull/4861) which will go out in our next release. 

In the meantime you can either pin your `aws-amplify` version to `6.0.5`, or point your `@aws-amplify/ui-react` version to `next`.
