### ISSUE TITLE
I agree with the Terms & Conditions cannot be removed

### ISSUE THREAD

**Issue by kenneth-ede** [aws-amplify/amplify-ui#4852]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Which region are you seeing the problem in?

eu-west-1

### Please describe your bug.

**I agree with the Terms & Conditions** checkbox is automatically added to a sign up form and I cannot remove it.

### What's the expected behaviour?

I apply form fields; id terms and conditions is not there then it sould not be displayed

### Help us reproduce the bug!

below is the entire file/vue component
![signup](https://github.com/aws-amplify/amplify-ui/assets/19793660/2988c214-91e4-468a-be14-10730f3b6fc1)

### Code Snippet

```typescript
// Put your code below this line.
<script setup lang="ts">
  import { Authenticator, AuthenticatorSignUpFormFields, useAuthenticator } from '@aws-amplify/ui-vue';
  import '@aws-amplify/ui-vue/styles.css';

  import { Amplify } from 'aws-amplify';
  import awsconfig from '../aws-exports';
  //import { fetchAuthSession } from 'aws-amplify/auth';

  // import axios from 'axios';
  import { toRefs } from 'vue';
  Amplify.configure(awsconfig);

  const { validationErrors } = toRefs(useAuthenticator());

  /*
  async function getAccessToken() {
    try {
      const accessToken = (await fetchAuthSession()).tokens?.accessToken ?? {};
      return accessToken;
    } catch (err) {
      console.log(err);
    }
  }
  */

  const formFields = {
    signUp: {
      email : {
        labelHidden: true,
        placeholder: 'Your email address*',
        isRequired: true,
        order: 1
      },
      password: {
        labelHidden: true,
        placeholder: 'Your password*',
        isRequired: true,
        order: 2
      },
      confirm_password: {
        labelHidden: true,
        placeholder: 'Confirm password*',
        isRequired: true,
        order: 3 
      },
      'language_custom_attribute': {
        labelHidden: true,
        placeholder: '- Select your preferred language -',
        isRequired: false,
        order: 4
      }
    }
  }

</script>

<template>
  <authenticator usernameAlias="email" initial-state="signUp" :form-fields="formFields">
    <template v-slot:sign-up-fields>
      <authenticator-sign-up-form-fields />
      <amplify-check-box :errorMessage="validationErrors.acknowledgement" />
    </template>
  </authenticator>

</template>''
```

### Additional information and screenshots

![signup](https://github.com/aws-amplify/amplify-ui/assets/19793660/24630c65-0c6b-4447-ae23-ad4952de4f5a)

**Comment by calebpollman** [comment]
Hi @kenneth-ede. Using the example code provided I was unable to repro your issue:
<img width="496" alt="CleanShot 2023-12-14 at 09 26 17@2x" src="https://github.com/aws-amplify/amplify-ui/assets/15002885/aa3ef01a-42ac-47fd-a394-f5b92fb8f353">

A couple things to note from the example code:
- the `authenticator` element does not recognize `usernameAlias` as a property and should be removed
- the `amplify-check-box` element is not resolved as it has not been imported and should be removed. Believe this was copied over from the documentation [here](https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#sign-up-fields) which includes adding a "terms and conditions" input

Can make the changes above and let us know if you are still having issues?

**Comment by kenneth-ede** [comment]
Hi Caleb,

Thanks for your response.  It worked !

There are two other things I want to add.  The first is a select list, and
the second is a cancel button with would just redirect the user.

Are there docs somewhere showing how to do these?

Cheers
Ken

**Comment by calebpollman** [comment]
For adding a cancel button, can use either the `Header` or `Footer` slots to pass in custom UI, see the docs [here](https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#headers--footers). 

`select` elements are not supported by the `formFields` property, you will need to add the html directly in the `sign-up-fields` slot, for example:
```
<template v-slot:sign-up-fields>
  <authenticator-sign-up-form-fields />
  <select name="language_custom_attribute">
    <option>Option 1</option>
    <option>Option 2</option>
  </select>
</template>
```

Going to close the issue, please open a new issue if you run in to any further issues!
