### ISSUE TITLE
Wrong uasge with useLayoutEffect and addEventListener/removeEventListener.

### ISSUE THREAD

**Issue by wenlixun** [aws-amplify/amplify-ui#4858]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Webpack

### Please describe your bug.

Cannot remove the EventListener like below.It may cause the memory rise

### What's the expected behaviour?

That should be
```typescript
useLayoutEffect(() => {
  function fn(e) {
    sendLandscapeWarning(e.matches);
  }
  
  // Listen for future orientation changes and send warning
  landscapeMediaQuery.addEventListener('change', fn);

   // Remove matchMedia event listener
  return () => {
    landscapeMediaQuery.removeEventListener('change', fn);
  };
}, [])
```

### Help us reproduce the bug!

It's easy to see

### Code Snippet

```typescript
React.useLayoutEffect(() => {
    if (isMobile) {
      // ...
      // Listen for future orientation changes and send warning
      landscapeMediaQuery.addEventListener('change', (e) => {
        sendLandscapeWarning(e.matches);
      });

      // Remove matchMedia event listener
      return () => {
        landscapeMediaQuery.removeEventListener('change', (e) =>
          sendLandscapeWarning(e.matches)
        );
      };
    }
  }, [isMobile, send]);
```

**Comment by thaddmt** [comment]
Hello @wenlixun ! Thanks for filing the bug. The intention here is for this event listener to only run when the `isMobile` flag is true. When testing I have found that it does seem to correct add and remove the event listener on mobile devices and does not do so on non-mobile devices. Is there still a concern here?

**Comment by reesscot** [comment]
Closing out as this is working as expected.
