### ISSUE TITLE
Clarification on theming authenticator

### ISSUE THREAD

**Issue by hanna-becker** [aws-amplify/amplify-ui#4864]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

expo

### Which region are you seeing the problem in?

eu-central-1

### Please describe your bug.

After migrating to @aws-amplify/ui-react-native v2.0.6, our previous theming does not work to change the color of the buttons in the authenticator any longer. We changed the primary colors inside the "brand" object as described [in the docs](https://ui.docs.amplify.aws/react-native/connected-components/authenticator/customization#theme-provider), however, while this changed the authenticator button colors in v1, it does not any longer do so in v2:
```
theme={{
  tokens: {
    colors: {
      brand: {
        primary: {
          10: '{colors.pink.10}',
          20: '{colors.pink.20}',
          40: '{colors.pink.40}',
          60: '{colors.pink.60}',
          80: '{colors.pink.80}',
          90: '{colors.pink.90}',
          100: '{colors.pink.100}',
        },
      },
    },
  },
}}
```

I can see that it works again if I discard the "brand" layer and just apply my color stylings on a "top-level" primary object like so:

```
theme={{
  tokens: {
    colors: {
      primary: {
        10: '{colors.pink.10}',
        20: '{colors.pink.20}',
        40: '{colors.pink.40}',
        60: '{colors.pink.60}',
        80: '{colors.pink.80}',
        90: '{colors.pink.90}',
        100: '{colors.pink.100}',
      },
    },
  },
}}
```

It is not very clear to me from the provided docs how we should go about styling the amplify components, e.g. where the brand value gets applied and where it doesn't, and whether this is a bug. First and foremost, this ticket is a request to update the documentation and make it easier to understand the styling system.

### What's the expected behaviour?

The docs for styling the authenticator should provide the correct details for changing stuff developers most obviously would like to theme, i.e. the buttons.

### Help us reproduce the bug!

1. Create an amplify react native app according to the docs with the newest libraries.
2. Try to theme authenticator buttons given the instructions in the authenticator theming section.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hanna-becker** [comment]
It seems like the brand namespace was removed with this commit: https://github.com/aws-amplify/amplify-ui/pull/4635

Currently, I'm struggling with the following two issues in Android:
1. The ActivityIndicator component from the "react-native" library (https://reactnative.dev/docs/activityindicator) renders in a teal color (amplify ui default primary color) in my application. It says in the link that it uses the "system accent default color" if no color is specified, so I'd like to know how to set the color in my ThemeProvider, so that it stops using the teal color. This has an easy workaround, as I can just pass the color as a property in all the places where I use the ActivityIndicator. I'd prefer a global solution, though, if possible.
2. When I select text in my app by long pressing, the background color of the highlighted text and the two bubbles marking the start and end of the highlighted text also have the amplify default teal color. I don't have a workaround on how to change the color on this one, yet.

How do we properly set up the ThemeProvider for this?

**Comment by hbuchel** [comment]
@hanna-becker Just a follow up, you should be able to share your theme tokens with other components using `useTheme()`. For example, if I wanted to style the react-native `<Text />` element I could do something like:

```js
import { StyleSheet, Text } from 'react-native';

const { tokens } = useTheme();
const styles = StyleSheet.create({
  text: {
    color: tokens.colors.primary[10],
  },
});

// Usage
<Text style={styles.text}>Test</Text>
```

`useTheme()` isn't really included in the RN theming docs, but [is documented here](https://ui.docs.amplify.aws/react/theming/theme-provider#usage). I would probably be a good addition for us to include a reference to that in the RN theming docs.
