### ISSUE TITLE
Missing docs for V5 of Amplify UI

### ISSUE THREAD

**Issue by bhelabhav** [aws-amplify/amplify-ui#4866]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Other

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

No way to see v5 documentation for Amplify UI Library @ https://ui.docs.amplify.aws/

### What's the expected behaviour?

v5 docs are available for Amplify UI Library @ https://ui.docs.amplify.aws/

### Help us reproduce the bug!

Navigate to Amplify Docs Tab: 
https://docs.amplify.aws/react/

You will see a toggle for v5 vs v6.

Navigate to:
https://ui.docs.amplify.aws/

You will NOT see a toggle for v5 vs v6 - there seems to be no way to view previous documentation. Only guides on how to migrate.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by bhelabhav** [comment]
Why this feels like an issue:

1. Most users still use v5 - AFAICT v5 is still a major supported version (since v6 only came out recently).
2. All major supported versions should have readily accessible docs for users - without having to dig through the open-source lib code to learn how to build docs (asking users to act more like contributors).

Thanks for the work done to maintain the lib and consider this feedback.

Ultimately, I'm looking for a way to access v5 docs for Amplify UI even if this isn't fixed on a whole (though I strongly feel it should be addressed widely).

**Comment by reesscot** [comment]
Hi @bhelabhav,
Are there particular v5 docs that you're looking for? The primary changes between ui-react v5 and v6 in terms of the Authenticator are changes in the underlying JS library, along with a few prop name changes: https://ui.docs.amplify.aws/react/getting-started/migration#1-updates-to-the-authenticator

I do agree, however, that we need to add notes to the UI docs where API's have changed.

**Comment by tnurmi82** [comment]
Ok so.., I wanted to use the Accordion but I couldn't import it. I quickly noticed the docs say: "In Amplify UI v5 this was called Expander.".

Which made me realize the docs are for v6 which is apparently the latest, I'm still on v5. I can't find Expander docs anywhere. There is no version selector at the UI doc site. This is not a great developer experience. Well, luckily it's easy to create an Accordion.

**Comment by bhelabhav** [comment]
This has since been fixed. See here:
https://docs.amplify.aws/react/prev/build-a-backend/

![Uploading Screenshot 2024-02-08 at 1.01.11 PM.png…]()

**Comment by reesscot** [comment]
Hi @bhelabhav,
I'm reopening this because we are still making some changes to improve the UI docs experience for v5 users. Here's the PR that should allow us to close this issue:  
https://github.com/aws-amplify/amplify-ui/pull/4985

**Comment by bhelabhav** [comment]
@reesscot Got it - thanks for clarifying and handling this with care. Very much appreciated.

**Comment by calebpollman** [comment]
Issue resolved by https://github.com/aws-amplify/amplify-ui/pull/5153
