### ISSUE TITLE
Table Striped Variation Does Not Work

### ISSUE THREAD

**Issue by thomas-j-moffett** [aws-amplify/amplify-ui#4885]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

The table variation of "striped" doesn't work. I am using version 6.1.0 of `@aws-amplify/ui-react` package.

### What's the expected behaviour?

The striped variation should make the table striped.

### Help us reproduce the bug!

This can easily be seen in your own documentation here: https://ui.docs.amplify.aws/react/components/table?tab=#variation

It seems to work if I manually add `data-variation="striped"` to the `table` element while modifying the HTML in Chrome dev tools on your documentation page linked above. It seems that there is a `amplify-table--bordered` CSS class generated for the bordered one, and there is a corresponding CSS rule in the source. There is also a `amplify-table--striped` CSS class generated for the striped table, but no corresponding CSS rule could be found. I did find the `data-variation="striped"` in the source which is why I tried it out.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ioanabrooks** [comment]
@thomas-j-moffett Thank you for bringing this to our attention, will be addressed asap.

**Comment by ioanabrooks** [comment]
@thomas-j-moffett We just released `@aws-amplify/ui-react@6.1.1` with this fix!

**Comment by thomas-j-moffett** [comment]
Thanks!
