### ISSUE TITLE
problem with IOS Facebook federated identify when user cancel instead of confirm the signout

### ISSUE THREAD

**Issue by ericowhadi** [aws-amplify/amplify-ui#4910]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

react-native start

### What browsers are you seeing the problem on?

iOS (React Native)

### Please describe your bug.

when login using facebook federated identity to login, then click on signout button, on IOS, get prompted with something like:
"myapp" wants to use "amazoncognito" to sign in (note the confusing message because I am signin out, not signin in).
Now if I hit cancel instead of Continue, the Authenticator is in bogus state:
The ui will display the login page, but if you click on Sign In With Facebook, you will get a "Possible unhandled promise rejection. UserAlreadyAuthenticatedException: There is already a signed in user.
The only way I found to get out of that state is to restart the IOS simulator, then signoff and now correctly hit continue instead of cancel when prompted with the message.

### What's the expected behaviour?

ideally, the code should detect this situation and force logout  

### Help us reproduce the bug!

when login using facebook federated identity to login, then click on signout button, on IOS, get prompted with something like:
"myapp" wants to use "amazoncognito" to sign in (note the confusing message because I am signin out, not signin in).
Now if I hit cancel instead of Continue, the Authenticator is in bogus state:
The ui will display the login page, but if you click on Sign In With Facebook, you will get a "Possible unhandled promise rejection. UserAlreadyAuthenticatedException: There is already a signed in user.
The only way I found to get out of that state is to restart the IOS simulator, then signoff and now correctly hit continue instead of cancel when prompted with the message.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by calebpollman** [comment]
@ericowhadi Was able to reproduce the sign out behavior on our end when using the `signOut` function returned from `useAuthenticator`. Until a fix is available, a workaround is available by importing `signOut` directly from `aws-amplify/auth`:
```tsx
import { signOut } from 'aws-amplify/auth';'
```
