### ISSUE TITLE
user.username contains facebook_someid or google_someid and not the email

### ISSUE THREAD

**Issue by frederic-thibault** [aws-amplify/amplify-ui#4911]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

angular buidl system

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

When using the component amplify-authenticator or the following code, the user.username contains facebook_111111111111111 or google_1111111111111111 and not the email. The only way to get the email is to get it directly from the bearer token in the localStorage. In any cases I have the email or the fullname, it is only available in the bearer token and I can see it in the aws cognito console.

### What's the expected behaviour?

I expect to have the user that contains the user email and/or fullname like specified in the amplify doc

### Help us reproduce the bug!

configure an angular app using the command line and the code provided https://ui.docs.amplify.aws/angular/connected-components/authenticator/configuration 

### Code Snippet

```typescript
// Put your code below this line.
public ngOnInit(): void {
		this.authenticator.subscribe(i => {
			console.log(i.user);
			/*
				i.user.username should contains email or name but not facebook_someid or google_someid
			*/
		});
	}
```

### Console log output

![image](https://github.com/aws-amplify/amplify-ui/assets/47924659/df2e8c2f-6684-4754-980f-c642a8016007)

Then userId contains a guid and facebook_someNumericValue. Smae thing with google, juste different values.

**Comment by frederic-thibault** [comment]
This is the packages and versions I currently use.

"dependencies": {
		"@angular/animations": "^16.2.0",
		"@angular/common": "^16.2.0",
		"@angular/compiler": "^16.2.0",
		"@angular/core": "^16.2.0",
		"@angular/forms": "^16.2.0",
		"@angular/platform-browser": "^16.2.0",
		"@angular/platform-browser-dynamic": "^16.2.0",
		"@angular/router": "^16.2.0",
		"@ngx-translate/core": "^15.0.0",
		"@ngx-translate/http-loader": "^8.0.0",
		"@aws-amplify/ui-angular": "^5.0.7",
		"aws-amplify": "^6.0.12",
		"bootstrap": "^5.2.3",
		"linq-to-typescript": "^11.0.0",
		"ngx-bootstrap": "^11.0.2",
		"ngx-cookie-service": "^17.0.1",
		"rxjs": "~7.8.0",
		"tslib": "^2.3.0",
		"zone.js": "~0.13.0"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "^16.2.3",
		"@angular-eslint/builder": "16.2.0",
		"@angular-eslint/eslint-plugin": "16.2.0",
		"@angular-eslint/eslint-plugin-template": "16.2.0",
		"@angular-eslint/schematics": "16.2.0",
		"@angular-eslint/template-parser": "16.2.0",
		"@angular/cli": "~16.2.3",
		"@angular/compiler-cli": "^16.2.0",
		"@types/jasmine": "~4.3.0",
		"@typescript-eslint/eslint-plugin": "5.62.0",
		"@typescript-eslint/parser": "5.62.0",
		"eslint": "^8.49.0",
		"jasmine-core": "~4.6.0",
		"karma": "~6.4.0",
		"karma-chrome-launcher": "~3.2.0",
		"karma-coverage": "~2.2.0",
		"karma-jasmine": "~5.1.0",
		"karma-jasmine-html-reporter": "~2.1.0",
		"typescript": "~5.1.3"
	}

**Comment by hbuchel** [comment]
Hi @frederic-thibault I confirmed that is the response I get testing federated sign in as well. 

You should be able to access user attributes like email using `fetchUserAttributes()`. 

```
import { fetchUserAttributes } from 'aws-amplify/auth';

async function handleFetchUserAttributes() {
  try {
    const userAttributes = await fetchUserAttributes();
    console.log(userAttributes);
  } catch (error) {
    console.log(error);
  }
}
```
You can find some details for that [here](https://docs.amplify.aws/angular/build-a-backend/auth/manage-user-profile/#retrieve-user-attributes) I tested this in my federated sign-in app and was able to access the users email address when signing in with Google.

**Comment by frederic-thibault** [comment]
Thanks, with the code you provide put in place, it is now populating the userAttributes with everything I need, but it has to do a round trip to aws cognito server to get the data. Since all the data is available locally in the bearer token and must be available in the parameter i where i.authStatus=='authenticated', it seems like a workaround. I might be wrong !?

`public async ngOnInit(): Promise<void> {
		await this.authenticator.subscribe(async i => {
			console.log(i.authStatus);
			if (i.authStatus === 'authenticated') {
				debugger;
				try {
					const userAttributes = await fetchUserAttributes();
					console.log(userAttributes);
				} catch (error) {
					console.log(error);
				}
			}
		});
	}`

**Comment by hbuchel** [comment]
Hi @frederic-thibault Checking with the JS team, it sounds like the suggestion to avoid that trip is you can use `fetchAuthSession` instead:

```js
import { fetchAuthSession } from 'aws-amplify/auth';

async function currentSession() {
  try {
    const { idToken } = (await fetchAuthSession()).tokens ?? {};
  } catch (err) {
    console.log(err);
  }
}
```

And e-mail can be accessed from `idToken.payload.email`

**Comment by frederic-thibault** [comment]
Thanks very much!
