### ISSUE TITLE
How to customize Sign In's submit button?

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#492]
From Discord (https://discord.com/channels/705853757799399426/708383821401161738/896128047282024470):

> I'm trying to replace the sign in  submit button in <AmplifySignIn /> with my own button. I am using slot="primary-footer-content" to do this and it does seem to be replacing my button correctly, but it is not submitting when I click it. It appears that what is happening is that if I override the footer, the button renders outside the form which is in the shadow dom, so clicking doesn't submit the form. Any ideas on how to make overriding the button work?
> <img width="363" alt="Screen_Shot_2021-10-08_at_4 15 30_PM" src="https://user-images.githubusercontent.com/15182/136835552-5c73d81a-ed97-4841-90fe-fad92b83b3b3.png">
 

When using the v1 Authenticator (https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#sign-in), customizing the Sign In button is possible, **but it doesn't work**.

I created a demo here:
> https://codesandbox.io/s/amplify-ui-custom-sign-in-button-33oqf?file=/src/App.js:962-1095

**Comment by ericclemmons** [comment]
Styling via CSS & customizing the label is the best solution today.

We need to understand a compelling reason to replace the button component _entirely_, which would remove accessibility by default.

**Comment by lewismvaughan** [comment]
This is so frustrating, none of the hub events fire on sign in, only after the post sign in functions complete, what about people trying to show a custom loading screen, or that want to display some type of thing once the button is clicked, i found a git hub article where someone asked for this and it seems like the request was just ignored.
