### ISSUE TITLE
Unable to add custome validation in ProccesFile using StorageManager

### ISSUE THREAD

**Issue by hasadata** [aws-amplify/amplify-ui#4928]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Storage (Storage Manager)

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Firefox

### Please describe your bug.

It would be beneficial to incorporate custom validation before transmitting a file to the server. I attempted to implement the processFile function as outlined in the documentation but encountered difficulties and achieved no success.

![image](https://github.com/aws-amplify/amplify-ui/assets/155987920/6487d268-4e61-44b8-8e70-1247aa6dfe2b)

### What's the expected behaviour?

we should be able to add costume validation for example checking the number of pages in pdf before sending 

### Help us reproduce the bug!

reproducible 

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
Hi @hasadata Can you please provide us any information to help reproduce your issue? This includes:

- example code 
- any console errors you were seeing when attempting to use `processFile`

**Comment by reesscot** [comment]
Closing this out since we haven't heard back. Please open a new issues if you still have questions about using `processFile`.
