### ISSUE TITLE
Image react component to support lazy loading

### ISSUE THREAD

**Issue by davidtong** [aws-amplify/amplify-ui#4936]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

Lazy loading is very useful especially for reducing S3 usage/cost for images stored there. See https://www.w3schools.com/tags/att_img_loading.asp

The current Image component does not support it: https://ui.docs.amplify.aws/react/components/image

### Please describe a solution you'd like.

Support the loading prop or a lazy prop similar to how the native img HTML element does.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @davidtong,
This is already supported using the native `loading` browser attributes, as the Image component will pass any props straight down to the underlying `img` HTML element. 

See:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#loading

Example: https://codesandbox.io/p/sandbox/image-example-9zrtgh?file=%2Fsrc%2FApp.js%3A12%2C29
