### ISSUE TITLE
Duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by abdifardin** [aws-amplify/amplify-ui#4946]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

React Native App

### Which region are you seeing the problem in?

US

### Please describe your bug.

I just started following your documentation to install and use react native ui authentication using amplify
In the doc, it start with installing the packages
npm install @aws-amplify/ui-react-native aws-amplify @aws-amplify/react-native react-native-safe-area-context amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage react-native-get-random-values react-native-url-polyfill

After running npx pod-install and then running the ios application it keep giving symbol duplication error
I

### What's the expected behaviour?

Running without error

### Help us reproduce the bug!

Just follow the doc to setup react native ui and run the ios simulator

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

 investigated the error and found out this package is included in the initial package installation amazon-cognito-identity-js 
And it has conflict with other amplify package which themself include aws cognito js library

I removed the package and installed it again and everything run well

So i suggest to update the doc and remove that unnecessary package

**Comment by calebpollman** [comment]
@abdifardin Thanks for raising this. The install script is out of date and includes an unnecessary dependency, can you try using:
```sh
npm install @aws-amplify/ui-react-native aws-amplify @aws-amplify/react-native react-native-safe-area-context @react-native-community/netinfo @react-native-async-storage/async-storage react-native-get-random-values react-native-url-polyfill
```

**Comment by abdifardin** [comment]
As I mentioned I found the solution by removing the congnito is and it works without any problems
