### ISSUE TITLE
Upgrade to `@xstate/react` v4

### ISSUE THREAD

**Issue by strmer15** [aws-amplify/amplify-ui#4952]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Both `xstate` and `@xstate/react` have new major versions available, but since our project uses `xstate` for other purposes besides the `@aws-amplify/ui-react` `Authenticator` component, we can't update to the latest until Amplify does as well.

Here's the migration guide: https://stately.ai/docs/migration

### Please describe a solution you'd like.

Please update to the latest `@xstate/react` and `xstate` package versions so that we can avoid errors using them in our own projects.

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@strmer15 Thank you for your feature request. We will consider it for our roadmap. I'm going to close this out, as we are already tracking this here: https://github.com/aws-amplify/amplify-ui/issues/4523
