### ISSUE TITLE
Vite Usage docs are out of date and duplicated

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#4956]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Vite

### Please describe your bug.

When running through the docs there is a Getting Started -> Usage -> [Vite](https://ui.docs.amplify.aws/react/getting-started/usage/vite) section. With version six of the `aws-amplify` JS library these configurations are no longer needed. I was able to build and run a brand new Vite app without issues. Perhaps this section should have a warning that it should only be necessary to add if the customer is on < 6 `aws-amplify` library?

Also if you click on the `TypeScript` tab in the Vite section steps 1 and 2 are duplicated.

<img width="939" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/65630/532953ea-c5f9-404e-97d8-a7134c3aea0d">

### What's the expected behaviour?

Vite section should be removed or have a call out that it's only necessary with older versions of the aws-amplify library. And if nothing else the duplicated section in TypeScript should be fixed. 

### Help us reproduce the bug!

Check output of Vite usage section. 

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
This was fixed in this PR https://github.com/aws-amplify/amplify-ui/pull/4950 which will be released next week.
