### ISSUE TITLE
Docs: Angular/Vue Usage section has visual glitch

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#4957]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular, Vue

### Which UI component?

Other

### How is your app built?

Docs

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Inside the docs the Vue -> Usage section has a floating bar on the page under the call out that `aws-amplify/ui-vue` only supports cloud-connected components.

<img width="947" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/65630/fafb3b0e-e159-4647-be5f-7ac1555f1402">

I also saw this same issue in the Angular section.

<img width="1172" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/65630/1e82da6c-13f2-49db-b920-6925b39c324b">

Also, this sections is a bit confusing. Someone who wants to use the Angular or Vue library probably has no idea what a cloud-connected component is, or why there is a warning for it. Perhaps the warning could be removed, or display the instructions on how to setup the Vue or Angular authenticator in this section, instead of forcing the user to click another link to get the usage information.

### What's the expected behaviour?

Visual glitch should not be there. Also usage section could be more useful.

### Help us reproduce the bug!

Go to the usage section for both Angular and Vue.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by calebpollman** [comment]
Fixed by https://github.com/aws-amplify/amplify-ui/pull/4920
