### ISSUE TITLE
Vue peer dependency is missing

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#4958]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### Please describe your bug.

The [Vue package.json](https://github.com/aws-amplify/amplify-ui/blob/main/packages/vue/package.json#L71) is missing the peer dependency for >= 3. Since the library only works with Vue 3 and higher, if a user installs the UI packages with Vue 2, npm won't warn them that they don't satisfy the peer dependency. 

This would also align with Angular and React package.json.

### What's the expected behaviour?

The Vue package should have the correct peer dependency.

### Help us reproduce the bug!

Try to install the ui-vue package in Vue 2. Missing warning error from npm.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by calebpollman** [comment]
@ErikCH Not sure how we missed this! Addressed in https://github.com/aws-amplify/amplify-ui/pull/4964
