### ISSUE TITLE
AccountSettings.DeleteUser not localizable

### ISSUE THREAD

**Issue by nkreipke** [aws-amplify/amplify-ui#4963]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Account Settings

### How is your app built?

Vite

### Please describe your bug.

The AccountSettings.DeleteUser component supports overriding the display texts like this:

```tsx
<AccountSettings.DeleteUser displayText={{
  deleteAccountButtonText: 'Konto löschen',
  warningText: 'Möchten Sie das Konto wirklich löschen?',
  cancelButtonText: 'Abbrechen',
  confirmDeleteButtonText: 'Konto jetzt löschen'
}} />
```

As a result, the caption of the "Delete Account" button is set accordingly. The warning, cancel button text and confirm button text is however not changed and the values warningText, cancelButtonText and confirmDeleteButtonText are ALWAYS ignored. The texts can also not be localized using the Amplify I18n module.

### What's the expected behaviour?

The displayText values are not ignored.

### Help us reproduce the bug!

The bug is probably caused by `displayText` not being passed to the `WarningView` here:

https://github.com/aws-amplify/amplify-ui/blob/693d7c0f1aeae205be782c765091a4f81bc8c537/packages/react/src/components/AccountSettings/DeleteUser/DeleteUser.tsx#L116

**Comment by calebpollman** [comment]
@nkreipke Error messages can be overridden by providing a `handleDelete` prop and wrapping `deleteUser` imported from _aws-amplify/auth_ in a `try`/`catch` and throwing a custom `Error`:

```tsx
import { deleteUser } from 'aws-amplify/auth';

const MyDeleteUser = () => (
  <AccountSettings.DeleteUser
    handleDelete={async () => {
      try {
        await deleteUser();
      } catch (e) {
        if (e.__type === 'NotAuthorizedException') {
          throw new Error('Account deletion is not allowed.');
        }
        throw new Error(`Error deleting user. Please try again later.`);
      }
    }}
  />
);
```

A list of exceptions returned from `deleteUser` can be found in the [Cognito docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DeleteUser.html).

**Comment by nkreipke** [comment]
@calebpollman Thank you for your reply. I'd kindly ask you to re-read my bug report. It has got nothing to do with overriding error messages (which I never mentioned) but rather overriding the button captions.

Please reopen this as my issue was clearly misunderstood.

**Comment by calebpollman** [comment]
@nkreipke Sorry for the churn here. Re-opening the issue
