### ISSUE TITLE
Version conflicts after using aws-amplify/ui-vue and aws-amplify

### ISSUE THREAD

**Issue by dadaguai-git** [aws-amplify/amplify-ui#4974]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Other

### How is your app built?

vite

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

local

### Please describe your bug.

`@aws-amplify/ui-vue`  **version:4.1.0** 
`aws-amplify`  **version:6.0.13**
node_modules/@aws-amplify/ui-vue/dist/index.js:4:105
`Could not resolve "@aws-amplify/core/internals/utils"`
`import { AuthAction, Category, InAppMessagingAction, GeoAction, StorageAction, setCustomUserAgent } from "@aws-amplify/core/internals/utils";`

I checked the source code and found that there is really no such file directory, how to solve the problem?

### What's the expected behaviour?

Being able to fetch this file and run the application successfully

### Help us reproduce the bug!

Upgrade aws-amplify version and aws-amplify/ui-vue version to the latest version

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by esauerbo** [comment]
Hi @dadaguai-git, thanks for creating this issue. `@aws-amplify/ui-vue@4.1.0` is compatible with `aws-amplify@6.0.13`. Look inside `node_modules/@aws-amplify/core/package.json` to check which version of aws-amplify is being used. If it's not 6.0.13, try deleting the `node_modules` folder and running `npm install` again. Let me know if this works!

**Comment by dadaguai-git** [comment]
> Hi @dadaguai-git, thanks for creating this issue. `@aws-amplify/ui-vue@4.1.0` is compatible with `aws-amplify@6.0.13`. Look inside `node_modules/@aws-amplify/core/package.json` to check which version of aws-amplify is being used. If it's not 6.0.13, try deleting the `node_modules` folder and running `npm install` again. Let me know if this works!

Not really, but I found that I was able to run the app properly after installing it using pnpm

![demo_20240126174341](https://github.com/aws-amplify/amplify-ui/assets/35138018/34739ef7-df2c-4482-91f0-ad1c34da7bd9)

**Comment by esauerbo** [comment]
Glad to hear it!
