### ISSUE TITLE
All Login Buttons are Frozen on Canceling Social Login

### ISSUE THREAD

**Issue by pmoghaddam** [aws-amplify/amplify-ui#4975]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

iOS Safari - however I suspect this happens in all browsers, it's only that iOS Safari doesn't cause a browser refresh which resets the state and avoids this problem.

### Please describe your bug.

When using social logins, if the user cancels or goes back, all login buttons (including native login) do not do anything. 

The user has to either refresh, or switch tabs, for them to become active again.

### What's the expected behaviour?

The buttons should work as usual.

### Help us reproduce the bug!

I do not have anything special. If you setup social buttons, click on Sing in with Google/Apple, but _cancel_ and go back, you'll be stuck.

https://github.com/aws-amplify/amplify-ui/issues/1660 helped improve the situation since before it'd simply be blank altogether, but now the Authenticator is present, but not functional.

**Comment by calebpollman** [comment]
@pmoghaddam Was able to recreate the issue using Firefox and have opened a fix [here](https://github.com/aws-amplify/amplify-ui/pull/4978)

**Comment by alex-breen** [comment]
Has this bug regressed?

I encounter the bug on Chrome and Safari with Authenticator on latest:
"aws-amplify": "^6.0.26",
"@aws-amplify/ui-react": "^6.1.6",

**Comment by calebpollman** [comment]
@alex-breen Can you please install `aws-amplify@latest` (currently `6.0.28`) and verify if you are seeing the issue still?

**Comment by alex-breen** [comment]
@calebpollman Yes, I confirmed the issue remains on `6.0.28`  `aws-amplify@6.0.28`.
Environment:
- Chrome (latest
- Authenticator (@aws-amplify/ui-react@6.1.6)
- Cognito with Identity providers: Cognito user pool directory, Google, SignInWithApple
- Cognito is configured to use a custom domain for auth

**Comment by calebpollman** [comment]
Thanks for confirming @alex-breen. Have been unable to repro, could you please open a new issue with a small reproduction?

**Comment by alex-breen** [comment]
@calebpollman - thanks all do that. I notice that it doesn't happen if I host using `vite dev`. But if I build for production and host using `vite preview` the buttons freeze. Please LMK if you think I'm missing something obvious.

**Comment by alex-breen** [comment]
@calebpollman - I created new issue: https://github.com/aws-amplify/amplify-ui/issues/5174

**Comment by pavellazar** [comment]
Any solution or workaround on this? The issue still exists with the latest version on mobile devices

**Comment by calebpollman** [comment]
Hey @pavellazar! Can you please open a [new issue](https://github.com/aws-amplify/amplify-ui/issues/new?template=1.bug_report.yaml) and include the framework and version details?
