### ISSUE TITLE
 The federated sign-in container on the sign-in page should appear immediately after signing out, but there is a delay before it appears.

### ISSUE THREAD

**Issue by IngaFrontend** [aws-amplify/amplify-ui#5001]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

webpack

### What browsers are you seeing the problem on?

Chrome, Firefox

### Which region are you seeing the problem in?

eu-central-1

### Please describe your bug.

After the user signs in with a federated provider (Google), upon pressing the "Sign out" button, the sign-in page initially displays without the social provider options for a few seconds before it appears. However, if the user signs in with Cognito, everything works as expected without any delays.

### What's the expected behaviour?

The federated sign-in container on the sign-in page should appear immediately after signing out, without delay.

### Help us reproduce the bug!

"@aws-amplify/ui-react": "^6.0.7",
 "aws-amplify": "^6.0.9",

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

https://github.com/aws-amplify/amplify-ui/assets/133216207/bfd43d8b-b562-4f13-b19b-8ccc7169b833

**Comment by calebpollman** [comment]
Hi @IngaFrontend. Was unable to repro the issue in `@aws-amplify/ui-react@6.14`. Can you try upgrading and see if the issue still persists? 

If the issue continues to persist It may be related to configuration or how you are calling the component. In that scenario it would be helpful to see how you are using the `Authenticator` in your code and the project config file (omitting any sensitive data for example `aws_cognito_identity_pool_id`)

**Comment by IngaFrontend** [comment]
Good evening,
I upgraded  @***@***.***, but the issue still persists. In
the attached file you will find a screenshot of the Authenticator wrapper.
The configuration retrieved from `Amplify.getConfig()` has the following
structure:
Auth: {
Cognito: {
userPoolId: "string",
userPoolClientId: "string",
identityPoolId: "string",
signUpVerificationMethod: "code",
loginWith: {
oauth: {
domain: "string",
scopes: ["email", "openid", "profile", "aws.cognito.signin.user.admin"],
redirectSignIn: ["http://localhost:8000"],
redirectSignOut: ["http://localhost:8000"],
responseType: "code",
},
},
},
},
API: { REST: { backend: { region: "string", endpoint: "string" } }
}


2024-02-16, pn, 22:35 Caleb Pollman ***@***.***> rašė:

**Comment by calebpollman** [comment]
@IngaFrontend Unable to reproduce in `@aws-amplify/ui-react@latest` (6.1.7), can you verify if the issue is still persisting and if so provide a small reproduction example?

**Comment by reesscot** [comment]
Closing this out as we haven't heard back and were unable to reproduce the issue. If the error persists, please open a new issue.
