### ISSUE TITLE
StorageManager's maxFileCount does not limit selectable files if value > 1

### ISSUE THREAD

**Issue by floriankrueper** [aws-amplify/amplify-ui#5019]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Storage (Storage Manager)

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Safari

### Which region are you seeing the problem in?

eu-central-1

### Please describe your bug.

StorageManager's maxFileCount property does not limit selectable files if value > 1

### What's the expected behaviour?

1. Set maxFileCount to 3
2. Try to upload 4 files at once
3. Selection is limited to three files and it is not possible to select a fourth

### Help us reproduce the bug!

1. Include StorageManager
2. Set maxFileCount to 3
3. Select 4 files for upload
4. Upload

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by esauerbo** [comment]
Hi @floriankrueper thanks for creating this issue. Which version of `@aws-amplify/ui-react-storage` are you seeing this behavior with? 

Also which method are you using to upload files (drag and drop or select files)? And do you have [manual uploads ](https://ui.docs.amplify.aws/react/connected-components/storage/storagemanager#manually-upload) enabled?

**Comment by floriankrueper** [comment]
Hi @esauerbo thank you for getting back to me!

The version of `@aws-amplify/ui-react-storage` is 2.3.0.
It does not matter whether you drag the files on the component or select them using the button. The result is the same.
And no, we are not using manual uploads.

this basically is how we use the component:
`<StorageManager                        
                        className="dropzone"
                        name={name}
                        key={index}
                        isRequired={required}
                        accessLevel="public"
                        defaultFiles={payload}
                        maxFileCount={limit}
                        maxFileSize={100000}
                        acceptedFileTypes={acceptedFileTypes || '*/*'}
                        onUploadError={(error, { key }) => {
                            setFiles((prevFiles) => {
                                return {
                                    ...prevFiles,
                                    [key]: {
                                        status: 'error',
                                    },
                                };
                            });
                        }}
                        onUploadSuccess={({ key }) => {
                            setFiles((prevFiles) => {
                                return {
                                    ...prevFiles,
                                    [name]: {
                                        key: key,
                                        status: 'success',
                                    },
                                };
                            });

                            validate(name, "hasFiles");                            
                        }}`

**Comment by esauerbo** [comment]
Hi @floriankrueper, I wasn't able to reproduce this behavior with version 2.3.0. I wanted to clarify something -- the [`maxFileCount`](https://ui.docs.amplify.aws/react/connected-components/storage/storagemanager#setting-limits) prop is intended to limit the number of files that can be uploaded at one time, not the total number of files that can be uploaded. 

Could you clarify the behavior you're seeing? i.e. can you select & upload 4 files _at once_ when `maxFileCount` is 3 vs. you're able to incrementally upload 4 files total.

Here's a screen recording that shows the expected behavior for when `maxFileCount` is 3

https://github.com/aws-amplify/amplify-ui/assets/70536670/b35d9d39-483e-4623-803e-4a0f46d9b740

**Comment by floriankrueper** [comment]
Hi @esauerbo, we are clear on the intended functionality. We implemented our own logic to limit the overall amount of files. What is not working is that we are able to select and upload 5 files at a time when maxFileCount is set to a lower number.

**Comment by floriankrueper** [comment]
Hi @esauerbo! Just seen your recording. It seems we had still misunderstood the intention of maxFileCount to make it impossible to actually upload more than the number of specified files and not "just" display an error message. The error message is for some reason hidden in our implementation, so we were unaware of it. So sorry to have bothered you with this! Thank you very much for your help!
