### ISSUE TITLE
React: It seems like all of the UI components in the @aws-amplify/ui-react is requiring placeholder as a property

### ISSUE THREAD

**Issue by amzn-mnnurza** [aws-amplify/amplify-ui#5033]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Primitive components

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### Please describe your bug.

Every component that has been imported from the @aws-amplify/ui-react is requiring placeholder to be declared. 
![Screenshot 2024-02-26 at 2 00 48 PM](https://github.com/aws-amplify/amplify-ui/assets/159466062/97345088-09cd-4383-a5c1-8d3afbc109ad)

### What's the expected behaviour?

The placeholder property should be optional especially on components like flex

### Help us reproduce the bug!

downloading the latest @aws-amplify/ui-react

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by hbuchel** [comment]
Hi @amzn-mnnurza Which version of @aws-amplify/ui-react are you using? Could you paste us your package.json? 

Additionally, one thing I would try is clearing our your node_modules folder; delete node_modules folder then run `yarn` or `npm` install, depending on which you are using.  Sometimes this type of error can popup if you have recently updated a package and types from different packages are out of sync.

**Comment by amzn-mnnurza** [comment]
Awesome. yeah it looked like our packages were outdated. Thanks for the help.
