### ISSUE TITLE
Angular: Importing AuthenticatorService from @aws-amplify/ui-angular not working with Jest tests

### ISSUE THREAD

**Issue by JuNe98** [aws-amplify/amplify-ui#5035]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Angular 16

### Please describe your bug.

I want to test my service where I am using `AuthenticatorService` from `@aws-amplify/ui-angular`.

I have tried to find how to setup my test environment with jest but the test are always failing.

### What's the expected behaviour?

Test should work as expected. No special outcome.

### Help us reproduce the bug!

Try to build a service which imports `AuthenticatorService` from `@aws-amplify/ui-angular`

### Code Snippet

jest.config.ts
```Typescript
import type { Config } from 'jest';

const config: Config = {
  // Automatically clear mock calls, instances, contexts and results before every test
  clearMocks: true,

  // Indicates whether the coverage information should be collected while executing the test
  collectCoverage: true,

  // The directory where Jest should output its coverage files
  coverageDirectory: 'coverage',

  // Indicates which provider should be used to instrument code for coverage
  coverageProvider: 'v8',

  // A map from regular expressions to module names or to arrays of module names that allow to stub out resources with a single module
  moduleNameMapper: {
    '^@environment$': '<rootDir>/src/environments/index.ts',
    '^@shared$': '<rootDir>/src/app/shared/index.ts',
    '^@shared/components$': '<rootDir>/src/app/shared/components/index.ts',
    '^@shared/directives$': '<rootDir>/src/app/shared/directives/index.ts',
    '^@shared/guards$': '<rootDir>/src/app/shared/guards/index.ts',
    '^@shared/models$': '<rootDir>/src/app/shared/models/index.ts',
    '^@shared/pipes$': '<rootDir>/src/app/shared/pipes/index.ts',
    '^@shared/services$': '<rootDir>/src/app/shared/services/index.ts',
    '^@shared/services-general$': '<rootDir>/src/app/shared/services-general/index.ts',
    '^@shared/services/api$': '<rootDir>/src/app/shared/services/api/generated/index.ts',
    '^@auth$': '<rootDir>/src/app/auth/index.ts',
  },

  // A preset that is used as a base for Jest's configuration
  preset: 'jest-preset-angular',

  // A list of paths to modules that run some code to configure or set up the testing framework before each test
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],

  // The test environment that will be used for testing
  testEnvironment: 'jsdom',
};

export default config;

```

auth.service.ts
```Typescript
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { BehaviorSubject, Observable, from, map, catchError, of } from 'rxjs';
import { UserRole } from '@shared/models';
import { AuthenticatorService } from '@aws-amplify/ui-angular';
import { fetchAuthSession, fetchUserAttributes } from '@aws-amplify/auth';

@Injectable({
  providedIn: 'root'
})
export class AuthService {

  public loggedIn: BehaviorSubject<boolean>;

  constructor(private readonly router: Router, private authenticatorService: AuthenticatorService) {
    this.loggedIn = new BehaviorSubject<boolean>(false);
  }

  public getAccessToken(): Observable<string | undefined> {
    return from(fetchAuthSession().then(res => {
      return res.tokens?.accessToken.toString();
    }));
  }

  public getIdTokenPayload(): Observable<any | undefined> {
    return from(fetchAuthSession().then(res => {
      return res.tokens?.idToken?.payload;
    }));
  }

  /** get authenticat state */
  public isAuthenticated(): Observable<boolean> {
    return from(fetchAuthSession())
      .pipe(
        map((_result) => {
          this.loggedIn.next(true);
          return true;
        }),
        catchError((_error: any) => {
          this.loggedIn.next(false);
          return of(false);
        })
      );
  }

  public getUserAttributes() {
    return from(fetchUserAttributes())
      .pipe(
        map((_result) => {
          return _result;
        }),
        catchError((_error: any) => {
          return of({});
        })
      );
  }

  public userGroups(): Observable<UserRole[]> {
    return from(fetchAuthSession()).pipe(
      map((res) => 
        res.tokens?.idToken?.payload['cognito:groups'] as UserRole[]
      )
    )
  }

  /** signout */
  public signOut() {
    this.authenticatorService.signOut();
    this.loggedIn.next(false);
    this.router.navigate(['/login']);
  }
}
```

auth.service.spec.ts
```Typescript
import { TestBed } from '@angular/core/testing';

import { AuthService } from './auth.service';
import { AmplifyAuthenticatorModule } from '@aws-amplify/ui-angular';

describe('AuthService', () => {
  let service: AuthService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [AmplifyAuthenticatorModule]
    });
    service = TestBed.inject(AuthService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
```

### Console log output

 FAIL  src/app/auth/auth.service.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    C:\Development\Production\ado\ds-cemtec\customer-portal-ui\node_modules\nanoid\index.prod.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { urlAlphabet } from './url-alphabet/index.js'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 | import { BehaviorSubject, Observable, from, map, catchError, of } from 'rxjs';
      4 | import { UserRole } from '@shared/models';
    > 5 | import { AuthenticatorService } from '@aws-amplify/ui-angular';
        | ^
      6 | import { fetchAuthSession, fetchUserAttributes } from '@aws-amplify/auth';
      7 |
      8 | @Injectable({

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (node_modules/@aws-amplify/ui-angular/fesm2020/aws-amplify-ui-angular.mjs:11:24)
      at Object.<anonymous> (src/app/auth/auth.service.ts:5:1)
      at Object.<anonymous> (src/app/auth/auth.service.spec.ts:3:1)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 | 
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        23.233 s

### Additional information and screenshots

Used package versions

- "@aws-amplify/ui-angular": "^5.0.10"
- "aws-amplify": "^6.0.10",
- "jest-preset-angular": "^14.0.0",
- "jest": "^29.5.0",

**Comment by reesscot** [comment]
@JuNe98 This sounds like an issue with compiling ES Modules to CJS which is supported in the Node execution environment. It looks like the error may be coming from nanoid:

```
C:\Development\Production\ado\ds-cemtec\customer-portal-ui\node_modules\nanoid\index.prod.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { urlAlphabet } from './url-alphabet/index.js'
```

Have you tried transforming the `nanoid` package?

**Comment by JuNe98** [comment]
@reesscot  Yes, no it`s working. I had to modify the `transformIgnorePatterns` as following:
```Typescript
transformIgnorePatterns: [
    '/node_modules/(?!(@angular|@aws-amplify|@ag-grid-community|nanoid))',
    '\\.pnp\\.[^\\/]+$',
],
```

Thanks
