### ISSUE TITLE
SessionNotFoundException 

### ISSUE THREAD

**Issue by Slopez-Newtech** [aws-amplify/amplify-ui#5043]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

Following the amplify installation guide I am getting this error, I am getting the sessionId correctly but when the FaceLivenessDetection component starts it tells me SessionNotFoundException

### What's the expected behaviour?

At this point the FacelivenessDetection component should start scanning the face.

### Help us reproduce the bug!

Front Reactjs
https://github.com/Slopez-Newtech/Onb-amazon-front

backend NodeJs
https://github.com/Slopez-Newtech/Onboarding-amazon-backend

### Code Snippet

```javascript
// Put your code below this line.
export function LivenessQuickStartReact() {
	const [loading, setLoading] = React.useState(true);
	const [createLivenessApiData, setCreateLivenessApiData] =
		React.useState(null);

	Amplify.configure(awsexports);

	React.useEffect(() => {
		try {
			const fetchCreateLiveness = async () => {
				const resp = await fetch("http://localhost:8080/api/faceliveness/create-session", {
					method: "get",
					headers: {
						"Content-Type": "application/json",
					},
				});

				const dta = await resp.json();
				console.log('rqst Is 1: ' + dta.requestId);
				await new Promise((r) => setTimeout(r, 2000));
				const mockResponse = { sessionId: dta.requestId };
				const data = mockResponse;

				setCreateLivenessApiData(data);
				setLoading(false);
			};

			fetchCreateLiveness();
		} catch (error) {
			console.log(error);
		}

	}, []);

	const handleAnalysisComplete = async () => {
		try {
			const response = await fetch(`localhost:8080/api/faceliveness/get-session-result/${createLivenessApiData.sessionId}`, {
				method: "get",
				headers: {
					"Content-Type": "application/json",
				},
			});
			const data = await response.json();
			if (data.isLive) {
				console.log('User is live');
			} else {
				console.log('User is not live');
			}
		} catch (error) {
			console.log(error);
		}
	};

	return (
		<div>

			{loading ? (
				<Loader />
			) : (
				<ThemeProvider>

					<FaceLivenessDetector
						sessionId={createLivenessApiData.sessionId}
						region="us-east-1"
						onAnalysisComplete={handleAnalysisComplete}
						onError={(error) => {
							console.error(error);
						}}
					/>
				</ThemeProvider>
			)}
		</div>

	);
}

AWS_EXPORT

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0870c1c5-98af-4f56-85a2-ef900d685b86",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tw5Dts9GL",
    "aws_user_pools_web_client_id": "4o25n6k1i462qtjdjai5dg7ata",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;

```

### Console log output

{
    "state": "SERVER_ERROR",
    "error": {
        "name": "SessionNotFoundException"
    }
}

### Additional information and screenshots

![Screenshot 2024-03-05 160446](https://github.com/aws-amplify/amplify-ui/assets/157845160/6b9430a2-57f8-4ec2-bec4-2d4f39473d4e)

**Comment by reesscot** [comment]
@Slopez-Newtech Please see the following troubleshooting guide
https://ui.docs.amplify.aws/react/connected-components/liveness/troubleshooting#error-server-error---session-not-found

Please let me know if this doesn't solve your issue.

**Comment by reesscot** [comment]
@Slopez-Newtech Were you able to try the suggestions mentioned in our troubleshooting guide? Were you able to resolve the error?

**Comment by reesscot** [comment]
Closing this out as we haven't heard back. Please open a new issue if you are still seeing this issue after following our troubleshooting guide.
