### ISSUE TITLE
amplify-authenticator returns sub as username when back-end is configured  as e-mail only

### ISSUE THREAD

**Issue by joeld98** [aws-amplify/amplify-ui#5052]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

Using Amplify Gen-2 to create auth backend configured for e-mail login only with email verification. Once the verification code step completed returns sub as user.username to amplify-authenticator instead of e-mail.

### What's the expected behaviour?

Expected amplify-authenticator user.username to return verified email instead of sub OR userAttributes.email made available to the component.

### Help us reproduce the bug!

Create auth backend with Amplify Gen 2 configured for email only login.
Add <amplify-authenticator [loginMechanisms]="['email']">  section to frontend.
Complete registration and email verification steps.
On Login display "Welcome {{ user.username }}

### Code Snippet

```typescript
// Put your code below this line.
/auth/resource.ts:
import { defineAuth } from '@aws-amplify/backend';

export const auth = defineAuth({
  loginWith: {
    email: {
      verificationEmailStyle: "CODE",
      verificationEmailBody: (code: string) =>
        `Welcome! Your verification code is ${code}.`,
      verificationEmailSubject: "Welcome! Here is your verification code",
    }
  },
  multifactor: {
    mode: 'OPTIONAL',
    totp: true,
    sms: false
  },
  userAttributes: {
  },
});

Frontend:

<amplify-authenticator [loginMechanisms]="['email']">
                    <ng-template
                      amplifySlot="authenticated"
                      let-user="user"
                      let-signOut="signOut"
                    >
                      <h1>Welcome {{ user.username }}!</h1>
                      <button (click)="signOut()">Sign Out</button>
                    </ng-template>
                  </amplify-authenticator>
```

**Comment by esauerbo** [comment]
Hi @joeld98 thanks for creating this issue. You can retrieve the user's email using the `fetchUserAttributes` API like so:
``` 
import { fetchUserAttributes } from 'aws-amplify/auth'
const { email } = fetchUserAttributes()
```
Here's the gen2 [documentation](https://docs.amplify.aws/gen2/build-a-backend/auth/manage-user-profile/#retrieve-user-attributes) on that. 

Let us know if this adequately addresses your use case!

**Comment by joeld98** [comment]
Thank you, will try pulling the attributes. The way I read the [Login Mechanism](https://ui.docs.amplify.aws/angular/connected-components/authenticator/configuration) section of the documentation was that [loginMechanisms]="['email'] on the amplify-authenticator control would override the default username binding.

**Comment by reesscot** [comment]
@joeld98 As of `aws-amplify` v6, `user.username` will always return the sub and the email address is only available via the `fetchUserAttributes` JS API. Hope this answers your question.

**Comment by joeld98** [comment]
Yes, thank you for clarifying.
