### ISSUE TITLE
[Documentation] React auth customization example referencing previous version (v5)

### ISSUE THREAD

**Issue by isaaccarrington** [aws-amplify/amplify-ui#5053]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

When I implemented an [override for function calls](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls) it took a while for me to figure out that the example was for version 5.

I would like the current example to use the current version, version 6. The documentation should also link to a list of available functions to override, currently you have to guess, or at least I did. The [v5 to v6 documentation](https://docs.amplify.aws/react/build-a-backend/auth/auth-migration-guide/#authsignup) was helpful but I still had to infer a lot and test a lot.

### Please describe a solution you'd like.

I think I have described what I would like the documentation to be updated to and have put my hand up to contribute.
```ts
import { Amplify } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import { signUp } from 'aws-amplify/auth';
import '@aws-amplify/ui-react/styles.css';
import awsExports from './aws-exports';
Amplify.configure(awsExports);

export default function AuthenticatorWithEmail() {
  const services = {
    async handleSignUp(formData) {
      let { username, password, options } = formData;
      // custom username
      username = username.toLowerCase();
      options.userAttributes.email = options.userAttributes.email.toLowerCase();
      return signUp({
        username,
        password,
        options,
      });
    },
  };

  return (
    <Authenticator services={services} initialState="signUp">
      {({ signOut }) => <button onClick={signOut}>Sign out</button>}
    </Authenticator>
  );
}
```

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by esauerbo** [comment]
Hi @isaaccarrington thanks for creating this issue. There's an open [pull request](https://github.com/aws-amplify/amplify-ui/pull/4985) to address the override function calls examples that highlights the differences between v5 and 6. If you feel like it's lacking anything let us know. 

There's currently a list of the `handle` overrides [here](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls) (can't link directly to it but if you scroll past the code sample). The list is a little outdated (e.g. `Auth.signUp` should be `signUp`) but is also part of the pr. 

I did notice we don't have a complete list of `validate` overrides, like `validateCustomSignUp`, which are part of the services object ([documentation](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#sign-up-fields)). We can include that in the open pr as well.

**Comment by isaaccarrington** [comment]
Thanks @esauerbo , apologies that I missed the PR. It looks good to me so I approved the PR. One thing that would put the icing on the cake would be a link to the signup API docs so people could look at an example and then see all the inputs and output for it and any of the other overrides. But nice work and thank you
