### ISSUE TITLE
Authenticator Modal Takes Up Whole Page And Covers Other Elements

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#509]
After adding in the authenticator to a Vue, React or Angular project, the `div` with the `data-amplify-modal` covers the whole page, obscuring any other HTML elements on the page (Other then the authenticator)

**Comment by ericclemmons** [comment]
@ErikCH Do you know off-hand what the default experience is for https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue/?

I remember when we launched last year, one of the first issues was that the form wasn't centered on the screen & we had to wrap it in a container.

**Comment by ErikCH** [comment]
The legacy Vue UI authenticator allows you to enter data above or below it. It is centered horizontally and vertically by using flex with a min-height. 

I like the `variation` approach with adding in `modal`. I can add that to vue perhaps?

**Comment by ericclemmons** [comment]
This will help out with the docs, too.

- [ ] Docs will just use an `Authenticator`.
- [ ] Remove `.example [data-authenticator]` overrides for docs.
- [ ] Centering within the given space for the Authenticator is desirable (e.g. `place-items: center` or `place-self: center` I think), but having `min-height` isn't IMO.
- [ ] Docs will need `Configuration > variant` added.
- [ ] `<Authenticator variant="modal">` will offer the modal experience. 
- [ ] Styles should target `[data-amplify-authenticator] [data-variant=modal]`
    
    I don't know if we need to change the markup vs. leaving the default unstyled?
