### ISSUE TITLE
Expose attributes in Auth.signIn

### ISSUE THREAD

**Issue by SinBirb** [aws-amplify/amplify-ui#5111]
### On which framework/platform would you like to see this feature implemented?

Vue

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Using [Override Function Calls](https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#override-function-calls), I override the `signIn()` function. There I want to access my custom attribute, but `attributes` are only available in the `Auth.signUp()` method, not in `Auth.signIn()`. I would expect it to be there as well.

Is there another way to access the value as a work-around?

### Please describe a solution you'd like.

Pass the `attributes` property to `signIn(formData)`.

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
@SinBirb Thank you for your question. Can you explain a bit more what you are trying to accomplish? Are you trying to set a custom attribute on sign in?

**Comment by SinBirb** [comment]
Yeah, I want the user to input a custom attribute (or get it from the URL, if set) and use it to create the actual username for sign in.

This way the user should be able to have multiple users with the same email address in the same user pool. We will construct the username from the email and the custom attribute.

**Comment by reesscot** [comment]
@SinBirb It sounds like your primary goal is to prepopulate the username field from the url? If that's the case you can use the `formFields` API. See: https://github.com/aws-amplify/amplify-ui/issues/1669#issuecomment-1421299691

Is this what you're looking for?

**Comment by SinBirb** [comment]
Yes, I found that in the meantime and it works, using `document.getElementsByName()[0]`. Didn't seem like the most elegant solution though.

To explain a bit more my use case: We want to implement multi-tenancy with usernames like "tenant/email@host.com". This way we work around the limit of 10,000 groups per user pool while being able to have multiple users with the same email address but different tenant. Users should be able to sign-in by specifying their email address and tenant, separately.

This is a recommended use-case by AWS but unfortunately, documentation is lacking: https://docs.aws.amazon.com/cognito/latest/developerguide/custom-attribute-based-multi-tenancy.html

**Comment by reesscot** [comment]
Just curious, why do you need to use `document.getElementsByName()[0]`? Where is the tenant name coming from? I'm still confused how you're going to get a custom attribute from Cognito before signing the user in.

**Comment by reesscot** [comment]
I'm going to close this out, as this isn't something we are planning to support.
