### ISSUE TITLE
Docs refer to aws-exports.js not amplifyconfiguration.json

### ISSUE THREAD

**Issue by mousedownmike** [aws-amplify/amplify-ui#5114]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### Please describe your bug.

The [documentation refers to an `aws-exports.js` file](https://ui.docs.amplify.aws/vue/connected-components/authenticator#step-1-configure-backend) being generated, but the CLI appears to generate a `amplifyconfiguration.json` file now.

### What's the expected behaviour?

Documentation should reflect the current code.

### Help us reproduce the bug!

Create a VUE project with typescript and then follow the [instructions for adding auth](https://docs.amplify.aws/vue/start/getting-started/auth/).

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hi @mousedownmike,
Both `aws-exports.js` and `amplifyconfiguration.json` files are being created in the current Amplify CLI. Are you using Gen2?

**Comment by mousedownmike** [comment]
I didn't get aws-exports.js the first time, but I'm unable to reproduce it now... closing.
