### ISSUE TITLE
[Bug] Liveness: Use credentialProvider 

### ISSUE THREAD

**Issue by luisbytes** [aws-amplify/amplify-ui#5126]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Microsoft Edge

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

When trying to use a custom credential provider in the Liveness component it is not possible, vs code shows that the property does not exist in the "FaceLivenessDetectorConfig" interface. Reviewing said interface I see that it extends "FaceLivenessDetectorCoreConfig" but omitting "credentialProvider" and "endpointOverride".

<img width="1298" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/137983537/e8f129bb-8ad3-4663-b8d7-e9b284a365e5">

I don't know if this is a bug, because in the documentation there is a section to implement a Custom Credentials Provider

<img width="900" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/137983537/41b00d0e-4c3c-4850-b5bd-df84410fe419">

### What's the expected behaviour?

Use credentialProvider in FaceLivenessDetector

### Help us reproduce the bug!

Follow the official [documentation](https://ui.docs.amplify.aws/react/connected-components/liveness) to implement a Custom Credential Provider 

### Code Snippet

```typescript
import { FaceLivenessDetectorCore, AwsCredentialProvider } from '@aws-amplify/ui-react-liveness';
 
const credentialProvider: AwsCredentialProvider = async () => {
  // Fetch the credentials
}

return (
  <FaceLivenessDetectorCore
    sessionId={'<sessionId>'}
    region={'<region>'}
    onAnalysisComplete={() => {}}
    onError={onError}
    config={{ credentialProvider }}
  />
);
```

**Comment by calebpollman** [comment]
@luisbytes Can you please provide some additional context (version of `@aws-amplify/ui-react-liveness` used in your project, code snippet of your use case, reproduction steps, etc)?

**Comment by luisbytes** [comment]
@calebpollman The version used is @aws-amplify/ui-react-liveness@3.0.16, para reproducirlo basta con seguir la documentación oficial. To reproduce it, just follow the official documentation.

<img width="1329" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/137983537/fff1d3eb-1de1-4c12-8e8f-a50cf2465f6d">

**Comment by calebpollman** [comment]
Can you try replacing `FaceLivenessDetector` with `FaceLivenessDetectorCore`?

**Comment by luisbytes** [comment]
@calebpollman Thanks, I think it was an error of interpretation on my part when reading the documentation.

<img width="1256" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/137983537/268b55b6-5ace-4821-9d05-8d21b4909d42">

The problem I have now is that I can't render the component.

<img width="1047" alt="image" src="https://github.com/aws-amplify/amplify-ui/assets/137983537/efb40448-a69a-49a7-8029-753512e3b1ee">

Context, I am trying to render the react liveness component in a WC with stencil, following the [example for angular](https://github.com/aws-samples/aws-rekognition-liveness-detection/blob/main/src/FaceLivenessReactWrapperComponent.tsx)

**Comment by calebpollman** [comment]
@luisbytes Are you able to reproduce this issue using in a React project (without Angular integration)?

**Comment by luisbytes** [comment]
Hello, I managed to execute it using createElement()
