### ISSUE TITLE
[Bug] Documentation: Liveness Custom CDN missing wasm setup instructions

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#5128]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

N/A

### Please describe your bug.

Currently the documentation for setting up a custom CDN only shows instructions for how to setup the SIMD version of the tensorflow backend. 

According to the documentation, Tensorflow supports regular WASM, SIMD, and SIMD + Multithreading
https://blog.tensorflow.org/2020/09/supercharging-tensorflowjs-webassembly.html

> At runtime we test for SIMD and multithreading support and serve the appropriate Wasm binary. Today we serve a different binary for each of the following cases:
> 
>     Default: The runtime does not support SIMD or multithreading
>     SIMD: The runtime supports SIMD but not multithreading
>     SIMD + multithreading: The runtime supports SIMD and multithreading

Customers are reporting a problem with older iPhones on iOS 15 and 16 which don't support SIMD. We need to update the instructions to include all three files in customers' custom CDN.

### What's the expected behaviour?

See above

### Help us reproduce the bug!

See above

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by marcosconceicao** [comment]
@reesscot Hi Scott, i don't know if is something that was solved yet but we noticed that when the files are missing the SDK doesn't throw any exception, we spent a few hours testing multiple scenarios to find the error.
Even without the Custom CDN solution, if the user has a network error when loading the model, what can we do to track those cases and also improve user experience?

**Comment by hbuchel** [comment]
Hi @marcosconceicao Which version of react-liveness are you using? When I test with a malformed URL for the binaryPath or to the model.json file, I can see the following errors thrown which [we're throwing here](https://github.com/aws-amplify/amplify-ui/blob/505a4db44e500551aaaca21626829736f75a8d49/packages/react-liveness/src/components/FaceLivenessDetector/service/utils/blazefaceFaceDetection.ts#L109-L124). : 

<img width="995" alt="Error: There was an error loading the TFJS WASM backend. If you are using a custom WASM path ensure that it ends with '/' and that it is not the full URL as @tensorflow/tfjs-backend-wasm will append the wasm binary file name. Read more: https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-
wasm/src/backend
_wasm. ts#L475." src="https://github.com/aws-amplify/amplify-ui/assets/376920/c8f3cda0-8adc-415f-8fff-3a7730d676ba">

<img width="843" alt="Initialization of backend wasm failed" src="https://github.com/aws-amplify/amplify-ui/assets/376920/6d0a4578-19bb-4d73-94f8-27e58de3fa33">
