### ISSUE TITLE
Authenticator Component produces "An unknown error has occurred" error message

### ISSUE THREAD

**Issue by thomas-hs** [aws-amplify/amplify-ui#5137]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Expo

### What browsers are you seeing the problem on?

iOS (React Native)

### Please describe your bug.

I am currently trying to use the Authenticator component with toptEnabled however, after entering the correct email and password I receive the error message "An unknown error has occurred". 

I would like to ask if the format of the aws config is the reason why it is causing this problem:
```typescript
const awsconfig = {
  Auth: {
    Cognito: {
      userPoolId: "..",
      userPoolClientId: "..",
      identityPoolId: "..",
      region: "eu-west-1",
      mfa: {
        totpEnabled: true,
      },
    },
  },
};

export default awsconfig;
```

If not, is it because I can't use topt enabled sign in in Expo? I read this somewhere but wasn't sure if this was true.

### What's the expected behaviour?

Once correct enter and password is provided it will just to MFA page/component awaiting for code to be entered. Not throw an error "An unknown error has occurred"

### Help us reproduce the bug!

The App.tsx is shown below
```JavaScript 
import { Button } from "react-native";

import { Authenticator, useAuthenticator } from "@aws-amplify/ui-react-native";
import { Amplify } from "aws-amplify";
import awsconfig from "./aws-exports";
Amplify.configure(awsconfig);

function SignOutButton() {
  const { signOut } = useAuthenticator();
  return <Button title="Sign Out" onPress={signOut} />;
}

export default function App() {
  return (
    <Authenticator.Provider>
      <Authenticator
        loginMechanisms={["email"]}
        components={{
          SignIn: (props) => <Authenticator.SignIn {...props} hideSignUp />,
        }}
      >
        <SignOutButton />
      </Authenticator>
    </Authenticator.Provider>
  );
}
```

The aws config file is in a format similar to below
```typescript
const awsconfig = {
  Auth: {
    Cognito: {
      userPoolId: "...",
      userPoolClientId: "...",
      identityPoolId: "...",
      region: "eu-west-1",
      mfa: {
        totpEnabled: true,
      },
    },
  },
};

export default awsconfig;
```

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

![image](https://github.com/aws-amplify/amplify-ui/assets/133004032/6c7c3895-813d-4075-8d2d-46cddb3f0945)

**Comment by itomtom** [comment]
Hi @calebpollman yes the project is using Expo Go

**Comment by macorifice** [comment]
I have the same issue using `withAuthenticator` , but the result is the same, the strange thing is I tried running the app on the web browser and it works fine, I'm able to do all the user actions (login signup forgot password create account) if I'm usign the app with react native I'm getting the same error
![Screenshot 2024-04-08 at 18 15 39](https://github.com/aws-amplify/amplify-ui/assets/2563910/8502caac-f8f5-4555-8780-a65fb4f869df)

**Comment by calebpollman** [comment]
@itomtom @macorifice The `aws-amplify@^6` dependency of the React Native `Authenticator` does not support Expo Go unfortunately. Expo itself is supported, you can build the project and run it locally with an Android emulator or iOS simulator by running:
```sh
// Android
npx expo run:android 

// iOS
npx expo run:ios
```

**Comment by itomtom** [comment]
@calebpollman can we assume that it will work with AWS Amplify v5 ?

**Comment by calebpollman** [comment]
Yes, `aws-amplify@^5` using `@aws-amplify/ui-react-native@^1` is compatible with Expo Go. One caveat, the federated sign in feature of the React Native `Authenticator` is only available in the current major version (`2.x`) of `@aws-amplify/ui-react-native`
