### ISSUE TITLE
Hide "Confirm Password" field during sign up

### ISSUE THREAD

**Issue by jxdp** [aws-amplify/amplify-ui#5158]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

The "Confirm Password" field during the Sign Up flow can't be hidden or removed.

Some people are very strong advocates for this field, other people less so. I am not interested in debating the virtues of it, but do think it is something that is opinion-laden enough that having the option to go without would be beneficial.

### Please describe a solution you'd like.

There's a few ways this could work, but I think my preferred approach would be able to toggle field visibility explicitly in the `formFields` prop, so something like:

```tsx
<Autocomplete formFields={{
  signUp: {
    confirm_password: {
      isRequired: false,
      isVisible: false,
    }
  }
}} />
```

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by reesscot** [comment]
Hi @jxdp,
Thank you for your feature request. I'm merging this with the existing feature request here: https://github.com/aws-amplify/amplify-ui/issues/2530.
