### ISSUE TITLE
[FR] Liveness -  Proxy for APIs

### ISSUE THREAD

**Issue by luisbytes** [aws-amplify/amplify-ui#5192]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Liveness

### Please describe your feature-request in detail.

I would like to set up a proxy under my own infrastructure to use the Liveness SDK

### Please describe a solution you'd like.

Currently I see that the FaceLivenessDetectorCore component accepts a property called endpointOverride, but in the comments of it it appears

```
/**
    * Internal use only - parameter for overriding the liveness endpoint
    */
```

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by thaddmt** [comment]
Can you describe more about what you are trying to proxy here? I think in most cases trying to use a different endpoint for performing the video streaming operations would not be feasible with our current setup but would be interested in hearing more about what you are trying to do!

**Comment by reesscot** [comment]
Closing this out as proxying the Liveness calls is not a feature we plan to support with the Liveness UI Component.
