### ISSUE TITLE
Inconsistent frontend validation of certain Authenticator form fields

### ISSUE THREAD

**Issue by lucasparker1** [aws-amplify/amplify-ui#5225]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Please describe your bug.

I've added a "Given Name" user attribute to my user pool and it's existence is not properly enforced in the Authenticator component. 
When the user inputs a name of length 1 (min length is 3), a proper validation message is displayed. 
But when the do not input a name, the form attempts to register the user and an ugly and non-standard error message is displayed.

### What's the expected behaviour?

When the user does not enter a name, let them know that a name is required by using the same mechanism that enacts when the length is too short.

### Help us reproduce the bug!

Create app with Auth using code snippets below.

### Console log output

amplify/auth/resources.ts:
```

import { defineAuth, secret } from "@aws-amplify/backend";

export const auth = defineAuth({
  loginWith: {
    email: true,
    externalProviders: {
    <REDACTED>
     }
  },
  userAttributes: {
    givenName: {
      required: true,
      mutable: true,
    },
  },
});

```

src/App.tsx:
```
import { Authenticator } from "@aws-amplify/ui-react";

const formFields = {
  signUp: {
    given_name: {
      label: "Name",
      placeholder: "Enter your Name",
      minLength: 3,
    },
  },
};

function App() {
  return (
    <Authenticator formFields={formFields}>
      {({ signOut }) => (
       <REDACTED>
      )}
    </Authenticator>
  );
}

export default App;
```

### Additional information and screenshots

When name of length 1 is given (good behavior):
![Screenshot 2024-05-08 at 10 10 35 AM](https://github.com/aws-amplify/amplify-ui/assets/26806259/006720ab-73fe-4f51-8387-fcc3c3699028)

When name of length 0 is given (bad behavior): 
![Screenshot 2024-05-08 at 10 11 14 AM](https://github.com/aws-amplify/amplify-ui/assets/26806259/be6fcd77-60c3-42f6-b0df-8a2b349b4a62)

**Comment by esauerbo** [comment]
Hey @lucasparker1 thanks for creating this issue. It looks like you're overriding the `isRequired` attribute when customizing the form fields here. Specifying `isRequired` like so should fix this:
```
given_name: {
   label: "Name",
   placeholder: "Enter your Name",
   minLength: 3,
   isRequired: true
},
```

Let us know if this works!

**Comment by lucasparker1** [comment]
Yes that worked thank you
