### ISSUE TITLE
Ionic Chatbot UI [missing-page]

### ISSUE THREAD

**Issue by fatiimadib** [aws-amplify/amplify-ui#5242]
**Page**: [`https://ui.docs.amplify.aws/react/components/chatbot?platform=angular`](https://ui.docs.amplify.aws/react/components/chatbot?platform=angular)
**Feedback**:

**Comment by esauerbo** [comment]
Hey @fatiimadib do you remember how you got directed to that link? The Amplify Chatbot is deprecated so that page no longer exists. There's a small note about it [here](https://ui.docs.amplify.aws/angular/getting-started/migration#5-aws-amplifyui-angular3x-removes-legacy-component-exports)

**Comment by reesscot** [comment]
Closing this out as we have an existing feature request to add a Chatbot component: https://github.com/aws-amplify/amplify-ui/issues/3542
