### ISSUE TITLE
Liveness - Your account isn't authorized to call this operation

### ISSUE THREAD

**Issue by marcelcaferati** [aws-amplify/amplify-ui#5262]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

CRA

### What browsers are you seeing the problem on?

Chrome, Safari, iOS (React Native), Android (React Native)

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

I have followed this guide:
https://ui.docs.amplify.aws/react/connected-components/liveness

My cognito is setting to allow guests and everyone is a guest, there is no cognito authenticator needed for this

Everything is working fine for most users, they do their liveness check and everything works fine.

However once in a while a random user will get this:
{"state":"SERVER_ERROR","message":"Your account isn't authorized to call this operation. Please check account permissions","name":"ValidationException"}

However most of the users work, so it doesn't seen to be a permission problem

### What's the expected behaviour?

The data to get to the API correctly so it doesn't throw that error

### Help us reproduce the bug!

Implementation was made following these steps, only change is that cognito accepts guests
https://ui.docs.amplify.aws/react/connected-components/liveness

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by zchenwei** [comment]
Hi @marcelcaferati, thanks for bringing this up. Did you follow the instruction [here](https://ui.docs.amplify.aws/react/connected-components/liveness#step-1-configure-auth]) to create an inline policy to allows guest user access Rekognition after you set up the auth?

**Comment by marcelcaferati** [comment]
Hello @zchenwei,

I didn't do that, however I do have a policy manually created and added to my cognito usepool that does that

`{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Allow",
			"Action": "rekognition:StartFaceLivenessSession",
			"Resource": "*"
		}
	]
}`

However i dont think it is a permission problem, since most of my users can perform the liveness check just fine, however in very random cases, those fail

**Comment by zchenwei** [comment]
Do you use amplify Gen1 or Gen2? Did you add the auth category via the amplify CLI? I think you need to attach the policy to a specific role `unauthRole`.

For Gen2:

```js
const livenessStack = backend.createStack("liveness-stack");

const livenessPolicy = new Policy(livenessStack, "LivenessPolicy", {
  statements: [
    new PolicyStatement({
      actions: ["rekognition:StartFaceLivenessSession"],
      resources: ["*"],
    }),
  ],
});
backend.auth.resources.unauthenticatedUserIamRole.attachInlinePolicy(livenessPolicy); // allows guest user access
backend.auth.resources.authenticatedUserIamRole.attachInlinePolicy(livenessPolicy); // allows logged in user access
```

For Gen 1:
1. Go to AWS IAM console → Roles

2. Select the newly created unauthRole for your project (amplify-<project_name>-<env_name>-<id>-unauthRole if using the Amplify CLI). Note that unauthRole should be used if you are not logging in, but if you are using an authenticator with your application, you will need to use authRole.

3. Choose Add Permissions, then select Create Inline Policy, then choose JSON and paste the following:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "rekognition:StartFaceLivenessSession",
            "Resource": "*"
        }
    ]
}
```

**Comment by zchenwei** [comment]
What do you mean by most of your users? Do they include authenticated users? I guess it will work for your authenticated users for sure and only happen on guest users

**Comment by marcelcaferati** [comment]
@zchenwei the permissions are fine, I dont have any authenticated user, yet for most of my users it works, a very small amount get this error. And they are all unauthenticated

**Comment by zchenwei** [comment]
Thanks for confirming. Could you provide the session id, region and datetime of request for us to investigate a bit further?

**Comment by marcelcaferati** [comment]
@zchenwei hello, apparently it was something related to concurrent quota or something like that, i havent received another error like that since 2 days ago

**Comment by zchenwei** [comment]
Hi @marcelcaferati, glad to hear that it is working for you again. Like I mentioned, it would be helpful if you can provide the session ids for our engineers to further investigate. In the meantime, we will go check if there is such a limit. Thanks

**Comment by zchenwei** [comment]
> @zchenwei hello, apparently it was something related to concurrent quota or something like that, i havent received another error like that since 2 days ago

Hi @marcelcaferati, glad to hear that it is working for you again. Like I mentioned, it would be helpful if you can provide the session ids for our engineers to further investigate. In the meantime, we will go check if there is such a limit. Thanks!

**Comment by zchenwei** [comment]
Updates:

I check with the Cognito team. They said there is no such quota thing of guess access. Plus, if it is an issue of quota exhaustion from Cognito the response would be `TooManyRequestsException`. It was weird that that would be translated to a not authorized message. Again, it would be helpful if you can provide the session ids for our engineers to further investigate.

**Comment by marcelcaferati** [comment]
@zchenwei thank you for looking into it for me!

Unfortunately at the times I was getting those errors I wasn't logging the session ID, since those happens client side I have to send them to me.

I did find another wierd bug that I cant get much info from, if you can look in to that for me and see if there is any sort of additional information on your end that helps me debug this:

When the user tries to start the face check it instantly times out, here are the logs

[7:42]{"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"ae52eb51-c759-444d-9347-10b2b97044e6"}
[7:42]( {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"0e675db9-dff2-46a9-95e4-8f1f618e652f"}
7:42 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"95303b31-9a54-4e56-bd65-75bc25a2601d"}
[7:42] {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"f19d2c53-1e1f-4a50-b1f3-a185ebd48a1d"}
7:43{"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"3262a42e-92af-4b9a-a320-06de61561b75"}
7:43 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"dbbfc714-3af3-4073-ba5e-39b99d999fe8"}
[7:43] {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"ef61620b-731a-4b5b-93a0-32a5f0f558ae"}
7:44 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"f7e8ac76-b665-4b53-bbfe-cd2bf698a133"}
7:44 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"7d3e6311-8a3d-463a-bbf6-6c03c7615754"}
7:44 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"f47db1d5-8e02-49be-a951-e7a613e78d7e"}
[7:44] {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"b92db4ed-5f49-4658-9e16-37ea94bd1eed"}

As far as I understand this time out should be around 2 minutes, that is the log from the same user, as you can see there are several tries within one minute

**Comment by zchenwei** [comment]
@marcelcaferati You are welcome! For the bug you mentioned above, could you create a new issue for it? It is hard to track the issues when mixing them and easier for others to reference back. I will go ahead and close this one since no furthur actions can be taken. Thanks!

**Comment by williamvinc** [comment]
i also experienced the same thing, while this still occure in dev environment, but i have a hard time to fix this. I dont think this is about my aws roles or user, because i already give them full access

![image](https://github.com/aws-amplify/amplify-ui/assets/142376368/219df9e8-0c05-434a-b981-2bc1bcfcfe4c)

![image](https://github.com/aws-amplify/amplify-ui/assets/142376368/8c4fad57-b0cf-4c4a-8f07-c6d7aaf3da2b)

**Comment by jslopez** [comment]
Hi @zchenwei, we are experiencing the same issue originally reported, unauthenticated users are able to run the `StartFaceLivenessSession`, but a specific user is receiving a `ValidationException: Your account isn't authorized to call this operation. Please check account permissions`, the error is also registered on CloudTrail, giving `"completionMessage": "Your Liveness stream failed due to an issue"` as additional information, but it's not enough to get an idea of why this specific user is getting the error.

Any idea on why is happening only on this specific case?

**Comment by BryanTacuri-Iroute** [comment]
Hi, I'm having the same problem. I've been developing using Face Liveness and it was working fine for three months until today. Today I got the message "Your account isn't authorized to call this operation. Please check account permissions" and I haven't made any changes to the code or AWS.
