### ISSUE TITLE
Amplify Auth using SAML

### ISSUE THREAD

**Issue by ShiFbau** [aws-amplify/amplify-ui#527]
I have a web application developed in ReactJS using Amplify framework.  Initially I was using Amplify Auth for customized user authentication where I had developed customized SignUp, SignIn and SignOut functionality using Authenticator component and everything worked fine.
Now my requirement is authenticate users with enterprise Single Sign On.  I have configured SAML identity provider in Cognito user pool and it gives me launch URL for hosted UI but when I launch my application's URL I am still getting old login page instead of getting redirected to my enterprise single sign on page.

I tried using Auth.federatedSignIn() for login to go to the hosted UI page but it gives me folowwing exception:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'oauthSignIn')
    at AuthClass.<anonymous> (Auth.ts:1936)
    at step (Auth.ts:12)
    at Object.next (Auth.ts:12)
    at Auth.ts:12
    at new Promise (<anonymous>)
    at push../node_modules/@aws-amplify/auth/lib-esm/Auth.js.__awaiter (Auth.ts:12)
    at AuthClass.federatedSignIn (Auth.ts:1887)
    at onClick (SamlAuthWrapper.js:53)
I also tried calling the Hosted UI login URL (justbookit-fbau-uat.auth.ap-southeast-2.amazoncognito.com/login?client_id=token&response_type=code&scope=&redirect_uri=URL) with in the application on click of a button, which open the single sign on page but when I try to get  user details by using Auth.currentAuthenticatedUser(), it give unauthenticated user error.

Could you please help me to get it working.

**Comment by carlos-molero** [comment]
I have the exact same problem, did you find a fix? At first I thought it was Amplify SSR configuration since I'm working with NextJS but it's not the case.

**Comment by Milan-Shah** [comment]
@ShiFbau and @carlos-molero , we have released a newer version of @aws-amplify/ui-react@2.1.0. We also recently launched a new Authenticator UI Component which supports custom styling, themes, zero config support, custom sign up attributes, password manager support and many more. Please give it a try and let us know if you are seeing the same issue. 

Feel free to open this issue or create a new one if you have any suggestion for any improvements we can make. We are here to help :)

**Comment by arpecop** [comment]
One year later I got the same issue as @ShiFbau and @carlos-molero with Next.js app , it happens only in production all SSO providers return `auth-3a30e006b444ee27.js:1 Uncaught (in promise) Error: TypeError: Cannot read properties of undefined (reading 'oauthSignIn')` is there some breaking changes in aws-config.js/ts ? 
What is the difference between "aws-amplify" and "@aws-amplify/whatever/package" npm's  ?
