### ISSUE TITLE
Confirmação manual de login

### ISSUE THREAD

**Issue by Fabao37** [aws-amplify/amplify-ui#5270]
estou tentando conectar o AWS ao projeto react native.
quando o navegador abre(apos inserir o codigo do aws no nodejs) para poder confirmar o login, 
é solicitado o email e senha. insiro os dois e dá erro.
porém, faço o login na plataforma com os mesmo dados.
peço recuperação de senha via email, porém o codigo não é enviado de forma alguma para o email.

**Comment by timngyn** [comment]
👋 Hi @Fabao37, what version of Amplify UI are using?

**Comment by esauerbo** [comment]
Closing out as we haven't heard back. Please open a new issue if you need further assistance.
