### ISSUE TITLE
Vite React - Component does not work correctly in mobile browsers, especially Google browsers

### ISSUE THREAD

**Issue by pkfonseca** [aws-amplify/amplify-ui#5271]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator, Liveness

### How is your app built?

vite

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

sa-east-1

### Please describe your bug.

Instability when trying to perform facial validation on your smartphone.

When accessing the react application and trying to perform facial validation, it is not recognizing the user's approach, which generates a client timeout error.

On the desktop it works normally.

The error occurs mainly in the Google browser on the smartphone, tested in Opera and works normally, however, problems have been reported in other browsers.

### What's the expected behaviour?

Identify the user's approach and perform validation

### Help us reproduce the bug!

Try using the component in the Chrome browser via your smartphone.

### Code Snippet

```typescript
// Put your code below this line.
interface IFaceLivenessProps {
  formValues: FormSigninType | null;
  onClose?: () => void;
  handleAuthenticate: (
    result: GetFaceLivenessSessionResultsCommandOutput
  ) => void;
}
export function FaceLiveness({
  formValues,
  onClose,
  handleAuthenticate,
}: IFaceLivenessProps) {
  const mutation = useFaceLivenessResult();
  const { data, isLoading, isFetching } = useFaceLivenessSessionId(formValues);
  const [open, setOpen] = useState(!!data);

  useEffect(() => {
    if (data) {
      setOpen(true);
      return;
    }
    setOpen(false);
  }, [data, formValues]);

  const handleAnalysisComplete: () => Promise<void> = async () => {
    const result = await mutation.mutateAsync(data!);
    const conf = result.Confidence!.toFixed(2)!;

    if (Number(conf) <= Number(import.meta.env.VITE_FACELIVENESS_CONFIDENCE)) {
      handleCancel();
      toast.error(`Baixa confiabilidade : ${result.Confidence?.toFixed(2)}`);
      return;
    }

    handleCancel();
    handleAuthenticate(result);
  };

  const handleCancel = () => {
    setOpen(false);
    if (onClose) {
      onClose();
    }
  };

  return (
    <AlertDialog open={open}>
      <AlertDialogContent className="flex w-full h-full md:h-[95%] p-1 md:p-6 bg-white outline-none border-none max-w-xl">
        <section className="w-full p-0 relative flex flex-col gap-4 justify-center items-center">
          {isFetching || isLoading ? (
            <Loader className="w-20" />
          ) : (
            <>
              <ThemeProvider theme={faceLesstheme}>
                <FaceLivenessDetector
                  displayText={defaultLivenessDisplayText}
                  sessionId={data!}
                  region="us-east-1"
                  onAnalysisComplete={handleAnalysisComplete}
                  onUserCancel={handleCancel}
                  onError={(e) => toast.error(e.error.message)}
                />
              </ThemeProvider>
              <Button
                type="button"
                variant={"secondary"}
                className="rounded-[8px] flex items-center gap-2 font-semibold text-neutrals-dark text-base max-w-fit"
                onClick={handleCancel}
              >
                Fechar
              </Button>
            </>
          )}
        </section>
      </AlertDialogContent>
    </AlertDialog>
  );
}
```

### Console log output

Client timeout

**Comment by zchenwei** [comment]
Hi @pkfonseca, I am sorry that this happens to you. I have tried to reproduce the issue with my phone but I could not. I used the component with my phone on Chrome and the validation check works for me as it does on web. It would be helpful if you can provide more info about how you set up the component, configs, etc. Thanks!

**Comment by pkfonseca** [comment]
Hi @zchenwei , Thanks for your attention.

That's the problem, only some users are receiving client timeout when the component is called. For some reason, these clients are not having their approaching movement detected.

But basically the component is called within a dialog that takes the user's entire screen.

I checked the browser version and managed to reproduce the error on my smartphone. 

Chrome 125.0.6422.72

**Comment by reesscot** [comment]
@pkfonseca Can you please confirm what smartphone you are using? Model and OS version?

**Comment by floelm** [comment]
This is probably the same error as https://github.com/aws-amplify/amplify-ui/issues/5272

**Comment by pkfonseca** [comment]
@reesscot Moto G52, Android 13

**Comment by pkfonseca** [comment]
@floelm  Yes, it appears to be the same error. The difference is that my application is completely web-based.

I don't know if there was any update, however, this didn't happen before and it is very variable, as it happens to some users of my application.

**Comment by reesscot** [comment]
See: https://github.com/aws-amplify/amplify-ui/issues/5272#issuecomment-2142716922

**Comment by reesscot** [comment]
@pkfonseca @floelm You should be seeing recovery now as the bug in Chromium has been patched. If you still having users using this particular version of Chromium, please update to the latest version of `ui-react-liveness` which has a patch workaround for Android + Chrome 125.
