### ISSUE TITLE
Liveness - Users getting timeout error as soon as they try to load 

### ISSUE THREAD

**Issue by marcelcaferati** [aws-amplify/amplify-ui#5272]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

CRA

### What browsers are you seeing the problem on?

iOS , Android 

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

I got a few users that try to start the liveness check but as soon as they click to start, they get a time out error

[7:42]{"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"ae52eb51-c759-444d-9347-10b2b97044e6"} 
[7:42]( {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"0e675db9-dff2-46a9-95e4-8f1f618e652f"} 
7:42 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"95303b31-9a54-4e56-bd65-75bc25a2601d"} 
[7:42] {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"f19d2c53-1e1f-4a50-b1f3-a185ebd48a1d"} 
7:43{"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"3262a42e-92af-4b9a-a320-06de61561b75"} 
7:43 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"dbbfc714-3af3-4073-ba5e-39b99d999fe8"} 
[7:43] {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"ef61620b-731a-4b5b-93a0-32a5f0f558ae"} 
7:44 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"f7e8ac76-b665-4b53-bbfe-cd2bf698a133"} 
7:44 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"7d3e6311-8a3d-463a-bbf6-6c03c7615754"} 
7:44 {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"f47db1d5-8e02-49be-a951-e7a613e78d7e"} 
[7:44] {"state":"TIMEOUT","message":"Client Timeout","name":"TIMEOUT","sessionId":"b92db4ed-5f49-4658-9e16-37ea94bd1eed"}

As far as I understand this time out should be around 2 minutes, that is the log from the same user, as you can see there are several tries within one minute

This is happening quite often, since we launched a few days ago, we got at least 7 users with this behaviour

I wasn't able to find any information on this specific error and the message is kind of generic

### What's the expected behaviour?

The user to be able to complete the Liveness check and only timesout after a while trying to focus

### Help us reproduce the bug!

I don't I got the session IDs for the timeout connections

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by floelm** [comment]
I can confirm seeing exactly the same issue as well with a quite some users.

**Comment by marcelcaferati** [comment]
> I can confirm seeing exactly the same issue as well with a quite some users.

were you able to come up with any theories? browser chache, internet or something?

Some users are reporting that if they clear the cache and/or try with another internet it works, but since they are trying again on the next day, and it doens't work for every user, I don't think that is the issue.

**Comment by floelm** [comment]
We are opening the web app in a webview from within our apps.

I did not come up with any specific pattern yet, I was only considering downgrading this package and see if it fixes anything. https://github.com/aws-amplify/amplify-ui/releases?q=ui-react-liveness&expanded=true 3.0.17 had something related to timeouts, maybe that introduced a new issue?

**Comment by marcelcaferati** [comment]
> We are opening the web app in a webview from within our apps.
> 
> I did not come up with any specific pattern yet, I was only considering downgrading this package and see if it fixes anything. https://github.com/aws-amplify/amplify-ui/releases?q=ui-react-liveness&expanded=true 3.0.17 had something related to timeouts, maybe that introduced a new issue?

by any change did you downgrade? if so, did it solve the problem?

**Comment by floelm** [comment]
hi @marcelcaferati - i did not try downgrading yet. Tbh i'm a bit scared with the potential side-effects of doing so

**Comment by thaddmt** [comment]
Is it occurring with any specific browser and OS combinations? We have opened a ticket with chrome as it seems to be an issue with MediaRecorder on Chrome 125 with certain versions of android - https://issues.chromium.org/issues/343638942

**Comment by floelm** [comment]
From what I see this issue is only reported on Android devices. I do not have information about the OS versions

**Comment by marcelcaferati** [comment]
> Is it occurring with any specific browser and OS combinations? We have opened a ticket with chrome as it seems to be an issue with MediaRecorder on Chrome 125 with certain versions of android - https://issues.chromium.org/issues/343638942

It could be the case, the people we were able to contact about it were android users, we run the liveness check at a webview, for both android and iOS

**Comment by thaddmt** [comment]
It looks like there was a confirmed issue on chrome 125 with certain android devices, they just recently made the issue public - https://issues.chromium.org/issues/343199623

**Comment by marcelcaferati** [comment]
> It looks like there was a confirmed issue on chrome 125 with certain android devices, they just recently made the issue public - https://issues.chromium.org/issues/343199623

Just to give some feedback, some people are already updating their OS and being apple to complete de liveness check, looks like it should be working from now on

**Comment by thaddmt** [comment]
Great to hear the fix is being released! Please let us know if you see any more issues!
