### ISSUE TITLE
Customizable Visual Feedback Colors in Liveness Component

### ISSUE THREAD

**Issue by slomelirdz** [aws-amplify/amplify-ui#5278]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Liveness

### Please describe your feature-request in detail.

I'm using the FaceLivenessDetectorCore component and would like to know if it is possible to customize the colors that are part of the visual feedback provided by the component during the liveness detection process. I've reviewed the documentation but couldn't find a way to customize these colors. I hope someone can help me out with this matter.

Thank you!

<img width="261" alt="Screenshot 2024-05-30 at 7 55 36 AM" src="https://github.com/aws-amplify/amplify-ui/assets/92738879/f60c2d7f-7841-46d8-a8ab-abb66177b58a">

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by thaddmt** [comment]
Hi @slomelirdz currently there is no way to customize these colors as they are randomized by the service to increase check accuracy. We don't currently have any plans to make this customizable

**Comment by slomelirdz** [comment]
Thank you for the clarification!

**Comment by R-o-d-r-i-g-o** [comment]
Hi @thaddmt,

I'd love to contribute to this feature, even though it's not currently in the future plans. My idea is to make it as configurable as possible. We can set this color range as the default effect and allow users to change the colors or override the state with another custom component.

Can you explain the process for making PRs in Amplify (docs, bureaucracy, etc.) and who I should talk to?

**Comment by BochaXD** [comment]
Hello,
Is there any update on this in 2025?
Has there been any recent change to the SDK, or is there now any way—official or experimental—to attenuate, change, or customize the feedback colors during the liveness detection process?
