### ISSUE TITLE
React: Set unique id to each authenticator step's button 

### ISSUE THREAD

**Issue by OxionAICTeam** [aws-amplify/amplify-ui#5304]
Hi there,

In order to collect some user activities' metrics, we would like to add some unique id to the main buttos of each step. I have read all the documentation and I didn't find any particular configuration to set this data. ¿Is there any way to set this in the creation of the component?

I'm trying to use a useEffect with the route object as dependency (and set manually the id to the button)... but I was wondering if there was a more direct and correct way

Thanks!

**Comment by esauerbo** [comment]
Hey @OxionAICTeam we do not have a baked-in way to add id's to buttons that are already rendered. Can you describe your use case in more detail? Why do you need the IDs? We might be able to help you find a better workaround.

**Comment by OxionAICTeam** [comment]
Hi,

The main objective of setting this unique ids is to track the user activities through GTM. 
We have found a workaround, setting a custom component as Footer in each step of the Authenticator component, which detects the submit button and adds this unique id to it.

Thanks!

**Comment by esauerbo** [comment]
@OxionAICTeam glad you were able to get this working! Closing this out
