### ISSUE TITLE
[i18n] update  dictionaries/authenticator/kr.ts

### ISSUE THREAD

**Issue by YuJM** [aws-amplify/amplify-ui#5308]
### On which framework/platform would you like to see this feature implemented?

Other

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

The Kr.ts file is missing something and needs to be added.

### Please describe a solution you'd like.

Modified gist link(https://gist.github.com/YuJM/66da4bdc84b2f0ab8c1e5d78f37a9cfe)

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by YuJM** [comment]
Need to add content

**Comment by esauerbo** [comment]
Hey @YuJM thanks raising this! If this is something you'd be able to implement, feel free to make a pr to add the missing translation and our team will review it.
