### ISSUE TITLE
SERVER_ERROR: Signature expired: 20240614T145057Z is now earlier than 20240614T154633Z

### ISSUE THREAD

**Issue by anahiforesi** [aws-amplify/amplify-ui#5325]
Hi team, 
we are using the React UI for Liveness process, and we have encountered the issue describe in the title.
As we understand it, this is an issue caused by the device and server clocks sync.
We were told you are already working on a fix and asked to open an issue to make it easier to track the release.

Thank you

**Comment by timngyn** [comment]
Hi @anahiforesi, thank you for reporting this issue. Please track this feature request in the following issue: https://github.com/aws-amplify/amplify-ui/issues/5124
