### ISSUE TITLE
Allow further customization of Amplify

### ISSUE THREAD

**Issue by cwoolum** [aws-amplify/amplify-ui#5326]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Primitive components

### Please describe your feature-request in detail.

We have some designs that require us to have more ability to customize the Amplify primitives

We need to be able to customize the following properties

1. TextField
    * backgroundColor
3. Badge
    * border
    * borderRadius
    * boxShadow
5. Alert
    * borderRadius
    * boxShadow

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by dbanksdesign** [comment]
Customization for all valid CSS will be available once we get #5170 merged in

**Comment by reesscot** [comment]
Fixed by https://github.com/aws-amplify/amplify-ui/pull/5170

**Comment by cwoolum** [comment]
Thanks! Excited to try it!
