### ISSUE TITLE
Wrong error message validation on "Email verification" when signin 

### ISSUE THREAD

**Issue by dmoran-wpt** [aws-amplify/amplify-ui#5336]
### Before creating a new issue, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

When a user login and try to press the button Verify when no "option" is selected it gives an error
![imagen](https://github.com/aws-amplify/amplify-ui/assets/119600047/273de0bb-92cd-4d8c-a4a8-326f10d6767a)
 
In the browser console its possible to see the POST request that contains the showed message

### What's the expected behaviour?

Better error message (or customizable) or form validation avoiding pressing the button if nothing is selected

### Help us reproduce the bug!

Dependencies used:
```json
"@aws-amplify/ui-vue": "^4.2.8", 
"aws-amplify": "^6.3.0"
```

- Create a Vue application (`npm create vue@latest`)
- Add the Authenticator component, as outlined in this AWS documentation: `https://ui.docs.amplify.aws/vue/connected-components/`authenticator
- Run amplify init
- Run amplify add auth
- Log in with a user that has a non-verified email and phone number
- Click "Verify" button without selecting an option

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by reesscot** [comment]
Hi @dmoran-wpt,
Thanks for reporting this issue. We should be validating the form before submitting this verification form.
