### ISSUE TITLE
Cannot get accessToken within Authenticator element

### ISSUE THREAD

**Issue by tszchung019** [aws-amplify/amplify-ui#5346]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Authenticator element is expecting an AuthUser in v6, which does not contains getSignInUserSession().getAccessToken(). 

### What's the expected behaviour?

It is expected to have an accessToken which contains the cognito user group

### Help us reproduce the bug!

Refer to the code snippet

### Code Snippet

```
<Authenticator>
    {({ signOut, user }) => (
    <main>
        <Button variant="text" sx={{position: 'absolute', top: '5px', right: '10px'}} onClick={signOut}>Sign out</Button>
        <div className="container">
            {user.getSignInUserSession().getAccessToken().payload['cognito:groups']=='Admin'? (
                <div>
                <section>
                    <Text>Welcome, administrator {user.username}!</Text>
                </section>
                <ManageBlogs />
                </div>
            ) : (
                <section>
                <h1>Hello {user.username}</h1>
                <p>This is your portal for managing your projects with me. You can start a new project, ask for a quote, and manage the work schedule with existing projects</p>
                </section>
            )}
            <div className="project-section">
                <section id='userPortal'>
                <BasicTabs
                    user={user.username}
                />
                </section>
            </div>
        </div>
    </main>
    )}
</Authenticator>
```

**Comment by RRolfes** [comment]
@tszchung019 I am having the same issue. How did you resolve?

**Comment by tszchung019** [comment]
@RRolfes Please describe your issue, are you using Amplify V5 or V6? As Amplify V5 is no longer supported, and therefore some of the former functions are deprecated. In V6, you will have to import { fetchAuthSession } from "was-amplify/auth" and use tokens.access token.payload[cognito:groups]
