### ISSUE TITLE
Customize Login Page

### ISSUE THREAD

**Issue by RMJSolutions** [aws-amplify/amplify-ui#5483]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I am no programmer, but did manage to create a React app.  I'm using Amplify Auth (Gen 2) and it presents a basic login screen.  How can I customize it by adding a background picture or changing the colors?  It's not very clear for a beginner to know where to start.  

Thank you.

### Please describe a solution you'd like.

Just some direction on how to start customizing. 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by timngyn** [comment]
👋 Hi @RMJSolutions, this is more of a question related to web development in general and not necessarily related to the Authenticator itself. It might be useful to go through the Next.js tutorial, https://nextjs.org/learn-pages-router/basics/create-nextjs-app, to learn more about how Next.js sets up the app itself.

There's a section on styling here, https://nextjs.org/learn-pages-router/basics/assets-metadata-css, that should help with styling your page

**Comment by RMJSolutions** [comment]
Thank you very much for the information.
I will check it out.
I appreciate it!

**Comment by timngyn** [comment]
I forgot to mention, but we also have a guide here if you were looking to customize the actual Authenticator component itself: https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#styling

**Comment by RMJSolutions** [comment]
This is great!  Thank you so much!! This will be a big help.
