### ISSUE TITLE
Getting Initialization of backend wasm failed when using FaceLivenessDetectorCore in React

### ISSUE THREAD

**Issue by bard-fauz** [aws-amplify/amplify-ui#5490]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Webpack 4

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

When rendering the `FaceLivenessDetectorCore` component in my react project with valid credentials and sessionToken, and initiating the Liveness check, the flow is stuck on the stage "Move in front of the Camera".

On checking the console this warning keeps on repeating:

```
Initialization of backend wasm failed
 
TypeError: Class constructor KernelBackend cannot be invoked without 'new'
    at new BackendWasm (tf-backend-wasm.node.js:9092:1)
    at tf-backend-wasm.node.js:9526:1
    at step (tf-backend-wasm.node.js:144:1)
    at Object.next (tf-backend-wasm.node.js:93:45)
    at fulfilled (tf-backend-wasm.node.js:74:1)
```

### What's the expected behaviour?

On clicking the "Strart Video check", the component should proceed with the liveness check and indicate the user with further instructions to be followed for their liveness check.

### Help us reproduce the bug!

On initiating the server, with the given code, I simply open the page in a browser and render the `FaceLivenessDetectorCore` component. This error pop's up them.

The server is ran via webpack 4 configurations.

### Code Snippet

```typescript
// Put your code below this line.

/**
 * Configuration for the AWS Amplify FaceLivenessDetectorCore component
 */
export interface AmplifyCoreLivenessDetectorConfiguration {
  sessionId: string,
  region: string,
  credentialProvider: AwsCredentialProvider,
  onAnalysisComplete: () => Promise<void>,
  onError: (error: LivenessError) => void,
  onUserCancel: () => void,
  disableStartScreen?: boolean,
}

/**
 * Customization for the AWS Amplify FaceLivenessDetectorCore component
 * Refer - https://ui.docs.amplify.aws/react/connected-components/liveness/customization
 */
export interface AmplifyCoreLivenessDetectorCustomization {
  components: FaceLivenessDetectorComponents,
  displayText: LivenessDisplayText,
  theme: Theme
}

export function AmplifyCoreLivenessDetector (props: AmplifyCoreLivenessDetectorConfiguration &
  Partial<AmplifyCoreLivenessDetectorCustomization>) {
  const {
    sessionId,
    region,
    credentialProvider,
    components,
    displayText,
    theme,
    onAnalysisComplete,
    onError,
    disableStartScreen,
    onUserCancel
  } = props;

  return <ThemeProvider theme={theme}>
    <FaceLivenessDetectorCore
      sessionId={sessionId}
      onAnalysisComplete={onAnalysisComplete}
      region={region}
      config={{ credentialProvider }}
      components={components}
      displayText={displayText}
      onError={onError}
      disableStartScreen={disableStartScreen}
      onUserCancel={onUserCancel}
    />
  </ThemeProvider>;
}

------------

In index.tsx

------------
function getActivePage(){
   return <AmplifyCoreLivenessDetector
          configuration={{
            sessionId: SESSION_ID,
            region: REGION,
            credentialProvider: CREDENTIALS_PROVIDER,
            onError: (error) => {
              console.log(error);
            },
            onUserCancel: () => {
              console.log("User cancelled");
            },
          } as AmplifyCoreLivenessDetectorConfiguration }
          customization={{} as Partial<AmplifyCoreLivenessDetectorCustomization>} />;
}
```

### Console log output

```
Initialization of backend wasm failed
 
TypeError: Class constructor KernelBackend cannot be invoked without 'new'
    at new BackendWasm (tf-backend-wasm.node.js:9092:1)
    at tf-backend-wasm.node.js:9526:1
    at step (tf-backend-wasm.node.js:144:1)
    at Object.next (tf-backend-wasm.node.js:93:45)
    at fulfilled (tf-backend-wasm.node.js:74:1)
```

These are repeated multiple times in the console, with their rate of appearance decreasing based on time.

### Additional information and screenshots

https://github.com/user-attachments/assets/ba82ab2b-554e-4ca4-b634-e8c7daa18d08

We are using Webpack 4 for our project setup and babel is also being used. 

Webpack 4 configs added to handle building of the amplify-liveness:

```
module: {
    rules: [
      {
        test: /\.(mjs|js|jsx|ts|tsx)$/,
        include: /node_modules\/((aws-amplify|@aws-amplify|@smithy|@aws-sdk)\/).*/,
        use: {
          loader: "babel-loader",
          options: {
            presets: [
              [
                "@babel/preset-env", {
                include: [
                  "@babel/plugin-transform-optional-chaining",
                  "@babel/plugin-transform-nullish-coalescing-operator"],
                }
              ]
            ]
          }
        },
        type: "javascript/auto",
      },
   // other rules
  ]
}
```

**Comment by esauerbo** [comment]
Hi @bard-fauz thanks for creating this issue, we're working on reproducing this behavior. In the meantime, are you able to tell whether the CDN loaded?

**Comment by bard-fauz** [comment]
Yes, I am getting 200 OK response on the CDN call.

<img width="1078" alt="Screenshot 2024-07-30 at 10 10 51 AM" src="https://github.com/user-attachments/assets/3a92a3f3-987e-47b5-8514-26a69f60d8f1">

**Comment by reesscot** [comment]
Hi @bard-fauz,
Can you try changing your target to es6? See: https://github.com/tensorflow/tfjs/issues/6307

**Comment by bard-fauz** [comment]
Already tried changing the target to es6, also tried other options too, like es2020, etc, still the issue persists.

**Comment by esauerbo** [comment]
Hey @bard-fauz thanks for your patience. I wasn't able to reproduce this with a wepback 4 project using your config. The error you're seeing is likely related to a specific configuration -- would you be able to provide a minimal reproduction?  Ideally this would contain the simplest version of your code that still results in the error, and could be shared as a Github repo. Don't worry about the Liveness backend logic, you can use a mock sessionId and we'll use our team backend. 

Let me know if you need any guidance with this!

**Comment by bard-fauz** [comment]
Sure, working on it

**Comment by bard-fauz** [comment]
Hi @esauerbo, I tried to generate a minimum build for this, but I am also not able to reproduce this issue. My guess is there are certain internal dependencies that my project is using which are confidential and cannot be shared publicly, thus I didn't used them for creating a minimum build, due to which the issue was not reproducing.

Still I did some deep dive and I managed to resolve the TypeError. As from the logs, this error was occurring in the @tensorflow package, I suspected that there could be incompatibility between the transpiled JS code and the @tensorflow dependency code. Thus I modified the existing rule to also include `@tensorflow` and use babel-loader on it. Now the component after rendering ans starting the video check, proceed to Instruct the uses to move their face in center and start the socket.

But one issue I encountered, while using dummy values for the sessionId and credentials, the socket connects should fails to establish, which happens, but in my browser console I get this:

```
Uncaught (in promise) Error: Websocket connection timeout
    at CustomWebSocketFetchHandler.mjs:112:24
```
The console code pointer is for [here](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react-liveness/src/components/FaceLivenessDetector/service/utils/createStreamingClient/CustomWebSocketFetchHandler.ts#L188)

Now in happy case, the onError function that I provided to the `FaceLivenessDetectorCore` component should have been invoked and as amplify handles these errors automatically a pop-up with the message Connection time out should have appeared. But for me, the screen remains in the same state with the connecting loader on the top and my onError function is not invoked.

**Comment by esauerbo** [comment]
@bard-fauz that's definitely strange behavior. the connection timeout should be caught [here](https://github.com/aws-amplify/amplify-ui/blob/e52db7be1792fb3f83fd7934f25524cdaee2d100/packages/react-liveness/src/components/FaceLivenessDetector/service/machine/machine.ts#L113) . I tried passing in a dummy value for sessionId and credentials, and I get a `SERVER_ERROR: ValidationException` which is caught by the onError handler. Are you able to provide a reproduction of this or provide any code that would help us reproduce?

**Comment by bard-fauz** [comment]
Agreed, that part is indeed strange. Since the code includes some internal packages, I've shared an internal build directly with you @<username>, as it cannot be posted publicly. Meanwhile I'm also going through the code to understand why this behavior could occur. Thank you for your assistance.

**Comment by bard-fauz** [comment]
Shared the steps to reproduce the bug and the code with @thaddmt for their reference and investigation. I'll be continuing the investigation on my end too and notify if any developments happen on this.

**Comment by bard-fauz** [comment]
As the issue was due to certain internal dependencies, I managed to resolve this by building a wrapper which consumes the Amplify Liveness component separately and then used the generated minified code of that wrapper in our project. This has resolved all the issues and the component works correctly. Sharing this here so that other's if facing this issue can also resolve it.
