### ISSUE TITLE
Documentation error/omission

### ISSUE THREAD

**Issue by iondisc** [aws-amplify/amplify-ui#5493]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Authenticator

### How is your app built?

Nuxt.js 

### Please describe your bug.

The code example on the Vue::Authenticator::Customization is missing the top portion of code examples. (https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization)

### What's the expected behaviour?

Expect to have the full code example on the Vue::Authenticator::Customization.

### Help us reproduce the bug!

Vue this page and examine the top code example for configuration options. https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization

If you toggle over to React you can see the react version of this code example.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by esauerbo** [comment]
Hi @iondisc thanks for reporting this. We'll add this to our roadmap to update the documentation.
