### ISSUE TITLE
Errors in FaceLivenessDetector Component Usage in Next.js 14

### ISSUE THREAD

**Issue by LingXiongDev** [aws-amplify/amplify-ui#5519]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

us-east-1

### Please describe your bug.

Description
I'm experiencing two main issues when using the FaceLivenessDetector component from @aws-amplify/ui-react-liveness in a Next.js 14 project:

Error Message: "Cannot complete check due to server issue"

The component fetches the sessionId correctly.
When starting face detection, the error message "Cannot complete check due to server issue" is displayed.
Upon clicking "Try Again", the component does not reinitialize or prompt for a new detection.
Component Not Resetting on Retry

When the detection fails and the "Try Again" button is clicked, the component does not reset or reinitialize for a new detection session.
Steps to Reproduce
Implement the FaceLivenessDetector component as per the [Amplify UI React Liveness Documentation](https://ui.docs.amplify.aws/react/connected-components/liveness).I am a front-end development engineer and I did not set the aws-export.js configuration file in the document. I don't know if this is the problem.
Ensure the backend API for session creation is correctly set up to provide valid session IDs.
Run the Next.js application and attempt to use the FaceLivenessDetector component.
Observe the error message when starting face detection.
Click the "Try Again" button and observe the lack of component reinitialization.

Actual Behavior
The error message "Cannot complete check due to server issue" is displayed during face detection.
Clicking "Try Again" does not reset the component for a new detection session.
![image](https://github.com/user-attachments/assets/9d8d9219-4617-4d78-95d7-5f4bca68ae36)
![image](https://github.com/user-attachments/assets/a6d58241-1b13-4685-9256-2853cc4e69ce)

### What's the expected behaviour?

The FaceLivenessDetector should initiate the face detection process without server errors.
Clicking "Try Again" should reset the component and allow for a new detection session.

### Help us reproduce the bug!

```js
'use client';

// components/LivenessComponent.js
import React, { useEffect, useState } from 'react';
import { FaceLivenessDetector } from '@aws-amplify/ui-react-liveness';
import { Loader, ThemeProvider } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import {
  fetchFaceLivenessSession,
  getFaceLivenessSessionResults,
} from './api/face-liveness-api';

const LivenessComponent = () => {
  const [loading, setLoading] = useState(true);
  const [sessionId, setSessionId] = useState(null);
  const [error, setError] = useState(null);

  const fetchCreateLiveness = async () => {
    try {
      const sessionId = await fetchFaceLivenessSession();
      setSessionId(sessionId);
      setLoading(false);
    } catch (error) {
      console.error('Error creating liveness session:', error);
      setError('Failed to create liveness session');
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCreateLiveness();
  }, []);

  const handleAnalysisComplete = async () => {
    try {
      const response = await getFaceLivenessSessionResults({ session_id: sessionId });
      const data = await response.json();

      if (data) {
        console.log('User is live');
      } else {
        console.log('User is not live');
      }
    } catch (error) {
      console.error('Error during analysis:', error);
      setError('Failed to complete analysis');
    }
  };

  const handleRetry = () => {
    setError(null);
    setLoading(true);
    fetchCreateLiveness();
  };

  return (
    <ThemeProvider>
      {loading ? (
        <Loader />
      ) : (
        <div className="flex h-full w-full items-center justify-center">
          <div className="h-[600px] w-[600px]">
            {error ? (
              <div>
                <p>{error}</p>
                <button onClick={handleRetry}>Try Again</button>
              </div>
            ) : (
              <FaceLivenessDetector
                sessionId={sessionId}
                region="us-east-1"
                onAnalysisComplete={handleAnalysisComplete}
                onError={(error) => {
                  console.error(error);
                  setError('Error during face detection');
                }}
                onUserCancel={() => {
                  console.log('User cancelled');
                }}
              />
            )}
          </div>
        </div>
      )}
    </ThemeProvider>
  );
};

export default LivenessComponent;

```

### Code Snippet

```typescript
"@aws-amplify/ui-react": "6.1.14",
    "@aws-amplify/ui-react-liveness": "3.1.3",
    "aws-amplify": "6.4.3",

```

**Comment by esauerbo** [comment]
Hi @LingXiongDev, thanks for creating this issue.

Regarding the first error, you will need to provide an `aws-exports` file. More information on this is outlined in [Step 1. Configure Auth](https://ui.docs.amplify.aws/react/connected-components/liveness#step-1-configure-auth)

The "Try Again" button requires that you implement `onUserCancel`. Right now it looks like it's running `console.log('User cancelled');` in that callback, but you'll need to fetch a new `sessionId` from the backend and remount the component with the updated `sessionId`. 

Let us know if you have any more questions!

**Comment by LingXiongDev** [comment]
> Hi @LingXiongDev, thanks for creating this issue.
> 
> Regarding the first error, you will need to provide an `aws-exports` file. More information on this is outlined in [Step 1. Configure Auth](https://ui.docs.amplify.aws/react/connected-components/liveness#step-1-configure-auth)
> 
> The "Try Again" button requires that you implement `onUserCancel`. Right now it looks like it's running `console.log('User cancelled');` in that callback, but you'll need to fetch a new `sessionId` from the backend and remount the component with the updated `sessionId`.
> 
> Let us know if you have any more questions!


Hello, thank you for your response. I have another question regarding Step 1: Configure Auth. Should this be configured on the backend and then the aws-exports file provided to the frontend, or should the frontend generate it by itself? I am unsure about where to place the aws-exports file and how to generate it. I understood that the backend generates this file and the frontend only needs to get the sessionId, but it seems incorrect now.

**Comment by LingXiongDev** [comment]
> Hi @LingXiongDev, thanks for creating this issue.
> 
> Regarding the first error, you will need to provide an `aws-exports` file. More information on this is outlined in [Step 1. Configure Auth](https://ui.docs.amplify.aws/react/connected-components/liveness#step-1-configure-auth)
> 
> The "Try Again" button requires that you implement `onUserCancel`. Right now it looks like it's running `console.log('User cancelled');` in that callback, but you'll need to fetch a new `sessionId` from the backend and remount the component with the updated `sessionId`.
> 
> Let us know if you have any more questions!

Hi @esauerbo Could you please tell me how to generate the aws-exports.js file and what content it needs? I couldn't find a specific method to generate the aws-exports.js file.

**Comment by LingXiongDev** [comment]
> Hi @LingXiongDev, thanks for creating this issue.
> 
> Regarding the first error, you will need to provide an `aws-exports` file. More information on this is outlined in [Step 1. Configure Auth](https://ui.docs.amplify.aws/react/connected-components/liveness#step-1-configure-auth)
> 
> The "Try Again" button requires that you implement `onUserCancel`. Right now it looks like it's running `console.log('User cancelled');` in that callback, but you'll need to fetch a new `sessionId` from the backend and remount the component with the updated `sessionId`.
> 
> Let us know if you have any more questions!

**Comment by esauerbo** [comment]
@LingXiongDev you can generate an amplify configuration following the instructions under Step 1. The different tabs (Amplify Gen 2, Amplify Gen 1, etc) are the different options for configuring auth. If you do not have a preference, we recommend you use Amplify Gen 2, which is the default (but any will work). 

The instructions will explain how to generate an `amplify_outputs.json` file, which can be used to configure Amplify. (`aws-exports` is the equivalent file for Amplify Gen 1). 

<img width="1024" alt="Screenshot 2024-08-05 at 12 55 06 PM" src="https://github.com/user-attachments/assets/ad9af5d2-fafe-46a9-94bb-67408db6019e">

**Comment by LingXiongDev** [comment]
> @LingXiongDev you can generate an amplify configuration following the instructions under Step 1. The different tabs (Amplify Gen 2, Amplify Gen 1, etc) are the different options for configuring auth. If you do not have a preference, we recommend you use Amplify Gen 2, which is the default (but any will work).
> 
> The instructions will explain how to generate an `amplify_outputs.json` file, which can be used to configure Amplify. (`aws-exports` is the equivalent file for Amplify Gen 1).
> 
> <img alt="Screenshot 2024-08-05 at 12 55 06 PM" width="1024" src="https://private-user-images.githubusercontent.com/70536670/355182449-ad9af5d2-fafe-46a9-94bb-67408db6019e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjA1MDksIm5iZiI6MTcyMjk2MDIwOSwicGF0aCI6Ii83MDUzNjY3MC8zNTUxODI0NDktYWQ5YWY1ZDItZmFmZS00NmE5LTk0YmItNjc0MDhkYjYwMTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE2MDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZTkyMTNjMmJiNDViZDRiZmIwMjEzYWYwNmY1OWM3MjE1ZTUyNDk0M2Q3ODEyYmIzZjdhNWVkYThjYTc3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d1dTi63Wo4X9ePaE74tcAeqvtO-ZlYDNl1PuYF0qAyA">

Hello, we are using Gen2. We should use the link you provided to select an existing project in the AWS Console, right? Then, we can generate the amplify_outputs.json file, download it, and use it in the frontend project. At the same time, we use the command amplify pull --appId d13i5yd5akm2xp --envName dev to update it locally, and the configuration is complete. Is that correct?

I also saw another method, which uses the commands amplify init and amplify push, but the generated file doesn't seem right. This should be the Gen1 method, right? Also, the tasks we pushed up remain in the progress state.
![image](https://github.com/user-attachments/assets/c9afa4c8-b3ce-4408-a609-394af75e1fd6)

**Comment by esauerbo** [comment]
@LingXiongDev yes that's correct!

And yes, amplify init/push are Gen1 commands, and wouldn't be relevant if you're using  Gen2.
