### ISSUE TITLE
"Center your face" UI is different between the actual phone and PC Chrome emulation mode

### ISSUE THREAD

**Issue by chemicalist11** [aws-amplify/amplify-ui#5565]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Liveness

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome

### Which region are you seeing the problem in?

ap-northeast-1

### Please describe your bug.

Description
I am experiencing one issue when using the FaceLivenessDetectorCore component of @aws-amplify/ui-react-liveness in my React18 project.

On the actual phone, "Center your face" does **not** superimpose the camera's frame.
In PC Chrome emulation mode, "Center your face"  does superimpose the camera's frame.
This is a bug that there is a difference in the UI of "Center your face" between the actual phone and PC Chrome emulation mode.

Steps to Reproduce
Implement according to [Amplify UI React Liveness ドキュメント](https://ui.docs.amplify.aws/react/connected-components/liveness).
Implement the <FaceLivenessDetectorCore> component to obtain credentials from the Cognito Identity Pool without using the Auth Backend.

Actual Behavior
In PC Chrome emulation mode, the "Center your face" area is superimposed on the camera's circled frame.
![PC-chrome-liveness](https://github.com/user-attachments/assets/b0900fa2-4c75-4c47-bc30-9e6cd89c5b83)

### What's the expected behaviour?

The "Center your face" area does not superimpose on the camera in PC Chrome emulation mode as it does on the actual phone.

### Help us reproduce the bug!

``` js
import React from "react";
import { fromCognitoIdentityPool } from "@aws-sdk/credential-providers";
import { RekognitionClient, CreateFaceLivenessSessionCommand, GetFaceLivenessSessionResultsCommand } from "@aws-sdk/client-rekognition";
import { Loader, ThemeProvider } from '@aws-amplify/ui-react';
import { FaceLivenessDetectorCore } from '@aws-amplify/ui-react-liveness';
import '@aws-amplify/ui-react/styles.css';

export default function App() {
  const [loading, setLoading] = React.useState(true);
  const [sessionId, setSessionId] = React.useState(null);
  const [targetOrigin, setTargetOrigin] = React.useState("");

  const credentials = 
  fromCognitoIdentityPool({
    clientConfig: { region: import.meta.env.VITE_REGION },
    identityPoolId: import.meta.env.VITE_IDENTITY_POOL_ID,
  });

  window.addEventListener('message', (event) => {
    setTargetOrigin(event.data.targetOrigin)
  });

  React.useEffect(() => {
    const getRekognitionClientResponse = async () => {
      const client = new RekognitionClient({
        region: import.meta.env.VITE_REGION,
        credentials
      });

      const command = new CreateFaceLivenessSessionCommand({ Settings: { AuditImagesLimit: 1 } });
      const response = await client.send(command);
      setSessionId(response.SessionId);
      setLoading(false);
    }

    getRekognitionClientResponse();
  }, []);

  const handleAnalysisComplete = async () => {
    const client = new RekognitionClient({
      region: import.meta.env.VITE_REGION,
      credentials
    });

    const command = new GetFaceLivenessSessionResultsCommand({ SessionId: sessionId });
    const response = await client.send(command);
    const SUCCESSFUL_SCORE = 80; 
    const isLive = response.Confidence > SUCCESSFUL_SCORE;
    postMessage(isLive, response.AuditImages[0].Bytes);
  };

  const postMessage = (isLive, faceImage) => {
    const postData = isLive
      ? { type: "liveness", isError: false }
      : { type: "liveness", isError: true };
    window.parent.postMessage(postData, targetOrigin);
  }

  return (
    <ThemeProvider>
      {loading ? (
        <Loader />
      ) : (
        <FaceLivenessDetectorCore
          sessionId={sessionId}
          region={import.meta.env.VITE_REGION}
          onAnalysisComplete={handleAnalysisComplete}
          onError={(error) => {
            console.error("face liveness error", error);
            postMessage(false);
          }}
          config={{ credentialProvider: credentials}}
        />
      )}
    </ThemeProvider>
  );
};
```

**Comment by jacoblogan** [comment]
@chemicalist11 Thank you for raising this issue.  Once you start the video check is there anything superimposed on the camera frame?

**Comment by chemicalist11** [comment]
@jacoblogan 
No, nothing is superimposed on the camera frame.
![start-liveness1](https://github.com/user-attachments/assets/791fcc77-4b1e-43db-97c9-58cf9e32870a)
![start-liveness2](https://github.com/user-attachments/assets/eacc7225-1c7b-4eaa-8c62-f208f33af0bd)

**Comment by reesscot** [comment]
@chemicalist11 What is the issue here? The Chrome emulator is just an emulator and may not match the experience on a real mobile device. Is there an issue you are seeing on a real mobile device?

**Comment by chemicalist11** [comment]
@reesscot 
It is not a issue and I am making it known.
If you are already aware of this issue and would like to keep it that way, it is resolved.
There is no issue with a real mobile device.

**Comment by reesscot** [comment]
@chemicalist11 Thanks for the update, I'll close this out since there is no issue with non-emulated mobile devices.
