### ISSUE TITLE
Unable to resolve "style-dictionary/lib/utils/deepExtend"

### ISSUE THREAD

**Issue by Felix1772** [aws-amplify/amplify-ui#5590]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

Expo

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari, iOS (React Native), Android (React Native)

### Please describe your bug.

After following the installation guide of AmplifyUI and installing all necessary modules I experience the following error:
`Unable to resolve "style-dictionary/lib/utils/deepExtend" from "node_modules/@aws-amplify/ui-react-native/src/theme/createTheme.ts"`

Then I tried to install `style-dictionary` which fixed this specific error, but created a new one:
`Unable to resolve "style-dictionary/lib/utils/references/usesReference" from "node_modules/@aws-amplify/ui-react-native/src/theme/createTheme.ts`

After looking into `createTheme.ts` and the node_module of `style-dictionary` I noticed that it is called `usesReferences`.
After changing to that I got the error that `structuredClone` is not available on native platforms as it is only available on the web.

### What's the expected behaviour?

Working Authenticator without a `style-dictionary`-error and not having to install it because it is not described in the installation guide.

### Help us reproduce the bug!

1. Initialize expo project
2. Installation of:
    ```
    npm add \
      @aws-amplify/ui-react-native \
      @aws-amplify/react-native \
      aws-amplify \
      @react-native-community/netinfo \
      @react-native-async-storage/async-storage \
      react-native-safe-area-context \
      react-native-get-random-values \
      react-native-url-polyfill
    ```

### Code Snippet

```typescript
// Put your code below this line.

```

### Console log output

`Unable to resolve "style-dictionary/lib/utils/deepExtend" from "node_modules/@aws-amplify/ui-react-native/src/theme/createTheme.ts`

**Comment by justinmakaila** [comment]
Between `d02d3c6edf667b89692c54cef7a98eb5eff21f29` and `d73bd9cc84a2bd07c86d0c6937cbde35fc2c4bc2`, style-dictionary became a dev dependency of `ui` and broke every other lib

**Comment by justinmakaila** [comment]
Adding it as a dependency of my root project does nothing. Top 2 lines stop being red, but the last one persists: `import usesReference from 'style-dictionary/lib/utils/references/usesReference';`

**Comment by jordanvn** [comment]
Hello, we're currently working on a fix for this issue.

In the meantime, we have updated the `latest` version of the `@aws-amplify/ui-react-native` to use the most recent working version (2.2.3). We are currently working on resolving this issue, but in the meantime we suggest using the 2.2.3 version of `@aws-amplify/ui-react-native`.

**Comment by jordanvn** [comment]
This issue was validated to be fixed in https://github.com/aws-amplify/amplify-ui/pull/5594

A new version has been released. `latest` version is now 2.2.5, which is safe.

Closing this issue as resolved.
