### ISSUE TITLE
Support ui-liveness for Vue

### ISSUE THREAD

**Issue by Snake-Zeng** [aws-amplify/amplify-ui#5605]
### On which framework/platform would you like to see this feature implemented?

Vue

### Which UI component is this feature-request for?

Liveness

### Please describe your feature-request in detail.

Do there are plans to support ui-liveness for vue versions?

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [X] ⚠️ This feature might incur a breaking change.

**Comment by jordanvn** [comment]
Hello @Snake-Zeng, thank you for this feature request. I'm going to close this issue as a duplicate of https://github.com/aws-amplify/amplify-ui/issues/4398. We currently do not have plans for adding Liveness support for Vue, but we will still continue to take it into consideration for our roadmap.

**Comment by Snake-Zeng** [comment]
> Hello @Snake-Zeng, thank you for this feature request. I'm going to close this issue as a duplicate of #4398. We currently do not have plans for adding Liveness support for Vue, but we will still continue to take it into consideration for our roadmap.

All right, thanks for the reply. I will look forward to further progress.
