### ISSUE TITLE
Docs: Improve discoverability of notes on usage with SSR

### ISSUE THREAD

**Issue by jaysonwor** [aws-amplify/amplify-ui#5653]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

amplify gen 2 / nextjs 

### What browsers are you seeing the problem on?

Firefox

### Please describe your bug.

I am running into an issue when trying to use @aws-amplify/ui-react in a ssr tsx. Not sure a bug or expected behavior. It is not clear in the documentation that usage of these ui-react components must be done in the client side. Is that a fact? Am I missing something?

Code snippet:
`import React from "react";
import {
Authenticator,
Button,
Card,
Flex,
Heading,
Text,
} from "@aws-amplify/ui-react";

const App = () => {
return (

< Heading >testing 12</ Heading >

);
};

export default App;`

Error:
./node_modules/@aws-amplify/ui-react-core/dist/esm/components/FormCore/FormProvider.mjs
Attempted import error: 'useForm' is not exported from 'react-hook-form' (imported as 'useForm').

### What's the expected behaviour?

See above

### Help us reproduce the bug!

See above

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by jaysonwor** [comment]
Thank you. There is a lot of ambiguity around what can be used in a csr vs
ssr in Amplify. It would nice to preface the scope e.g csr only, ssr only,
csr and ssr

**Comment by reesscot** [comment]
I think the best option for improving our docs here would be to put this specific error message in our troubleshooting section so it can easily be found.

**Comment by esauerbo** [comment]
Hey @jaysonwor, we updated our troubleshooting guide to include this specific message, and this will go out in our next release. This is mentioned in the guide, but to clarify, all of our components are meant to be used in client components.
