### ISSUE TITLE
[Feedback] First impression on the new authenticator / UI.

### ISSUE THREAD

**Issue by artidata** [aws-amplify/amplify-ui#569]
**Page**: [`/ui`](https://ui.docs.amplify.aws/ui)

**Feedback**: It has a pretty good design. However, the documentation has a lot to work on, No instruction on how to add more fields on the sign up form. I wish to be able to override the components from other UI frameworks. I will definitely migrate just for the good design.

**Comment by ericclemmons** [comment]
Working on the fix @artidata , I'll update here once it's out 🙏

**Comment by ericclemmons** [comment]
Alrighty, #606 fixes the bug, adds several tests, and we'll get this resolved for React, Angular, & Vue 🙏

**Comment by artidata** [comment]
Great, the fixes work. Migrating sooner than expected. 👍
