### ISSUE TITLE
[Feedback]Password show/hide feature

### ISSUE THREAD

**Issue by jssuttles** [aws-amplify/amplify-ui#571]
**Page**: [`/ui/auth/authenticator/q/framework/[framework]`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue)

**Feedback**:

I don't see any mention of a password show/hide feature. Does one exist?

Amplify
![image](https://user-images.githubusercontent.com/8527741/138526192-0b627e38-3192-4192-aadb-d96831ea83f0.png)

AWS SSO
![image](https://user-images.githubusercontent.com/8527741/138526029-d8c719f9-c029-484c-ab24-cd236b5a4ca4.png)

Google
![image](https://user-images.githubusercontent.com/8527741/138526070-df3e6386-a5f7-4adc-acae-f110088d322b.png)

**Comment by Milan-Shah** [comment]
@jssuttles as @ErikCH mentioned, we have launched a new version for [Authenticator UI Component](https://ui.docs.amplify.aws/components/authenticator). Apart from password show/hide, we have added many more features like password manager support, custom sign up attributes, custom styling and theme, zero config support etc. 

Let us know if we can add any more improvements for you. We are here to help :)
