### ISSUE TITLE
More detail please on the installation instructions

### ISSUE THREAD

**Issue by work-bw** [aws-amplify/amplify-ui#5779]
### On which framework/platform would you like to see this feature implemented?

Other

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

Would it be possible to add a little more detail for folks not familiar with what you have already in the instructions?  What operating systems are supported and more detail for how to install the product.  It looks like installation is only supported for some specific linux versions.  Which ones?  Any Windows or Mac support?  Can I use Cloudshell?  From what you show on the instructions today it seems like a lot of work to try it out for someone not familiar with Amplify.

### Please describe a solution you'd like.

More detail in the installation instructions for folks not familiar with Amplify.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by jordanvn** [comment]
Hi @work-bw thank you for this feature request. We’ll take this into consideration in our roadmap. If others are interested, please +1 or comment on this issue.

**Comment by reesscot** [comment]
@work-bw Can you provide some more details on what you are trying to install? Are you trying to setup the new StorageBrowser component?

**Comment by work-bw** [comment]
I just want to try out StorageBrowser and was not able to figure out from the instructions how to do that.

**Comment by reesscot** [comment]
Hi @work-bw,
The quickest setup to test out the StorageBrowser is to use Amplify Auth. We've added more detailed installation instructions to the RFC which you can follow here:
https://github.com/aws-amplify/amplify-ui/issues/5731#2-auth
I'm going to close this out for now, but please open a new issue if you are still having issues with getting setup.
