### ISSUE TITLE
Export `FileUploaderHandle` type in ui-react-storage

### ISSUE THREAD

**Issue by nam-truong-le** [aws-amplify/amplify-ui#5813]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Storage

### Please describe your feature-request in detail.

Hi team, in order to create a typed ref `ref = useRef<FileUploaderHandle>(null)`, the type `FileUploaderHandle` has to be exported.

### Please describe a solution you'd like.

We just need this export in `components/FileUploader/index.d.ts`.

```typescript
export { FileUploaderProps, FileUploaderHandle } from './types';
```

### We love contributors! Is this something you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by esauerbo** [comment]
Hey @nam-truong-le thank you for your feature request. This makes sense to implement, so we're adding it to our project roadmap. We'll update you here once that's been released.

**Comment by esauerbo** [comment]
This has been released in the latest version `@aws-amplify/uii-react-storage` https://www.npmjs.com/package/@aws-amplify/ui-react-storage/v/3.3.4
