### ISSUE TITLE
Getting - Auth UserPool not configured.

### ISSUE THREAD

**Issue by vashu0804** [aws-amplify/amplify-ui#5839]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Which region are you seeing the problem in?

India, Mumbai

### Please describe your bug.

I have a react project in which aws amplify is getting utilised now on clicking the login button with google i am getting Auth UserPool not configured on my local. Please suggest something incase anyone have incountered the similar issue previously.

### What's the expected behaviour?

Ideally it should log me in the website home page on click the sign in with google button.

### Help us reproduce the bug!

Sharing the code snipped below for your reference. Getting the error on my local system

### Code Snippet

```typescript
// Put your code below this line.
import { fetchAuthSession } from "aws-amplify/auth";

export const awsConfig = {
  Auth: {
    Cognito: {
      // region: import.meta.env.VITE_COGNITO_REGION,
      userPoolId: import.meta.env.VITE_COGNITO_USER_POOLS_ID,
      userPoolClientId: import.meta.env.VITE_COGNITO_WEB_CLIENT_ID,
      // signUpVerificationMethod: 'link',
      // storage: localStorage,
      // authenticationFlowType: 'ALLOW_REFRESH_TOKEN_AUTH',
      loginWith: {
        oauth: {
          domain: import.meta.env.VITE_OAUTH_DOMAIN_NAME,
          scopes: [
            "phone",
            "email",
            "profile",
            "openid",
            "aws.cognito.signin.user.admin",
          ],
          redirectSignIn: [import.meta.env.VITE_OAUTH_REDIRECT_SIGNIN_URL],
          redirectSignOut: [import.meta.env.VITE_OAUTH_REDIRECT_SIGNOUT_URL],
          responseType: "code",
        },
      },
    },
  },
};

export async function setCurrentSession() {
  try {
    const { accessToken, idToken } = (await fetchAuthSession()).tokens ?? {};
    const { username } = accessToken?.payload || {};
    const accessTokenString = accessToken?.toString() || "";
    const { name, email, picture } = idToken?.payload || {};
    setUserAttributes(
      username as string,
      name as string,
      email as string,
      picture as string,
      accessTokenString
    );
  } catch (err) {
    console.log(err);
  }
}

export const setUserAttributes = (id: string, name: string, email: string, profilePicture: string, accessToken: string) => {
  const userInfo = {
    id,
    name,
    email,
    profilePicture,
    accessToken,
  };
  localStorage.setItem('UserInfo', JSON.stringify(userInfo));
};

export const getUserAttributes = () => {
  return JSON.parse(localStorage.getItem('UserInfo') || '{}');
};

export async function refreshCurrentSession() {
  try {
    const userInfo = getUserAttributes();
    const { tokens } = await fetchAuthSession({ forceRefresh: true });
    const accessToken = tokens?.accessToken.toString() || "";

    setUserAttributes(
      userInfo?.id,
      userInfo?.name,
      userInfo?.email,
      userInfo?.profilePicture,
      accessToken
    );
  } catch (err) {
    console.log(err);
  }
}


//Have another file for fetchAuthSession

import { AuthSession, FetchAuthSessionOptions } from '../Auth/types';
/**
 * Fetch the auth session including the tokens and credentials if they are available. By default it
 * does not refresh the auth tokens or credentials if they are loaded in storage already. You can force a refresh
 * with `{ forceRefresh: true }` input.
 *
 * @param options - Options configuring the fetch behavior.
 * @throws {@link AuthError} - Throws error when session information cannot be refreshed.
 * @returns Promise<AuthSession>
 */
export declare const fetchAuthSession: (options?: FetchAuthSessionOptions) => Promise<AuthSession>;

```

### Console log output

<img width="694" alt="Screenshot 2024-09-25 at 2 27 31 PM" src="https://github.com/user-attachments/assets/c7638324-5b49-467f-ba01-2e49c0aaa7c1">

**Comment by thaddmt** [comment]
Can you also post the code where you use the Authenticator? Usually when this error occurs if your Amplify configuration is not set up correctly. Can you also show where you use the `awsConfig` with `Amplify.configure`?

**Comment by vashu0804** [comment]
> Can you also post the code where you use the Authenticator? Usually when this error occurs if your Amplify configuration is not set up correctly. Can you also show where you use the `awsConfig` with `Amplify.configure`?

Sure sharing the entire files step by step:
In Main.tsx
`/* eslint-disable @typescript-eslint/ban-ts-comment */
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { Amplify } from "aws-amplify";
import { Authenticator } from "@aws-amplify/ui-react";
import { IntlProvider } from "react-intl";
import { flatten } from "flat";
import {
  QueryClient,
  QueryCache,
  MutationCache,
  QueryClientProvider,
} from "@tanstack/react-query";
// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import enMessages from "./translations/en.json";
import { SnackbarProvider, SnackbarOrigin } from "notistack";
import { MuiThemeProvider } from "./styles/muiTheme.tsx";
import { GlobalContextProvider } from "./context/GlobalContext";
import App from "./App.tsx";
import "./styles/main.css";
import { awsConfig } from "./utils/auth";
import ErrorBoundary from "./components/Common/ErrorBoundary.tsx";

//@ts-ignore
Amplify.configure(awsConfig);

const localeConfig: Record<string, any> = {
  en: enMessages,
};

const queryClient = new QueryClient({
  queryCache: new QueryCache({
    onError: (error) => console.error(`Something went wrong: ${error}`),
  }),
  mutationCache: new MutationCache({
    onError: (error) => console.error(`Something went wrong: ${error}`),
  }),
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
});

const defaultSnackBarOrigin: SnackbarOrigin = {
  vertical: "top",
  horizontal: "center",
};

ReactDOM.createRoot(document.getElementById("root")!).render(
  <ErrorBoundary>
    <BrowserRouter>
      <MuiThemeProvider>
        {/* // Todo: Solve this */}
        {/* Default locale en is being used as a fallback due to missing locale data
      for undefined locale in React-intl */}
        <IntlProvider locale={"en"} messages={flatten(localeConfig.en)}>
          <GlobalContextProvider>
            <Authenticator.Provider>
              <QueryClientProvider client={queryClient}>
                {/* <ReactQueryDevtools initialIsOpen={false} /> */}
                <SnackbarProvider
                  maxSnack={3}
                  autoHideDuration={2000}
                  anchorOrigin={defaultSnackBarOrigin}
                >
                  <App />
                </SnackbarProvider>
              </QueryClientProvider>
            </Authenticator.Provider>
          </GlobalContextProvider>
        </IntlProvider>
      </MuiThemeProvider>
    </BrowserRouter>
  </ErrorBoundary>
);
`

In Login.tsx
`import { Box } from "@mui/material";
import { useLocation, Navigate } from "react-router-dom";
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import { useAuthenticator } from "@aws-amplify/ui-react";
import LogoSvg from "../assets/logo.svg";
import { LoginWrapper, AuthWrapper } from "./LoginStyles";

interface LocationState {
  from?: {
    pathname?: string;
  };
}
const LoginPage = () => {
  const { authStatus } = useAuthenticator((context: any) => [context.user]);
  const location = useLocation();
  const locationState = location.state as LocationState;
  const from = locationState?.from?.pathname || "/";

  if (authStatus === "authenticated") return <Navigate replace to={from} />;

  return (
    <LoginWrapper>
      <Box sx={{ paddingTop: "20px" }}>
        <img
          className="logoIcon"
          src={LogoSvg}
          style={{ height: "50px", width: "200px" }}
        />
      </Box>
      <AuthWrapper>
        <Authenticator socialProviders={["google"]} />
        {/* <SignUpWrapper>
          <div>Don't have any account?</div>
          <Link to={"/signup"}>
            <Button
              sx={{
                textTransform: "none",
                margin: "auto",
                fontSize: "16px",
              }}
            >
              Register
            </Button>
          </Link>
        </SignUpWrapper> */}
      </AuthWrapper>
    </LoginWrapper>
  );
};
export default LoginPage;
`

In loginWithGoogle.tsx
`import { useEffect } from "react";
import queryString from "query-string";
import { signInWithRedirect } from "aws-amplify/auth";
import { useAuthenticator } from "@aws-amplify/ui-react";
import { useNavigate } from "react-router-dom";

const LoginWithGooglePage = () => {
  const navigate = useNavigate();
  const { authStatus } = useAuthenticator((context: any) => [context.user]);
  const queryParams = queryString.parse(location.search);
  const hashParams = location.hash;
  const continueParam = queryParams["continue"] || "/home";

  useEffect(() => {
    if (authStatus === "authenticated") {
      navigate("/home");
    } else
      signInWithRedirect({
        provider: "Google",
        customState: `${continueParam}${hashParams}` as string,
      });
  }, [authStatus]);

  return <></>;
};

export default LoginWithGooglePage;
`

Have used it at few more places I hope this is good for your understanding.

**Comment by vashu0804** [comment]
@thaddmt Have you checked this?

**Comment by thaddmt** [comment]
@vashu0804 are you able to verify that your awsConfig has a value for `userPoolId: import.meta.env.VITE_COGNITO_USER_POOLS_ID,`? In a minimal repro the only time I get the error with oauth google login is if i remove the `userPoolId`

**Comment by vashu0804** [comment]
@thaddmt Yes, I have added the userPoolId in my evn config file and also I am getting the error while logging in with google just like you were having.

**Comment by cwomack** [comment]
Hey, @vashu0804 👋.  Just to make sure we can cross this off the list, can you double check that the Cognito resource ID's for User Pool and Identity Pool aligns to what is within your environment variables? Also, can you see if hard coding the ID's into the config call resolves the issue?  Thanks.

**Comment by vashu0804** [comment]
Hey @cwomack , I double checked the Pool ID's still facing the same issue, can you please help me more in this. I also tried hard coding the values and it is working then but getting undefined.

**Comment by vashu0804** [comment]
@cwomack Sure sharing the enitre package.json below.

`{
  "name": "frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite --port 3000",
    "test": "echo \"Error: no test specified\"",
    "build": "tsc && vite build",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "lint:fix": "eslint . --ext .js,.jsx,.ts,.tsx --fix",
    "format": "prettier --write .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^6.1.1",
    "@babel/runtime": "^7.24.1",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@mui/icons-material": "^5.15.0",
    "@mui/material": "^5.15.0",
    "@mui/styles": "^6.1.1",
    "@mui/system": "^5.15.0",
    "@mui/x-date-pickers": "^6.18.6",
    "@react-oauth/google": "^0.12.1",
    "@tanstack/react-query": "^5.17.0",
    "@tanstack/react-query-devtools": "^5.17.0",
    "@tanstack/react-table": "^8.11.7",
    "@tiptap/extension-collaboration": "^2.2.4",
    "@tiptap/extension-collaboration-cursor": "^2.2.4",
    "@tiptap/extension-color": "^2.2.4",
    "@tiptap/extension-link": "^2.2.4",
    "@tiptap/extension-list-item": "^2.2.4",
    "@tiptap/extension-ordered-list": "^2.2.4",
    "@tiptap/extension-placeholder": "^2.2.4",
    "@tiptap/extension-text-style": "^2.2.4",
    "@tiptap/extension-underline": "^2.2.4",
    "@tiptap/pm": "^2.2.4",
    "@tiptap/react": "^2.2.4",
    "@tiptap/starter-kit": "^2.2.4",
    "@types/react-router-dom": "^5.3.3",
    "aws-amplify": "^6.0.13",
    "axios": "^1.6.2",
    "chart.js": "^4.4.4",
    "chartjs-plugin-datalabels": "^2.2.0",
    "dayjs": "^1.11.10",
    "file-saver": "^2.0.5",
    "flat": "^6.0.1",
    "html-react-parser": "^5.1.1",
    "i": "^0.3.7",
    "lodash": "^4.17.21",
    "material-react-table": "^2.9.2",
    "notistack": "^3.0.1",
    "npm": "^10.2.5",
    "postcss-import": "^16.1.0",
    "postcss-nesting": "^12.1.1",
    "query-string": "^8.1.0",
    "react": "^18.2.0",
    "react-big-calendar": "^1.11.2",
    "react-chartjs-2": "^5.2.0",
    "react-dom": "^18.2.0",
    "react-dropzone": "^14.2.3",
    "react-intl": "^6.5.5",
    "react-router-dom": "^6.20.1",
    "react-select": "^5.8.0",
    "sanitize-html": "^2.13.0",
    "source-map": "^0.7.4",
    "uuid": "^9.0.1",
    "vite-plugin-node-polyfills": "^0.22.0",
    "vite-tsconfig-paths": "^4.2.2",
    "y-prosemirror": "^1.2.3",
    "y-webrtc": "^10.3.0",
    "yjs": "^13.6.14"
  },
  "devDependencies": {
    "@babel/core": "^7.24.3",
    "@tanstack/eslint-plugin-query": "^5.14.6",
    "@types/file-saver": "^2.0.7",
    "@types/flat": "^5.0.5",
    "@types/lodash": "^4.14.202",
    "@types/node": "^22.5.5",
    "@types/react": "^18.2.43",
    "@types/react-big-calendar": "^1.8.9",
    "@types/react-dom": "^18.2.17",
    "@types/sanitize-html": "^2.11.0",
    "@types/uuid": "^9.0.7",
    "@typescript-eslint/eslint-plugin": "^6.14.0",
    "@typescript-eslint/parser": "^6.14.0",
    "@vitejs/plugin-react": "^4.2.1",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.55.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-prettier": "^5.0.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.5",
    "node-polyfill-webpack-plugin": "^4.0.0",
    "postcss": "^8.4.32",
    "prettier": "^3.1.1",
    "tailwindcss": "^3.3.6",
    "typescript": "^5.2.2",
    "vite": "^5.0.8"
  }
}
`

**Comment by vashu0804** [comment]
@cwomack thanks for your help. I changed the mui version from 5 to 6 and now it is working.
