### ISSUE TITLE
[Angular] amplify-authenticator does not appear in components using OnPush change detection strategy

### ISSUE THREAD

**Issue by WojciechKasprzyk** [aws-amplify/amplify-ui#5899]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari, iOS (React Native), Android (React Native)

### Please describe your bug.

`amplify-authenticator` tag remains empty in OnPush components (even triggering change detection manually does not help).

``` ts
import { AfterViewInit, ChangeDetectionStrategy, ChangeDetectorRef, Component, inject } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { TodosComponent } from './todos/todos.component';
import { AmplifyAuthenticatorModule } from "@aws-amplify/ui-angular";


@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  imports: [RouterOutlet, TodosComponent, AmplifyAuthenticatorModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements AfterViewInit {
  title = 'amplify-angular-template';
  private cdr = inject(ChangeDetectorRef)
  ngAfterViewInit() {
    this.cdr.detectChanges();
  }
}

```

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/a65aea0b-9581-49a9-9a54-48af0a2ece05">

### What's the expected behaviour?

I expect to see the authenticator element

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/d7911157-2bfd-4bf1-bf3d-7d3c09710cbd">

### Help us reproduce the bug!

Use the official demo app ( https://github.com/aws-samples/amplify-angular-template ) with authenticator, and change changeDetection to OnPush

**Comment by esauerbo** [comment]
Hi @WojciechKasprzyk thanks for reporting this. Please track this feature request in https://github.com/aws-amplify/amplify-ui/issues/4899.
