### ISSUE TITLE
Posenet or tf loaded as script in DOM conflicts with the posenet loaded

### ISSUE THREAD

**Issue by logesh-jarvis** [aws-amplify/amplify-ui#5901]
Hi,

I am using react-liveness as a wrapper inside my angular component. I already have the script loaded in my DOM and loading the posenet using posenet.load(). If I load my react-liveness wrapper then the posenet.load() is not loading. If I comment the liveness code the posenet.load() is working as expected.

**Comment by hbuchel** [comment]
Hi @logesh-jarvis We don't own that tensorflow library and don't have plans to support debugging issues related to it.
