### ISSUE TITLE
Bug(Authenticator): Clicking the Sign in tab when already on the Sign In tab opens the 

### ISSUE THREAD

**Issue by hbuchel** [aws-amplify/amplify-ui#5911]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

In the Authenticator component, if you click on the tab that is currently active, it switches the active tab.

### What's the expected behaviour?

Clicking the active tab button should not switch the active tab to the other.

### Help us reproduce the bug!

In the example on https://ui.docs.amplify.aws/react/connected-components/authenticator, with the "Sign in" tab open, click the "Sign in" tab again and it switches the active tab to Create Account.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by mjdepalma** [comment]
Some extra context in case it helps.  Selecting a particular page title should (1) switch to that page if user focus is currently on opposite page (which works), and (2) stay on that page if user is already on that page (which doesn't work).   That is the way all menus and spreadsheet pages work, and is the way that users will expect it to work as well.

(1) With focus on Sign In page, select "Sign In", and focus will incorrectly toggle to "Create Account"
(2) select "Sign In" again, and focus will toggle back to "Sign In"
(3) you can repeat steps 3 & 4 over and over to see the issue
(4) with focus on Create Account page, select "Create Account" page title, and focus will incorrectly toggle to "Sign In"
(5) select "Create Account" again, and focus will toggle back to "Create Account"
(6) you can repeat steps 6 & 7 over and over to see the issue

Hope this helps!

**Comment by hbuchel** [comment]
Thanks for the extra context @mjdepalma
