### ISSUE TITLE
Exclude specific branches detection not working in Amplify

### ISSUE THREAD

**Issue by ashokvaddevalli** [aws-amplify/amplify-ui#5931]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Account Settings, Other

### How is your app built?

selvete

### Please describe your bug.

I am trying to exclude develop, release, prod branches and remaining all branches need to be detect in Amplify but it is not working exclude detect branches.

*,!release,!prod,!develop (noticed after save it is moving automatically order like this  !release,!prod,!develop,*) - Not working exclude branches

"*","!release","!develop","!prod" - Noticed after save it is changing order like this "!develop","!prod","!release","*" - Not working exclude branches

How to exclude specific branches and remaining all branches need to include for auto detect in Amplify?

### What's the expected behaviour?

I am trying to exclude develop, release, prod branches and remaining all branches need to be detect in Amplify but it is not working exclude detect branches.

*,!release,!prod,!develop (noticed after save it is moving automatically order like this  !release,!prod,!develop,*) - Not working exclude branches

"*","!release","!develop","!prod" - Noticed after save it is changing order like this "!develop","!prod","!release","*" - Not working exclude branches

How to exclude specific branches and remaining all branches need to include for auto detect in Amplify?

### Help us reproduce the bug!

I am trying to exclude develop, release, prod branches and remaining all branches need to be detect in Amplify but it is not working exclude detect branches.

*,!release,!prod,!develop (noticed after save it is moving automatically order like this  !release,!prod,!develop,*) - Not working exclude branches

"*","!release","!develop","!prod" - Noticed after save it is changing order like this "!develop","!prod","!release","*" - Not working exclude branches

How to exclude specific branches and remaining all branches need to include for auto detect in Amplify?

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by cwomack** [comment]
Hello, @ashokvaddevalli 👋.  Have you made any changes to the auto-build settings in the Amplify console under "App Settings"?  Want to see if simply disabling the auto-build in this way is what you're looking for first: 
![Screenshot 2024-10-22 at 10 37 51 AM](https://github.com/user-attachments/assets/9c6df128-9e8d-4619-88fc-95a705bf03ee)

**Comment by cwomack** [comment]
Following up because I think we have a better idea of what you're looking for here, @ashokvaddevalli.  Let me know if [these Amplify Hosting docs](https://docs.aws.amazon.com/amplify/latest/userguide/pattern-based-feature-branch-deployments.html) help clarify how you can automatically add branches to Amplify. You can put together a regex pattern and if the git branch name matches the pattern specified, then a corresponding Amplify branch will be created.

Let me know if this helps further!

**Comment by cwomack** [comment]
@ashokvaddevalli, thanks for following up with some clarity here.  After reviewing it with our Hosting team internally and seeing that you've also got issue [#2138](https://github.com/aws-amplify/amplify-backend/issues/2138) opened on the Hosting repo, we'll close out this one.  Was going to transfer this over to that repo anyways, so you're in good hands over there! 

We'll provide any updates and further follow up on that issue.  Thanks!
