### ISSUE TITLE
Removing the "Create Account" tab

### ISSUE THREAD

**Issue by StephenK9** [aws-amplify/amplify-ui#594]
When using I18n, where do we put the following code?

`    I18n.putVocabulariesForLanguage('en', {
        'Sign In': 'Login', // Tab header
        'Sign in': 'Log in', // Button label
        'Sign in to your account': 'Welcome Back!',
        Username: 'Enter your username', // Username label
        Password: 'Enter your password', // Password label
        'Forgot your password? ': 'Reset Password',
      });`
I've imported I18n and added the code above to my App.js file, but nothing changes when I do.

**Comment by ErikCH** [comment]
Hi @StephenK9 !

Thanks for the feedback. I believe this is a bug, and I'm pushing up a fix write now for it! I'll let you know as soon as it's fixed. 

Did you have a question on removing the `Create Account` tab too?

**Comment by StephenK9** [comment]
> Did you have a question on removing the `Create Account` tab too?

Yes, thanks! How do we explicitly remove that tab? I do not see any place in the docs that explicitly states how to remove that tab. The only image I see of the login screen without the 'create account' tab is the the one that falls under the i18N sections: https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#labels--text

**Comment by ErikCH** [comment]
Hi @StephenK9 !  We have pushed up the fix for custom translations, and update the documentation. Please try that.

As for removing tabs, the easiest way to do that is to add this to your style sheet.

```
.amplify-tabs {
  display: none;
}
```

Then make sure when you initialize the authenticator that you send over `initialState: 'signIn`.

```
export default withAuthenticator(App, {
  initialState: 'signIn',
});
```

Let me know if that works for you. We'll be adding that to the documentation soon.

**Comment by Milan-Shah** [comment]
@StephenK9 Please let us know if you have any issue applying @ErikCH 's suggestion above! Marking the issue as resolved, but do let us know if you have any more issues with Authenticator.
