### ISSUE TITLE
[ui-react-native] peer support for react-native ^0.76

### ISSUE THREAD

**Issue by allxie** [aws-amplify/amplify-ui#5973]
### On which framework/platform would you like to see this feature implemented?

React Native

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

Currently the peer dependency for react native is described as follows in `@aws-amplify/ui-react-native@2.2.16`:
`  "react-native": "^0.70 || ^0.71 || ^0.72 || ^0.73 || ^0.74 || ^0.75",
`

This results in the following error when upgrading to react native .76:
```
npm error Found: react-native@0.76.0
npm error node_modules/react-native
npm error   react-native@"0.76.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react-native@"^0.70 || ^0.71 || ^0.72 || ^0.73 || ^0.74 || ^0.75" from @aws-amplify/ui-react-native@2.2.16
npm error node_modules/@aws-amplify/ui-react-native
npm error   @aws-amplify/ui-react-native@"^2.2.16" from the root project
```

### Please describe a solution you'd like.

Would love one of the following:

- would love support for react-native `0.76`, or
- update to the peer dependency in the package.json if it's already supported, or 
- some updates to documentation about it not being supported yet and why

Thank you!

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by jacoblogan** [comment]
Thank you for your feature request, we will consider this in our roadmap moving forward.

**Comment by brtech99** [comment]
This is not a feature request, it's a bug.  You can't use amplify UI in react-native without it.  in fact, if you try to run the quickstart (https://docs.amplify.aws/react-native/start/quickstart/) it will fail because of this bug.   You must have a reason for requiring explicit versions of react-native in this module, but the consequence is that you need to update this dependency whenever react-native bumps a version.

**Comment by cwomack** [comment]
@brtech99 we're keeping this labeled as a feature request for now, but wanted to follow up here and let you know that we've got this internally marked as a high priority item to be resolved in the short term.  We'll follow up on this issue as soon as we have a fix out.

**Comment by mertarica** [comment]
I can't upgrade my packages and can't use new features just because of this bug and I think I'm not alone. Do you guys have any estimation as to when it will be done?

**Comment by cwomack** [comment]
@berg-dee, we appreciate the feedback will update this issue as soon as we can.

**Comment by giacomoarru** [comment]
I also am affected by this problem

**Comment by cwomack** [comment]
PR #6266 has been introduced to address this issue.  Once we have that merged, we'll follow up here.
