### ISSUE TITLE
Optimize bundle size

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#599]
### Metrics

- https://bundlephobia.com/package/@aws-amplify/ui-react@next

    > ![Screen Shot 2021-11-01 at 1 50 29 PM](https://user-images.githubusercontent.com/15182/139724986-004d17c7-f7eb-4349-8a04-0e6bd654bffc.png)

- https://bundlephobia.com/package/@aws-amplify/ui-angular@next
- https://bundlephobia.com/package/@aws-amplify/ui-vue@next

### Opportunities

- Remove Icons (https://github.com/aws-amplify/amplify-ui/discussions/480)
- Audit `postcss` & `caniuse` usage
- Audit real-world bundle-sizes (https://github.com/vercel/next.js/tree/canary/packages/next-bundle-analyzer)

**Comment by Milan-Shah** [comment]
@ErikCH has already merged a PR to reduce the bundle size. Marking it as resolved!
