### ISSUE TITLE
Docs Site Header links go to 404

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#605]
Clicking any of the heading links causes a 404 page.

![image](https://user-images.githubusercontent.com/65630/139919399-c9987d8c-0a11-4efd-92cc-cc05aaa9c22f.png)

**Comment by ericclemmons** [comment]
We'll know by Friday (Nov 5th) if we'll even keep the `amplify-docs` theme.  Replacing it would solve several issues like these.

**Comment by ericclemmons** [comment]
Closed via #626 

https://ui.docs.amplify.aws/ui/components/authenticator?platform=react#zero-configuration
