### ISSUE TITLE
Update create-react-app-auth-amplify

### ISSUE THREAD

**Issue by Milan-Shah** [aws-amplify/amplify-ui#631]
https://github.com/aws-samples/create-react-app-auth-amplify

**Comment by swaminator** [comment]
This sample has nearly 5K stars and is featured on the Amplify console.
![image](https://user-images.githubusercontent.com/2429410/140403457-59954d53-b4aa-4822-ac05-5812be8443e9.png)

**Comment by ericclemmons** [comment]
This will need to be done _after_ `@latest` has published so that the `package.json` can reference that release.

(Also, with the usage of `package-lock.json` and `yarn.lock` files on install, those dependencies should probably use `@latest` instead of a hard-coded version)
