### ISSUE TITLE
imgProps values are being overridden in AmplifyS3Image component

### ISSUE THREAD

**Issue by coe720** [aws-amplify/amplify-ui#641]
When height and width values are passed into the imgProps prop in the AmplifyS3Image the values are being overridden by the resolution of the image.

**Comment by hvergara** [comment]
Hi @coe720!

`<AmplifyS3Image>` component uses CSS variables to determine image dimensions, as described in [Amplify UI components > Storage > AmplifyS3Image](https://docs.amplify.aws/ui/storage/s3-image/q/framework/react/)

There are two ways to specify width/height:

**1. Wrap `AmplifyS3Image` component within a custom element + CSS selector:**

CSS:
```css
.my-component amplify-s3-image {
  --width: 400px;
  --height: 200px;
}
```

HTML:
```html
<div className="my-component">
  <AmplifyS3Image imgKey="image.jpg" />
</div>
```

**2. Override CSS variables through `imgProps.style`:**

```jsx
<AmplifyS3Image
  imgKey="image.jpg"
  imgProps={{
    style: {
      "--width": "400px",
      "--height": "200px",
    }
  }}
/>
```

Please let us know if any of these options works for you :)

**Comment by Milan-Shah** [comment]
@coe720 Please let us know if you have any issues as per @hvergara's suggestion above! We are here to help :)
