### ISSUE TITLE
Push `@next` tag to origin

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#644]
#490 publishes to `@next`, but we need this as an actual tag so the repo can be pulled at an explicit version:

> https://github.com/aws-amplify/amplify-ui/tags

(Tags haven't been pushed since #490)

**Comment by ericclemmons** [comment]
From @alharris-at:
> Is it possible to get those published as actual tags, so we can pull down the repo at a particular release version? This will be helpful if we need to pull a quick patch release of amplify-ui and release into amplify studio for some reason, but don't have a week or so to wait around for an npmpm import.

**Comment by wlee221** [comment]
Is this something we need after GA though?

**Comment by ericclemmons** [comment]
We need _before_ GA as-soon-as-possible for internal teams to immediately leverage fixes on `main` since there's a 3-day window to use the NPM tag.

I think the trick will be whether this uses `--tags` or `--follow-tags` because we **don't want to update `main`**:
> https://git-scm.com/docs/git-push

**Comment by wlee221** [comment]
I believe this can be closed as per https://github.com/aws-amplify/amplify-ui/pull/652.

**Comment by alharris-at** [comment]
Perfect, thank you!
