### ISSUE TITLE
Clean up Sign In & Sign Up screens

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#645]
- [ ] Remove default text from slots #637 

	Here's what that looks like:

	![Screen Shot 2021-11-08 at 3 02 01 PM](https://user-images.githubusercontent.com/15182/140818452-cbd3bbff-f18b-4c4b-9394-567297a22fb7.png)

	![Screen Shot 2021-11-08 at 3 02 15 PM](https://user-images.githubusercontent.com/15182/140818454-ffe3554d-f03e-492a-996d-3cd73d110a45.png)

	![Screen Shot 2021-11-08 at 3 03 45 PM](https://user-images.githubusercontent.com/15182/140818456-be6911c6-3b77-4d4c-be1e-d791454c76d0.png)
	
	![Screen Shot 2021-11-08 at 3 03 59 PM](https://user-images.githubusercontent.com/15182/140818457-7a343fcb-da95-44ce-9e1d-a745cc0292de.png)

- [ ] Move the social buttons **above** the default form.

	See: https://codesandbox.io/s/aws-amplify-react-federated-7o5yl?file=/src/App.js

- [ ] Replace the `<hr />` with a `– or –` divider 

	See: https://codesandbox.io/s/aws-amplify-react-federated-7o5yl?file=/src/App.js

- [ ] On the **Sign Up** screen, make the text say `Sign Up with...` instead of `Sign In with...`

**Comment by swaminator** [comment]
@ericclemmons why isn't the text within the social buttons centered?

**Comment by ericclemmons** [comment]
@swaminator Some default styles need to be updated:
<img width="446" alt="Screen Shot 2021-11-10 at 10 36 20 AM" src="https://user-images.githubusercontent.com/15182/141154283-19f06c8f-2e8f-4841-8414-dc46c17a50cd.png">

**Comment by ErikCH** [comment]
This fix is done
