### ISSUE TITLE
Code snippets are missing highlight markers

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#655]
- [ ] Apply styles like `.mdx-marker`

	https://github.com/aws-amplify/amplify-ui/blob/441693d36109d067f57762a0bff3ac83744f0f2a/docs/src/styles/styles.css#L1-L3

	> ![Screen Shot 2021-11-09 at 12 47 39 PM](https://user-images.githubusercontent.com/15182/140996438-aaad2bf5-6f40-4646-99f0-259864c6022d.png)
	> ![Screen Shot 2021-11-09 at 12 47 44 PM](https://user-images.githubusercontent.com/15182/140996440-40d9f7bb-6c3c-4ad1-8905-64af7a6ffc62.png)

- [ ] Remove `styles.css` (which doesn't seem to be used anymore!)

**Comment by dbanksdesign** [comment]
Both done in #656
