### ISSUE TITLE
[@next] Unable to boostrap via create-react-app & "Getting Started" docs

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-ui#667]
**Describe the bug**
The @next "Getting Started" section has instructions to install just the UI package, but that package appears to have dependencies on aws-amplify packages including data store. I suspect this is actually a dependency issue not a documentation issue, but I'll start here.

**To Reproduce**
1. Navigate to https://ui.docs.amplify.aws/getting-started/installation
2. In local workspace create a new app: `npx create-react-app test-project`
3. In the local app workspace, install UI dependency per instructions: `yarn add @aws-amplify/ui-react@next`
4. Edit `src/index.js` to import the provider per instructions: `import { AmplifyProvider } from '@aws-amplify/ui-react';`
5. Start a dev server: `yarn start`
6. Observe an error in the console: 
```
Failed to compile.

./node_modules/@aws-amplify/ui-react/dist/esm/index.js
Module not found: Can't resolve '@aws-amplify/datastore' in '/Users/schmelte/src/studio/test-project/node_modules/@aws-amplify/ui-react/dist/esm'
```

**Expected behavior**
The app compiles and launches

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 11.6.1
 - Browser: Chrome 
 - Version: 95.0.4638.69

**Comment by palpatim** [comment]
Followup: manually installing the missing datastore dependency didn't resolve the issue. It now fails with an error on `aws-amplify`:

```
% yarn add @aws-amplify/datastore
% yarn start
Failed to compile.

./node_modules/@aws-amplify/ui-react/dist/esm/index.js
Module not found: Can't resolve 'aws-amplify' in '/Users/schmelte/src/studio/test-project/node_modules/@aws-amplify/ui-react/dist/esm'
```

**Comment by reesscot** [comment]
It seems that our yarn instructions are missing the `aws-amplify` depencency, so the full yarn install command should be:
```
yarn add aws-amplify @aws-amplify/ui-react@next
```

**Comment by palpatim** [comment]
Thanks! I should have just stuck with npm. :)
