### ISSUE TITLE
Docs: Add responsive design

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#684]
Design for Docs site breaks on smaller screen sizes. This should be fixed. 

Also the menu button should work. 

![image](https://user-images.githubusercontent.com/65630/141357757-fbe693f5-1cee-480b-b82b-3540188c92ac.png)

**Comment by dbanksdesign** [comment]
Assigned it to myself, should have a fix for review by Monday.

**Comment by Milan-Shah** [comment]
The issue has been fixed on our end. Hence, marking it closed!
