### ISSUE TITLE
`SelectField` labels don't render by default on the docs page

### ISSUE THREAD

**Issue by cwoolum** [aws-amplify/amplify-ui#687]
When visiting the docs page, the label prop is not rendered except when it's used with a placeholder. Toggling `labelHidden` will cause it to render.

https://ui.docs.amplify.aws/components/selectfield

**Comment by reesscot** [comment]
I believe this is only an issue with when the the demo component causes a re-render, and not a general issue affecting the `SelectField` in normal use. Needs further investigation.

**Comment by zchenwei** [comment]
I think I found the problem. It is just a demo issue, not related to the component itself. Will put out a PR to get that fixed
