### ISSUE TITLE
Link component doesn't have "to" prop in types

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-ui#705]
This issue is related to the `amplify-ui@next` for React.

The docs for the `Link` component, under the section [Routing Libraries](https://ui.docs.amplify.aws/components/link#routing-libraries) shows an example with `react-router-dom`:
```js
import { Link } from '@aws-amplify/ui-react';
import {
  BrowserRouter as Router,
  Link as ReactRouterLink,
} from 'react-router-dom';

/* React Router Example */
<Router>
  <Link as={ReactRouterLink} to="/home">
    Home
  </Link>
</Router>;
```

When following the example in Typescript, the prop `to` gives error (see screenshot)

![image](https://user-images.githubusercontent.com/7353869/141653273-50fa10cb-8271-40ab-8f82-414027c3c339.png)

**Comment by dbanksdesign** [comment]
Thank you for flagging this issue! We have noticed the `Link` component needs some work to play nicely with other frameworks, we are looking into it this week.

**Comment by Milan-Shah** [comment]
@dreamorosi We need to do some research for our link component to support child attribute. We will keep the ticket updated as soon as we bring it into our upcoming sprint.

**Comment by bestickley** [comment]
@joebuono, any updates on this?

**Comment by joebuono** [comment]
@bestickley Thank you for reminding me of this issue. I found that the `<Link />` component now has the `to` prop. 

![Amplify_Link_Demo](https://user-images.githubusercontent.com/48109584/153103909-6dcde0f5-7303-435c-a8d0-46389302ae9b.gif)

Below is the code I used in my `App.js` after running `create-react-app`:

```javascript
import { Link, Flex, Heading } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import {
  BrowserRouter as Router,
  Link as ReactRouterLink,
  Routes,
  Route,
} from 'react-router-dom';

function App() {
  return (
    <Router>
      <Flex>
        <Link as={ReactRouterLink} to="/">Home</Link>
        <Link as={ReactRouterLink} to="/about">About</Link>
        <Link as={ReactRouterLink} to="/users">Users</Link>
      </Flex>

      <Routes>
        <Route path="/about" element={<About />} />
        <Route path="/users" element={<Users />} />
        <Route path="/" element={<Home />} />
      </Routes>
    </Router>
  );
}

function Home() {
  return <Heading level={2}>Home</Heading>;
}

function About() {
  return <Heading level={2}>About</Heading>;
}

function Users() {
  return <Heading level={2}>Users</Heading>;
}

export default App;
```

Hope this helps! 👍

**Comment by bestickley** [comment]
@joebuono, you're welcome! Thanks for the example. What about in a TS project?
Types seem to be incorrect :/
![image](https://user-images.githubusercontent.com/35735118/153225508-df0cee08-91bb-4634-ba88-1873ef3368f8.png)

**Comment by joebuono** [comment]
@bestickley Ah good catch! Just created a PR to fix it: https://github.com/aws-amplify/amplify-ui/pull/1285
