### ISSUE TITLE
onChange event for TextField component is wrong type

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-ui#707]
This issue is related to the `amplify-ui@next` for React.

The event passed as argument to the function should be something like `ChangeEvent<HTMLInputElement>`, like it is in `<PasswordField>`, but instead has `any` (see screenshot below). 
![image](https://user-images.githubusercontent.com/7353869/141680782-3536c655-4023-454c-b543-f1759e1e18c4.png)

This means that when trying to access things like the value of the target (`e.target.value`) TS  won't compile unless I explicitly set the type in the signature of the event handler like:
```ts
onChange={(e: ChangeEvent<HTMLInputElement>) => { /*...*/ }}
```

Expected:
![image](https://user-images.githubusercontent.com/7353869/141680851-259172a4-9596-49ea-9333-435678bdb94f.png)

**Comment by hvergara** [comment]
good catch! `TextField` is a tricky component, as it can act as an `input` or a `textarea` depending on the value of the `isMultiline` property. Will take a look and provide a fix to provide type-safety on event handlers.

**Comment by reesscot** [comment]
This will be fixed in our next major release.

**Comment by ErikCH** [comment]
This should be fixed @dreamorosi ! Please reopen if you are still having an issue.

**Comment by zchenwei** [comment]
This should be fixed by 4.x release now
