### ISSUE TITLE
Flex & Grid don't accept ref prop while View does

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-ui#710]
This issue is related to `@aws-amplify/ui-react` next.

As shown in the image below, trying to pass a `ref` to a `<Flex />` component, the same happens with the `<Grid />` one. 
![image](https://user-images.githubusercontent.com/7353869/141821659-bf63a3d2-0264-4906-bde8-8ed1295d64ba.png)

On the other hand, the `<View />` component accepts it.

**Comment by reesscot** [comment]
Hi @dreamorosi, thanks for opening this ticket, it confirms that this is a needed feature. Currently only View and Button support the ref prop. I'm currently in the process of adding support for the ref prop on the other primitives. Stay tuned!
