### ISSUE TITLE
Authenticator@next: When loginMechanism set to email, the forget password placeholder should be email.

### ISSUE THREAD

**Issue by artidata** [aws-amplify/amplify-ui#714]
Currently the placeholder is written as username, though putting down email address will still progress. 
https://user-images.githubusercontent.com/20266094/141839509-0e93e49b-3742-43d5-948d-be42a66fab9a.mp4

**Comment by ErikCH** [comment]
Hi @artidata ! I'm working on a fix for this now, so it will show correctly, instead of just `username` for all types of inputs.

**Comment by ericclemmons** [comment]
Fixed via #738 🎉
