### ISSUE TITLE
Create per-package README.md files

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#728]
https://www.npmjs.com/package/@aws-amplify/ui-react is blank.

This is because https://github.com/aws-amplify/amplify-ui/tree/main/packages/react doesn't have a `README.md`.

For comparison, https://www.npmjs.com/package/aws-amplify-react _does_:
> https://www.npmjs.com/package/aws-amplify-react

**Comment by reesscot** [comment]
This has been fixed: https://www.npmjs.com/package/@aws-amplify/ui-react
