### ISSUE TITLE
[Feedback] Authenticator@next Confirm password, arguably a bad UX.

### ISSUE THREAD

**Issue by artidata** [aws-amplify/amplify-ui#767]
In my opinion, the confirm password whether in the sign up form or reset password form of the authenticator is a bad UX. There are 2 things that I don't like. 

First, The error message is shown on the **first** character typed. Users definitely know that it doesn't match, why prompt them?   

![Screenshot 2021-11-18 10 18 34 AM](https://user-images.githubusercontent.com/20266094/142365272-bb58eddd-79c3-4757-9f95-f095066d1079.png). 

There are better ways to show the error. Facebook's report password only report such error when the number of retyped characters is larger. I personally show the error when users press the submit button. Watch here: 

https://user-images.githubusercontent.com/20266094/142366396-aca4de0a-8f77-4d8d-b73e-e6fd9e1c9097.mp4

Second, I don't really like the phrase _'Your passwords must match'_. Facebook's reset password use the phrase _'Passwords do not match'_ . I personally use 'Passwords need to match'. However, this comes down to personal preference.

**Comment by ericclemmons** [comment]
I agree – this experience can be optimized in a non-breaking way 👍

**Comment by slaymance** [comment]
Another idea if we decide we want to keep password validation prior to submitting the form: we could validate on a blur event for the Confirm Password field. From a user's standpoint, the error message would only display after they have moved focus away from the Confirm Password field.

Maybe even blur event handling + showing error message when confirm length exceeds initial new password length.

**Comment by wlee221** [comment]
One more thing, we need to make those validation messages customizable too. Agreed with @slaymance to use `blur` event to start password validations.

**Comment by Milan-Shah** [comment]
@artidata We have improved our confirm password error validation experience. You can try it out in our latest version @aws-amplify/ui-angular@2.0.3. Let us know if you have any more suggestions. We are here to help :)
