### ISSUE TITLE
System Dark Mode different than Dark Mode

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-ui#795]
This is most notable in code blocks:

<img width="1306" alt="Screen Shot 2021-11-18 at 5 31 43 PM" src="https://user-images.githubusercontent.com/15182/142513240-810fe045-7942-4a67-9e07-f1dc0dbe2a99.png">
<img width="1306" alt="Screen Shot 2021-11-18 at 5 31 46 PM" src="https://user-images.githubusercontent.com/15182/142513241-f9c18cbc-5774-460b-a0bc-8cdf64ed4888.png">

**Comment by michaelbrewer** [comment]
Same for the dark mode page itself.

<img width="1723" alt="Screen Shot 2021-11-19 at 11 34 35 PM" src="https://user-images.githubusercontent.com/5442469/142718562-fd2a9b0e-01ef-4db0-aac7-8f19080c1459.png">

**Comment by Milan-Shah** [comment]
Closing it as its fixed!
