### ISSUE TITLE
After @aws-amplify/ui-react v2.0.0 upgrade the Auth.configure({ ... }) stop working

### ISSUE THREAD

**Issue by kingferiol** [aws-amplify/amplify-ui#816]
After @aws-amplify/ui-react v2.0.0 upgrade the Auth.configure({ ... }) stop working.

Now I can just see the standard login page

```
import { Auth } from "@aws-amplify/auth";

Auth.configure({
  region: ...,
  userPoolId: ...,
  userPoolWebClientId: ...,
  oauth: {
    domain: ...,
    redirectSignIn: ...,
    redirectSignOut: ...,
    scope: ["email", "profile", "openid", "aws.cognito.signin.user.admin"],
    responseType: "code"
  }
});

function App(): JSX.Element {

}

export default withAuthenticator(App);
```

![image](https://user-images.githubusercontent.com/19843920/142702075-78b06f18-c666-4ad5-91da-eb45f87f0561.png)

**Comment by ericclemmons** [comment]
@kingferiol I'd like to better understand:
> Auth.configure({ ... }) stop working....Now I can just see the standard login page

What were you seeing before?  

If your backend is configured with the Amplify CLI, you can benefit from [Zero Configuration](https://ui.docs.amplify.aws/components/authenticator#zero-configuration).

**Comment by kingferiol** [comment]
Hi @ericclemmons 

We know that the zero configuration is the proper target and the step forward was done with the option to reuse a user pool that already exists.

Unfortunately, we still have some backend functions (API Gateway that we didn't build in the context of this project) and we have some friction in migrating to a full CLI world.

Maurizio

**Comment by ericclemmons** [comment]
@kingferiol I totally understand, let's get this back up & working for you.

> Auth.configure({ ... }) stop working....Now I can just see the standard login page

What were you seeing before?  

It'd help to have a code snippet of the previous `<AmplifyAuthenticator>` and a screenshot or something to understand what you mean by "stop working". I can even use that to help write a migration guide!

**Comment by kingferiol** [comment]
We are just using AWS Cognito as the identity provider.

The ideal solution is a direct redirect to the AWS Cognito page.

![image](https://user-images.githubusercontent.com/19843920/143483997-02134da5-d74a-4e31-9d6f-b388bc90cd34.png)

Thanks a lot 

Maurizio

**Comment by ErikCH** [comment]
Hi @kingferiol !

From what your describing are you talking about going to the Login with AWS page? Or are you expecting the login to go to the [Cognito Hosted UI](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html)?

**Comment by ErikCH** [comment]
Closing this for now, please reopen if it's still occurring.

**Comment by kingferiol** [comment]
Hi @ErikCH sorry to ping again on this closed issue but I'm quite close to what I want to achieve and this lead me to incredible frustration.

My application is working with AWS Cognito (I don't have any social provider) federated with an identity provider (it is not Google, Facebook, or Amazon).

I can't find a way to add a button to be redirected to the AWS Cognito Hosted UI page (as I was able to do in the past). It seems that the section OAuth now is ignored. Documentation doesn't help that much in this super plain scenario (no need to work with Google, Facebook, Amazon .... just want to land to the AWS Cognito Hosted UI).

```
Auth.configure({
  region: ...,
  userPoolId: ...,
  userPoolWebClientId: ...,
  oauth: {
    domain: ...,
    redirectSignIn: ...,
    redirectSignOut: ...,
    scope: ["email", "profile", "openid", "aws.cognito.signin.user.admin"],
    responseType: "code"
  }
});
```

Maurizio
