### ISSUE TITLE
New Authenticator component does not support dialCode attribute?

### ISSUE THREAD

**Issue by gomesp** [aws-amplify/amplify-ui#821]
I used to be able to define the "dialCode" in the previous ```AmplifyAuthenticator``` react component (via ```AmplifySignUp/formFields``` attribute). 

It seems that now I need to create a completely custom component if I wanted the same behaviour (i.e. using the ```PhoneNumberField``` component).

Is it possible to add the dialCode attribute as a value of the ```signUpAttributes``` instead to keep the implementations simple?

**Comment by ericclemmons** [comment]
@gomesp You're looking to have it default to a different value (e.g. `+55`) rather than `+1` correct?

We just need to expose it with something like:

```js
<Authenticator
  initialFormValues={{
    countryCode: '+55',
    email: 'my@example.com'
  }}
>
```

The alternative is exposing a `SignUp.PhoneNumber` slot that could be replaced with https://ui.docs.amplify.aws/components/phonenumberfield#usage:

```js
<PhoneNumberField defaultCountryCode="+55" label="Phone Number" />;
```

Is either of these what you're looking for?

**Comment by gomesp** [comment]
Thanks @ericclemmons, yeah, I was hoping there would be a way to setup the default country code as in your first example. 

If I understand the [documentation correctly](https://ui.docs.amplify.aws/components/authenticator#sign-up-fields), I could add the PhoneNumberField as a slot, but I thought that would be a small enough improvement to the out-of-the-box experience that would help users avoid having to customising the component if they don't need to.

**Comment by ericclemmons** [comment]
@gomesp We haven't created a slot just for the phone number for exactly the reason you described.

Providing initial form values would be best, so #826 will help resolve this need for all field values 🙏

**Comment by gomesp** [comment]
Thanks @ericclemmons, I'll subscribe to the PR and see how it progresses.
