### ISSUE TITLE
Zero Config: Add Password Protection Settings To Password Validation

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#846]
Zero config provides password protection settings. These settings should automatically be added to the password validation, so if the password entered by the user doesn't match the protection settings an appropriate error message is displayed, rather then waiting until the form is submitted to Cognito.

**Example Setting in aws-exports file**
```
"aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
```

**Comment by VaughanG** [comment]
This will be very welcome as the existing Cognito validation error messages are clunky and badly phrased. I can change the color in Cognito but not the text. It will be much better to allow the user to correct the password before submission.

**Comment by ErikCH** [comment]
This has been added in. Closing.
