### ISSUE TITLE
Should be an option to hide Reset password 

### ISSUE THREAD

**Issue by sourabhgrover** [aws-amplify/amplify-ui#847]
Unable to hide Reset password feature as we have for hiding sign up option mentioned below
`<AmplifySignIn  hideSignUp/>`

For now is there any alternate way to hide Reset Password feature on SignIn page?

**Comment by reesscot** [comment]
Hi @sourabhgrover, assuming you are using the 2.x version of the Authenticator, you can return `null` for the `SignIn.Footer` slot to remove the "Forgot Password" link. See: https://ui.docs.amplify.aws/components/authenticator#headers--footers

**Comment by sourabhgrover** [comment]
Hi @reesscot  I am using v1.2.14.
But I am able to hide Reset Password by the following approach

```
<AmplifyAuthenticator>
      <AmplifySignIn
        slot="sign-in"
        hideSignUp
        formFields={[
          {
            type: "username",
            label: "Username*",
            placeholder: "Enter your username",
            inputProps: { required: true, autocomplete: "username" },
          },
          {
            type: "password",
            label: "Password*",
            hint: "",
            placeholder: "Enter your password",
            inputProps: { required: true, autocomplete: "new-password" },
          },
        ]}
      />
    </AmplifyAuthenticator>
```

I have passed formFields and for the password field, I return the hint object as an empty string.

We can close this request
