### ISSUE TITLE
Homepage installation missing peer dependency `aws-amplify`

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#875]
Current docs:
```
npm i @aws-amplify/ui-react
```
Should include the peer dependency `aws-amplify`
```
npm i aws-amplify @aws-amplify/ui-react
```

Without installing the `aws-amplify` dependency, I get the following error:
```
 > node_modules/@aws-amplify/ui-react/dist/esm/index.js:1:1104852: error: Could not resolve "aws-amplify" (mark it as external to exclude it from the bundle)
    1 │ ...s OX,Logger as _X}from"aws-amplify";import{getActorState...
      ╵                          ~~~~~~~~~~~~~
```

_Screenshots:_
<img width="731" alt="Screen Shot 2021-11-24 at 11 48 01 AM" src="https://user-images.githubusercontent.com/6165315/143297520-66345d3c-2eba-4447-8ced-f8fcf54d8e27.png">
<img width="642" alt="Screen Shot 2021-11-24 at 11 51 35 AM" src="https://user-images.githubusercontent.com/6165315/143297513-195c6947-b3c6-4a9b-95cf-1de1cd35c46c.png">

**Comment by Milan-Shah** [comment]
We have added Peer dependency install on homepage. Closing the issue!
