### ISSUE TITLE
Setup TOTP UI - how to read QR code when it's on your phone's screen

### ISSUE THREAD

**Issue by ClaudioVR** [aws-amplify/amplify-ui#881]
Hi

I'm working on a Vue app which uses amplify-ui's authenticator component with MFA activated. We have run into a bit of a QR conundrum. 

The QR code displayed in the setup totp component works fine if the user is working on a desktop and uses their phone to take a picture of the QR code.

However, if the user is working on their phone, they are suddenly faced with a QR code on their own screen. Although not impossible to do, reading the QR code in this situation can become tedious and frustrating. 

Could a solution be to add the SETUP CODE as a string beneath the QR code. On mobile, the user would now be able to copy the code and enter it manually into their authentication app???

As users will mostly only have to scan the QR code once when creating an account, I realise one solution is to have users create an account whilst on a desktop machine....

Is this even a problem? It's my first time using mfa on an application. 
Please do let me know if there's already a practical solution to this out there. 

Many thanks in advance.

**Comment by ErikCH** [comment]
Hi @ClaudioVR ! Thanks for the request. 

This could be a handy addition. I'll mark this as a future feature request.
