### ISSUE TITLE
Add an option to pick between SignIn / SignUp and SignInSignUpTabs in New Authenticator UI component  

### ISSUE THREAD

**Issue by evagm** [aws-amplify/amplify-ui#884]
**Request**

I was wondering if there would be a way to add an option to choose between using the SignInSignUpTabs vs the SignIn / SignUp components. 

**Use Case**

An application uses the Authenticator with the default SignIn as well as the other default components but requires a custom SignUp component on a separate page. Currently this scenario cannot work since the SignIn and SignUp components are wrapped together within the SignInSignUpTabs.

https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/components/Authenticator/Router/index.tsx#L63-L65

**Comment by ErikCH** [comment]
Hi @evagm !

Could it be possible to hide the sign in/ sign out tabs with [CSS](https://ui.docs.amplify.aws/components/authenticator?platform=vue#additional-css-styling). Then set the initial state to [`signIn`](https://ui.docs.amplify.aws/components/authenticator?platform=vue#initialstate)? That way the user can only sign in. Then if you wanted too add in your custom sign-up page link you can overwrite the [footer](https://ui.docs.amplify.aws/components/authenticator?platform=vue#headers--footers)?

**Comment by evagm** [comment]
Hi @ErikCH! Thanks for the quick response! 

I'm not sure that this would be an ideal fix -- the sign up form would still be rendered in the DOM. My use case would require the sign up form to only be available under certain circumstances.

**Comment by wlee221** [comment]
Hmm, I don't think `SignUp` is actually rendered until user actually clicks the `signUp` tab -- https://github.com/aws-amplify/amplify-ui/blob/bb8906dc5c204833463d2703102635ec70c73bd3/packages/react/src/components/Authenticator/shared/SignInSignUpTabs.tsx#L23. 

Would that be sufficient?

**Comment by evagm** [comment]
@wlee221  yeah... sorry for the brain fart!

I meant to say -- the tab for the signup would still be rendered in the DOM and could trigger the signup form to render.
Maybe I'm trying to be extra careful but I only want the sign up form to be available in one specific page.

Would there anyway to disable that tab?

**Comment by ErikCH** [comment]
@evagm ! This could be a good addition to have, I'll add it as a future feature request. We would like to have better ways of disabling the tab at some point, rather than just CSS.

Until then, the workaround would be to hide via CSS.

**Comment by evagm** [comment]
Thanks @ErikCH and @wlee221 !

**Comment by AsemK** [comment]
I also need this feature. Use case: my app doesn't allow users to create an account, they must be added by an admin. So, sign up is not needed.

**Comment by kippert** [comment]
I also need this feature of being able to choose to disable the create account tab. Additionally, the css trick of setting `.amplify-tabs` to display none defaults my app to signUp, and setting the initial state to signIn actually re-enables the tabs 🤔

**Comment by pauchena** [comment]
Hey👋 Here another project that needs this feature. Thanks!

**Comment by Milan-Shah** [comment]
We have started the implementation and will update the thread by the end of our upcoming sprint (Feb 11).

**Comment by Milan-Shah** [comment]
Duplicate Reference : #1078

**Comment by ErikCH** [comment]
I just merged this in! It should be available in our next release. There will be a new `hideSignUp` prop you can pass in, to hide the sign up page. Closing this for now.
