### ISSUE TITLE
Migration guide for moving from @aws-amplify/ui-react from v1 to v2?

### ISSUE THREAD

**Issue by Milan-Shah** [aws-amplify/amplify-ui#897]
We need to put a section on our UI doc site to help customers migrate to v2.

**Comment by dbanksdesign** [comment]
Should include info about Cypress testing as this article won't work in v2: https://aws.amazon.com/blogs/mobile/run-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/
