### ISSUE TITLE
'global is not defined' in Angular

### ISSUE THREAD

**Issue by raviagheda** [aws-amplify/amplify-ui#899]
In Angular WebApp.  
While using `userPool = new CognitoUserPool(this.poolData);`

Console error return `global is not defined`  
  
### In `src/polyfills.ts`  add   

```javascript
(window as any).global = window
```

Ref: [`https://stackoverflow.com/a/52175667`](https://stackoverflow.com/a/52175667)

**Comment by wlee221** [comment]
Correct, you need to add `global` polyfills. This is pointed out [here](https://ui.docs.amplify.aws/getting-started/installation?platform=angular#global-and-process-shim) and [here](https://docs.amplify.aws/start/getting-started/setup/q/integration/angular/#angular-6-support), but we can and need to make it more visible in our docs. I have an issue open for that -- #892. 

We'll close this one in favor of #892, and look to resolve it this week. If you're looking for a comprehensive fix for that error without needing the workaround, please consider opening an issue in the Amplify JS repo, which owns the Cognito package.
