### ISSUE TITLE
Update Getting Started for Authenticator on Amplify Doc Site

### ISSUE THREAD

**Issue by Milan-Shah** [aws-amplify/amplify-ui#913]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Authenticator

### Please describe your bug.

We need to update Use Pre Built [UI Authenticator Component reference](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#option-1-use-pre-built-ui-components) on Amplify Doc site. 

### What's the expected behaviour?

We should reference the link to Authenticator UI Doc site getting started guide. 

### Help us reproduce the bug!

NA

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by ericclemmons** [comment]
https://github.com/aws-amplify/docs/pull/3851 has been deployed:
> https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#option-1-use-pre-built-ui-components

https://github.com/aws-amplify/docs/pull/3850 is still awaiting review, but unrelated to this PR.
