### ISSUE TITLE
No documentation for Angular

### ISSUE THREAD

**Issue by scastaldi** [aws-amplify/amplify-ui#916]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### Please describe your bug.

https://ui.docs.amplify.aws/ has no documentation for Angular

### What's the expected behaviour?

 no documentation for Angular

### Help us reproduce the bug!

 no documentation for Angular

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by wlee221** [comment]
Hi @scastaldi, Angular Authenticator documentation is available on https://ui.docs.amplify.aws/components/authenticator?platform=angular. 

Was there a mishavior on navigating to that page?

**Comment by scastaldi** [comment]
thank you! that worked... could you please update this documentation?

https://docs.amplify.aws/start/getting-started/setup/q/integration/angular/#create-a-new-amplify-backend

If you follow that Tutorial you create everything in Amplify 1x
