### ISSUE TITLE
Upgrading from @aws-amplify/ui-angular@1.x.x   to 2.x.x

### ISSUE THREAD

**Issue by scastaldi** [aws-amplify/amplify-ui#917]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### Please describe your bug.

I'm trying to update from @aws-amplify/ui-angular@1.x.x to 2.x.x and there is zero documentation 

### What's the expected behaviour?

everything should work

### Help us reproduce the bug!

after installing 2.x the modules do not recognize AmplifyUIAngularModule

### Code Snippet

```typescript
// Put your code below this line.
Error: ./src/app/app.module.ts 19:12-34
"export 'AmplifyUIAngularModule' was not found in '@aws-amplify/ui-angular'
```

**Comment by wlee221** [comment]
Hello @scastaldi, as mentioned in #916, Angular documentation is available here https://ui.docs.amplify.aws/components/authenticator?platform=angular. 

As per `AmplifyUiAngularModule`, we're using component-specific modules to help with code split: https://ui.docs.amplify.aws/components/authenticator?platform=angular#quick-start

There is quite a lot of breaking change as it's an entirely new implementation, and we definitely agree that migration guide is missing. Is this what you're looking for?

**Comment by scastaldi** [comment]
Thank you! that worked.. I changed everything to 2.x
could you please update this tutorial?
https://docs.amplify.aws/start/getting-started/setup/q/integration/angular/#create-a-new-amplify-backend

**Comment by wlee221** [comment]
Glad it worked! We have #913 open to update that. I'll close this issue in favor of tracking #913, thanks 🙏
