### ISSUE TITLE
Add `labelPosition` to CheckboxField

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-ui#928]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

The SwitchField has a `labelPosition` prop and a CheckboxField is very similar to a SwitchField. 

### Please describe a solution you'd like.

```jsx
<CheckboxField label="Pineapple" labelPosition="start" />
```

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by rkoleci** [comment]
Can you assign this to me ? I would like to contribute

**Comment by ericclemmons** [comment]
@rkoleci We'd love to help you contribute, too!

If you'd like to get started, see – https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md

Feel free to open a draft PR for this issue and we'll work together on it 💪

**Comment by dbanksdesign** [comment]
<img width="1438" alt="CleanShot 2022-02-18 at 10 36 40@2x" src="https://user-images.githubusercontent.com/321279/154742566-ec70477a-0710-41f3-b3bd-0bcc61d15921.png">

https://ui.docs.amplify.aws/components/checkboxfield

This is in!
