### ISSUE TITLE
How to validate/modify formData on SignUp with new ui 2.0 ui-vue component?

### ISSUE THREAD

**Issue by Milan-Shah** [aws-amplify/amplify-ui#929]
### Discussed in https://github.com/aws-amplify/amplify-ui/discussions/836

<div type='discussions-op-text'>

<sup>Originally posted by **jeff-wishnie** November 22, 2021</sup>
With Web Components it is possible to implement `handleSignUp` to validate and modify asccount data before calling `Auth.signUp`

I used this to, for example, force email addresses to lower-case before creating a new user so that email addrs in the Cognito User Pool are always lower case.

I'm unable to see how to do this possible with the new ui-vue v2.0.0

I can implement a form validation service, but this is called on every key-press and does not allow modifying the data (as for as I can see).

If I add `@signUpSubmit="validateSubmit"'` to the <authenticator> tag, it is never called...

If I add `@submit="validateSubmit"` to authenticator, it is called but formData is not passed.

Is there a way to do this?

@ErikCH any ideas here? Why @signUpSubmit isn't capturing the event?</div>

**Comment by ErikCH** [comment]
Going to close this for now, pushed
