### ISSUE TITLE
Reset password: cannot re-type email after click "back to sign in" button.

### ISSUE THREAD

**Issue by Eisekson** [aws-amplify/amplify-ui#946]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### Please describe your bug.

in login page -> click "reset password" button -> 
in reset password page -> type email address -> click "SEND CODE" -> 
in verify code page -> click "Back to Sign In" -> 
in login page -> click "reset password" button -> 
in verify code page -> click "Back to Sign In"

### What's the expected behaviour?

in login page -> click "reset password" button -> 
in reset password page -> type email address -> click "SEND CODE" -> 
in verify code page -> click "Back to Sign In" -> 
in login page -> click "reset password" button -> 
in reset password page -> type email address -> click "SEND CODE" ->
in verify code page -> click "Back to Sign In"

### Help us reproduce the bug!

use amplify angular ui

### Additional information and screenshots

https://user-images.githubusercontent.com/4337049/144805290-4517491d-74cf-440d-b744-0684ebfb13fe.mov

**Comment by ericclemmons** [comment]
We released a new version of `@aws-amplify/ui-angular` with several fixes for behavior like this:
> https://ui.docs.amplify.aws/components/authenticator?platform=angular

After updating to the latest CLI & UI, can you share if you run into any more issues?

**Comment by ErikCH** [comment]
Closing this one. Please re-open if it occurs again
