### ISSUE TITLE
Docs site mobile improvements

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-ui#952]
### All pages with ToC

https://user-images.githubusercontent.com/321279/145106242-2ff235fb-1069-41b7-bcde-84bdd9dcbb5e.mp4

- [] ToC works on hover for web, which doesn't work well on a mobile device

**Comment by 0618** [comment]
Move the first one https://github.com/aws-amplify/amplify-ui/issues/1547

**Comment by reesscot** [comment]
Moved another section to #1549

**Comment by joebuono** [comment]
Moved another section to https://github.com/aws-amplify/amplify-ui/issues/1550

**Comment by 0618** [comment]
Moved another section to https://github.com/aws-amplify/amplify-ui/issues/1551

**Comment by jacoblogan** [comment]
Moved another section to #1552

**Comment by joebuono** [comment]
Moved another section to https://github.com/aws-amplify/amplify-ui/issues/1556
