### ISSUE TITLE
FR (Authenticator): Federated auth client ID overrides

### ISSUE THREAD

**Issue by jreynar** [aws-amplify/amplify-ui#954]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

In version 1.x of @aws-amplfiy/ui-react you could add Google (and Facebook and other services') login like this (which is a quote from the documentation found at https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#using-amplify-ui-components):
```jsx
import { AmplifyAuthenticator } from '@aws-amplify/ui-react';

const federated = {
    googleClientId: '', // Enter your googleClientId here
    facebookAppId: '', // Enter your facebookAppId here
    amazonClientId: '' // Enter your amazonClientId here
};

return (
    <AmplifyAuthenticator federated={federated}>
)

In version 2, you can add a service provider like this (according to the docs found at https://ui.docs.amplify.aws/components/authenticator#socialproviders):
export default function App() {
  return (
    <Authenticator socialProviders={['amazon', 'apple', 'facebook', 'google']}>
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user.username}</h1>
          <button onClick={signOut}>Sign out</button>
        </main>
      )}
    </Authenticator>
  );
}
```

However, this seems to only work if you use the CLI to configure social providers. It'd be great to bring back the option to pass the google client id (and other service providers' ids) to Amplify via another attribute on the authenticator component as was done in the previous version with federated. 

Currently the recommended approach is to follow the pattern of creating a separate SignInWithGoogle function (see https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#google-sign-in-react) but that's more work AND, crucially, means that you also have to wire up your own button since there appears to be no way to connect that function to the button created by setting up a social provider. 

### Please describe a solution you'd like.

In addition to being able to specify a list of socialProviders on the Authenticator component, it would be ideal to also be able to pass in the googleClientID (and other service provider ids) and have the same functionality present in the 1.x version of the react components.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by dehli** [comment]
Hi, this is actually supported with the current version! You need to make sure you pass in an `oauth` key when you're calling `Auth.configure()`. Check out the full docs here: https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource.

```js
oauth: {
  domain: 'your_cognito_domain',
  scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
  redirectSignIn: 'http://localhost:3000/',
  redirectSignOut: 'http://localhost:3000/',
  responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
}
```

**Comment by reesscot** [comment]
Closing out as this is supported in Gen2: https://docs.amplify.aws/react/build-a-backend/auth/concepts/external-identity-providers/
