### ISSUE TITLE
Authenticator NEW_PASSWORD_REQUIRED flow not redirecting to SMS_MFA challenge screen

### ISSUE THREAD

**Issue by Matt-Web** [aws-amplify/amplify-ui#955]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### Please describe your bug.

When signing in with a user with a status of FORCE_CHANGE_PASSWORD I'm redirected to the change password screen. Following submission of the new password the screen redirects to a logged in state despite the post request returning a "SMS_MFA" challenge.

### What's the expected behaviour?

Like the previous version following the update of the password the authenticate component should display the screen asking for 2fa confirmation and then log the user in.

### Help us reproduce the bug!

Version "@aws-amplify/ui-react": "^2.1.2"

Using the quick start component detailed here https://ui.docs.amplify.aws/components/authenticator#quick-start

Register a cognito user with the following settings:
Account Status =  Enabled / FORCE_CHANGE_PASSWORD
SMS MFA Status  = Enabled
email_verified = true

Attempt to login using email & existing password
Update password screen will display
Enter and save new password
Screen will show as a user logged in, despite the payload returning `ChallengeName: "SMS_MFA"`

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by AntonBarwald** [comment]
I have similar issues with the Authenticator component.

It also seems to be an issue when you do the first login using Cognito Hosted UI (the required MFA is ignored and user is successfully logged in) using same settings as mentioned above:
SMS MFA Status = Enabled
Account Status Enabled = "FORCE_CHANGE_PASSWORD"

**Comment by ErikCH** [comment]
Hi @Matt-Web and @AntonBarwald !

Thanks for brining this up. We'll need to test this out, but it seems like it might be a bug. I know our xstate machine checks if the user has a force new password change or if they need to confirm their sign in, with `SMS_MFA` or `SOFTWARE_TOKEN_MFA`. 

It might not route correctly for a user that needs both. We'll add it to our backlog!

**Comment by ErikCH** [comment]
Hey @Matt-Web and @AntonBarwald 

I pushed a fix for this, it should be on `aws-amplify/ui-vue@next` branch until we do our next release later this week You could try it out.

It should now detect if the user needs to verify their account with SMS MFA.

**Comment by ErikCH** [comment]
You should be able to test it now, be reinstalling the latest version of `@aws-amplify/ui-*` from your package.json.

**Comment by ErikCH** [comment]
Closing this for now, please reopen or create a new issue if there are problems.
