### ISSUE TITLE
Reusing amplify-ui after login

### ISSUE THREAD

**Issue by Dongw1126** [aws-amplify/amplify-ui#961]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I was trying to create a button to reset password after login.
But I couldn't find a way to reuse the Reset Password screen after login.  

 I called toResetPassword from useAuthenticator but it didn't work.
```
const { toResetPassword } = useAuthenticator();

<Authenticator>
    {({ signOut, user }) => {
        return(
            <main>
            <h2>{user.username}</h2>
            <Button variation="link" onClick={toResetPassword}>change passworkd</Button>
            <Button variation="link" onClick={signOut}>SignOut</Button>
        </main>
        );
    }}
</Authenticator>
```

It would be nice to be able to reuse amplify-ui after login.

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by paaulfilipan** [comment]
Any updates on this?

**Comment by wlee221** [comment]
Hi! We added https://ui.docs.amplify.aws/react/connected-components/account-settings/change-password component to allow password change after sign in. This is in developer preview fyi, and appreciate any feedbacks. Thanks! 🙏

**Comment by wlee221** [comment]
cc @Dongw1126, @paaulfilipan
