### ISSUE TITLE
Not able to find type of "signOut" of "Authenticator" for typescript 

### ISSUE THREAD

**Issue by tranminhhaifet** [aws-amplify/amplify-ui#978]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### Please describe your bug.

interface TestProps {
  **signOut: () => void;**  // whay type should be here? 
  user: CognitoUserAmplify; 
}

// Error 
 <Authenticator>
        {({ signOut, user }) => (
          <Sidebar 
            **signOut={signOut}** // error not assignable type 
            user={user}
          >
          </Sidebar>
        )}
      </Authenticator>

### What's the expected behaviour?

signOut type should be specified in the document 

### Help us reproduce the bug!

interface TestProps {
  **signOut: () => void;**  // whay type should be here? 
  user: CognitoUserAmplify; 
}

// Error 
 <Authenticator>
        {({ signOut, user }) => (
          <Sidebar 
            **signOut={signOut}** // error not assignable type 
            user={user}
          >
          </Sidebar>
        )}
      </Authenticator>

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by mouimet-infinisoft** [comment]
What you are looking for can be found under @aws-amplify/ui-react/dist/index.d.ts

line 173
```
declare type RouterProps = {
    className?: string;
    children: ({ signOut, user, }: {
        signOut: ReturnType<typeof useAuthenticator>['signOut'];
        user: CognitoUserAmplify;
    }) => JSX.Element;
    variation?: 'default' | 'modal';
};
```

Infered type is
var signOut: (data?: Record<string | number | symbol, any> | undefined) => void


Hope that helps :)
