### ISSUE TITLE
Documentation on amplfiy ui/angular/Customization code missing

### ISSUE THREAD

**Issue by myonara** [aws-amplify/amplify-ui#980]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### Please describe your bug.

In the documentation ([direct link](https://ui.docs.amplify.aws/components/authenticator?platform=angular#headers--footers)) there are in the click-part of the buttons or links an object authenticator used, but the parts where authenticator is defined in the ts-Module are missing! Cannot compile the example successfully.

### What's the expected behaviour?

Please extend the documentation, how to define the authenticator object in the according ts-Module belonging to the html-template shown in the documentation.

### Help us reproduce the bug!

Use a new angular/amplify project, do the setup/configuration of the auth module within amplify, and then try to compile the app component with the content described in the customization section of the documentation.

### Code Snippet

```typescript
// Put your code below this line.

```
```
  <ng-template amplifySlot="sign-in-footer">
    <div style="text-align: center">
      <button
        (click)="authenticator.toResetPassword()"
        class="amplify-button amplify-field-group__control"
        data-fullwidth="false"
        data-size="small"
        data-variation="link"
        type="button"
        style="font-weight: normal"
      >
        Reset Password
      </button>
    </div>
  </ng-template>

```
### Additional information and screenshots

Error: src/app/app.component.html:24:18 - error TS2339: Property 'authenticator' does not exist on type 'AppComponent'.

24         (click)="authenticator.toResetPassword()"
                    ~~~~~~~~~~~~~

  src/app/app.component.ts:8:16
    8   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

**Comment by wlee221** [comment]
Hello @myonara, thanks for the catch!

We will work on extending the documentation. Meanwhile, note that `authenticator` can be initiated as follows:

_app.component.ts_
```diff
import { AuthenticatorService } from '@aws-amplify/ui-angular';

@Component({
  selector: 'app-component',
  templateUrl: 'app.component.html',
})
export class AppComponent {
+ constructor(public authenticator: AuthenticatorService) {}
}
```
