### ISSUE TITLE
Pressed state of `ToggleButton` doesn't have a background color

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#983]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### Please describe your bug.

Pressed state of ToggleButton with variation doesn't have a background color. When pressed, it only changes the font color, but not the background color. This doesn't represent enough of a contrast to meet accessibility guidelines.

UnPressed (default state):
![Screen Shot 2021-12-13 at 11 05 28 AM](https://user-images.githubusercontent.com/6165315/145873175-de06e99b-a41d-429f-973c-5fd39a51a9fa.png)

Pressed:

![Screen Shot 2021-12-13 at 11 05 18 AM](https://user-images.githubusercontent.com/6165315/145873198-d6954879-1ad7-402b-a2fa-918a2d446e25.png)

See: https://ui.docs.amplify.aws/components/togglebutton#variations

### What's the expected behaviour?

When in pressed state, it should have a background color. In the example below, the far left item is pressed, but doesn't have a gray background color:

![Screen Shot 2021-12-13 at 11 10 25 AM](https://user-images.githubusercontent.com/6165315/145873400-74abb464-b731-49e1-8d0a-720f3cfef65a.png)

### Help us reproduce the bug!

Go to to docs: https://ui.docs.amplify.aws/components/togglebutton#togglebuttongroup
Click on a button and notice that only the font color changes.

**Comment by zchenwei** [comment]
#1080
