### ISSUE TITLE
Better error message when `Authenticator` component children missing

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-ui#987]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Other

### Please describe your feature-request in detail.

When a customer doesn't include provide `children` to render when a user has logged in, as shown in the following code:

```
export function App() {
  return (
    <AmplifyProvider>
      <main>
        <Authenticator components={components} />
      </main>
    </AmplifyProvider>
  );
}
```

The following cryptic error is thrown from `Router`

```
s is not a function
```

### Please describe a solution you'd like.

Instead of the message above, we should give a hint that the user forgot to put something inside the `Authenticator`

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by Danm72** [comment]
I legit can't find any docs that tell us we should use the provider as the outer wrapper, then Authenticator inside.

I'm just coming up with the error above - s is not a function
```
const components = {
    Header() {}
//other auth screen changes
} 
function MyApp({Component, pageProps, router}) {
    const apolloClient = useApollo(pageProps);


    return (
        <AmplifyProvider>
                <Authenticator components={components}>
                    <Component {...pageProps} />
                </Authenticator>
        </AmplifyProvider>
);
}
export default MyApp;
```

**Comment by ErikCH** [comment]
This has just been merged, and you no longer need to pass values as render props. Any value can be passed in between the opening and closing brackets.  Please re-open if you have any issues.
