### ISSUE TITLE
Custom issuer for QR code

### ISSUE THREAD

**Issue by jngtn** [aws-amplify/amplify-ui#988]
### On which framework/platform would you like to see this feature implemented?

Vue

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

Hi,

First off, I'm new to Amplify and in particular the newly released Amplify UI.

I would like the option to set a custom issuer for the QR code in the MFA/TOTP setup.
This in order for the end users to more easily be able to locate the correct option to use in their authenticator app.

When investigating the component (setup-totp.vue), it seems this is hardcoded to AWSCognito.
Would it make sense to have it configurable in some way?

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by jngtn** [comment]
Hi @ErikCH!

Thank you for your reply! Well, my problem is mostly my own lacking knowledge. About many things, including AWS, Amplify and MFA in general.
My request came from the fact that I can see a potential issue where a user signs up for multiple applications from different suppliers using AWS Cognito via Amplify and thus having several MFA codes in their authenticator app, all with the same name. How to know which one to select?

I should probably have done more studying before making a feature request, but I was confused by the fact that it was possible to set a custom issuer name in the previous generation of Amplify UI. With that set I could customise the name the user would see in their authenticator app.

Feel free to just drop this request if it is not applicable, since I'm out on pretty deep water here.

Thank you.

**Comment by ErikCH** [comment]
Interesting!

Yes, I do see that this was an option in a previous version. I'll add this to a future feature request to get that added back in.

**Comment by bwindsor** [comment]
@ErikCH I also used this feature of the old UI and need it in the new one which I've just updated to. It's confusing for the user if their authenticator app displays the token as `AWSCognito` instead of `MyAppName` - the user doesn't know that the authentication technology the web app uses is actually Cognito under the covers.

I can create a PR for this, would that be useful? Or if it's quicker/easier for you to do it yourself that's fine too. I think these would be the changes required, although I'm not incredibly familiar with the codebase so I can't be sure!

1. Add `totpIssuer?: string;` here:
https://github.com/aws-amplify/amplify-ui/blob/e0fcf3685164075fe385f8e09247f9620a7e6ccc/packages/ui/src/types/authMachine.ts#L10-L15

1. Bring it in here by changing to `const { _state, submitForm, updateForm, isPending, totpIssuer } = useAuthenticator();`
https://github.com/aws-amplify/amplify-ui/blob/e0fcf3685164075fe385f8e09247f9620a7e6ccc/packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx#L24

1. Change this to `const issuer = encodeURI(totpIssuer ? totpIssuer : 'AWSCognito'); ` (`encodeURI` is needed because the custom issuer could have e.g. a space in its name)
https://github.com/aws-amplify/amplify-ui/blob/e0fcf3685164075fe385f8e09247f9620a7e6ccc/packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx#L34

Then the `Authenticator` component can be used as
```tsx
<Authenticator totpIssuer={'My TOTP Issuer'}>...</Authenticator>
```

**Comment by rohan-passbird** [comment]
Any update on this? Both the issuer and username should be customizable. Currently issuer is AWSCognito and username is some random uuid which looks weird in the authenticator app.

**Comment by mroest** [comment]
I have the same issue here. The user prop as issuer should be customisable.

**Comment by mroest** [comment]
> @ErikCH I also used this feature of the old UI and need it in the new one which I've just updated to. It's confusing for the user if their authenticator app displays the token as `AWSCognito` instead of `MyAppName` - the user doesn't know that the authentication technology the web app uses is actually Cognito under the covers.
> 
> I can create a PR for this, would that be useful? Or if it's quicker/easier for you to do it yourself that's fine too. I think these would be the changes required, although I'm not incredibly familiar with the codebase so I can't be sure!
> 
> 1. Add `totpIssuer?: string;` here:
>    https://github.com/aws-amplify/amplify-ui/blob/e0fcf3685164075fe385f8e09247f9620a7e6ccc/packages/ui/src/types/authMachine.ts#L10-L15
> 2. Bring it in here by adding `const { totpIssuer = 'AWSCognito' } = _state.context.config;`
>    https://github.com/aws-amplify/amplify-ui/blob/e0fcf3685164075fe385f8e09247f9620a7e6ccc/packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx#L24
> 3. Change this to `const issuer = encodeURI(totpIssuer); ` (`encodeURI` is needed because the custom issuer could have e.g. a space in its name)
>    https://github.com/aws-amplify/amplify-ui/blob/e0fcf3685164075fe385f8e09247f9620a7e6ccc/packages/react/src/components/Authenticator/SetupTOTP/SetupTOTP.tsx#L34
> 
> Then the `Authenticator` component can be used as
> 
> ```tsx
> <Authenticator totpIssuer={'My TOTP Issuer'}>...</Authenticator>
> ```

Nice! But pls do not forget to include the prop for user. When Cognito uses for example a email as username this shows a weird looking uuid which make no sense to the actual user

**Comment by ErikCH** [comment]
Hi @mroest !

I am working on adding a `formFields` prop, that will make it easier to add in labels, placeholders, required, defaultPhoneNumberField too many of the inputs in the app.

I'll add in this QR code requirement as well, as another key on the `formFields` prop that can be passed into the QR code component. I'll have updates by the end of the week!

**Comment by mroest** [comment]
> Hi @mroest !
> 
> I am working on adding a `formFields` prop, that will make it easier to add in labels, placeholders, required, defaultPhoneNumberField too many of the inputs in the app.
> 
> I'll add in this QR code requirement as well, as another key on the `formFields` prop that can be passed into the QR code component. I'll have updates by the end of the week!

Awsome! Looking forward Thanks

**Comment by wesselvanderlinden** [comment]
I was looking for this feature as well, since I need to customize the issuer and username in het `SetupTOTP` component. 

Good to see that @ErikCH is working on it! Good luck, and hopefully we can use it soon :)

**Comment by ErikCH** [comment]
Hi @wesselvanderlinden , @jngtn , @mroest 

I've added this feature. You can now set the `totpIssuer` and the `totpUsername` under a new `formFields` prop. The instructions are here. https://ui.docs.amplify.aws/components/authenticator#update-setup-totp-qr-issuer-and-username

Please create a bug on this if you have any issues. It will be released today.

**Comment by mroest** [comment]
Iam currently testing this but is there an example on how to use for example the email address of the user which is setting up the totp?

**Comment by ErikCH** [comment]
Hi @mroest !

Right now it defaults to the `user.username`. But there is no mechanism to set it to the email address automatically. If you're interested, you could open a new issue on that, and we can set it as a future feature request.

**Comment by jasonwadsworth** [comment]
I'm still unable to set the totpIssuer. I've updated to the latest `@aws-amplify/ui-react` (version 3.5.10) and have a simple, hard coded, value in the `formFields` but I still get the "AWSCognito" name on the issuer.

```
                <Authenticator
                    formFields={{
                        setupTOTP: {
                            QR: {
                                totpIssuer: 'MyIssuerName',
                            },
                        },
                    }}
                >
```
