### ISSUE TITLE
Add React ConfirmSignUp Customization Slot

### ISSUE THREAD

**Issue by ErikCH** [aws-amplify/amplify-ui#994]
### Discussed in https://github.com/aws-amplify/amplify-ui/discussions/958

<div type='discussions-op-text'>

<sup>Originally posted by **k-wolf-dev** December  7, 2021</sup>
Using the new Amplify Authenticator component.

Is it possible to customize the ConfirmSignUp page using the new <Header> slot functionality?

Thanks!</div>

* This only works in Vue and Angular, and is missing from React

**Comment by ErikCH** [comment]
This is related to https://github.com/aws-amplify/amplify-ui/issues/1019

**Comment by wlee221** [comment]
Is this to customize the whole `ConfirmSignUp` opposed to just its `formfield`?

**Comment by ErikCH** [comment]
@wlee221 we are missing all the slots in the Confirm Sign Up page in React, while they exist in Vue and React. We probably don't need the ones for `formField` yet. Just the normal header/footer ones.

**Comment by ErikCH** [comment]
This has been added!
